### ISSUE TITLE
some error in log when sending OffsetCommitRequest, any suggestion ？

### ISSUE THREAD

**Issue by chiwah-keen** [dpkp/kafka-python#1004]
kafka.coordinator ERROR base.py:312 2017-03-02 09:56:06,657  Error sending OffsetCommitRequest_v2 to node 0 [NodeNotReadyError: 0]

**Comment by dpkp** [comment]
NodeNotReadyError means only that the socket has not connected yet. The request should retry and once the socket is connected it should succeed.

I realize this error message can be confusing, and I have a PR up that should fix the logging (because it isn't really an Error in sending).

**Comment by chiwah-keen** [comment]
thank you!
