### ISSUE TITLE
giving error in log , but all seems alright。any suggestion？

### ISSUE THREAD

**Issue by chiwah-keen** [dpkp/kafka-python#1013]
kafka.coordinator ERROR base.py:312 2017-03-02 09:56:06,657  Error sending OffsetCommitRequest_v2 to node 0 [NodeNotReadyError: 0]
kafka.coordinator ERROR base.py:312 2017-03-02 09:56:07,095  Error sending OffsetCommitRequest_v2 to node 0 [NodeNotReadyError: 0]
kafka.coordinator ERROR base.py:312 2017-03-02 09:56:09,552  Error sending OffsetCommitRequest_v2 to node 0 [NodeNotReadyError: 0]

**Comment by dpkp** [comment]
NodeNotReadyError means only that a connection has not yet been established. You can ignore if the request eventually succeeds.
