### ISSUE TITLE
Records returned by KafkaConsumer.poll() are not the same for each return

### ISSUE THREAD

**Issue by gaoyangthu** [dpkp/kafka-python#1014]
I create a topic with one replication factor and three partitions in a Kafka cluster with three servers.

> kafka-topics.sh --describe --zookeeper 10.0.10.10:2181,10.0.10.11:2181,10.0.10.12:2181 --topic test
   Topic:test	PartitionCount:3	ReplicationFactor:1	Configs:
   Topic: test	Partition: 0	Leader: 0	Replicas: 0	Isr: 0
   Topic: test	Partition: 1	Leader: 1	Replicas: 1	Isr: 1
   Topic: test	Partition: 2	Leader: 2	Replicas: 2	Isr: 2

Then, I create a producer to send messages.

```python
producer = KafkaProducer(bootstrap_servers='10.0.10.10:9092')
for i in range(30):
    producer.send('test', str(i))
```

After that, I create a consumer to receive meaasges.

```python
consumer = KafkaConsumer(bootstrap_servers='10.0.10.10:9092', group_id=None, auto_offset_reset='earliest')
consumer.assign([TopicPartition(topic=u'test', partition=0),TopicPartition(topic=u'test', partition=1),TopicPartition(topic=u'test', partition=2)])
```

Every time, I run codes below and get different records returned by KafkaConsumer.poll().  Sometimes it returns only one partition's records, sometimes it returns two partitions' records, and other times it returns all records.
Besides that, the order of sending records is disrupted in the KafkaConsumer.poll() results.

```python
consumer.seek_to_beginning()
consumer.poll(timeout_ms=100000, max_records=5000)
```

Is there any solutions for this? Or could I use other API to do this?
Thanks a lot!

**Comment by dpkp** [comment]
Kafka does not guarantee ordering between partitions. If you want consistent ordering, assign a single partition.
