### ISSUE TITLE
How can I continue reading a topic in Kafka using kafka-python?

### ISSUE THREAD

**Issue by d-chugunov** [dpkp/kafka-python#1015]
I have Kafka 0.10.0.0, kafka-python 1.3.1. My code for reading a topic is:

```
consumer = KafkaConsumer("test-topic", bootstrap_servers=["localhost:9092"],
                             group_id="test-group", client_id="test-client-id",
                             enable_auto_commit=False, consumer_timeout_ms=1000)
while True:
    for msg in consumer:
        print("msg")
        topicPartition = TopicPartition(msg.topic, msg.partition)
        consumer.commit({topicPartition: OffsetAndMetadata(msg.offset + 1, '')})
    print("idle")
```

My topic test-topic has 32 partitions. I start my program and add a few messages to the topic. The programs reads these messages. I stop it (Ctrl+C). Then I add more messages to the topic and run my program again. In some cases the program gets new messages, but in some cases doesn't. I can't find any regularity in this behaviour and have already given up in finding an explanation in Kafka and kafka-python documentation. What have I missed?

**Comment by dpkp** [comment]
Have you tried looking at the logs? I suspect you're simply running into a session timeout because your consumer isn't leaving gracefully. Try waiting for 30 seconds (or whatever your session_timeout_ms is) before restarting your consumer.

**Comment by d-chugunov** [comment]
I tried waiting before restarting and after restarting. But no new messages come.

**Comment by d-chugunov** [comment]
In kafka-python logs I can see the message like "Group test-group has no committed offset for partition TopicPartition(topic='irkkt', partition=25)" when I start my consumer. How should I commit offsets for group?

**Comment by d-chugunov** [comment]
How long does the group coordinator store committed offsets for group? It seems it is the root of the problem...

**Comment by d-chugunov** [comment]
So the root of the problem was in offset storing time. It's 24 hours by default. That's why my code wasn't able to continue reading before committing offset of each partition.

**Comment by jeffwidman** [comment]
Thanks for posting your solution. I've also been bitten by the 24 hours thing, I personally think that default should be raised a bit, but haven't had time to put together a KIP for it.
