### ISSUE TITLE
Cannot connect to IPv6 with non-zero scope-id

### ISSUE THREAD

**Issue by dpkp** [dpkp/kafka-python#1018]
Following on debug logs posted to #868 , it looks like we are not handling ipv6 sockaddr tuples correctly. At https://github.com/dpkp/kafka-python/blob/fb09c0aa727141eaf0ec94c76a86b2f3b9328de8/kafka/conn.py#L260 we extract the host / port from the sockaddr. This is fine for ipv4 where sockaddr is just a 2-tuple . But in IPv6 sockaddr is a 4-tuple, including flow-info and scope-id. If those are non-zero, we will not be able to connect correctly when we call connect_ex((host, port)).

**Comment by goern** [comment]
a workaround seems to be to have zookeeper (clientPortAddress) and kafka (listeners) listening on 127.0.0.1 so they dont try to listen on any IPv6

**Comment by lifuyan2684** [comment]
we extract the host / port from the sockaddr. This is fine for ipv4 where sockaddr is just a 2-tuple . But in IPv6 sockaddr is a 4-tuple, including flow-info and scope-id. 
Is there any solution for this? @dpkp @goern 
when I use kafka-python in IPV6, the host name always be cut short.
for example:
the host I used is director-2001:da8:2004:1000:202:116:163:41
but actually in code, it is director-2001:da8:2004:1000:202:116:163
