### ISSUE TITLE
Do I need to process synchronous problems when I use several producer for the same topic?

### ISSUE THREAD

**Issue by onlyone509** [dpkp/kafka-python#1020]
Hi, 
I am using your codes for message processing. And there are several producer thread for one topic. So do I need to process synchronous problems to avoid race condition?

Hope your response.

**Comment by dpkp** [comment]
I'm not aware of any issues. If you have a specific problem, perhaps post a code snippet with the issue description. Otherwise there's not much I can do to help.

**Comment by onlyone509** [comment]
For example ,there are 3 clients writing messages to the same topic. So they will store the offset for 3 copies. In this condition, should I split the partitions of the topic for each client or let it go and each client can write messages to all the partitions?
