### ISSUE TITLE
consumer pattern wildcard not work

### ISSUE THREAD

**Issue by wanyikang** [dpkp/kafka-python#1022]
```
# -*- coding: utf-8 -*-
from kafka import KafkaConsumer
consumer = KafkaConsumer(
    group_id='test_group',
    bootstrap_servers=['172.16.6.7:9092','172.16.6.6:9092','172.16.6.5:9092']
)
consumer.subscribe(pattern='meterdata2000')
for message in consumer:
    print ("%s:%d:%d: key=%s value=%s" % (message.topic, message.partition,
                                          message.offset, message.key,
                                          message.value))
```

```
# -*- coding: utf-8 -*-
from kafka import KafkaProducer
import json

producer = KafkaProducer(
    bootstrap_servers=['172.16.6.7:9092','172.16.6.6:9092','172.16.6.5:9092'],
    value_serializer=lambda m: json.dumps(m).encode('ascii')
    )

for i in range(100):
    value = 'value' + str(i)
    producer.send('meterdata2000', {'key': value})

producer.flush(timeout=120)
```

I use these code to test wildcard pattern, but it do not work. I use kafka-python (1.3.2) and Kafka(0.10.0.0). I think maybe there is a bug in the kafka-python client

**Comment by dpkp** [comment]
Does the topic exist when you start your consumer? If not, you must wait for `metadata_max_age_ms` (default is 300000 ms == 5 mins) before the consumer will see the new topic created by your producer.

Try lowering metadata_max_age_ms or starting the producer first.

**Comment by wanyikang** [comment]
yes, I'm sure the topic exist. I change the consumer code below and it gets the topics.

`# -*- coding: utf-8 -*-
from kafka import KafkaConsumer
consumer = KafkaConsumer(
    group_id='test_group',
    auto_offset_reset='earliest',
    metadata_max_age_ms=5000,
    bootstrap_servers=['172.16.6.7:9092','172.16.6.6:9092','172.16.6.5:9092']
)
consumer.subscribe(['meterdata_2000', 'meterdata2000'])
print consumer.subscription()
for message in consumer:
print ("%s:%d:%d: key=%s value=%s" % (message.topic, message.partition,
                                          message.offset, message.key,
                                          message.value))
`
I get this on my shell.  `set(['meterdata2000', 'meterdata_2000'])`

when I change the keyword parameter of consumer.subscribe to topic list, it work fine, but if the keyword parameter is pattern string, it always gets `set([])`
