### ISSUE TITLE
KAFKA-1935 Consumer and Coordinator should use a separate socket for connections.

### ISSUE THREAD

**Issue by tvoinarovskyi** [dpkp/kafka-python#1026]
Started this as per an issue in aiokafka [Slow commit](https://github.com/aio-libs/aiokafka/issues/128).
The problem is that if a consumer starts a request with `fetch.max.wait.ms` and `fetch.min.bytes`it blocks the socket, as the protocol is synchronous.  If the same node is the coordinator node we will end up in a block for all commits, heartbeats and all other tasks. 

For example this code will (correct me if I'm wrong, didn't actually try...) slow down first commit by 500ms if there's no more data.
```python
consumer = Consumer(..., fetch_max_wait_ms=500)
while True:
    data = consumer.poll()
    for tp, messages in data.items():
        for msg in messages:
            # process message
            consumer.commit({tp: OffsetAndMetadata(msg.offset, "")})
```

**Comment by Drizzt1991** [comment]
If someone knows more on the topic I would be glad to hear. I'm not really sure how much is it a problem to separate or not separate Fetching and Coordinator sockets.

**Comment by dpkp** [comment]
Interesting. I think that's a good idea. It will probably take some
refactoring and I assume we would have to break from the Java client
design. How do they handle this problem?

**Comment by Drizzt1991** [comment]
@dpkp Currently they have a quite dirty hack in place (they just inject a new Node object with a different ID):
https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/consumer/internals/AbstractCoordinator.java#L575

[KAFKA-1935](https://issues.apache.org/jira/browse/KAFKA-1925) is the actual ticket (still not resolved) to fix that hack and get a solid implementation.

**Comment by Drizzt1991** [comment]
Haha, found out, that I made a mistake in previous comment, where I wrote KAFKA-1935, but the link was for KAFKA-1925, that was related to this issue, but was resolved with the hack. The actual followup is KAFKA-1935 =)

**Comment by dpkp** [comment]
We have added support for this using the same approach as the java client: "fake" a different coordinator node id. If/when KAFKA-1935 is resolved, we can think about adopting a different pattern.
