### ISSUE TITLE
Kafka ClusterMetadata fetches internal topics by default

### ISSUE THREAD

**Issue by shreyasp** [dpkp/kafka-python#1034]
As per the documentation for the functionality no internal topics should be fetched unless `KafkaClient.cluster.topics()` is explicitly called with `exclude_internal_topics=False`. But it seems to ignore the value of parameter and showing internal topic **`__consumer_offsets`**, rendering no effect of default truth value for `exclude_internal_topics`

Please specify, if there is any additional configuration that we need to set on producer or client to actually make the exclusion parameter effective while querying for topics using `KafkaClient`.

Also `KafkaClient.cluster.internal_topics` returns **Empty Set**

**Comment by dpkp** [comment]
Can you provide code to reproduce?

**Comment by dpkp** [comment]
Also, what do you mean 'no internal topics should be fetched'? A MetadataRequest is either sent w/ a limited topic list set to the subscription, or it is left null for all topics. There is no protocol flag that I am aware of to request all topics but not internal. So I'm not sure what you're asking for here.

See http://kafka.apache.org/protocol.html

**Comment by jeffwidman** [comment]
The consumer exposes this flag (`exclude_internal_topics`), but not the low-level client. That may have been the source of confusion.
