### ISSUE TITLE
group_id always set to NONE

### ISSUE THREAD

**Issue by PlayMa256** [dpkp/kafka-python#1035]
In my project i was using version kafka-python version `1.3.2` without any group_id parameter on KafkaConsumer (i noticed that it was calling ConsumerCoordinator), which was using the default group.

I decided to upgrade to the lastest version using pip and i got `1.3.3`. I kept using in the same way but it was throwing me errors saying that the group_id was set to NONE and auto commit was disabled. I dove into the code and print on a file the constructor so i could check the parameters it was recieving. Under [this](https://github.com/dpkp/kafka-python/blob/master/kafka/coordinator/consumer.py#L81) piece of code, i printed out `self.config` and `configs`.

#### The result was:
`self.config`:
```
{'metric_group_prefix': 'consumer', 'assignors': (<class 'kafka.coordinator.assignors.range.RangePartitionAssignor'>, <class 'kafka.coordinator.assignors.roundrobin.RoundRobinPartitionAssignor'>), 'session_timeout_ms': 30000, 'auto_commit_interval_ms': 500, 'retry_backoff_ms': 100, 'exclude_internal_topics': True, 'default_offset_commit_callback': <function <lambda> at 0x7f7030d8daa0>, 'enable_auto_commit': True, 'heartbeat_interval_ms': 3000, 'group_id': None, 'api_version': (0, 10, 1)}
```

`configs`:

```json
{'reconnect_backoff_ms': 50, 'ssl_check_hostname': True, 'fetch_max_bytes': 52428800, 'sasl_mechanism': None, 'receive_buffer_bytes': None, 'partition_assignment_strategy': (<class 'kafka.coordinator.assignors.range.RangePartitionAssignor'>, <class 'kafka.coordinator.assignors.roundrobin.RoundRobinPartitionAssignor'>), 'auto_offset_reset': 'latest', 'metadata_max_age_ms': 300000, 'bootstrap_servers': u'kafka:9092', 'sasl_plain_password': None, 'ssl_password': None, 'skip_double_compressed_messages': False, 'ssl_cafile': None, 'default_offset_commit_callback': <function <lambda> at 0x7f7030d8daa0>, 'request_timeout_ms': 40000, 'enable_auto_commit': True, 'heartbeat_interval_ms': 3000, 'ssl_keyfile': None, 'max_in_flight_requests_per_connection': 5, 'api_version': (0, 10, 1), 'ssl_certfile': None, 'assignors': (<class 'kafka.coordinator.assignors.range.RangePartitionAssignor'>, <class 'kafka.coordinator.assignors.roundrobin.RoundRobinPartitionAssignor'>), 'api_version_auto_timeout_ms': 2000, 'consumer_timeout_ms': inf, 'key_deserializer': None, 'send_buffer_bytes': None, 'ssl_crlfile': None, 'exclude_internal_topics': True, 'max_partition_fetch_bytes': 1048576, 'check_crcs': True, 'metrics_num_samples': 2, 'client_id': 'kafka-python-1.3.3', 'sasl_plain_username': None, 'selector': <class 'kafka.vendor.selectors34.EpollSelector'>, 'ssl_context': None, 'metric_group_prefix': 'consumer', 'connections_max_idle_ms': 540000, 'session_timeout_ms': 30000, 'max_poll_records': 500, 'auto_commit_interval_ms': 500, 'retry_backoff_ms': 100, 'security_protocol': 'PLAINTEXT', 'metric_reporters': [], 'metrics_sample_window_ms': 30000, 'value_deserializer': None, 'socket_options': [(6, 1, 1)], 'group_id': None, 'fetch_max_wait_ms': 500, 'fetch_min_bytes': 1}
```

As you can see, `self.config` is not being override even if i pass something in the constructor.

This was called using:  `KafkaConsumer(group_id="test", bootstrap_servers=self._server,
auto_offset_reset='latest',  auto_commit_interval_ms=500  )`

When i rolled back to version `1.3.2` it worked well, the valued passed to the constructor overrode `self.config`.

**Comment by dpkp** [comment]
This is expected -- 1.3.3 no longer sets a default consumer group. See ChangeLog:
```
* No longer configure a default consumer group (dpkp 1016)
```

**Comment by PlayMa256** [comment]
Alright, it doesnt configure, but even me forcing in the constructor a group_id, it doesnt override the one in the `DEFAULT_CONFIGS`

**Comment by dpkp** [comment]
I cannot reproduce. We have integration tests that cover this case so my hunch is your configuration is not getting passed through correctly. If you can provide a specific reproduce case and actual error messages / logs, I may be able to investigate further.
