### ISSUE TITLE
always warning in log, happens almost every 10 minutes。use Intranet address, network may not the problem， any suggestion？

### ISSUE THREAD

**Issue by chiwah-keen** [dpkp/kafka-python#1040]
kafka.conn WARNING conn.py:603 2017-03-20 12:02:27,250  <BrokerConnection host=10.165.127.38/10.165.127.38 port=9092>: socket disconnected
kafka.client WARNING client_async.py:304 2017-03-20 12:02:27,250  Node 1 connection failed -- refreshing metadata
kafka.client WARNING client_async.py:304 2017-03-20 12:02:38,620  Node 1 connection failed -- refreshing metadata
kafka.client WARNING client_async.py:304 2017-03-20 12:07:16,953  Node 1 connection failed -- refreshing metadata
kafka.client WARNING client_async.py:304 2017-03-20 12:17:19,496  Node 0 connection failed -- refreshing metadata
kafka.client WARNING client_async.py:304 2017-03-20 12:17:27,357  Node 0 connection failed -- refreshing metadata

**Comment by mike1991** [comment]
![error](https://cloud.githubusercontent.com/assets/11882117/25386185/0dfee746-29f9-11e7-9d1b-f757f8b8827f.JPG)

I have the same question. Have you solved the problem?

**Comment by dpkp** [comment]
Are you running master?

**Comment by Drizzt1991** [comment]
A side effect of dropping idle connections maybe?

**Comment by chiwah-keen** [comment]
Got no idea, it will retry and effect nothing in my opinion, so i changed warning to info.
