### ISSUE TITLE
some question when use Poll() method。

### ISSUE THREAD

**Issue by chiwah-keen** [dpkp/kafka-python#1044]
In my opinion，poll() method can get the limited number messages in a certain time。
but In a topic, i have almost 50 messages to consume per second， so i set timeout as 1000 ms
and max_records as 1000, i want to get 50 records per second not return 1 record immediately。 any suggestion？thank you!

**Comment by dpkp** [comment]
I'm not sure I understand: do you want to limit the rate of consumption?

**Comment by chiwah-keen** [comment]
I have 10 messages per second, i want to get all in 1 s not get one in 0.1 s. thank you !

**Comment by barrotsteindev** [comment]
do you mean something like spark streaming, where you specify a time window and create a sort of micro batch?
i.e. wait 15 seconds and get all the messages that were sent during that time?

**Comment by chiwah-keen** [comment]
Right.

**Comment by jeffwidman** [comment]
The following `KafkaConsumer` params provide some knobs for tuning this: `fetch_min_bytes` / `fetch_max_wait_ms` / `fetch_max_bytes`.
