### ISSUE TITLE
Does kafka-python's producer support send a picture?

### ISSUE THREAD

**Issue by raopku** [dpkp/kafka-python#1045]
or , how can kafka-python's consumer get a picture message?

**Comment by gaoyangthu** [comment]
You can pickle it to bytes and then send by producer or receive by consumer.

**Comment by Drizzt1991** [comment]
@raopku Hey there, you can send a picture same as any other data. Messages in Kafka are binary data. But the problem would be, that image data can be quite large, so could you provide details on your use case?
For example if you are developing a messaging system and you want to attach images to messages it could be quite troublesome, as the message size would very a lot.

**Comment by gaoyangthu** [comment]
@Drizzt1991 How can I send messages quite large? It is mentioned in issue #1046 . Do you have any ideas? Thanks a lot!

**Comment by jeffwidman** [comment]
This feels like a better fit for StackOverflow and not the kafka-python issue tracker as it's general Q&A about working with Kafka rather than bug report/feature request specific to `kafka-python`.

**Comment by raopku** [comment]
@Drizzt1991 Thank you
I am new to kafka-python.
I think i can use the expression below to send a picture:
```
from kafka import KafkaProducer
producer = KafkaProducer(value_serializer=lambda m: pickle.dumps(m).encode('ascii'),bootstrap_servers=['localhost:9092'])
import numpy as np
producer.send('rltest', np.zeros((2,2)))
```
And I can see somedata is stored in kafka which means that producer sends data successfully
However, i am sure how can i get it from consumer
I have tried this code
```
from kafka import KafkaConsumer
consumer = KafkaConsumer('rltest', value_deserializer=lambda m: pickle.loads(m.decode('ascii')), bootstrap_servers=['localhost:9092'])
```

i don know what API can i get the record？
consumer.poll()  return a empy {}

**Comment by dpkp** [comment]
The pythonic way to consume messages from a consumer is to use it as an iterator:
```
for message in consumer:
    do_something_with(message)
```
Otherwise you can call `consumer.poll()` but there are still some cases where it returns an empty dict. Typically you would call it in a loop:
```
while True:
    batch = consumer.poll(timeout=1000)
    for partition, messages in batch.items():
        do_something_with(messages)
```

**Comment by ajithvallabai** [comment]
Producer code 
```
from kafka import KafkaProducer
producer=KafkaProducer(bootstrap_servers=['localhost:9092'],api_version=(0,10,1))
image = cv2.imread("birds1.jpg")
ret, buffer = cv2.imencode('.jpg', image)
producer.send("TestTopic",buffer.tobytes())
```

consumer code 

```
from PIL import Image
from io import BytesIO
from kafka import KafkaConsumer
consumer = KafkaConsumer("TestTopic",bootstrap_servers=['localhost:9092'],
                        api_version=(0,10,1))

for message in consumer:
    stream = BytesIO(message.value)
    image = Image.open(stream).convert("RGBA")
    print(image.shape)
    stream.close()
    image.show()
```

its working , if on first attempt it didnt work try for next
