### ISSUE TITLE
How to correctly send messages of large size by multi-processing programming.

### ISSUE THREAD

**Issue by gaoyangthu** [dpkp/kafka-python#1046]
I want to efficiently send data of 4GB size via Kafka producer by multi-processing programming. Although the function of producer.send() does not throw any exceptions, Kafka cluster does not recieve any data by checking logs of that topic. And consumer can not fetch anything.

```python
def produce_data(cluster, topic, msg):
    producer = kafka.KafkaProducer(bootstrap_servers=cluster, acks=1)
    producer.send(self.topic, msg)
    producer.flush()
for msg in data:
    p = multiprocessing.Process(target=produce_data, args=(['host1:9092', 'host2:9092', 'host3:9092'], 'test', msg))
    p.daemon = True
    procs.append(p)
for p in procs:
    p.start()
for p in procs:
    p.join()
```

The total size of data is 4GB. It uses 16 processes to send them.
If the size of data is 4MB, everything is OK.
What is the problem?
Thank you!

**Comment by Drizzt1991** [comment]
* Just don't send 4GB messages as 1 message. If it's something around 10-20MB its ok, but not GB.
* Of course even 10s of MB are more than you can handle by default. See  http://stackoverflow.com/questions/21020347/kafka-sending-a-15mb-message for details. It's old, so your config would differ, but the idea is the same. TLDR:
```
You need to adjust three (or four) properties:

Consumer side:fetch.message.max.bytes - this will determine the largest size of a message that can be fetched by the consumer.
Broker side: replica.fetch.max.bytes - this will allow for the replicas in the brokers to send messages within the cluster and make sure the messages are replicated correctly. If this is too small, then the message will never be replicated, and therefore, the consumer will never see the message because the message will never be committed (fully replicated).
Broker side: message.max.bytes - this is the largest size of the message that can be received by the broker from a producer.
Broker side (per topic): max.message.bytes - this is the largest size of the message the broker will allow to be appended to the topic. This size is validated pre-compression. (Defaults to broker's message.max.bytes.)
```
* Don't use multiprocessing if you're only sending data without compression or preprocessing. Multiprocessing will copy your messages to new processes and spawning/killing processes will make it slow. Just create 1 producer and send data to it, the task should not be CPU bound.

Also what version of the broker are you using? If it's the newest one (0.10.1+) it should handle large messages without fetch_message_max_bytes

**Comment by gaoyangthu** [comment]
@Drizzt1991 Thanks for your reply.
In my application, I want to query data from a table in a database and concatenate all records for future aggregate calculating.
Since the size of the table is tens of GB. If using single process, it takes a long time. If using multiprocessing, it will reduce time of query data but take a long time to concatenate. Because python multiprocessing programming is inefficient for sharing memory between processes.
My solution for this problem is querying data by multiprocessing and sending them to Kafka. The version of Kafka I am using is 0.10.2.0.

**Comment by Drizzt1991** [comment]
As you are using never broker, setting proper `message.max.bytes` or `max.message.bytes` (per topic config) should be enough. But still don't send GB, split into minor messages

**Comment by gaoyangthu** [comment]
@Drizzt1991 It works. Thanks a lot.
