### ISSUE TITLE
KafkaConsumer Issue

### ISSUE THREAD

**Issue by dhuadaar** [dpkp/kafka-python#1048]
I was trying to consume a kafka-topic (say `ABC`) 

KafkaConsumer indefinitely polls without consuming a single message.

```
consumer = KafkaConsumer(
                        bootstrap_servers=<broker_id>,
                        group_id="some_id",
                        value_deserializer=lambda m: json.loads(m.decode('utf-8'))
                        )

consumer.subscribe(["ABC"])
for message in consumer:
    print message.topic, message.offset
```
The Pykafka and JavaClient works fine. (A code path is given for them as well)

```client = KafkaClient(brokers)
topic = client.topics[topicName]

consumer = topic.get_balanced_consumer(
                     consumer_group="SomeName",
                     auto_commit_enable=True,
                     use_rdkafka = True,
                     auto_commit_interval_ms =10,
                     zookeeper_connect = zkBrokers
        )

for message in consumer:
    if message is not None:
        print message.value
```
This one successfully prints the messages

Also, I get the following logs from kafka-python

```03/23/2017 12:11:10,174 kafka.coordinator INFO Successfully joined group indexer-daemon-stag-1 with generation 1
03/23/2017 12:11:10,174 kafka.consumer.subscription_state INFO Updated partition assignment: []
03/23/2017 12:11:10,174 kafka.coordinator.consumer INFO Setting newly assigned partitions set([]) for group indexer-daemon-stag-1
03/23/2017 12:11:10,347 kafka.consumer.subscription_state WARNING subscription unchanged by change_subscription([u'stag_78288_Messages_v1')
03/23/2017 12:16:10,441 kafka.consumer.subscription_state WARNING subscription unchanged by change_subscription([u'stag_78288_Messages_v1'])
```
Environment

```
OS: Ubuntu16
Python: 2.7 and 3.5
Kafka-Python=1.3.1
```

**Comment by dhuadaar** [comment]
Also

I was checking the zookeeper metadata. The kafka consumer groups with pykafka had a key set in `/consumers/<consumer-name>/ids`. Something like `[96e99aba5919:25bf04ec-40a5-4816-bfe3-8672de34225a]` .

The same in kafka-python groups are blank like `[]`

**Comment by Drizzt1991** [comment]
Can it be, that there's some other consumer with the same `group_id` as `group_id="some_id"` set in python-kafka? As I see it assigned 0 partitions to your consumer, so I would presume they were assigned to someone else.
It would be more helpful to see DEBUG level log for this case.

**Comment by jeffwidman** [comment]
IIRC, the `ids` are used by the Java code that is old consumer, before the self-balancing consumer. pykafka copies this Java style of sticking an "ids" and "owners" subnodes in zookeeper, which is why you see that. 

But kafka-python's new KafkaConsumer is a new style / self-balancing consumer, and actually shouldn't create anything under zookeeper's `/consumers` for this consumer group. 

Assuming you're only using kafka-python for this consumer group, then you should remove the subnode for it from zookeeper `/consumers`. If it comes back, then somewhere something other than kafka-python is creating a consumer group with that same name... you'd need to track that down and kill it.

**Comment by dhuadaar** [comment]
Multiple Consumers cant be an issue as I am only running a single consumer instance as of now for some testing. 

I will run the scenario with the DEBUG level logs and share the same here. 

Also, thanks for the info on zookeeper. I will evaluate  that further.

**Comment by dhuadaar** [comment]
Hello

As you said, 
>But kafka-python's new KafkaConsumer is a new style / self-balancing consumer, and actually shouldn't create anything under zookeeper's /consumers for this consumer group.

I was wondering how would a specific group-id maintain the offsets in that case in case I start multiple consumers or in case my consumer is killed for a specific group-id.

**Comment by Drizzt1991** [comment]
> I was wondering how would a specific group-id maintain the offsets in that case in case I start multiple consumers or in case my consumer is killed for a specific group-id.

Docs have all answers: https://kafka.apache.org/documentation/#impl_offsettracking. Well TLDR; 
```
When the offset manager receives an OffsetCommitRequest, it appends the request to a special compacted Kafka topic named __consumer_offsets
```
It stores commits in a special Kafka Topic.

**Comment by dpkp** [comment]
There is not enough information here to help debug your issue. As mentioned above, kafka-python does not use zookeeper so you may be experiencing some issues there. Otherwise, perhaps try `auto_offset_reset='earliest'`.
