### ISSUE TITLE
Why does KafkaClient have both `ready()` and `is_ready()` which look identical?

### ISSUE THREAD

**Issue by jeffwidman** [dpkp/kafka-python#1055]
Am I missing something?

**Comment by dpkp** [comment]
The only difference is that `ready` will initiate / complete connections. `is_ready` only reports the current state.

**Comment by dpkp** [comment]
Also it was originally based on the NetworkClient java implementation, which has separate `ready` and `isReady` methods.

**Comment by jeffwidman** [comment]
Thanks.

I'm still a little confused because the docs say `is_ready()` blocks until metadata is ready for the node, so wouldn't that be the one that initiates/completes connections before returning and not `ready`?

**Comment by jeffwidman** [comment]
Finally got a few mins to check the code. `ready()` wraps `is_ready()`, so any guarantees from `is_ready()` are inherited by `ready()`.
