### ISSUE TITLE
consumer_timeout_ms - Understanding the right approach

### ISSUE THREAD

**Issue by JohnOmernik** [dpkp/kafka-python#1065]
I have loop that uses either then number of records, the size of the records, or the time since last sync to determine when to "write" the records received in kafka. 

so:
```
maxrecs=100
maxsize=1000
maxtime=60

for message in consumer:
  cursize = len(message.value)
  currecs += 1
  listrecs = listrecs.append(message.value)
  if cursize > max size or currecs > maxrecs etc then
    o.write(listrecs)
```

This works well, however, since I have consumer_timeout_ms set to the default, if I get a records and none of the criteria are met, then I wait the max time can go well over my time because the consumer is blocked.  It needs to have ONE more record, and then it flushes based on last time, however, that's not desired behavior. 

I guees, with consumer_timeout_ms,  if I set that to be 60000 then it will raise an exception if nothing has been heard in that time right?  My main question is this, can I catch that exception to cause a "flush" of my current records, while still leaving the consumer open? I don't want to reopen the consumer or find my place, I just want something to be triggered every 60000ms that let's me flush any cached records, and then continue to wait... is this how it would work? If so, could you please show me where I would put the try block? i.e. would try:  for message in consumer? Any links or examples would be much appreciated. 

Thanks!

John

**Comment by dpkp** [comment]
something like this:

```
while True:
    for msg in consumer:
        maybe_write(msg)
    else:
        # handle consumer_timeout_ms
        always_write(msg)
```
