### ISSUE TITLE
How to best signal aliveness

### ISSUE THREAD

**Issue by jmgpeeters** [dpkp/kafka-python#1070]
I have a situation where I have two consumers (c1 and c2), and want to poll from c1 until there is nothing left (c1.poll(..) returns empty), and then start polling from c2 (and check c1 again afterwards). Essentially, c1 has priority over c2.

Now, this means I'll be polling frequently from c1, and ideally I just want to keep c2 alive until I need it. If I don't poll it at all until I want to, I eventually get kafka.error.CommitFailedError when I commit c2, because the time between its polls was too long and things have rebalanced.

So I tried interleaving c1.poll(...) with something like c2.poll(timeout, 0), just to signal that it  shouldn't rebalance, and I don't want records right now, but this runs into the assertion that the max_records needs to be larger than 0.

So is there any way to signal (a heartbeat of sorts) that c2 is still there, I just don't want any records from it right now? Something poll(timeout, 0) would achieve, I guess, if it was allowed.

Thanks!
-Joris.

**Comment by jeffwidman** [comment]
You could write a custom assignment strategy for the consumers. And just say "assign all partitions to the first consumer in the group". Then any additional consumers are assigned no partitions, they are merely backup for HA failover purposes if the first consumer dies.

**Comment by jmgpeeters** [comment]
Should probably have clarified that the two consumers are listening to different topics, in different consumer groups.  The use case is more that of joining two different streams together.

**Comment by jeffwidman** [comment]
I'm not sure there's a clean way to handle this. You'll probably need to do this within your app somehow. You can easily do poll() and it will return with no values and then switch to another consumer, but as you're probably aware under the covers the async thread is still fetching records, even if you don't fetch them into the main thread with poll(). At least, that's how the docs implies it works, I haven't looked at the actual code in detail. So if the concern is you don't even want them fetched at all, then I'm not sure how to do that. If you just don't want them in the main thread, that's easy enough to stop once poll() returns 0, and then do some other processing.
