### ISSUE TITLE
consumer poll() and iterator interface

### ISSUE THREAD

**Issue by ugomariaguicciardini** [dpkp/kafka-python#1071]
Hi all,

This is a simplified versione of my code:

```
consumer = KafkaConsumer('mytopic', bootstrap_servers=[server], group_id=group_id, enable_auto_commit=True)
#dummy poll
consumer.poll()
#go to end of the stream
consumer.seek_to_end()
#start iterate
for message in consumer:
    print(message)

consumer.close()
```

The documentation states that the poll() method is incompatible with the iterator interface, which i guess is the the one I use in the loop at the end of my script. However from initial testing, this code looks like to work correctly.

Is it safe to use it? Or did I misunderstood the docuementation?

I apologize for cross-posting this question on stackoverflow.

Thanks
UMG

**Comment by dpkp** [comment]
why not just use `auto_offset_reset='latest'` ?

**Comment by ugomariaguicciardini** [comment]
Hi,

thanks for the answer, even if my question wasnt very clear. Apologize for that!
With 

`auto_offset_reset='latest'`

I dont get the rusults I want.

Here is what i would like to achieve: when my producer starts, i would like it will start to consume messages from kafka, generated only after the time the consumer was started. Basically it will consume the newest messages only, ingnoring the ones generated while the consumer was down.

How can I achieve that?

Thanks

**Comment by dpkp** [comment]
Don't use auto commit

**Comment by ugomariaguicciardini** [comment]
Hi!
Thanks for the answer. Also please excuse me if i ma asking silly questions but i am going through the learning curve of kafka and some concepts might still be not clear enough to me.

If i set enable_auto_commit=False and i dont do any manual offset control, i should restart from the oldest message of the queue every time i start the consumer. Is this correct?
If this is the case, it is the opposite from what i want to do it (i want to restart from the newest message).

For the java consumer doc, looks like the suggested way to control the position of the offset of the queued messages from a consumer is to use the seek() methods. 
Is this true also in the python-kafka apis?

If yes, is the code below valid?

```
consumer = KafkaConsumer('mytopic', bootstrap_servers=[server], group_id=group_id, enable_auto_commit=True)
#dummy poll
consumer.poll()
#go to end of the stream
consumer.seek_to_end()
#start iterate
for message in consumer:
    print(message)

consumer.close()
```
Thanks
UMG

**Comment by dpkp** [comment]
use `auto_offset_reset` to choose whether to start at beginning or end of a partition.

**Comment by jcrsilva** [comment]
@dpkp I'm using that strategy (kafka 10) and auto_offset_reset is not working

**Comment by jeffwidman** [comment]
I'm highly doubtful this is a bug as we run kafka 10.0 and `auto_offset_reset='latest'` in production at my day job. So I think this is better handled over in StackOverflow questions, as it's likely just a misunderstanding of what the settings are doing.

**Comment by jscrapy** [comment]
@jeffwidman this is a bug I think and I agree @ugomariaguicciardini . I tried many method to let my client to read  the newest message from kafka but failed. 
```python
def do_check():
    logger = logging.getLogger()
    # consumer = KafkaConsumer(config.kafka_raw_proxy_topic, bootstrap_servers=config.kafka_bootstrap_server,
    #                          group_id=config.kafka_check_proxy_thread_group,
    #                          value_deserializer=lambda m: json.loads(m.decode('utf-8')), auto_offset_reset='latest',
    #                          enable_auto_commit=True)
    consumer = KafkaConsumer(bootstrap_servers=config.kafka_bootstrap_server,
                             value_deserializer=lambda m: json.loads(m.decode('utf-8')), auto_offset_reset='latest',
                             enable_auto_commit=True)
    producer = KafkaProducer(bootstrap_servers=config.kafka_bootstrap_server,
                             value_serializer=lambda m: json.dumps(m).encode('utf-8'))

    partation_num = len(consumer.partitions_for_topic(config.kafka_raw_proxy_topic))
    partition_order = int(threading.current_thread().getName())
    assigned_partation = str(partition_order % partation_num)
    if partation_num > config.TASK_OK_PROXY_SCAN_THREAD_N:
        logger.error("线程数目比kafka partition数目要小，因此不是所有的数据都能被处理掉")
    logger.info("start..")

    mypartition = TopicPartition(config.kafka_raw_proxy_topic, assigned_partation)
    assigned_topic = [mypartition]
    consumer.assign(assigned_topic)
    last_pos = consumer.end_offsets(assigned_topic)
    consumer.seek(mypartition, last_pos-2)
    # consumer.seek_to_end(TopicPartition(config.kafka_raw_proxy_topic, assigned_partation))
    print_vol = 0;
    consumer.poll()

    for msg in consumer:
        proxy = msg.value

```

the code hung at  `for msg in consumer` for ever and get nothing, but my kafka really got many message from producer。

**Comment by jscrapy** [comment]
I and @ugomariaguicciardini just want to skip some `timeout` message, just want to process the comming message.

**Comment by jeffwidman** [comment]
@jscrapy can you open a new bug report? Generally when someone chimes in super late, on a closed bug report, it's actually a different issue and easier to discuss in a new thread.

**Comment by jeffwidman** [comment]
--@jscrapy can you open a new bug report? Generally when someone chimes in super late, on a closed bug report, it's actually a different issue and easier to discuss in a new thread.--

Actually, looks like you already filed #1405

**Comment by jscrapy** [comment]
@jeffwidman   should use both  auto_offset_reset ='latest' and enable_auto_commit=False  to consume the latest message(skip the old msg)
