### ISSUE TITLE
Kafka notify: RecordAccumulator is closed

### ISSUE THREAD

**Issue by vokhuongcse0604** [dpkp/kafka-python#1075]
I write a program with multi thread to send messages using 1 procedure. It run ok but after 30 minutes, it throw an exception "RecordAccumulator is closed". I dont understand why and how can i fix it?

**Comment by jeffwidman** [comment]
Threading is not recommended/supported for `kafka-python` as it's already multi-threaded and so it's easy for application threads to step on each other. Try multi-process or you might be able to get away with `gevent` style greenlets, but I don't know, I've never had an excuse to play with them much.

**Comment by jianbin-wei** [comment]
@vokhuongcse0604, do you have a sample program that can re-produce the issue?  What is the exception stack?
