### ISSUE TITLE
Will KafkaConsumer re-commit offsets even if there are no new messages?

### ISSUE THREAD

**Issue by jeffwidman** [dpkp/kafka-python#1076]
The Java consumer's behavior is that if there are no new messages to consume, then it won't commit a new offset because the new offset would be the same as the old offset.

However, Kafka brokers remove offsets that are older than `offsets.retention.minutes`, which defaults to 1440. So if a partition doesn't get a new message in that time, then the existing consumer offset will be deleted because its too old, even though the consumer is alive and working. 

If the consumer defaults to `earliest`, this deletion by the broker will cause the consumer to reprocess all messages in the partition. If the consumer defaults to `latest`, then the consumer will miss any messages that are produced to the partition between the final `poll()` call with an existing offset and the next `poll()` that defaults to `latest`.

KAFKA-3806 and KAFKA-4682 both describe the problem and potential
workarounds.

How does the `KafkaConsumer` handle this scenario? Do we also need to amend it's behavior to regularly re-commit unchanged offsets?

**Comment by jianbin-wei** [comment]
> On Apr 12, 2017, at 16:16, Jeff Widman <notifications@github.com> wrote:
> 
> The Java consumer's behavior is that if there are no new messages to consume, then it won't commit a new offset because the new offset would be the same as the old offset.
> 
> However, Kafka brokers remove offsets that are older than offsets.retention.minutes, which defaults to 1440. So if a partition doesn't get a new message in that time, then the existing consumer offset will be deleted because its too old, even though the consumer is alive and working
> 
I think this "the consumer is alive and working" is not complete.  It is very possible that the consumer is stopped for more than 1440 minutes and is started again.

**Comment by dpkp** [comment]
Can you link to the upstream kafka issue? As I understand it, the offsets are calculated via `SubscriptionState.all_consumed_offsets()` and that does not limit the offsets to those that have not already been committed. The java client uses the same logic, so I'm surprised by this description. Is it an error at the broker-level? If the offset didn't change, the broker discards the commit?

**Comment by jeffwidman** [comment]
KAFKA-3806 and KAFKA-4682 both describe the problem and potential
workarounds.

**Comment by dpkp** [comment]
Ok -- I dont think auto_commit in either client is affected by this. But
there are plenty of folks that disable auto-commit and commit offsets
manually based on the messages consumed. Certainly if using the message
iterator in KafkaConsumer while attempting to manually commit offsets could
hit this issue. Nonetheless, I do not think it affects standard auto-commit
consumers. In either case, I'm not sure that there is much to be done at
the client.

**Comment by Drizzt1991** [comment]
@jeffwidman Thanks for the issue, I had no idea there even was a retention for commits. This behaviour should have really been documented in Kafka's docs. I find the behaviour very unintuitive, so thanks for sharing the info.
