### ISSUE TITLE
kafka consume one message and stop listening

### ISSUE THREAD

**Issue by ishitat** [dpkp/kafka-python#1080]
Hi,

I want to achieve something like this. Consumer connect to kafka node. Fetch a message (If exists) and return.

How can I do it with this lib?

**Comment by Drizzt1991** [comment]
For starts be aware, Kafka is not designed for such a use case. What is you're use case? Do you actually spawn a process, get 1 message and exit? If not it would make more sense to persist the consumer between requests.
But as you asked it should be something like:
```python
from kafka import KafkaConsumer

consumer = KafkaConsumer(
    'my-topic',
    group_id='my-group',
    bootstrap_servers=['localhost:9092'])
for msg in consumer:
    # Process your message
    print ("%s:%d:%d: key=%s value=%s" % (message.topic, message.partition,
                                              message.offset, message.key,
                                              message.value))

    # End after only 1 message
    break
consumer.close()
```
