### ISSUE TITLE
No way of getting metadata, that was committed with OffsetAndMetadata

### ISSUE THREAD

**Issue by tvoinarovskyi** [dpkp/kafka-python#1082]
When we use `consumer.commit({tp: OffsetAndMetadata(msg.offset+1, "Some metadata")})` the API requires us to pass the `OffsetAndMetadata` structure, but then that metadata can't be retured nowhere.
In Java Client it's returned as part of `consumer.committed(tp)` response. See https://kafka.apache.org/0101/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#committed(org.apache.kafka.common.TopicPartition)

@dpkp Any ideas how to go with API change to fix this? Like we can't just change the return value of `committed` at this point without a deprecation period.

**Comment by dpkp** [comment]
I think we can just add an optional parameter like `consumer.committed(tp, metadata=True)`
