### ISSUE TITLE
Call the producer.close() in a while loop will case an Error 

### ISSUE THREAD

**Issue by CheongHoo** [dpkp/kafka-python#1090]
my code is like this:

    while True:
        producer = KafkaProducer(bootstrap_servers=KAFKA_SERVER)
        producer.send('test', b'xxx')
        producer.close()

it will cause a error like bellow:
error: [Errono 9] Bad file descriptor
point to the line
`if self._wake_w.send(b'x') !=1` in the client_async.py

**Comment by ryanjmccall** [comment]
addressed in the latest release 1.3.4 cf https://github.com/dpkp/kafka-python/pull/1069
