### ISSUE TITLE
Flush Raising AssertionError

### ISSUE THREAD

**Issue by infecto** [dpkp/kafka-python#1094]
https://github.com/dpkp/kafka-python/blob/07e09c1c2ec6787fc7e4f3c2578d31b4a15d20bc/kafka/producer/record_accumulator.py#L525

We are still unsure why but we are encountering the above assertion failing in a small percentage of cases. Maybe network issues, rebalancing, the reason has yet to be determined. 

This AssertionError bleeds through. Instead I think kafka-python should be catching it and raising a defined exception within this framework. Any thoughts?

**Comment by dpkp** [comment]
Agree. `producer.flush()` should either raise a KafkaTimeout exception or just return False if the flush did not complete within the specified timeout. Happy to merge a PR for this.

**Comment by infecto** [comment]
@dpkp Will create a PR. Thanks

**Comment by infecto** [comment]
@dpkp https://github.com/dpkp/kafka-python/pull/1097
