### ISSUE TITLE
Retry hidden danger.

### ISSUE THREAD

**Issue by chiwah-keen** [dpkp/kafka-python#1099]
Question:
     6 brokers cluster, and kafka-python as client,
     logs show that if one process connect to broker failed  then kafka-python will retry all the time, 
    so there will be too many connections, all the connections's  status  is WAIT_CLOSE 。after that broker down.
Opinion:
    in my opinion, if one broker down, or connection failed, kafka-python should not try to connect the same broker, is this true, anyone can solve this?

**Comment by Drizzt1991** [comment]
I don't find any WAIT_CLOSE status in kafka's code, did you mean that you have a lot of TCP sockets in ``CLOSE_WAIT `` state? Is so, please provide some details:

* The problem is on Broker or Client machine?
* Are client's producing, consuming or both?
* What kind of Broker failure are you simulating/experiencing? TCP sockets should not have CLOSE_WAIT if it's a hard failure of the machine...

**Comment by chiwah-keen** [comment]
Sorry, It's tcp CLOSE_WAIT status, details as follows:
1， The problem is on Broker。
2，The client producing and consuming
3，Brokers seems work well， until "netstat -ant" command tells me the number of connection is too large.
thank u.

**Comment by Entiy** [comment]
> Sorry, It's tcp CLOSE_WAIT status, details as follows:
> 1， The problem is on Broker。
> 2，The client producing and consuming
> 3，Brokers seems work well， until "netstat -ant" command tells me the number of connection is too large.
> thank u.



> Question:
> 6 brokers cluster, and kafka-python as client,
> logs show that if one process connect to broker failed then kafka-python will retry all the time,
> so there will be too many connections, all the connections's status is WAIT_CLOSE 。after that broker down.
> Opinion:
> in my opinion, if one broker down, or connection failed, kafka-python should not try to connect the same broker, is this true, anyone can solve this?

@chiwah-keen  Did you solve this question? I also meet this question as the same
