### ISSUE TITLE
seek_to_beginning causes consumer iteration stop

### ISSUE THREAD

**Issue by starplanet** [dpkp/kafka-python#1100]
my test code is following:
```python
from kafka import KafkaConsumer
consumer = KafkaConsumer('test', bootstrap_servers=['172.16.24.45', '172.16.24.44'], group_id='mygroup')
consumer.seek_to_beginning()

# first call the following code, iteration will immediately return
for msg in consumer:
    print(msg)

# Try again, iteration will output records.
for msg in consumer:
    print(msg)
```

As shown above, when I call seek_to_beginning and first use consumer iteration, it will immediately return. Then I try again, it will output records.
Can I control this strange behavior?

**Comment by dpkp** [comment]
This is fixed in kafka-python 1.4.7, though you will have to subscribe to a topic and get partitions assigned before you can seek_to_beginning
