### ISSUE TITLE
Client is trying to connect to local host only

### ISSUE THREAD

**Issue by sanksh** [dpkp/kafka-python#1102]
With this code:
class Producer(threading.Thread):
    daemon = True
    
    def run(self):
        producer = KafkaProducer(bootstrap_severs= ['192.168.1.69'])
        while True:
            producer.send('kafkatopic', b'Test message')
            time.sleep(1)
            
Client is failing trying to connect to broker on local host only

**Comment by jeffwidman** [comment]
How do you know that's the root cause of the problem? Is there an actual exception you're seeing?
