### ISSUE TITLE
KafkaProducer stuck when connecting to remote kafka

### ISSUE THREAD

**Issue by NoneGG** [dpkp/kafka-python#1103]
## problem
Hi dear, my KafkaProducer stuck when trying to connect to remote kafka. The code always runs smoothly and it is the first time the problem take place. Should i use a connect timeout parameter to avoid similar problem again? I am not sure whether it is the problem of network or client (since the kafka server has no related error log)

The log is like below, please notice the time, it seems to got stuck for hours and then run again
```
[I 170513 05:31:53 cdn_consumer    : 313] SID: 2728 IN CDN WHITE LIST: False
[I 170514 23:22:28 conn            : 808] Broker version identifed as 0.10
[I 170514 23:22:28 conn            : 810] Set configuration api_version=(0, 10) to skip auto check_version requests on startup
```
I try to trace the bug, and the only thing after logging `SID: 2728 IN CDN WHITE LIST: False` is initialization of a KafkaProducer, and it seems to be stucked when trying to check api version?

## config

kafka-python==1.3.1

``` Python
BOOTSTRAP_SERVERS = ['172.16.xxx.xxx', '172.16.xxx.xxx' ]
KAFKA_PRODUCER_CONFIG = {
    'bootstrap_servers': BOOTSTRAP_SERVERS,
    'batch_size': 1024,
}
```

**Comment by jeffwidman** [comment]
What version are your Kafka brokers?

**Comment by NoneGG** [comment]
@jeffwidman 
Sorry for the late response, i was not notified by github.
The version of broker is 0.10 and from then on the bug never occurs again, so i think it may be the problem caused by IDC network and hard to reproduce.
