### ISSUE TITLE
Add CreateTopics support to kafka-python's AdminClient

### ISSUE THREAD

**Issue by vineetgoel** [dpkp/kafka-python#1104]
From what I know, currently there is support for creating topics only with the `client.ensure_topic_exists`. It would be nice to be able to create topics using the Kafka Create Topics protocol mentioned here: https://kafka.apache.org/protocol#The_Messages_CreateTopics

This would be useful for programmatically creating topics with custom configs/partition number.

**Comment by vineet-rh** [comment]
Looks like the protocol structs are defined: https://github.com/dpkp/kafka-python/blob/master/kafka/protocol/admin.py#L51-L87 but I can't seem to find its usage. Am I missing something here?

**Comment by Drizzt1991** [comment]
No, you are correct, there is still no implementation for AdminClient. There's an open issue #935 for this. The main problem, as far as I remember, is that Java's Kafka still does not have an interface for this too. It will be released in 0.11 ~ mid summer. I would expect `kafka-python` to follow up shortly.

**Comment by jeffwidman** [comment]
This landed in https://github.com/dpkp/kafka-python/pull/1540, many thanks to @llamahunter
