### ISSUE TITLE
Clearly document that KafkaConsumer is not thread safe

### ISSUE THREAD

**Issue by ecksun** [dpkp/kafka-python#1105]
The question is basically in the title.

On the one hand, we had `MultiprocessConsumer` which I assume must be, but it has been deprecated in favor of `KafkaConsumer`, which leads me to think that `KafkaConsumer` also is thread safe.

On the other hand I just got this error using it:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "code/node_list/reaction.py", line 27, in run
  File "code/env/local/lib/python3.5/site-packages/event_consumers/event_consumer.py", line 28, in __iter__
    for message in self.consumer:
  File "code/env/local/lib/python3.5/site-packages/kafka/consumer/group.py", line 964, in __next__
    return next(self._iterator)
  File "code/env/local/lib/python3.5/site-packages/kafka/consumer/group.py", line 904, in _message_generator
    self._client.poll(timeout_ms=poll_ms, sleep=True)
  File "code/env/local/lib/python3.5/site-packages/kafka/client_async.py", line 525, in poll
    responses.extend(self._poll(timeout, sleep=sleep))
  File "code/env/local/lib/python3.5/site-packages/kafka/client_async.py", line 578, in _poll
    response = conn.recv()  # Note: conn.recv runs callbacks / errbacks
  File "code/env/local/lib/python3.5/site-packages/kafka/conn.py", line 607, in recv
    response = self._recv()
  File "code/env/local/lib/python3.5/site-packages/kafka/conn.py", line 654, in _recv
    raise Errors.KafkaError('this should not happen - are you threading?')
kafka.errors.KafkaError: KafkaError: this should not happen - are you threading?
```

Which suggest it is not.

Edit: [this example](https://github.com/dpkp/kafka-python/blob/master/example.py) also clearly indicates that using threading should be fine

Can I safely use `KafkaConsumer` in a threaded environment?

**Comment by dpkp** [comment]
No. KafkaConsumer is not suitable for sharing across threads.

**Comment by ecksun** [comment]
> No. KafkaConsumer is not suitable for sharing across threads.

Alright, if I interpret that literally thats not a problem in my case (nor in the example). As both I and the example I linked have one consumer per thread. Is that also an unsuitable setup?

**Comment by dpkp** [comment]
Thread-local KafkaConsumer should work. I wouldn't recommend it for other
reasons, but it should not crash.

**Comment by ecksun** [comment]
> Thread-local KafkaConsumer should work. I wouldn't recommend it for other
reasons, but it should not crash.

What reasons are those? What would you recommend?

**Comment by dpkp** [comment]
I'd recommend multiprocessing for running parallel consumers. Python
threading is not useful given GIL.

**Comment by jeffwidman** [comment]
Actually, re-opening as this is a consistent question on the issue tracker, implying we should more explicitly address this in the readme and/or docs.

**Comment by ecksun** [comment]
> I'd recommend multiprocessing for running parallel consumers. Python
threading is not useful given GIL.

Yes, I actually rewrote all my stuff to use multiprocessing, turns out the instrumentation library I use (prometheus) doesn't support that :(

> Actually, re-opening as this is a consistent question on the issue tracker, implying we should more explicitly address this in the readme and/or docs.

Yes, I was going to suggest that.

Both detailing in the docs that no, it is not thread safe (unlike the producer), as well as the recommendation for multiprocessing.

**Comment by ecksun** [comment]
I created a small PR for it, consider it a draft and feel free to do anything with it, I just thought I would provide something to start with.

**Comment by dpkp** [comment]
Thanks for the PR w/ documentation updates. Merged!
