### ISSUE TITLE
KafkaConsumer re-consumes all topics if metadata changes

### ISSUE THREAD

**Issue by Drizzt1991** [dpkp/kafka-python#1108]
I'm not sure if this is desirable,  but it sure is unintuitive. 
```python
from kafka import KafkaConsumer
import random

# To consume latest messages and auto-commit offsets
consumer = KafkaConsumer(group_id="Test_Kafka_python-%s" % random.random(),
                         bootstrap_servers=['localhost:9092'],
                         metadata_max_age_ms=5000,
                         auto_offset_reset="earliest",
                         enable_auto_commit=False)
consumer.subscribe(pattern="test-ok-*")
for message in consumer:
    # message value and key are raw bytes -- decode if necessary!
    # e.g., for unicode: `message.value.decode('utf-8')`
    print ("%s:%d:%d: key=%s value=%s" % (message.topic, message.partition,
                                          message.offset, message.key,
                                          message.value))
```

If you consume from a pattern (say `test-ok-*`), disable autocommit and add a new topic (say consumed 10msgs from ``test-ok-1`` and add ``test-ok-2``) Consumer will replay all data read before (those 10msgs from `test-ok-1`).

**Comment by Drizzt1991** [comment]
The same behaviour will happen if metadata changes, like partition count is changed for subscribed topic.

**Comment by hustshawn** [comment]
How about you specify a fixed group id instead of the random one?  Since Kafka will deliever the msg to every consumer group which subscribed the topic.

**Comment by Drizzt1991** [comment]
@hustshawn It's random, so the script is reproducible, it's not from any production codebase.
And no, inactive groups don't have overhead in performance. They only stay in memory causing minor memory overhead.

**Comment by barrotsteindev** [comment]
@Drizzt1991  Do you commit messages you've already read?

**Comment by dpkp** [comment]
That is the expected behavior for this configuration. You've chosen (1) group coordination, (2) not committing offsets, (3) auto resetting to earliest. It's certainly a strange combination, but if you choose to configure that way you should expect to get reset to the beginning on any group or broker change.

**Comment by Drizzt1991** [comment]
I would not expect such behaviour in any way. Think about it, it means that you may not call `poll` without committing at all. Code like this:
```
msgs_count = 0
while True:
    msgs = consumer.poll(timeout_ms=5000)
    # Process messages
    msgs_count += sum([len(batch) for batch in msgs.values()])
    if msgs_count >= 1000:
        msgs_count = 0
        consumer.commit()
```

Becomes completely broken. You can have duplicates or *SKIP* messages without any warning of whatsoever (depending on reset policy).

**Comment by dpkp** [comment]
yes, that is how kafka works. You should plan for duplicates if you choose `earliest` or skipped messages if you choose `latest`. Alternately you can choose `None` and have an exception raised and you can manage the issue manually.

**Comment by Drizzt1991** [comment]
Ok, lets say that's the case for `group_id` set to something. You need to commit and will not have an issue here. But what about `group_id=None`. The same problem arises and you can't commit, cause you have no group. Basically pattern subscription is not usable with `group_id=None`.

**Comment by dpkp** [comment]
I think most uses of `group_id=None` use auto_offset_reset `latest` . Note that the java client does not permit group_id=None, so it is very much a convenience function added by kafka-python.

**Comment by Drizzt1991** [comment]
@dpkp Thanks for the information. While the behaviour still seems strange to me, it's clearly as designed and Java's client should behave in a similar fashion.
I will try to move this discussion to Kafka's main tracker to understand the reasons behind such behaviour.
