### ISSUE TITLE
consumer_timeout_ms block  forever

### ISSUE THREAD

**Issue by fword** [dpkp/kafka-python#1109]
when i set consumer_timeout_ms to 5000,it block forever. but when i set it to 1000, it don't block why is that

**Comment by Drizzt1991** [comment]
Enable debug logging and try to figure out, or post them here, we'll help you. Right now we can only guess...

**Comment by fword** [comment]
how can i enable debug logging in python-kafka

my code is like this 
class KafkaClient(object):
    def __init__(self, config):
        self.brokers = config.get('kafka', 'brokers').split(',')
        self.topics = config.get('kafka', 'topics')
        self.group = config.get('kafka', 'group')
        self.max_partition_fetch_bytes = config.getint('kafka', 'max_partition_fetch_bytes')
        self.consumer_timeout_ms = config.getint('kafka', 'consumer_timeout_ms')
        self.producer = KafkaProducer(bootstrap_servers = self.brokers)
        self.consumer = KafkaConsumer(self.topics, group_id = self.group, bootstrap_servers = self.brokers, max_partition_fetch_bytes =
 self.max_partition_fetch_bytes, consumer_timeout_ms = self.consumer_timeout_ms)

    def get_consumer(self):
        return self.consumer

    def get_producer(self):
        return self.producer


   def handle_kafka(self):
        self.record = []
        for message in self.consumer:
            self.record.append(message)

**Comment by dpkp** [comment]
See https://docs.python.org/3/library/logging.html for info about python logging. A quick and dirty approach:
```
import logging
logging.basicConfig(level='DEBUG')
```
