### ISSUE TITLE
How can I continue reading a topic in Kafka using kafka-python?

### ISSUE THREAD

**Issue by d-chugunov** [dpkp/kafka-python#1110]
It's a continuation of issue https://github.com/dpkp/kafka-python/issues/1015 In short the problem is that kafka stores group offsets for 24 hours by default. Eventually if my group consumer haven't been working for more than 24 hours it starts reading for the end of the topic. But I can't find kafka configuration option to change this store time. What can I do? Is there a way to increase this time besides writing my own offsets storage?

**Comment by jeffwidman** [comment]
Google for `offsets.retention.minutes`
