### ISSUE TITLE
Does KafkaConsumer automatically commit offsets with manual partition assignment/Kafka 0.8.2.1?

### ISSUE THREAD

**Issue by dcrosta** [dpkp/kafka-python#1111]
Since we're using Kafka 0.8.2.1, we are unable to use the GroupCoordinator, and so we have to use assignment of partitions manually. I do set a group_id to the same value across the several consumers that share the partitions.

I haven't been able to trace through the code yet, and the docs don't clearly state that offsets are committed when using this set up. I hope it's the case that they are, but I wanted to get a confirmation here.

**Comment by dpkp** [comment]
Yes, though you will need to enable auto-commit or otherwise call `consumer.commit()` manually. 0.8.2.1 uses zookeeper-backed offset storage.

**Comment by dcrosta** [comment]
Cool thanks!
