### ISSUE TITLE
poll() does not always return messages

### ISSUE THREAD

**Issue by demestav** [dpkp/kafka-python#1113]
After subscribing to a partition of a topic which contains messages and then calling `poll()`, sometimes it doesn't return the messages. Even though the position can be set at an arbitrary position (using `seek()`), the `poll()` command needs to be executed multiple times to return the messages.

Example code:

	from kafka import KafkaConsumer
	from kafka import TopicPartition

	consumer = KafkaConsumer(group_id='test', bootstrap_servers='kafka')
	tp = TopicPartition('test',0)

	consumer.assign([tp])
	consumer.seek_to_beginning()
	consumer.position(tp) # Returns 0
	consumer.poll() # Returns {} --- Expecting to return the messages
	consumer.position(tp) # Returns 0 

	# Code below may need multiple runs to return the messages
	consumer.poll() # Returns the messages
	consumer.position(tp) # Returns 60

**Comment by Drizzt1991** [comment]
Did you try to pass `timeout_ms` to poll?

**Comment by demestav** [comment]
@Drizzt1991 I tried your suggestion and after some quick testing, it seems to work!

**Comment by Drizzt1991** [comment]
The default is `timeout_ms=0`, so you can sometimes assume, it will wait for a message infinitely, but it will only do a single check and return right away. The iterator interface will always return messages if you need something more easy to work with:
```
for msg in consumer:
    # Process message.
```

**Comment by demestav** [comment]
> it will wait for a message infinitely

> it will only do a single check and return right away

Aren't these two contradicting?

**Comment by Drizzt1991** [comment]
Sorry, my english ) I ment it will NOT wait infinitely and only do a single check.

**Comment by demestav** [comment]
Thank you for clarifying.

Since this is the expected behavior, I am closing this.
