### ISSUE TITLE
Exception on host:port given as quoted environment variable

### ISSUE THREAD

**Issue by jwbowen** [dpkp/kafka-python#1115]
I set an environment variable `KAFKA_HOSTS="kafka:9103"`, then attempted to create a consumer by passing the environment variable `kc = kafka.KafkaConsumer(os.environ.get('KAFKA_HOSTS'))` and received an exception: `ValueError: invalid literal for int() with base 10: '9103"'`.

The snippet above works if I change the environment variable to `KAFKA_HOSTS=kafka:9103`. I would have expected it to handle the environment variable being quoted, though.

**Comment by dpkp** [comment]
Looks like you are putting literal quotes in the variable value, which is
generally not ok. Not the same as shell quoting in shell, which does not
include literal quotes in the value.
