### ISSUE TITLE
Trouble trying to get meta-data from Kafka - consumer group lag

### ISSUE THREAD

**Issue by buchs** [dpkp/kafka-python#1116]
I ultimately want to be able to find out the lag in particular consumer groups. I spent a lot of time trying to get this to work, but fell short. I will attach a zip archive containing a Jupyter notebook and HTML capture of it to show what I was trying. I found no information was returned for Consumer.assignment() and later method calls. Any help you can provide would be appreciated.

[Archive.zip](https://github.com/dpkp/kafka-python/files/1061069/Archive.zip)

**Comment by jeffwidman** [comment]
Here's an example of how I did it: https://github.com/DataDog/integrations-core/pull/423
