### ISSUE TITLE
Multiple consumers with same group id get same message

### ISSUE THREAD

**Issue by dfdx** [dpkp/kafka-python#112]
Kafka manual says that each message is delivered exactly to one consumer from a group (with a same group id). And this is what I see with Java high-level API and expected to see with Python's `SimpleConsumer`. However, when I run 2 consumers simultaneously (see code below) and send new message, both instances of consumer receive it. 

---

```
# consumer.py
from kafka.client import KafkaClient
from kafka.consumer import SimpleConsumer

kafka = KafkaClient("broker", 9092)
consumer = SimpleConsumer(kafka, "my-group", "my-topic",
                          auto_commit=False)
while True:
    msg = consumer.get_message()
    if msg:
        print(msg)
    else:
        print('no new messages')
kafka.close()
```

---

```
# producer.py
from kafka.client import KafkaClient
from kafka.producer import SimpleProducer

kafka = KafkaClient("broker", 9092)

producer = SimpleProducer(kafka, "my-topic")
producer.send_messages("my message")

kafka.close()
```

---

Note, that `auto_commit` in consumer is set to `False` to overcome problem with Kafka 0.8.1 and current version of kafka-python, but changing it to True only adds exceptions and doesn't fix consumption problem.

**Comment by coffenbacher** [comment]
Is #164 still the answer for this one? Looks like it is still open / possibly abandoned. @wizzat is it expected to work out of the box on a single partition? I'll test it out, just wondering what the expected behavior is.

This is pretty important for my team, so if there's no working solution yet I may take a shot at adding this

**Comment by magcius** [comment]
It seems #164 was closed with "it was fixed with other commits" -- is that the case? We're still not seeing consumer balancing with kafka-python.

**Comment by magcius** [comment]
Oh, it seems this will be implemented in #38 -- this is a dupe of that, basically.

**Comment by dpkp** [comment]
yes, #38 is the tracking issue. consumer rebalancing will be supported when using kafka brokers >= v0.9.0.0 . Development is on the 0.9 git branch.

**Comment by sadaf2605** [comment]
```
pip3 freeze | grep kafka
kafka==1.3.4.1
```
All my consumer with same group are getting all the same messages from all the producers.
