### ISSUE TITLE
why we can't define self.producer=KafkaProducer in a subclass of multiprocessing.Process?

### ISSUE THREAD

**Issue by jeffreysoon** [dpkp/kafka-python#1120]
#I notice if we do:
`
Class A(Process):
    def __init__(self):
        self.producer = KafkaProducer(**config)
`
we would hit kafkatimeout: failed to allocate memory error.

But if we define producer in other function other than __init__, it works.
`Class A(Process):
     def run(self):
        producer = KafkaProducer(**config)
`
I searched, and @dpkp said "You should not expect to share a KafkaProducer instance across processes; instead you will need to create a new instance for each process."
I am confused. In my understanding, self.producer is not shared across processes. In first class, each instance has its producer instance, and it's not shared.
Can anyone please direct me? Thanks.

**Comment by dpkp** [comment]
This is mostly just multiprocessing semantics. The Process object is instantiated in the calling process, so anything you do in __init__ is actually *shared* and will need to be pickled. It may be that 'run' is executed in the subprocess context and is not shared. This would explain why one fails and the other works. Nonetheless, I'd recommend not subclassing multiprocessing.Process. Just define a function and pass it with `target=`.  See https://docs.python.org/3/library/multiprocessing.html
