### ISSUE TITLE
Examples for having on_assign and on_revoke callbacks for consumer

### ISSUE THREAD

**Issue by amitripshtos** [dpkp/kafka-python#1129]
Hey guys, thanks for awesome package!
I was wondering how should I add callbacks when my consumer is assigning/revoking partitions,

The problem is that my consumer is stateful, and when a topic is being assign/revoked I need to change the application state.

I could not find any good callback for that (I'm used to from confluent kafka), and I was wondering if I miss something

Thanks!

**Comment by amitripshtos** [comment]
Sorry, I found ConsumerRebalanceListener
The docs are not easy to understand this one, thanks anyway :)

**Comment by jeffwidman** [comment]
Pull requests to improve the docs and add examples are always welcome.
