### ISSUE TITLE
Consumer Group_id not showing up in KafkaMonitor

### ISSUE THREAD

**Issue by krautt** [dpkp/kafka-python#1131]
I've noticed that using the client against 0.8.2 brokers that the group_id specified upon creating the consumer object doesn't show up in the KafkaMonitor tool (https://github.com/linkedin/kafka-monitor)  

I know the readme suggests an upgrade to a newer broker but it would be great to not have to do that at this point for me.  Has anyone seen this/resolved it?  Thanks - jason.

**Comment by Drizzt1991** [comment]
Kafka-python client manages group information in the same way Java client would. The deal here is that Kafka 0.8 brokers don't have the API that KafkaMonitor uses to list groups. If you need support for 0.8.2 brokers you could post an issue on KafkaMonitor side...

**Comment by krautt** [comment]
ok thanks for the explanation.
