### ISSUE TITLE
IRC channel #kafka-python on Freenode

### ISSUE THREAD

**Issue by mumrah** [dpkp/kafka-python#114]
FYI, just created an IRC channel on freenode.net for this project. This channel is for users of the library as well as developers.

<a href="irc://irc.freenode.net/kafka-python">#kafka-python on Freenode</a>

**Comment by takwas** [comment]
Is this still in use? (It doesn't appear to be.)

**Comment by mumrah** [comment]
I would guess that it's not active anymore. You can open issues on this project or maybe try the kafka-clients mailing list https://groups.google.com/g/kafka-clients/about
