### ISSUE TITLE
How to deserialize or parse a bytearray

### ISSUE THREAD

**Issue by Mairire** [dpkp/kafka-python#1144]
In my consumer, I am receiving messages that are representing time series in a bytearray (or bytes), each reading two bytes long. These have been serialized on the sending end in Java. I need to deserialize them in Python, in chunks of two bytes, and turn them into array of ints. So far, I did not manage to find a good solution. I have tested something like this, it works fine for the first two bytes but it does not work once I try to put it in the loop and iterate through offsets.

```python
a= bytes(msg.val[0:2]) 
beat = int.from_bytes(a, "little")
print(a) #checkpoint
print(beat) #checkpoint
```

I am new to both python and kafka, and so far I could not make any version of the iterations work. Let me know what am I missing and if python-kafka has any API similar to Java for serialization.

**Comment by dpkp** [comment]
This is more of a general python question, but since you asked:
```
In [1]: import struct
In [2]: foo = b'\x01\x02\x03\x04\x05\x06\x07\x08\x09\x0a'
In [3]: [struct.unpack('>H', foo[i:i+2])[0] for i in range(0, len(foo), 2)]
Out[3]: [258, 772, 1286, 1800, 2314]
```

See python docs for `struct` package. Likely you'll want to pick an appropriate format string to set for your byte order (big or little endian), and integer type (signed or unsigned).
