### ISSUE TITLE
Kafka exactly once support

### ISSUE THREAD

**Issue by vineet-rh** [dpkp/kafka-python#1145]
Is there a plan on when kafka-python will support the newly added exactly once semantics using Idempotent and Transactional Producers?

**Comment by dpkp** [comment]
I'm not working on this specifically, but it sounds like fun! kafka-python code mostly mirrors the java client, so if someone wants to tackle then the place to start is to look at the PRs merged into the java client and merge those changes in here.

**Comment by tvoinarovskyi** [comment]
I believe that we can close this in favour of existing #1063 to track the issue.
