### ISSUE TITLE
Kafka Producer may not invoke callback both successfully and error

### ISSUE THREAD

**Issue by nghiaminhle** [dpkp/kafka-python#1150]
Hi all,

I've used kafka producer for months. When i send a message, i use two callback both successfully and error. If the callback is successful, my application'll work normally and have the log data about the successful message. If the callback is fail, our application'll stop and start a retry process. Below is my config:
`class KafkaPublisher(EventHandler):
    _producer = None  # KafkaProducer

    def __init__(self):
        self._producer = KafkaProducer(
                                    bootstrap_servers=kafka_bootstrap_server, 
                                    max_in_flight_requests_per_connection=1, 
                                    retries=2147483647, 
                                    acks='all')
    
    def handle(self, envelope, success_callback, fail_callback):
        topic = envelope.topic
        partition_key = str.encode(envelope.partition_key) if envelope.partition_key != None else None
        json_body = json.dumps(envelope.body.to_dict(), sort_keys=True, default=datetime_handler)
        future = self._producer.send(topic, str.encode(json_body), partition_key)
        future.add_callback(success_callback, checkpoint=envelope.log_metadata)
        future.add_errback(fail_callback, checkpoint=envelope.log_metadata)`

The successful and error handles:
`
def _publish_successful_callback(self, metadata, checkpoint: BinLogMetadata):
        self._checkpoint_commiter.release_checkpoint(checkpoint)
        self._instrumentation.publish_to_kafka()
`

`
def _publish_fail_callback(self, metadata, checkpoint: BinLogMetadata):
msg = "Publish Kafka Fail {} {}".format(datetime.now(), checkpoint.key)
logger = logging.getLogger('general')
logger.debug(msg)
self.stop()
`

Is there anyone has the same issue similar mine? Could you give me some guildline.
Thank all!

**Comment by jeffwidman** [comment]
What is the actual problem you are hitting?

All I see is sample code, no exception or problem description.
