### ISSUE TITLE
Does the Kafka-python supports balanced consumer like pykafka?

### ISSUE THREAD

**Issue by amitt001** [dpkp/kafka-python#1153]
I think kafka-0.9 natively supports the balanced consumer and earlier only JVM languages supported it. Now that this support is there and Pykafka already supports it for so long.

Is this feature available in kafka-pyhton also?

**Comment by dpkp** [comment]
Yes. afaik pykafka uses a custom zookeeper management system that they wrote prior to server apis in 0.9 . kafka-python requires the server apis, so you must have server version 0.9 +.

**Comment by amitt001** [comment]
@dpkp Can you please point me to the docs describing how to achieve this?

**Comment by dpkp** [comment]
See kafka-python.readthedocs.org . All you have to do is use the same
group_id

**Comment by jeffwidman** [comment]
Use Kafka brokers >= 0.9 and the `KafkaConsumer` class (not the deprecated `SimpleConsumer`)
