### ISSUE TITLE
Question: 1.3.4 availability?

### ISSUE THREAD

**Issue by bjustin-ibm** [dpkp/kafka-python#1157]
Sorry to have to ask this, but I couldn't find the answer elsewhere... is there a planned release date for 1.3.4? I have a need for one of the post-1.3.3 commits, but pulling the client directly using a commit hash gives me the willies.

Thanks in advance!

**Comment by dpkp** [comment]
No set plans. It does seem like we should release soon though!

**Comment by bjustin-ibm** [comment]
@dpkp Thanks, I'll keep checking back. FWIW, 1.3.4 has, I believe, significant improvements in the way producer connections are established, making it much faster to establish a new connection. At least to my code, that's a big win 😉

**Comment by jeffwidman** [comment]
https://github.com/dpkp/kafka-python/pull/1160 will also be very useful for our production code as we just hit a very similar issue in production with our `pykafka` based producers, while our old `SimpleClient` based producers hummed merrily along. We are just starting to roll out `KafkaProducer`-based clients, so looking forward to seeing this land.

**Comment by dpkp** [comment]
1.3.4 released -- https://github.com/dpkp/kafka-python/releases/tag/1.3.4
