### ISSUE TITLE
KafkaProducer send() method missing callback parameter.

### ISSUE THREAD

**Issue by jpaulodit** [dpkp/kafka-python#1163]
Is there a reason why the KafkaProducer `send` method does not support the use of callback? I noticed it is in the Java implementation. https://kafka.apache.org/0101/javadoc/index.html?org/apache/kafka/clients/producer/KafkaProducer.html

I am thinking of exposing the error callback used internally here. https://github.com/udemy/kafka-python/blob/master/kafka/producer/future.py#L38 Is that a good idea and what issues do I need to be aware of?

The problem I am trying to solve is to log exceptions when the send fails without using synchronous send with `get`. Calling `send` function inside a try-except block does not work.

**Comment by dpkp** [comment]
`producer.send` returns a future to which you can add any callbacks / errbacks that you need. See
https://github.com/dpkp/kafka-python/blob/1.3.3/kafka/future.py#L48-L64

**Comment by dpkp** [comment]
specifically, try `producer.send(...).add_errback(my_custom_log_method)`

**Comment by jpaulodit** [comment]
Thank you for responding so quickly. I appreciate it ! 
The solution works for me.
