### ISSUE TITLE
Question: Do we have some kafka tools ?

### ISSUE THREAD

**Issue by buptljy** [dpkp/kafka-python#1170]
I am trying to use kafka-python to inspect a topic's basic information such as partitions, 
but I am not sure that the module can help me because I didn't see any instructions.
I am using kafka-python 1.3.3.

Is there any way that can help me do this with python instead of using command line ?
`kafka-topics --list --zookeeper localhost:2181`
`kafka-run-class kafka.tools.GetOffsetShell --broker-list localhost:9092 -topic vital_signs --time -1`

**Comment by tvoinarovskyi** [comment]
I think what you really want is https://github.com/dpkp/kafka-python/issues/935, but we still did not work on that.

**Comment by jeffwidman** [comment]
It's been a little while since I looked at the protocol low-level primitives, but I suspect you can get this by reaching deep into the `kafka-python`'s internals and using `KafkaClient` to do explicit sending/receiving of protocol structs. 

But as @tvoinarovskyi said what you really want is #935
