### ISSUE TITLE
KafkaProducer.send with explicit key fails to send message to broker

### ISSUE THREAD

**Issue by AnvilStriker** [dpkp/kafka-python#1172]
Using kafka-python 1.3.3., Python 2.7.11-1

Brief description of issue:

Sending messages without an explicit key works fine, and results in random partitioning as expected. Sending *with* a string key (where `key_serializer` has been initialized to `str.encode`) results in **no** messages being sent, ever.

Furthermore, attempting to determine what happened to the `send` in the latter case by calling `get` on the object returned by `send` raises a `TypeError` exception, with the message "descriptor 'encode' requires a 'str' object but received a 'unicode'".

Detailed description of issue is here: https://stackoverflow.com/questions/45470055/kafka-python-1-3-3-kafkaproducer-send-with-explicit-key-fails-to-send-message-t

**Comment by tvoinarovskyi** [comment]
How about you don't use `str.encode`? What do you even want to achieve with it?
```python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> str.encode(u"Some message")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: descriptor 'encode' requires a 'str' object but received a 'unicode'
```

**Comment by tvoinarovskyi** [comment]
I mean the error is from you're key serializer: `str.encode`.

**Comment by AnvilStriker** [comment]
I got `str.encode` from the example in the documentation. Since my key is a string, I need a key_serializer to turn it into bytes, no?

And in any case, if the problem is with key or its encoding, shouldn't the exception be raised by `KafkaProducer.send` rather than `FutureRecordMetadata.get`?

**Comment by AnvilStriker** [comment]
Argh, you are right. I was convinced that my key value was a `str` -- but in fact it is a `unicode`. When I encode it directly using `.encode('utf-8')`, my messages do get published, and they do partition consistently. So thanks for making me re-examine my assumptions. 

One thing that made this more difficult than it needed to be was the inadequacy of documentation on `FutureRecordMetadata`, and on what one can expect as a result of calling `get` on it. The sole example in the documentation suggests that the only kind of exception one should expect from it is `KafkaError`, which I now understand isn't the only possibility. `get` can in fact raise *any* exception that `KafkaProducer.send` encountered.

The concept of a calling a function so that it will raise an arbitrary exception that was encountered by some *other* function is unusual enough that some explanation of that model should be given in the documentation.

**Comment by jeffwidman** [comment]
Thanks for reporting back. Pull requests to improve the docs are always appreciated.

**Comment by AnvilStriker** [comment]
Excellent, thanks! Will see what I can come up with.
