### ISSUE TITLE
How to request for metadatas conveniently?

### ISSUE THREAD

**Issue by buptljy** [dpkp/kafka-python#1178]
It seems that kafka-python has only two main roles: KafkaConsumer and KafkaProducer, and we need to initialize one of them before our opreration. However, we don't want to be a consumer or a producer when we request for kafka metadata such as partition offsets for a specific topic. Have you considered adding a new role in kafka-python such as "metadata-tools" ?

**Comment by tvoinarovskyi** [comment]
So you need something like Admin tools, to only check that no partitions are lagging and such? If so, you can track our progress on https://github.com/dpkp/kafka-python/issues/935. There's still no roadmap for it thou.
