### ISSUE TITLE
Poll does not returns all the produced messages

### ISSUE THREAD

**Issue by 88manpreet** [dpkp/kafka-python#1179]
Scenario: (all in a single process)
1. Create and start a consumer
2. Produce 4 messages
3. Poll for 4 messages (timeout can be low to very high)
Result poll always returns 2 messages.
4. 2nd poll returns remaining 2 messages.

Some observations:
1. Waiting after producing messages does not have any effect (i.e. messages are produced).
2. If we sleep for 1 second after starting the consumer (step 1) i.e. starting the consumer, the first poll returns 4 messages.
3. timeout in poll does not seem to an issue here.

**Comment by jeffwidman** [comment]
This really sounds like a tuning error and very unlikely to be a bug with kafka-python.

Can you post your code here along with what version of kafka-python and kafka that you're using and a copy of your kafka cluster's server.properties file?

**Comment by dpkp** [comment]
The consumer is not transactional. This doesn't seem to me like incorrect behavior.
