### ISSUE TITLE
Travis build failing with error "cryptography 1.9 is not compatible with PyPy < 5.3"

### ISSUE THREAD

**Issue by 88manpreet** [dpkp/kafka-python#1181]
For KAFKA_VERSION=0.9.0.1 and python:pypy, the job is failing with the following error:
"RuntimeError: cryptography 1.9 is not compatible with PyPy < 5.3. Please upgrade PyPy to use this library."
More details [here](https://travis-ci.org/Yelp/kafka-python/jobs/266953868).

It looks like it fails while trying to download latest coveralls pakage (version-1.2) which was uploaded on pypi on [08-16-2016](https://pypi.python.org/pypi/coveralls). The latest kafka-python build seem to have been run on master on 08-15-2017 and probably that's why it's not caught yet.
The build fails trying to download cryptography package for pypy version 2.5 (required minimum 5.3).

Could the PyPy version be upgraded on the box where the job is running?

**Comment by jeffwidman** [comment]
I don't see this error with the current travis tests on master.

**Comment by dens2204** [comment]
i have same problem
