### ISSUE TITLE
consumer.assign and consumer.subscribe mixed in a same group cause crash

### ISSUE THREAD

**Issue by buaawht** [dpkp/kafka-python#1182]
OS:mac Darwin Kernel Version 15.6.0
Kafka version:0.11.0.0

1.  Use python-kafka to create a consumer, group_id = 'my_group', use the assign method to subscribe to a specific topic = 'assign_topic', partition = [0,1,2,3,4],  create five consumer to consume messages, consumer.assign() do not use consumer's group Management functionality.

2.  Now I create a new consumer, subscribe the new topic = 'subscribe_topic' using consumer.subscribe() method,  the partitions can be dynamically balanced, partitions = [0,1,2,3,4], group_id = 'my_group', start the consumer.

3.  Results: the consumer created in Step2 is running successfully with the topic of 'subscribe_topic', but the five consumers created in Step1 looks like died (the process did not throw an exception, use ps -ef can find pid is still alive), but cannot get any messages.  [Kafka official website](https: //kafka.apache.org/090/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html) states:
**It is not possible to mix both answer to specific partitions (with no load balancing) and to topics (with load balancing) using the same consumer instance.** . But the key point is that my mixed subscription is not used in a same consumer instance.

4.  When I changed the consumer group_id in Step2, such as group_id='hello_topic', everything goes well. I am not sure what reason cause the issue. Maybe I use the consumer incorrectly. Maybe...

**Comment by buaawht** [comment]
OS:mac Darwin Kernel Version 15.6.0
Kafka version:0.11.0.0

1.  Use python-kafka to create a consumer, group_id = 'my_group', use the assign method to subscribe to a specific topic = 'assign_topic', partition = [0,1,2,3,4],  create five consumer to consume messages, consumer.assign() do not use consumer's group Management functionality.

2.  Now I create a new consumer, subscribe the new topic = 'subscribe_topic' using consumer.subscribe() method,  the partitions can be dynamically balanced, partitions = [0,1,2,3,4], group_id = 'my_group', start the consumer.

3.  Results: the consumer created in Step2 is running successfully with the topic of 'subscribe_topic', but the five consumers created in Step1 looks like died (the process did not throw an exception, use ps -ef can find pid is still alive), but cannot get any messages.  [Kafka official website](https: //kafka.apache.org/090/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html) states:
**It is not possible to mix both answer to specific partitions (with no load balancing) and to topics (with load balancing) using the same consumer instance.** . But the key point is that my mixed subscription is not used in a same consumer instance.

4.  When I changed the consumer group_id in Step2, such as group_id='hello_topic', everything goes well. I am not sure what reason cause the issue. Maybe I use the consumer incorrectly. Maybe...

**Comment by tvoinarovskyi** [comment]
I'm a bit confused about the use case of running such a setup. @buaawht what did you want to achieve with running such consumers in the same group? Did you assign each consumer 1 partition in the first example?

**Comment by dpkp** [comment]
Please attach a code sample that reproduces this issue. I'm closing for now.
