### ISSUE TITLE
Getting cluster metadata not working ...

### ISSUE THREAD

**Issue by rugging24** [dpkp/kafka-python#1183]
Hello ,
I tried using the class : kafka.cluster.ClusterMetadata, and its associated functions such as broker_metadata or brokers.
And it always returns this part of the code: 

return 'ClusterMetadata(brokers: %d, topics: %d, groups: %d)' % \
               (len(self._brokers), len(self._partitions), len(self._groups))

perhaps I am doing something wrong, could someone please show a workable example on how to use this ?

Cheers

**Comment by jeffwidman** [comment]
What is the specific error you are seeing? Do you have a reproducable code example?

**Comment by rugging24** [comment]
Here's a sample script am using : 


#!/usr/bin/python


import kafka


class MonitorUtils(object):
    @staticmethod
    def kProducer(config):
        """ obtain a kafka producer"""
        return kafka.KafkaProducer(**config)

    @staticmethod
    def kConsumer(config):
        """obtain a kafka consumer"""
        return kafka.KafkaConsumer(**config)

    @staticmethod
    def clusterMetadata(config):
        return kafka.cluster.ClusterMetadata(**config)

    def getBrokerStats(self,config):
        return self.clusterMetadata(config).brokers()


if __name__ == "__main__":
    config = {'bootstrap_servers': ''}
    print MonitorUtils().getBrokerStats(config,'fridatestTopic')




result : 

set([])

**Comment by jeffwidman** [comment]
It's late, so I may be missing something, but it looks like you're trying to use the cluster w/o an associated client. 

I would instead instantiate a KafkaClient, then access it's connected cluster object, as the client is what handles actually updating the state of the cluster object to represent the real broker state.
