### ISSUE TITLE
Can't get kafka-python module working

### ISSUE THREAD

**Issue by kchandan** [dpkp/kafka-python#1186]
I downloaded the kafka from official website and followed the steps.

https://kafka.apache.org/quickstart

I can get the kafka producer and consumer working from official shell scripts provided. Then I followed python-kafka official [ from this github repo ] but could not get message sent across using Python producer and consumer. 

If I try to use it without providing the api_version=(0,10), it always complains about NoBroker error. I checked other issues reported on github and checked my hostname etc. Anyways I switched using IP instead to root out any DNS issue. I am using VM on my local machine.

```
producer = KafkaProducer(bootstrap_servers=['127.0.0.1:6667'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/kafka/producer/kafka.py", line 347, in __init__
    **self.config)
  File "/usr/lib/python2.7/site-packages/kafka/client_async.py", line 220, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/usr/lib/python2.7/site-packages/kafka/client_async.py", line 841, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
```

If I use the api_version, it suppresses the error but messages are never received on the other side

Python Producer:
```
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from kafka import KafkaProducer
>>> from kafka.errors import KafkaError
>>> producer = KafkaProducer(bootstrap_servers=['127.0.0.1:6667'],api_version=(0,10))
>>> ret = producer.send('test','Hello World from Python')
>>> ret
<kafka.producer.future.FutureRecordMetadata object at 0x11c3850>
>>>

```

Python Consumer:
```
>>> consumer = KafkaConsumer('test',bootstrap_servers=['127.0.0.1:6667'],api_version=(0,10))
>>> for msg in consumer:
...     print(msg)
...

```
Producer [official example working]:
```
[root@localhost kafka]# /usr/hdp/2.6.1.0-129/kafka/bin/kafka-console-producer.sh --broker-list localhost:6667 --topic test
Hello
```
Consumer[official example working]:
```
/usr/hdp/2.6.1.0-129/kafka/bin/kafka-console-consumer.sh --bootstrap-server localhost:6667 --topic test --from-beginning
Hello
```

I am using 

Kafka | 0.10.1
CentOS 7
HDP 2.6.1
[ I am having same issue if I manually download kafka jars from official Apache kafka website]

**Comment by tvoinarovskyi** [comment]
Hey there. You probably did not configure the `advertised.listeners` property in broker config. See https://kafka.apache.org/documentation/#brokerconfigs.
You can confirm, if it's not a `kafka-python` issue if you try console producer (https://kafka.apache.org/quickstart#quickstart_send) and console consumer (https://kafka.apache.org/quickstart#quickstart_consume) examples from the Quickstart tutorial.

**Comment by tvoinarovskyi** [comment]
Basically `advertised.listeners` is what's used for broker discovery. Ie. those are the addresses clients will connect to after the initial bootstrap connection (which is done based on `bootstrap_servers `)

**Comment by kchandan** [comment]
Thanks, as suspected it was configuration issue. Thanks for such a prompt response.
