### ISSUE TITLE
Does auto-commit happen when also explicitly committing?

### ISSUE THREAD

**Issue by smontanaro** [dpkp/kafka-python#1190]
Looking at #722 I saw the submitter didn't explicitly turn off auto-commit, but calls the consumer's commit() method. In that scenario, are auto-commits also happening, or does the first call to commit() disable any auto-commit actions? I ask because I want to control when commits happen. do I need to explicitly pass enable_auto_commit=False when instantiating the KafkaConsumer instance?

**Comment by dpkp** [comment]
Yes, you must explicitly pass `enable_auto_commit=False` to disable.
