### ISSUE TITLE
KafkaConsumer Re-process messages / rewind to offset not working as expected

### ISSUE THREAD

**Issue by y5wang** [dpkp/kafka-python#1191]
Trying to re-process messages in a partitioned topic by ```seek(p, offset)```. To do that, first I need to get the active assignment which only works after a successful ```poll()```. I assume if I specify ```auto_offset_reset``` to ```'earliest'```, I should be able to do that, but it didn't work. The code is here:

```
from kafka import KafkaConsumer

consumer = KafkaConsumer('my.topic', group_id='grp001', 
                         bootstrap_servers='localhost:9092', 
                         auto_offset_reset='earliest')

while True: 
    rec = consumer.poll(timeout_ms=1000, max_records=1)
    if len(rec) > 0:
        break;

topic_partitions = consumer.assignment()
offset = dict(zip(topic_partitions, [1503500000000]*len(topic_partitions)))
for p in topic_partitions:
    consumer.seek(p, offset[p].offset)
```

The call to ```poll()``` never succeeds until new messages are produced. Am I missing anything? I thought setting ```auto_offset_reset``` to ```'earliest'``` would let me go back and re-process the old messages. Do I need to do anything else? 

Running kafka-python 1.3.4 and kafka 0.11.0. The topic has three partitions. Thanks for any help.

**Comment by tvoinarovskyi** [comment]
Specifying `auto_offset_reset='earliest'` will not work if you already have a working commit point in the group. To force the position to the beginning you can do `consumer.seek_to_beginning()`. See http://kafka-python.readthedocs.io/en/master/apidoc/KafkaConsumer.html#kafka.KafkaConsumer.seek_to_beginning

**Comment by tvoinarovskyi** [comment]
If you could elaborate more on what you are trying to achieve I can help you with an actual code snippet, but I don't know when do you want to reprocess message...

**Comment by y5wang** [comment]
@tvoinarovskyi, thanks for the comments and suggestion. 

The immediate requirement is for a client to replay a topic partition from a given timestamp at client startup. Eventually business logic requires to seek back to find a specific message. 

I can't really do a ```seek_to_beginning()``` right after consumer declaration since no partitions are assigned. Would appreciate any help.

**Comment by tvoinarovskyi** [comment]
There is a problem with what you want to achieve - using a consumer group can trigger rebalances, at which you will lose the position of your consumer. So not only will you need to call `seek_to_beginning` on startup, but also decide what to do on rebalances. You can use a `listener` argument to [subscribe()](http://kafka-python.readthedocs.io/en/master/apidoc/KafkaConsumer.html#kafka.KafkaConsumer.subscribe) to perform actions before rebalances.

If you only need 1 consumer, not a [group](https://kafka.apache.org/documentation/#intro_consumers), just provide `group_id=None`. In this case, you will not rebalance and can not commit offsets, but `auto_offset_reset ` will do what you want (there's no commit point, and only 1 reset will be done on startup). If `group_id=None` it will assign all partitions at start, so you can `seek()` without waiting.

As for the timestamp, you are using a new Kafka, so just use [offsets_for_times](http://kafka-python.readthedocs.io/en/master/apidoc/KafkaConsumer.html#kafka.KafkaConsumer.offsets_for_times) API to get the offset you need to start from and seek to it.

**Comment by y5wang** [comment]
Thanks, @tvoinarovskyi 

My immediate issue is at startup to get a list of subscribed partitions of a consumer using consumer group so I can seek. ```seek_to_beginning()``` or set ```auto_offset_reset``` to ```'earliest'``` doesn't seem to work for different reasons. Just wondering if there is a solution. 

When rebalance happens, as you suggested, I can use a ```listener``` hook to determine if existing partitions arrive or leave then act accordingly. 

At the moment, the startup is the trouble I'm facing. :(

**Comment by tvoinarovskyi** [comment]
The best way is to provide a listener as such:
```python
from kafka import ConsumerRebalanceListener, KafkaConsumer


class MyListener(ConsumerRebalanceListener):

    def __init__(self, consumer):
        self.consumer = consumer

    def on_partitions_revoked(self, revoked):
        pass

    def on_partitions_assigned(self, assigned):
        print("partitions assigned", assigned)
        self.consumer.seek_to_beginning()


consumer = KafkaConsumer(
    bootstrap_servers="localhost:9092", group_id="grp1",
)
my_listener = MyListener(consumer)
consumer.subscribe("topic", listener=my_listener)

try:
    for msg in consumer:
        # Process messages
        print(msg)
finally:
    consumer.close()
```
If you want to just do it at the start this should do it:
```python
from kafka import KafkaConsumer


consumer = KafkaConsumer(
    bootstrap_servers="localhost:9092", group_id="grp1",
)
consumer.subscribe("topic")
consumer.poll(timeout_ms=0)  # Poll will always join group
print(consumer.assignment())
consumer.seek_to_beginning()

try:
    for msg in consumer:
        # Process messages
        pass
finally:
    consumer.close()
```

**Comment by dpkp** [comment]
Try using assign() instead of subscribe(). This will allow you to seek
without poll(). The reason this works is that subscribe forces the client
to check metadata for the topic within the poll() call. Assigning
partitions manually does not require fetching metadata so you can seek
immediately.

**Comment by jeffwidman** [comment]
I'm going to close because it sounds like the issue here is now well understood/explained. If there's an actual bug, happy to re-open.

**Comment by y5wang** [comment]
Thanks everybody for the help. I have got the startup part working with ```subscribe()```, ```offsets_for_times()``` and ```seek()```. Trying the listener callback. Will report back. 

@dpkp : If I understand it correctly, using ```assign()``` instead of ```subscribe()``` will end up with manual partition management which makes it very difficult if not impossible to be in a group where consumers come and go.
