### ISSUE TITLE
No brokersAvilable

### ISSUE THREAD

**Issue by ray1888** [dpkp/kafka-python#1192]
i just using a docker to start kafka services.but i fail to get the message from kafka by kafka-python module.but i use shell command to get message ,it work .so where is the problem?
shell command result:
root@5a781c3f9081:/usr/local/kafka/kafka_2.11-0.11.0.0# bin/kafka-console-consumer.sh --bootstrap-server kafka01:9092 --topic mysql_slow_log --from-beginning
# Time: 2017-08-29T12:05:34.002911Z
# User@Host: root[root] @ localhost []  Id:    14
# Query_time: 1.274002  Lock_time: 0.000484 Rows_sent: 200002  Rows_examined: 800015
SET timestamp=1504008334;
select stu.stuID,stu.stuName,c.classID,c.className, sc.score from class c,student stu,  course sc where c.classID=stu.classID and stu.stuID=sc.stuID order by c.classID,stu.stuID;

python error log:
DEBUG:kafka.conn:<BrokerConnection node_id=bootstrap host=127.0.0.1/127.0.0.1 port=9092> Request 1: MetadataRequest_v0(topics=[])
ERROR:kafka.conn:<BrokerConnection node_id=bootstrap host=127.0.0.1/127.0.0.1 port=9092>: Error receiving 4-byte payload header - closing socket
Traceback (most recent call last):
  File "/root/.virtualenvs/py2/local/lib/python2.7/site-packages/kafka/conn.py", line 737, in _recv
    data = self._sock.recv(bytes_to_read)
error: [Errno 104] Connection reset by peer
INFO:kafka.conn:<BrokerConnection node_id=bootstrap host=127.0.0.1/127.0.0.1 port=9092>: Closing connection. ConnectionError: [Errno 104] Connection reset by peer
DEBUG:kafka.conn:<BrokerConnection node_id=bootstrap host=127.0.0.1/127.0.0.1 port=9092>: reconnect backoff 0.054901787795 after 1 failures
ERROR:kafka.client:Unable to bootstrap from [('127.0.0.1', 9092, 2)]
NoBrokersAvailable: NoBrokersAvailable

**Comment by hugoren** [comment]
你要加上api_version这个参数

**Comment by tvoinarovskyi** [comment]
you're trying to connect to `127.0.0.1` in *kafka-python*, but use `kafka01 ` host for *console consumer*.
