### ISSUE TITLE
How can I use multiprocess consumer on kafka-brokers-0.8.1 ？

### ISSUE THREAD

**Issue by efeiefei** [dpkp/kafka-python#1197]
```
# Use multiple consumers in parallel w/ 0.9 kafka brokers
# typically you would run each on a different server / process / CPU
consumer1 = KafkaConsumer('my-topic',
                          group_id='my-group',
                          bootstrap_servers='my.server.com')
consumer2 = KafkaConsumer('my-topic',
                          group_id='my-group',
                          bootstrap_servers='my.server.com')
```

Is that mean KafkaConsumer can only be in parallel 0.9.x or higher version kafka brokers ？

Thx!

**Comment by jeffwidman** [comment]
You need Kafka 0.9 for the new consumer group APIs. If this doesn't make sense, I suggest reading the book on Kafka that Confluent provides for free to better understand overall Kafka design. And trust me, if you're on 0.8.1, you really want to upgrade, I had way too many production issues with the 0.8.x series...

**Comment by dpkp** [comment]
I agree with jeff. I'll only add that if you are using 0.8.1 brokers, your best approach to parallel consumers is going to be manually assigning different partitions to each of your subprocesses. This means you will not have "rebalancing" and you will need to monitor each of your consumers health yourself, and further that you will need to monitor load distribution among consumers. But it does work fine for some applications (I have a few that use this approach even with newer 0.10 brokers).
