### ISSUE TITLE
TypeError: 'JavaPackage' object is not callable?

### ISSUE THREAD

**Issue by saurabhbidwai** [dpkp/kafka-python#1201]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-b69a81af6891> in <module>()
      1 if __name__=="__main__":
----> 2     main()

<ipython-input-2-8489d7e61ff5> in main()
      1 def main():
      2     conf = SparkConf().setMaster("yarn-client").setAppName("Streamer")
----> 3     sc = SparkContext(conf=conf)
      4 
      5     # Creating a streaming context with batch interval of 60 sec

/home/daasuser/anaconda2/lib/python2.7/site-packages/pyspark/context.pyc in __init__(self, master, appName, sparkHome, pyFiles, environment, batchSize, serializer, conf, gateway, jsc, profiler_cls)
    116         try:
    117             self._do_init(master, appName, sparkHome, pyFiles, environment, batchSize, serializer,
--> 118                           conf, jsc, profiler_cls)
    119         except:
    120             # If an error occurs, clean up in order to allow future SparkContext creation:

/home/daasuser/anaconda2/lib/python2.7/site-packages/pyspark/context.pyc in _do_init(self, master, appName, sparkHome, pyFiles, environment, batchSize, serializer, conf, jsc, profiler_cls)
    186         self._accumulatorServer = accumulators._start_update_server()
    187         (host, port) = self._accumulatorServer.server_address
--> 188         self._javaAccumulator = self._jvm.PythonAccumulatorV2(host, port)
    189         self._jsc.sc().register(self._javaAccumulator)
    190 

TypeError: 'JavaPackage' object is not callable

**Comment by tvoinarovskyi** [comment]
Again, no mention of kafka-python. You will have more luck asking spark community about those errors.
