### ISSUE TITLE
The producer can send data , but consumers do not get data

### ISSUE THREAD

**Issue by hugoren** [dpkp/kafka-python#1205]
Consumers do not return data
return  object  "<kafka.consumer.group.KafkaConsumer object at 0x10bb35278>"

mycode (I'll follow the official example):
    
     consumer = KafkaConsumer('t3', bootstrap_servers=['{0}:{1}'.format(HOST, PORT)],
                             )
    print(consumer)
    for message in consumer:
        # message value and key are raw bytes -- decode if necessary!
        # e.g., for unicode: `message.value.decode('utf-8')`
        print("%s:%d:%d: key=%s value=%s" % (message.topic, message.partition,
                                             message.offset, message.key,
                                             message.value))

why?

**Comment by tvoinarovskyi** [comment]
Did you confirm, that you're setup works with any other client, ex. Console consumer, which ships with kafka distribution.

**Comment by jeffwidman** [comment]
Closing for now, if you try with a console consumer and it works fine but fails with this error than we can re-open and discuss further. If re-opening, we'll need the version of both the Kafka broker and the kafka-python code that you're using.

**Comment by hugoren** [comment]
yes, thank you !
console consumer works well.
but fails with kafka-python
kafka version is 2.11-0.11.0.0
kafka-python code is 
     def kafka_consumer():
    consumer = KafkaConsumer('t3', bootstrap_servers=['{0}:{1}'.format(HOST, PORT)],

                             )
    print(consumer)
    for message in consumer:
        # message value and key are raw bytes -- decode if necessary!
        # e.g., for unicode: `message.value.decode('utf-8')`
        print("%s:%d:%d: key=%s value=%s" % (message.topic, message.partition,
                                             message.offset, message.key,
                                             message.value))
i can't find the err
please help me

**Comment by jeffwidman** [comment]
I'm actually going to close this, this example code works perfectly, so sounds like a networking or firewall issue or some other misconfiguration.

**Comment by dpkp** [comment]
FYI, to enable logging add this to your python script:
```
import logging
logging.basicConfig(level='INFO')
```
