### ISSUE TITLE
SASL_PLAINTEXT authentication failure, doesn't even connect to the Kerberos server

### ISSUE THREAD

**Issue by adamjsonar** [dpkp/kafka-python#1217]
I'm trying to establish a SASL_PLAINTEXT connection to Kafka via kafka-python.

I am providing the necessary arguments listed in the documents:

    {
     'sasl_mechanism': 'PLAIN',
     'sasl_plain_username': 'user',
     'sasl_plain_password': 'secret',
     'security_protocol': 'SASL_PLAINTEXT'
    }

However, it always fails with the following error:

    File "/home/adam/j/kafka/.venv/lib/python3.4/site-packages/kafka/conn.py", line 461, in _handle_sasl_handshake_response
      return self._try_authenticate_plain(future)
    File "/home/adam/j/kafka/.venv/lib/python3.4/site-packages/kafka/conn.py", line 495, in _try_authenticate_plain
      raise error
    kafka.errors.AuthenticationFailedError: AuthenticationFailedError: Authentication failed for user user

I checked the Kerberos server logs, and it doesn't even register a connection attempt when this error happens. I also checked the code [around where the fatal exception occurs](https://github.com/dpkp/kafka-python/blob/master/kafka/conn.py#L484), and it seems to be communicating with a socket on the *Kafka* server, rather than the *Kerberos* server.

Now I'm no Kerberos expert, but since I'm trying to authenticate via Kerberos, shouldn't this part of the code connect to the Kerberos server?

In fact, how does it even know where the Kerberos server is?  When I (successfully) use the CLI tools to connect to Kafka with SASL, I must provide a `java.security.krb5.conf` file, which contains the network addresses of the `kdc` and `admin_server`. How do I provide this information to kafka-python?

**Comment by Harald-Berghoff** [comment]
Sorry for answering only now.

1. do you want to use Kerberos or SASL Plain? A listener with SASL_PLAINTEXT does not imply SASL plain authentication. If you want to use Kerberos, the sasl_mechanism must be 'GSSAPI'

2. even with Kerberos, the client will communicate with the Kafka server, not the Kerberos server. The Kafka server is supposed to verify the provided authentication token against the Kerberos server.

What you need is a Kerberos client installed and configured on the machine where you start the kafka client. You need to have a valid ticket, and then the kafka-python will use the ticket to try to authenticate against the Kafka broker.

Currently there is no way to configure a keytab to be used by kafka-python.
