### ISSUE TITLE
Traceback not sent to logger, but directly to stderr

### ISSUE THREAD

**Issue by dbgasaway** [dpkp/kafka-python#1220]
https://github.com/dpkp/kafka-python/blob/b1ae45c10d46e881492b0fd37f0919cac6d79224/kafka/conn.py#L618

At the line above, BrokerConnection prints a traceback directly to stderr, ignoring the logger. This makes it hard to filter out the traceback. Right now, for me the traceback occasionally starts generating GBs of output while at the same time a Producer stops sending information to Kafka, although why this happens I'm not sure yet, and I don't yet have a minimal example (I think it has something to do with losing a network connection though).

I think a better implementation would probably be to remove the traceback, and add stack_info=True to the previous logging call, as I think it does roughly the same thing. Or just get rid of the traceback, if it's not providing value to the project.

I should be able to provide a pull request, but I don't know if it would be preferable to get rid of the traceback entirely or not.

**Comment by dpkp** [comment]
Makes sense to me. I'm not sure how useful the stacktrace will be there, but if it seems useful in your debugging then we might as well keep it.
