### ISSUE TITLE
producer.send() function inside multiple threads causes increase in memory use

### ISSUE THREAD

**Issue by zyriljamez** [dpkp/kafka-python#1224]
I have a python script in which i am creating 100 threads each will take a connection to kafka. Each of these threads will spawn another 5 threads in each 15 seconds which will send some sample data to kafka using producer.send() function. Gradually memory usage of machine increases until full. All threads were getting closed properly. On debugging I could find out that producer.send() function is causing this issue. Please verify and give a solution for this issue.

**Comment by jeffwidman** [comment]
Why would you even be trying to do this? Why not run fewer threads as I'm guessing you're I/O bound not CPU bound.

I'm unclear from your description if this is an actual memory leak or simply you try to run too much stuff simultaneously and run out of memory. 

> Please verify and give a solution for this issue.

Given that this project is run by volunteers, I doubt any of us have the time to try to recreate this from just your description. If you put together a minimum working example, someone _may_ try running it and profiling it, although no guarantees: https://stackoverflow.com/help/mcve

**Comment by jeffwidman** [comment]
Closing for lack of detail, if it's actually a memory leak in `producer.send()` we would love to fix it, but we'd need a lot more help to replicate exactly what you're doing, ideally example code.
