### ISSUE TITLE
TypeError: <BrokerConnection node_id=1 host=myhost/127.0.0.1 port=9093> is not JSON serializable

### ISSUE THREAD

**Issue by so3500** [dpkp/kafka-python#1228]
i'm testing kafka-python consuemr, producer.
Curiously, even though errors like the one above occurred, consumers and producers were able to confirm that they were getting a good message.

Have you seen an error like the one above?

my environment:
- Ubuntu 16.04
- Python 2.7.13
- kafka_2.12-0.10.2.1

**Comment by so3500** [comment]
consumer, producer info

#### producer info
producer_addr = '{0}:{0}'.format('127.0.0.1', 9093)
producer = KafkaProducer(bootstrap_servers=producer_addr, value_serializer=lambda m: json.dumps(m).encode(utf-8)

#### consumer info
consumer_addr = '{0}:{0}'.format('127.0.0.1', 9093)
consumer = KafkaConsumer(bootstrap_servers=consumer_addr)
consumer.subscribe(['my-topic'])

**Comment by jeffwidman** [comment]
Can you add the full exception stacktrace?

**Comment by jeffwidman** [comment]
At least in the above code, the problem is `'{0}:{0}'` should be `'{0}:{1}'.format()`.

**Comment by so3500** [comment]
'{0}: {1}'. I tried to format () but I still get errors.
The interesting thing is that error logs are recorded, but sending and receiving messages also works well.

Below is the error screen shot.

![image](https://user-images.githubusercontent.com/19392136/31804983-611f4c2e-b598-11e7-943f-61145b7ab398.png)

![image](https://user-images.githubusercontent.com/19392136/31804992-76d62e7a-b598-11e7-9421-072096773934.png)

**Comment by dpkp** [comment]
These errors appear to be raised from a custom logging framework that you are using. Looks like a bug in the jsonformatter you're using.
