### ISSUE TITLE
Two `log.log` statements that do not make sense

### ISSUE THREAD

**Issue by jeffwidman** [dpkp/kafka-python#1233]
https://github.com/dpkp/kafka-python/commit/0adb71af3858a8f4d1cfb3fe072989499b3b3c4f added two `log.log()` statements.

I'm not familiar with this log level... Is this a valid python level, or should these two statements be switched to `log.debug()` or entirely removed?

**Comment by jeffwidman** [comment]
Ah, found https://docs.python.org/2.7/library/logging.html#logging.Logger.log, I didn't know about this before...

So given that Python has no explicit trace level, I'm fine leaving this as-is, as it makes sense that this could dominate debug level logs.

**Comment by dpkp** [comment]
yes -- I believe these were trace-level log statements in the java code. the `log.log(0, ...)` approach is pretty rare, but I thought it was better than spamming debug logs at the time. Also I was using debug a lot in the early days... ;)
