### ISSUE TITLE
KAFKA-3949: Fix race condition between group rebalance and metadata update

### ISSUE THREAD

**Issue by jeffwidman** [dpkp/kafka-python#1241]
Details in https://issues.apache.org/jira/browse/KAFKA-3949

Note that the fix refactored a fair bit of code for managing subscription state: https://github.com/apache/kafka/pull/1762

And then KIP-70 (tracked in #1242) further modified this code.

Related: #1237 / #1240 / #1242

**Comment by dpkp** [comment]
Yes, I have a PR ready but it depends on #1266 so I have not pushed it yet.

**Comment by jeffwidman** [comment]
@dpkp now that #1266 is merged, do you mind pushing up your PR for this?

**Comment by dpkp** [comment]
Yes -- unfortunately it has got some complex merge conflicts that need working out. Hoping to get these resolved + tested locally this week.
