### ISSUE TITLE
AssertionError: Unrecognized configs: {'sasl_kerberos_service_name': 'kafka'}

### ISSUE THREAD

**Issue by natedogs911** [dpkp/kafka-python#1263]
`kafka/producer/kafka.py` and `kafka/consumer/group.py`
 are missing the new parameter for sasl_kerberos_service_name, throwing the assertion error.

**PR coming**

**Comment by dpkp** [comment]
Thanks!

**Comment by just-OneKey** [comment]
I want to set the attribute 'max_poll_interval_ms' of Comsumer , but it seems that Consumer doesn't have  that attribute .
Here is codes and outputs:
`self.consumer = KafkaConsumer(self.topic,group_id=self.groupId,
                bootstrap_servers=[self.addrPort],
                auto_offset_reset='earliest',  
                enable_auto_commit=False, 
                max_partition_fetch_bytes = 1024*1024*2,
                max_poll_records=5,
                # max_poll_interval_ms=int(600000)  
                )`

> Traceback (most recent call last):
  File "main.py", line 148, in <module>
    taksConsumer = Consumer(taskQueue,"taskQueueConsumer",addrPort)
  File "/home/imas/kvm/provider_bak/provider/kafkawrapper/consumer.py", line 21, in __init__
    max_poll_interval_ms=int(600000) 
  File "/usr/local/lib/python3.6/dist-packages/kafka/consumer/group.py", line 286, in __init__
    assert not configs, 'Unrecognized configs: %s' % configs
AssertionError: Unrecognized configs: {'max_poll_interval_ms': 600000}
In exit

**Comment by TimurPlusPlus** [comment]
> I want to set the attribute 'max_poll_interval_ms' of Comsumer , but it seems that Consumer doesn't have that attribute .
> Here is codes and outputs:
> `self.consumer = KafkaConsumer(self.topic,group_id=self.groupId, bootstrap_servers=[self.addrPort], auto_offset_reset='earliest', enable_auto_commit=False, max_partition_fetch_bytes = 1024*1024*2, max_poll_records=5, # max_poll_interval_ms=int(600000) )`
> 
> > Traceback (most recent call last):
> > File "main.py", line 148, in 
> > taksConsumer = Consumer(taskQueue,"taskQueueConsumer",addrPort)
> > File "/home/imas/kvm/provider_bak/provider/kafkawrapper/consumer.py", line 21, in **init**
> > max_poll_interval_ms=int(600000)
> > File "/usr/local/lib/python3.6/dist-packages/kafka/consumer/group.py", line 286, in **init**
> > assert not configs, 'Unrecognized configs: %s' % configs
> > AssertionError: Unrecognized configs: {'max_poll_interval_ms': 600000}
> > In exit

I've solved the issue by installing **kafka-python** instead of **kafka**.   
Maybe it could save someone a few hours.
