### ISSUE TITLE
Background consumer with Kafka

### ISSUE THREAD

**Issue by aureliosaraiva** [dpkp/kafka-python#1265]
People, like I create a consumer to be shot in the background with kafka.

My goal is to have a Celery-Consumer style server to pick up messages and run an asynchronous task.

Can someone help me?

With Celery is very easy, more without celery is complex.

**Comment by jeffwidman** [comment]
I'm afraid I don't really understand your question... you can just run Celery and have your workers be kafka consumers, although that doesn't really make a lot of sense... better to just spin up a consumer group and use Kafka as the message queue itself. Support for actually using Kafka for the Celery broker is tracked in #528.
