### ISSUE TITLE
`KafkaProducer.send` should raise non-api exceptions (not metadata lookup)

### ISSUE THREAD

**Issue by tvoinarovskyi** [dpkp/kafka-python#1274]
After @jeffwidman pointed out in https://github.com/dpkp/kafka-python/pull/1272#issuecomment-338450001 that validation errors will not pop up on `Producer.send` went to the code and found this:
```python
        except Exception as e:
            log.debug("Exception occurred during message send: %s", e)
            return FutureRecordMetadata(
                FutureProduceResult(TopicPartition(topic, partition)),
                -1, None, None,
                len(key_bytes) if key_bytes is not None else -1,
                len(value_bytes) if value_bytes is not None else -1
            ).failure(e)
```

Ie, we explicitly delegate any errors to the future... Why? I find it very confusing and would just allow the exceptions to be raised to application level right away. @dpkp could you elaborate on this?

**Comment by dpkp** [comment]
That was copied in from the java client, which does this for ApiExceptions only, but it looks like it was expanded to all Exceptions incorrectly. I think raising unhandled exceptions from the foreground processing (serialization, buffering, etc) makes sense. The future approach is really only applicable when the error comes from the initial fetch-metadata phase, which happens in the foreground but probably should not be raised to the user.
