### ISSUE TITLE
Kafka Consumer Poll Records Issue

### ISSUE THREAD

**Issue by seenuvasan438** [dpkp/kafka-python#1289]
@dpkp 
I have the below consumer, 
 **consumer = KafkaConsumer('topic1','topic2','topic3',group_id='Application_Streaming',auto_offset_reset="latest",bootstrap_servers='localhost:8200',request_timeout_ms=130000,session_timeout_ms=120000, max_poll_records=500)**
        for message in consumer:
            consumer.commit()
            with open("/opt/prod/logs/Consumer.log", "a") as log_file:
                log_file.write(datetime.now().strftime('%Y-%m-%d %H:%M:%S') + '\t' + str(message.topic) + '\t' + str(message.offset) + '\n')
    except Exception as e:
        print(e)
    ssc.start()
    ssc.awaitTermination()

I am using Kafka 0.10 version, when I am trying to run the code it is running for 3o minutes without any issue. After sometimes, its failing with below error,

**CommitFailedError: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured session.timeout.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing the session timeout or by reducing the maximum size of batches returned in poll() with max.poll.records.**

Please help me to solve the issue by assining right property. Thanks in advance @dpkp

**Comment by jeffwidman** [comment]
The error is quite straightforward. Sometimes processing your 500 messages takes longer than the session timeout. 

As stated in the message, the solution is:
> You can address this either by increasing the session timeout or by reducing the maximum size of batches returned in poll() with max.poll.records.

**Comment by seenuvasan438** [comment]
I have tried both reducing poll records to 20 and increased session time out as well, Still facing the same failure. @jeffwidman . Are there any other property that I need to set it up?
