### ISSUE TITLE
Ambiguous documentation

### ISSUE THREAD

**Issue by neimad1985** [dpkp/kafka-python#1295]
Hi,

First thanks for the great lib, I'm having fun using it !

A question about the documentation please.
In the documentation for the **KafkaConsumer**, there is the parameter **fetch_max_bytes** (**fetch_min_bytes** as well, and others of the same kind..)
You say that it's default value is 50 **Mb**.
The problem is that the name of the function is about **bytes** and **Mb** is about **bits** (and **MB** is about **bytes**).
The question is : what is the real value/amount of data ? Because this leads to an **8** factor error.
If we talk about bits, then the function should have been named **fetch_max_bits**.
If we talk about bytes, the documentation should be patched to indicate 50 MB.

Same thing for all other functions of the same kind.

Thanks in advance for the tip and go on with the **great work** :)

**Comment by dpkp** [comment]
Good catch! I think you're referring to this:
```
        fetch_max_bytes (int): The maximum amount of data the server should
            return for a fetch request. This is not an absolute maximum, if the
            first message in the first non-empty partition of the fetch is
            larger than this value, the message will still be returned to
            ensure that the consumer can make progress. NOTE: consumer performs
            fetches to multiple brokers in parallel so memory usage will depend
            on the number of brokers containing partitions for the topic.
            Supported Kafka version >= 0.10.1.0. Default: 52428800 (50 Mb).
```
The actual default is `52428800` and the units are bytes as the configuration name indicates. You are correct that the parenthetical is incorrect and should be fixed (or deleted).

**Comment by neimad1985** [comment]
Yes that's exactly what I am talking about.
Thanks for the quick reply !
