### ISSUE TITLE
Can I use a single producer to write to multiple topics?

### ISSUE THREAD

**Issue by swaapnika-guntaka** [dpkp/kafka-python#1297]
I'm using kafka-python to create producer. Based on my schema(I'm using avro schema) it would be effective if I have 2 topics. Is it possible to create a single producer that can write to multiple topics?
Or should I instantiate producers for each topic?

**Comment by jeffwidman** [comment]
Use a single producer. The [`send()` signature](http://kafka-python.readthedocs.io/en/master/apidoc/KafkaProducer.html#kafka.KafkaProducer.send) includes specifying the topic.
