### ISSUE TITLE
wrapper get_messages method for high level consumer

### ISSUE THREAD

**Issue by AndyHoang** [dpkp/kafka-python#1299]
I'm trying to create a wrapper method get_messages for KafkaConsumer.
quite simple as
```
    def get_messages(self, max_records=50):
        #only work with auto comit True
        result = []
        count = 0
        while count < max_records:
            try:
                msg = next(self)
                count += 1
                result.append(msg)
            except StopIteration:
                break
        return result

```
But look like its not working if I pass enable_auto_commit is False.
After the method I try to use consumer.commit but I got error:
```
raise future.exception # pylint: disable-msg=raising-bad-type
kafka.errors.CommitFailedError: CommitFailedError: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured session.timeout.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing the session timeout or by reducing the maximum size of batches returned in poll() with max.poll.records
```

I understand that I must dig deeper into the implementation of our `_message_generator`
I notice that in order to keep waiting or continue to fetch more data we must use this
```https://github.com/dpkp/kafka-python/blob/master/kafka/consumer/group.py#L1067```
So I try to re create a similar method like _message_generator and add a counter so that I can pass my max_records into the function and start to compare/ conditionally raise StopIteration.
Still I got error ```kafka.errors.CommitFailedError```
So **my question is**, (i'm still digging deeper) should I follow this path, or I just give up and accept that this behavior should not be used with a high level consumer?
I have a user case that inside a thread, I have multiple consumer, consume different topic and do different thing between topics.
So it would look like:
```
While True:
    for msg in consumer1.get_messages(max_records=50): #result can be smaller than 50
       dostuff(msg)
    for msg in consumer2.get_messages(max_records=50):
      dostuff2(msg)
   time.sleep(5)
```
Thanks!

**Comment by jeffwidman** [comment]
I think the issue here is not that the code is broken, but your understanding of the Kafka consumer group semantics. You can do this, you just have to complete processing and issue commit before the consumer group's session timeout.
