### ISSUE TITLE
InvalidTimestampError

### ISSUE THREAD

**Issue by golbhu** [dpkp/kafka-python#1302]
Timestamp added to LogAppendTime causes code that worked, raise this error:
```
consumer = KafkaConsumer(topic, group_id='my_favorite_group',bootstrap_servers=host)

for msg in consumer:
    print(msg)
```

error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/kafka/consumer/group.py", line 1075, in __next__
    return next(self._iterator)
  File "/usr/local/lib/python3.5/site-packages/kafka/consumer/group.py", line 999, in _message_generator
    self._coordinator.ensure_active_group()
  File "/usr/local/lib/python3.5/site-packages/kafka/coordinator/base.py", line 274, in ensure_active_group
    raise exception  # pylint: disable-msg=raising-bad-type
kafka.errors.InvalidTimestampError: [Error 32] InvalidTimestampError
```

using kafka-python v1.3.5

Tried setting api_version (tried all available ones, inc (0,10)), didn't work.

Thank you!

**Comment by tvoinarovskyi** [comment]
What version of Kafka broker do you use? What do you refer to as LogAppendTime? A bit lacking on context, sorry.

**Comment by golbhu** [comment]
@tvoinarovskyi the kafka version is 0.10.2.0 i tried setting also `api_version=(0,10)` 
`LoagAppendTime` is a kafka native parameter that basically allow kafka to put the timestamp on the message: https://kafka.apache.org/0110/javadoc/org/apache/kafka/clients/producer/ProducerRecord.html

I also refer to the official kafka package for python thread about this - last comment related to this package: https://github.com/confluentinc/confluent-kafka-python/issues/96

**Comment by golbhu** [comment]
Found the reason. Kafka 0.10.2.0 installed. They had a bug https://issues.apache.org/jira/browse/KAFKA-4861 and upgrade to 0.10.2.1 solved this!

Thanks!
