### ISSUE TITLE
kafka

### ISSUE THREAD

**Issue by rizhashmi** [dpkp/kafka-python#1309]
the way we build the kafka consumer, each consumer instance knows partition id & each consumer poll message manually hence i disabled auto.commit flag. Also i stored kafka offset in database so in case of failure i can easily start from last place. 

my question is do i still need manual commit to kafka. if i dont manually commit to kafka will this imapct performance?

**Comment by jeffwidman** [comment]
This question feels a bit disjointed and unclear about the basics of how Kafka works. I suggest reading the docs again and then posting followup questions on StackOverflow, as this issue tracker is more about how kafka-python works.
