### ISSUE TITLE
on_partitions_revoked called with all partitions, not only the ones being revoked

### ISSUE THREAD

**Issue by netrounds-fredrik** [dpkp/kafka-python#1313]
When kafka is rebalancing the partitions, the `on_partitions_revoked` method will be called for all assigned partitions, not only the onces that are revoked. This was reproduced in kafka-python 1.3.2.

According to the documentation, a use case of this function is to be able to flush cached data for a partition that is no longer assigned. With the current behavior such function would flush the whole cache, even if there where only a new partition being assigned.

~I looked at the code and came up with a possible solution. I'm new to this code, so there might be something that I have missed, like what happens if the join fails.~

~1. Store the currently assigned partitions in `ConsumerCoordinator._on_join_prepare`.
2. Move the call to `on_partitions_revoked` from `ConsumerCoordinator._on_join_prepare` to `ConsumerCoordinator._on_join_complete`.
3. Diff the previous and the new assigned partitions in `ConsumerCoordinator._on_join_complete` and call `on_partitions_revoked` and `on_partitions_assigned` with the correct partitions.~

EDIT:
After working some more with other lower level libraries, I think that calling `on_partitions_revoked` with all partitions is probably the correct thing to do, What could be done is to clarify this in the documentation.

**Comment by dpkp** [comment]
The behavior here is identical to the official java client. I'm not opposed to improving documentation, but I don't want to change the behavior unless/until upstream does it first.
