### ISSUE TITLE
ConnectionError: Unable to connect to any of the names for 2aba43d449ac:9092 Docker and Kafka-python

### ISSUE THREAD

**Issue by cesarcolle** [dpkp/kafka-python#1324]
Hi,

I'm recently using your python's client.
First thanks to the community to take so much time to implement that kafka's client.

I have a problem with the connexion with kafka and the client.

My environment is : 
2aba43d449ac        spotify/kafka       "supervisord -n"  0.0.0.0:2181->2181/tcp, 0.0.0.0:9092->9092/tcp   

With kafka version 0.10.1
So my kafka is runing through a docker-compose using the spotify image.

So I want to produce message to the kafka bus. that is my code : 

```
from kafka import KafkaProducer
import logging
logging.basicConfig(level=logging.DEBUG)
producer = KafkaProducer(bootstrap_servers="localhost:9092")
producer.send("test", b"this is a message from France")
producer.flush() 
```

I'm sure that I can connect to the docker : 

> telnet localhost 9092
>Trying 127.0.0.1...
>Connected to localhost.

And when I try to connect I have that output into the DEBUG logs :

> INFO:kafka.conn:<BrokerConnection node_id=bootstrap host=localhost/127.0.0.1 port=9092>: connecting to 127.0.0.1:9092
> DEBUG:kafka.conn:<BrokerConnection node_id=bootstrap host=localhost/127.0.0.1 port=9092>: established TCP connection
> DEBUG:kafka.conn:<BrokerConnection node_id=bootstrap host=localhost/127.0.0.1 port=9092>: Connection complete.
> DEBUG:kafka.client:Node bootstrap connected
> DEBUG:kafka.conn:<BrokerConnection node_id=bootstrap host=localhost/127.0.0.1 port=9092> Request 1: MetadataRequest_v0(topics=[])
> DEBUG:kafka.conn:<BrokerConnection node_id=bootstrap host=localhost/127.0.0.1 port=9092> Response 1: MetadataResponse_v0(brokers=[(node_id=0, host='2aba43d449ac', port=9092)], topics=[(error_code=0, topic='__consumer_offsets', partitions=[(error_code=0, partition=23, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=41, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=32, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=8, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=17, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=44, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=35, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=26, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=11, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=29, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=38, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=47, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=20, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=2, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=5, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=14, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=46, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=49, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=40, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=4, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=13, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=22, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=31, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=16, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=7, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=43, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=25, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=34, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=10, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=37, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=1, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=19, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=28, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=45, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=36, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=27, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=9, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=18, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=21, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=48, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=12, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=3, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=30, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=39, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=15, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=42, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=24, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=33, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=6, leader=0, replicas=[0], isr=[0]), (error_code=0, partition=0, leader=0, replicas=[0], isr=[0])]), (error_code=0, topic='test', partitions=[(error_code=0, partition=0, leader=0, replicas=[0], isr=[0])])])
> DEBUG:kafka.cluster:Updated cluster metadata to ClusterMetadata(brokers: 1, topics: 2, groups: 0)
> INFO:kafka.client:Bootstrap succeeded: found 1 brokers and 2 topics.
> INFO:kafka.conn:<BrokerConnection node_id=bootstrap host=localhost/127.0.0.1 port=9092>: Closing connection. 
> DEBUG:kafka.conn:<BrokerConnection node_id=bootstrap host=localhost/127.0.0.1 port=9092>: reconnect backoff 0.040337390835905686 after 1 failures
> DEBUG:kafka.client:Initiating connection to node 0 at 2aba43d449ac:9092
> DEBUG:kafka.metrics.metrics:Added sensor with name node-0.bytes-sent
> DEBUG:kafka.metrics.metrics:Added sensor with name node-0.bytes-received
> DEBUG:kafka.metrics.metrics:Added sensor with name node-0.latency
> DEBUG:kafka.conn:<BrokerConnection node_id=0 host=2aba43d449ac/2aba43d449ac port=9092>: creating new socket
> WARNING:kafka.conn:DNS lookup failed for 2aba43d449ac:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
> ERROR:kafka.conn:Unable to connect to any of the names for 2aba43d449ac:9092
> WARNING:kafka.conn:<BrokerConnection node_id=0 host=2aba43d449ac/2aba43d449ac port=9092>: close() called on disconnected connection with error: ConnectionError: Unable to connect to any of the names for 2aba43d449ac:9092
> Stack (most recent call last):
>   File "/home/caesar/test-python-kafka/test.py", line 14, in <module>
>     key_serializer=str.encode)
>   File "/home/caesar/env/test-python-kafka/lib/python3.5/site-packages/kafka/producer/kafka.py", line 347, in __init__
>     **self.config)
>   File "/home/caesar/env/test-python-kafka/lib/python3.5/site-packages/kafka/client_async.py", line 221, in __init__
>     self.config['api_version'] = self.check_version(timeout=check_timeout)
>   File "/home/caesar/env/test-python-kafka/lib/python3.5/site-packages/kafka/client_async.py", line 827, in check_version
>     self._maybe_connect(try_node)
>   File "/home/caesar/env/test-python-kafka/lib/python3.5/site-packages/kafka/client_async.py", line 371, in _maybe_connect
>     conn.connect()
>   File "/home/caesar/env/test-python-kafka/lib/python3.5/site-packages/kafka/conn.py", line 290, in connect
>     self.close(Errors.ConnectionError(error))
>   File "/home/caesar/env/test-python-kafka/lib/python3.5/site-packages/kafka/conn.py", line 623, in close
>     log.warning('%s: close() called on disconnected connection with error: %s', self, error, stack_info=True)
> Traceback (most recent call last):
>   File "/home/caesar/test-python-kafka/test.py", line 14, in <module>
>     key_serializer=str.encode)
>   File "/home/caesar/env/test-python-kafka/lib/python3.5/site-packages/kafka/producer/kafka.py", line 347, in __init__
>     **self.config)
>   File "/home/caesar/env/test-python-kafka/lib/python3.5/site-packages/kafka/client_async.py", line 221, in __init__
>     self.config['api_version'] = self.check_version(timeout=check_timeout)
>   File "/home/caesar/env/test-python-kafka/lib/python3.5/site-packages/kafka/client_async.py", line 846, in check_version
>     raise Errors.NoBrokersAvailable()
> kafka.errors.NoBrokersAvailable: NoBrokersAvailable
> INFO:kafka.producer.kafka:Kafka producer closed
> 

So I when I checked the first part I was happy, but I have a consumer running in a other docker who read nothing from the topic.
Even with :

`bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic test --from-beginning`

If I send a message again, nothing happen...

Is anyone have the same issue ?

Thanks

**Comment by cesarcolle** [comment]
Edit : seems like you have to set up the api_version.

The new code is :
```
from kafka import KafkaProducer
import logging
logging.basicConfig(level=logging.DEBUG)
producer = KafkaProducer(bootstrap_servers="localhost:9092", api_version=(0, 10, 1))
producer.send("test", b"this is a message from France")
producer.flush()
producer.close()
```
But I have now this error :

> DEBUG:kafka.conn:<BrokerConnection node_id=0 host=2aba43d449ac/2aba43d449ac port=9092>: creating new socket
> ERROR:kafka.conn:Unable to connect to any of the names for 2aba43d449ac:9092
> WARNING:kafka.conn:<BrokerConnection node_id=0 host=2aba43d449ac/2aba43d449ac port=9092>: close() called on disconnected connection with error: ConnectionError: Unable to connect to any of the names for 2aba43d449ac:9092
> DEBUG:kafka.conn:<BrokerConnection node_id=0 host=2aba43d449ac/2aba43d449ac port=9092>: creating new socket
> ERROR:kafka.conn:Unable to connect to any of the names for 2aba43d449ac:9092
> WARNING:kafka.conn:<BrokerConnection node_id=0 host=2aba43d449ac/2aba43d449ac port=9092>: close() called on disconnected connection with error: ConnectionError: Unable to connect to any of the names for 2aba43d449ac:9092
> DEBUG:kafka.producer.sender:Node 0 not ready; delaying produce of accumulated batch
> DEBUG:kafka.producer.record_accumulator:Produced messages to topic-partition TopicPartition(topic='test', partition=0) with base offset -1 and error KafkaTimeoutError: Batch for TopicPartition(topic='test', partition=0) containing 1 record(s) expired: 30 seconds have passed since batch creation plus linger time.
> Traceback (most recent call last):
>   File "test.py", line 11, in <module>
>     producer.flush()
>   File "/usr/local/lib/python2.7/dist-packages/kafka/producer/kafka.py", line 577, in flush
>     self._accumulator.await_flush_completion(timeout=timeout)
>   File "/usr/local/lib/python2.7/dist-packages/kafka/producer/record_accumulator.py", line 529, in await_flush_completion
>     if not batch.produce_future.wait(timeout=timeout):
>   File "/usr/local/lib/python2.7/dist-packages/kafka/producer/future.py", line 28, in wait
>     return self._latch.wait(timeout) or self._latch.is_set()
>   File "/usr/lib/python2.7/threading.py", line 614, in wait
>     self.__cond.wait(timeout)
>   File "/usr/lib/python2.7/threading.py", line 340, in wait
>     waiter.acquire()
> KeyboardInterrupt
> INFO:kafka.producer.kafka:Closing the Kafka producer with 0 secs timeout.
> INFO:kafka.producer.kafka:Proceeding to force close the producer since pending requests could not be completed within timeout 0.
> DEBUG:kafka.producer.record_accumulator:Expired 1 batches in accumulator
> DEBUG:kafka.client:Initializing connection to node 0 for metadata request
> DEBUG:kafka.conn:<BrokerConnection node_id=0 host=2aba43d449ac/2aba43d449ac port=9092>: creating new socket
> ERROR:kafka.conn:Unable to connect to any of the names for 2aba43d449ac:9092
> WARNING:kafka.conn:<BrokerConnection node_id=0 host=2aba43d449ac/2aba43d449ac port=9092>: close() called on disconnected connection with error: ConnectionError: Unable to connect to any of the names for 2aba43d449ac:9092
> DEBUG:kafka.producer.sender:Beginning shutdown of Kafka producer I/O thread, sending remaining records.
> DEBUG:kafka.producer.sender:Shutdown of Kafka producer I/O thread has completed.
> DEBUG:kafka.producer.kafka:The Kafka producer has closed.
> INFO:kafka.producer.kafka:Kafka producer closed

**Comment by tvoinarovskyi** [comment]
Hi there, for start could you try `127.0.0.1: 9092`. Seems like the `localhost` is not resolved correctly. If no luck, you will need to provide proper `advertised.listeners` property to broker config. See [broker docs](https://kafka.apache.org/documentation/#brokerconfigs)

**Comment by cesarcolle** [comment]
You're right thanks :
