### ISSUE TITLE
KafkaProducer#send() not always asynchronous

### ISSUE THREAD

**Issue by HannesP** [dpkp/kafka-python#1325]
According to the docs, KafkaProducer#send() is always asynchronous. However, it will often block if I run a single node of Kafka, connect with kafka-python, and then shut down the Kafka node, i.e.:

    p = KafkaProducer()
    p.send('my-topic', b'some data')
    # Shut down broker
    # (Start the broker again)
    p.send('my-topic', b'more data') # This blocks

If there was a way to make a health check on the broker, I could probe it and create a new producer object to replace it before sending data, but I can't find a way to do that. Did I miss something in the docs?

**Comment by tvoinarovskyi** [comment]
Send only blocks to get metadata and if the queue is full. The timeout for this can be configured using `max_block_ms` configuration option. See [producer docs](http://kafka-python.readthedocs.io/en/master/apidoc/KafkaProducer.html). Maybe setting it to a lower value will help you.

**Comment by HannesP** [comment]
That was it, thanks a lot @tvoinarovskyi!
