### ISSUE TITLE
Support DescribeConfigs / AlterConfigs apis

### ISSUE THREAD

**Issue by llamahunter** [dpkp/kafka-python#1326]
Is there a way to query/alter topic configs?  It's available via the kafka wire protocol.

https://kafka.apache.org/protocol#The_Messages_DescribeConfigs
https://kafka.apache.org/protocol#The_Messages_AlterConfigs

**Comment by alexef** [comment]
@dpkp I can take a stab at this, if no one else already started implementing it :)

**Comment by dpkp** [comment]
Awesome! First step is to define the request / response classes in kafka.protocol.* . My initial though would be to put them in kafka.protocol.admin, but I'm open to other ideas!

**Comment by jeffwidman** [comment]
IIRC, Java heavily refactored where they put all the request/response classes to be much cleaner... agree with @dpkp that if you want to do it quickly `kafka.protocol.admin` is probably the easiest place, but long term we should probably refactor all these protocol class locations to match the Java upstream and reduce confusion...

**Comment by jeffwidman** [comment]
See also https://github.com/dpkp/kafka-python/pull/1869

**Comment by dpkp** [comment]
This is now supported in KafkaAdminClient
