### ISSUE TITLE
timestamp ignored in producer send command

### ISSUE THREAD

**Issue by raulvc** [dpkp/kafka-python#1335]
Here's my use case:
I'm copying messages from a specific time range from one server to another, so I consume a message and apply the same timestamp to a message I produce in another server like so:
```
from kafka import KafkaConsumer, KafkaProducer
consumer = KafkaConsumer(bootstrap_servers=SERVER_FROM, auto_offset_reset='earliest')
consumer.subscribe([SOURCE_TOPIC])
producer = KafkaProducer(bootstrap_servers=SERVER_TO, compression_type='gzip')
for msg in consumer:
    if in_time_range(msg.timestamp):
        producer.send(topic=TARGET_TOPIC, value=msg.value, timestamp_ms=msg.timestamp)
```
Problem is, when I consume this message I just produced, the timestamp is actually the time in which I produced instead of the copied one

brokers running kafka 0.10.0
kafka-python 1.3.4.dev0

**Comment by tvoinarovskyi** [comment]
Check your producer. If it's configured to APPEND_TIME it will have this behaviour.

**Comment by tvoinarovskyi** [comment]
There is a test in our test suite 'test_kafka_consumer_offsets_for_time' which relies on the timestamp behaviour, so it should be sent to broker correctly. Maybe there is a problem with 0.10.0 broker in this regard, not sure.
I'm writing from phone, so cant link the broker config option, but there is one that determines if log append or provided time is to be used. 
Also the broker only tolerates a range of values around current time, be careful with that. It is configurable too.

**Comment by jeffwidman** [comment]
I'm going to close this as it's most likely due to append time as @tvoinarovskyi explained. @raulvc if you have more info otherwise, please comment and we can re-open.
