### ISSUE TITLE
Fix circular references in KafkaMetrics

### ISSUE THREAD

**Issue by dpkp** [dpkp/kafka-python#1340]
It looks like there are several circular references within the metrics implementation. These prevent garbage collection when the consumer or producer object completes. These should be updated to use weakrefs where possible.

**Comment by kishorenc** [comment]
@dpkp We're witnessing memory leaks in `KafkaProducer` via these `KafkaMetric` objects. We periodically `close` the producer object and re-create the producer, and when we do that the garbage collector does not seem to free these metric objects: we were able to verify that with a memory dump. When we don't reuse the producer object without re-initializing it, we see no leaks.
