### ISSUE TITLE
KafkaProducer API create topic if topic is not exist

### ISSUE THREAD

**Issue by ksuthar** [dpkp/kafka-python#1341]
I am using kafka-python in my project. When I produce some message on non-exit Kafka topic, API will create the topic and produce the message. Is there any way in API to stop creation of new topic at the time produce ???

producer = KafkaProducer(bootstrap_servers=['localhost:9092'])

**Comment by tvoinarovskyi** [comment]
No Api to stop creating it, but there is a broker option to disable this behaviour

**Comment by jeffwidman** [comment]
As @tvoinarovskyi said, the brokers do not support an API to stop this happening in the produce calls. This is out of our control as we are bound to the limitations of the Kafka broker APIs.
