### ISSUE TITLE
Is there a use pattern for consuming one message at a time?

### ISSUE THREAD

**Issue by y5wang** [dpkp/kafka-python#1350]
What I'm trying to do is to read one message from Kafka at a time in a separate loop. Is there an accepted use pattern with kafka-python? Something like this:

while True:
  msg = _consumer.get_next()
  <do someting with msg>
  <do something not related to kafka>

If I use the consumer iterator, when no new message in Kafka, <do something not related to kafka> will never be executed. I can't seem to find the right way to fetch new message if any, or return. Can somebody point me to the right direction?

**Comment by dpkp** [comment]
The iterator is the preferred approach. You can use `consumer_timeout_ms` if you need to break when no new message is available. If you dont want to use the iterator, you can also try `consumer.poll` and either set max_poll_messages = 1 or loop through the batch of messages in your code.
