### ISSUE TITLE
Error running tests under pytest 3.4.0

### ISSUE THREAD

**Issue by dpkp** [dpkp/kafka-python#1360]
`INTERNALERROR> AttributeError: 'NoneType' object has no attribute 'testscollected'`
See https://github.com/pytest-dev/pytest/issues/3174

Seems like we'll need to either drop pytest-sugar (until the issue is fixed) or pin pytest==3.3.2

**Comment by tvoinarovskyi** [comment]
Yea, aiokafka is broken too. Needs fixes =( Lets pin to older version.

**Comment by dpkp** [comment]
See also https://github.com/Frozenball/pytest-sugar/pull/133 and https://github.com/pytest-dev/pytest/issues/3170
