### ISSUE TITLE
Run Kafka consumer in a background thread, CPU 100%

### ISSUE THREAD

**Issue by jwl2006** [dpkp/kafka-python#1366]
I create a consumer in the background thread with:
thread = threading.Thread(target=self.run_kafka_consumer, args=())

And create a consumer instance with:
self.consumer = KafkaConsumer(bootstrap_servers=XXX, auto_offset_reset='latest',  api_version='0.10')

I got a 100% CPU usage.

After add a group_id parameter, the CPU returns to normal state:
self.consumer = KafkaConsumer(bootstrap_servers=XXX,  group_id=XXX, auto_offset_reset='latest',  api_version='0.10')

**Comment by dpkp** [comment]
I dont think there is enough here to help you out. You might consider looking at your logs.
