### ISSUE TITLE
Multiple KafkaConsumer subscribed to same partition with same group id consuming same message

### ISSUE THREAD

**Issue by amitt001** [dpkp/kafka-python#1381]
I want to create a consumer with group "g1" that is subscribed to a `TopicPartition` now to back it up in case it fails I create another consumer with the same group that also subscribes to same `TopicPartition`.

Here strangely enough both the consumers subscribed to same TopicPartiton start consuming same messages.
```
In [1]: from kafka import TopicPartition, KafkaConsumer

In [2]: consumer = KafkaConsumer(group_id='py-group-1')

In [3]: consumer.assign([TopicPartition('py-test-2', 0)])

In [4]: for c in consumer:
   ...:     print(c)
```

I was expecting that at a time only one consumer will be consuming the messages.

This works fine in case partitions are not subscribed explicitly.

**Comment by tvoinarovskyi** [comment]
I don't know your particular use case, but 'assign' will disable automatic partition assignment. It's called manual assignment.
Maybe you can get the behaviour you want by combining 'subscribe' and 'pause' APIs. You set a listener to subscribe, that will pause all partitions except the desired one.
Why would you want to consume only a single partition?

**Comment by amitt001** [comment]
"listener to subscribe, that will pause all partitions except the desired one."

But this will stop all other partitions. @tvoinarovskyi it's kind of old system that is coded to have consumer performing a specific action based on topic(not the right logic).

**More than my use case I am interested in knowing what assigning a specific topic partition to two consumers with same group id results into both reading same messages?**

**Comment by dpkp** [comment]
What you are asking for is a subscription to a specific set of partitions. While this isn't impossible at a protocol level, it is not supported in kafka-python. And I do not believe it is supported in the java client.
