### ISSUE TITLE
Error creating topic using the kafka protocol when replication_factor is -1

### ISSUE THREAD

**Issue by diasjorge** [dpkp/kafka-python#1382]
According to the kafka protocol documentation https://kafka.apache.org/protocol#The_Messages_CreateTopics when replication_factor is set to -1 it means that the value is unset.

The problem I'm experiencing is the following:

```
kafka_1  | [2018-02-15 11:15:56,762] INFO [Admin Manager on Broker 1001]: Error processing create topic request for topic example with arguments (numPartitions=12, replicationFactor=-1, replicasAssignments={}, configs={}) (kafka.server.AdminManager)
kafka_1  | org.apache.kafka.common.errors.InvalidReplicationFactorException: Replication factor must be larger than 0.
```

Now I don't know if this is a bug in Kafka or has something to do with how the request is serialized. Any ideas?

Greetings

**Comment by dpkp** [comment]
Are you sending the request via kafka-python ? Can you provide any code snippets to help reproduce?

**Comment by diasjorge** [comment]
Hi, I created the following gist: https://gist.github.com/diasjorge/1eae844c3ebc425309b64c492e8890a8

**Comment by StephenSorriaux** [comment]
I think the kafka protocol documentation is sometimes a little confusing but if you check the code, you can see that you only have 2 ways to create a topic:
- specify num_partitions and replication_factor and keep replica_assignment empty
- unset num_partitions and replication_factor and specify replica_assignment

ref : method https://github.com/apache/kafka/blob/f6f65a78684e41bcd6115438a76cd6c552afc043/clients/src/main/java/org/apache/kafka/clients/admin/AdminClient.java#L99 and class https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/admin/NewTopic.java#L54

**Comment by jeffwidman** [comment]
This looks like it's being sent via the Java code, not `kafka-python` unless I misunderstand.
