### ISSUE TITLE
Compare and contrast features and usecases with confluent-kafka-python

### ISSUE THREAD

**Issue by ravikiranks** [dpkp/kafka-python#1385]
Could anybody pls compare and contrast features with confluent-kafka-python?
Interested to know if anybody did any comparative tests!

**Comment by dpkp** [comment]
splitters! https://www.youtube.com/watch?v=lF-cdujoNak

**Comment by tvoinarovskyi** [comment]
@ravikiranks 
`kafka-python` is a pure python implementation, that follows Java client's implementation as close as possible.
`confluent-kafka-python` is a python wrapper around `librdkafka`, which is a pure C based client, that does not follow Java's API and has speed as it's main objective (as far as I know).

What do you want to compare?
Features are relatively the same, as far as I am concerned. `librdkafka` still does not support Transactional Producers and AdminClient. Sadly does `kafka-python` atm. 
Speed is higher in `confluent-kafka-python`. How much faster, sorry can't tell.
As for support, I prefer the python implementation, you can debug it, logging uses Python default loggers etc. Also, as `kafka-python` follows Java's implementation, it's easier to find solutions to some problems, which were solved in Java client.

**Comment by ravikiranks** [comment]
Thank you!
Let me explain our specific need - 
We have requirement to mirror data from kafka cluster (0.8.2.1) to Kafka 0.10.1 (with SASL_PLAINTEXT). 

Regular 'Kafka Mirror Maker' is not working so we are testing different programs to achieve this 
requirement to handle mirroring consistently and robustness to handle high rate of messages/sec (around 200 K/sec) 

1) Consume from 0.8.2.1 topics
2) Produce to 0.10.1 topics (with SASL_PLAINTEXT) 
3) Threading should be robust to handle high rate (200 K/sec or more sometimes)

Thanks

**Comment by tvoinarovskyi** [comment]
@ravikiranks I would recommend `confluent-kafka-python`. The rate is quite high for python. As for `0.8.2.1` support, you should check with `confluent-kafka-python` docs, I don't have much expirience with it.

**Comment by jeffwidman** [comment]
Personally, I think that you'll find that sticking with the regular mirrormaker will be a better long term solution that hacking your own:
1) I'd first check out why the regular mirror maker isn't working. You'd want to use the mirrormaker from the 0.8 series.
2) Second, I'd look into directly upgrading the 0.8 cluster to a newer version... and then using the mirrormaker from that new version. I had a 0.8.2 cluster and it gave us all kinds of headaches that went away as soon as I upgraded the brokers to 0.10.0.1 (the newest at the time). The upgrade was flawless, just follow the docs.

I'm going to close this issue as it sounds like we've answered the original question.

**Comment by poonkothaip** [comment]
Hi
Am not sure if this thread is active. But I do have one question related to performance of confluent-kafka vs kafka-python  consumers when using with MSK . Any one has any benchmarking details based on latest version of these libraries. 
THanks
