### ISSUE TITLE
Only wheels available for v1.4.0 and v1.4.1

### ISSUE THREAD

**Issue by tvoinarovskyi** [dpkp/kafka-python#1388]
@dpkp See https://pypi.python.org/pypi/kafka-python/1.4.1 and https://pypi.python.org/pypi/kafka-python/1.3.5, the later contains source, but 1.4 has only a wheel. Stumbled upon this on windows, it does not install v1.4.1, as no source available =(

**Comment by tvoinarovskyi** [comment]
@dpkp Do we have an automatic deploy procedure, or you upload the versions by hand?

**Comment by dpkp** [comment]
I've been doing it by hand. Missed this, sorry! Will fix now.

**Comment by tvoinarovskyi** [comment]
We will need to configure travis to deploy those on a tag release

**Comment by dpkp** [comment]
sdists are now available on pypi for 1.4.0 and 1.4.1 . Feel free to open a new issue re: automated tag releases via travis

**Comment by infecto** [comment]
@tvoinarovskyi @dpkp Hmmm, looks like I am not longer able to grab 1.4.0 or 1.4.1 via pip.

`Could not find a version that satisfies the requirement kafka==unknown (from versions: 1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4.1, 1.3.5)`

**Comment by dpkp** [comment]
Try installing kafka-python not kafka

**Comment by infecto** [comment]
*headsmack* 

Thanks @dpkp was working on a lack of sleep yesterday I got it confused with how its imported.
