### ISSUE TITLE
Commit Failed Error with new version of kafka-python

### ISSUE THREAD

**Issue by aswinjoseroy** [dpkp/kafka-python#1401]
My forever-running consumer gave me this exception :

`kafka.errors.CommitFailedError: CommitFailedError: ('Commit cannot be completed since the group has already\n            rebalanced and assigned the partitions to another member.\n            This means that the time between subsequent calls to poll()\n            was longer than the configured max_poll_interval_ms, which\n            typically implies that the poll loop is spending too much\n            time message processing. You can address this either by\n            increasing the rebalance timeout with max_poll_interval_ms,\n            or by reducing the maximum size of batches returned in poll()\n            with max_poll_records.\n            ', 'Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured session_timeout_ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing the session timeout or by reducing the maximum size of batches returned in poll() with max_poll_record 	s.')`

From what I understand, with the latest version of kafka-python, 1.4.1, there is a separate background thread that keeps sending the heartbeats. In that case, why should this exception arise? Irrespective of the time the actual processing thread takes, heartbeats need to be sent in the background, as long as it hasn't stopped the polling due to some reason. Please correct me if I am wrong.

**Comment by tvoinarovskyi** [comment]
There are 2 configs in `1.4.1`: max_poll_interval_ms and session_timeout_ms. The second one is the time Broker will tolerate no heartbeats and the first one is the time it will tolerate to rejoin the group. If your processing time exceeds the first param Broker will kick you out of the group and subsequent commit will have the error above. Operate `max_poll_interval_ms` to have at least enough time for processing.

**Comment by tvoinarovskyi** [comment]
@dpkp @jeffwidman We should change the error text to match current Java error. It should mention the new param.

**Comment by dpkp** [comment]
The exception does have the updated error text (I added in the heartbeat thread PR), but it looks like I forgot to remove the old error text that was passed in as an arg. That is why the message shown above actually has two parts: the first is correct, but the second is old. Will fix.
