### ISSUE TITLE
Help: Monitoring kafka brokers

### ISSUE THREAD

**Issue by darkprisco** [dpkp/kafka-python#1402]
Hi ,
 I am using kafka-python 1.4.1 in the following way:

` self.cms_consumer = KafkaConsumer(bootstrap_servers=kafka_multi_hosts, auto_offset_reset='latest', enable_auto_commit=False, group_id=self.topics['customer']['group'], reconnect_backoff_ms=50, consumer_timeout_ms=1000, metadata_max_age_ms=30000)`

where my kafka_multi_hosts is formed by three brokers:

`kafka_multi_hosts= kafka-0.kafka.kafka:9092,kafka-1.kafka.kafka:9092,kafka-2.kafka.kafka:9092`

Unfortunately I have seen that KafkaConsumer transparently handle any exceptions, in case them are raised. 
In particular I want to see something in case one of the three brokers goes down.
If I got correctly, to verify the connection I should use BrokerConnection:
```

host = first broker
conn = BrokerConnection(host, 9092, socket.AF_INET)
conn.connect()..
print(conn.state)
```

Is this the correct way to check the status??? Shall I connect every time, considering that this is a periodic Is there any way to check broker connection from KafkaConsumer??? 

Tks
Prisco

@dpkp any help?

**Comment by dpkp** [comment]
kafka-python is not designed to function as a monitoring system. If that is what you are looking for I would suggest using the native broker JMX interface. If that isn't what you are looking for, can you explain a bit more how you would want the consumer to behave when a broker goes down?

**Comment by darkprisco** [comment]
I am interested to know if a broker goes down or not. 
Currently I am testing how library works by stopping the VM where brokers are running. With the latest version I can see that the library is transparently handling (as it is written in the documentation) exceptions, but if I got correctly the KafkaConsumer and KafkaProducer haven't a callback api we can set to manage exception.   
It seems that the only possible solution to my scenario is to use BrokerConnection. 
Now probably this object is not designed to check connection periodically, but it seems the only solution to my problem. right? 
My system is designed to raise alarms in case a broker is down, or at least is one of condition I would like to check.
Another think I have observed is that the subscribe method to one topic (with group id parameter filled because there are 2/3 consumer on the same group/topic) is very slowly to subscribe.  
Any suggestion also for this?

**Comment by tvoinarovskyi** [comment]
> Another think I have observed is that the subscribe method to one topic (with group id parameter filled because there are 2/3 consumer on the same group/topic) is very slowly to subscribe.

This is probably related to group rebalancing. If 1 of 3 consumer is not present the broker will wait for `session_timeout_ms` (or `max_poll_interval_ms` if kafka-python>1.4 and Broker > 0.10) before finishing partition assignment. It's not avoidable if 1 of the consumers just breaks (it will not wait if the consumer is closed properly thou).

**Comment by jeffwidman** [comment]
> My system is designed to raise alarms in case a broker is down, or at least is one of condition I would like to check.

Agree with @dpkp that the JMX interface + Zookeeper is first place I'd be setting alerts. The places you'd use Kafka-python are for monitoring kafka consumer lag, or overall cluster throughput validation/latency monitoring (a script that sends a message every so often, then tries to consume it to verify the message showed up at a reasonable time).

For just overall "liveliness", a very primitive way to monitor is to watch the ephemeral znode created by the brokers in Zookeeper to verify it's showing up. But really, I would suggest not rolling your own check scripts for Kafka by hand... there are a ton of them out there for most every monitoring system from nagios to graphite to ELK to vendors like datadog and signalfx.
