### ISSUE TITLE
'WeakMethod' object has no attribute 'RESPONSE_TYPE'

### ISSUE THREAD

**Issue by tomako** [dpkp/kafka-python#1406]
We got this while polling messages (v1.4.1):

```
AttributeError: 'WeakMethod' object has no attribute 'RESPONSE_TYPE'
  File "kafka/producer/sender.py", line 60, in run
    self.run_once()
  File "kafka/producer/sender.py", line 159, in run_once
    self._client.poll(poll_timeout_ms)
  File "kafka/client_async.py", line 573, in poll
    self._poll(timeout)
  File "kafka/client_async.py", line 626, in _poll
    self._pending_completion.extend(conn.recv())
  File "kafka/conn.py", line 731, in recv
    responses = self._recv()
  File "kafka/conn.py", line 788, in _recv
    responses = self._protocol.receive_bytes(recvd_data)
  File "kafka/protocol/parser.py", line 126, in receive_bytes
    resp = self._process_response(self._rbuffer)
  File "kafka/protocol/parser.py", line 160, in _process_response
    log.debug('Processing response %s', request.RESPONSE_TYPE.__name__)
```

**Comment by dpkp** [comment]
The root cause of this error is not obvious to me. Do you have any more details about the context / the code that generates this error?

**Comment by aptiko** [comment]
@dpkp We don't know much more than you do. All I can tell you is that the last few days this program has consumed very roughly 100 million messages from some topics and has produced an equal number on other topics. This problem has only appeared once. Could it be related to #1399? That one has appeared six times.

@tomako This doesn't seem to occur while the consumer is polling (or, if it does, it's a coincidence); the problem is on the producer (I guess it happens while the producer attempts to do things asynchronously).

(For convenience I repeat the stack trace in a better format.)
```
AttributeError: 'WeakMethod' object has no attribute 'RESPONSE_TYPE'
  File "kafka/producer/sender.py", line 60, in run
    self.run_once()
  File "kafka/producer/sender.py", line 159, in run_once
    self._client.poll(poll_timeout_ms)
  File "kafka/client_async.py", line 573, in poll
    self._poll(timeout)
  File "kafka/client_async.py", line 626, in _poll
    self._pending_completion.extend(conn.recv())
  File "kafka/conn.py", line 731, in recv
    responses = self._recv()
  File "kafka/conn.py", line 788, in _recv
    responses = self._protocol.receive_bytes(recvd_data)
  File "kafka/protocol/parser.py", line 126, in receive_bytes
    resp = self._process_response(self._rbuffer)
  File "kafka/protocol/parser.py", line 160, in _process_response
    log.debug('Processing response %s', request.RESPONSE_TYPE.__name__)
```

**Comment by dpkp** [comment]
Somehow an invalid request object is getting into the protocol parser queue. Are you able to hot-patch kafka-python in your environment? If so, add this and see if you get a stacktrace when the request is added (the trace above happens when it is popped):
```
diff --git a/kafka/protocol/parser.py b/kafka/protocol/parser.py
index 4d77bb3..e0934ed 100644
--- a/kafka/protocol/parser.py
+++ b/kafka/protocol/parser.py
@@ -4,7 +4,7 @@ import collections
 import logging

 import kafka.errors as Errors
-from kafka.protocol.api import RequestHeader
+from kafka.protocol.api import Request, RequestHeader
 from kafka.protocol.commit import GroupCoordinatorResponse
 from kafka.protocol.frame import KafkaBytes
 from kafka.protocol.types import Int32
@@ -50,6 +50,7 @@ class KafkaProtocol(object):
         Returns:
             correlation_id
         """
+        assert isinstance(request, Request), request
         log.debug('Sending request %s', request)
         if correlation_id is None:
             correlation_id = self._next_correlation_id()
```

**Comment by dpkp** [comment]
Hrm -- this may just be a bug related to our handling of `weakref.WeakMethod` objects. investigating further.

Update: I think the stacktrace probably refers to kafka.util.WeakMethod, which should be ok. This is a real stumper...

**Comment by tvoinarovskyi** [comment]
It's very strange again. Again you have a strange object in a strange place, like with #1429. @aptiko Do you use `gevent` or something similar. This really looks like some mocking, monkey patching or stack manipulation...

**Comment by aptiko** [comment]
@dpkp Patching our production environment would be difficult, and, besides, this only occurred once 7 days ago. @tvoinarovskyi No gevent, no mocking, monkey patching or other strangenesses (unless someone ran the unit tests on production, but in that case the entire consumer and producer are mocked out, and this is really a very wild guess). This is a worker process that reads from a topic, performs some processing, and writes results to another topic. I checked the code and it's quite clean; I don't see any way in which consumer stuff could be getting in producer stuff (on our side). Of course I could be mistaken.

**Comment by dpkp** [comment]
What version of python are you running? And what OS / distribution ?

**Comment by aptiko** [comment]
Ubuntu 16.04 with its packaged Python 3.5.2. Kafka 1.0.0.

**Comment by dpkp** [comment]
Haven't heard of this popping up again and I've never reproduced it. There's been significant changes to kafka-python internals since 1.4.1, so I'm going to close and assume it is no longer applicable.
