### ISSUE TITLE
Does Kerberos ticket status affect SSL and the “KafkaConsumer” module?

### ISSUE THREAD

**Issue by diwang917** [dpkp/kafka-python#1407]
I'm debugging a Kafka code
```
from kafka import KafkaConsumer, KafkaProducer
import ssl
...
context = ssl.create_default_context()
context.verify_mode = ssl.CERT_REQUIRED
context.load_verify_locations(self.ssl_cafile)
context.load_cert_chain(certfile=self.ssl_certfile, keyfile=self.ssl_keyfile)
context.options &= ssl.OP_NO_TLSv1
context.options &= ssl.OP_NO_TLSv1_1
return KafkaConsumer (self.inbound_topic, group_id=self.group_id, bootstrap_servers=json.loads(self.bootstrap_servers),
                                 auto_offset_reset=self.auto_offset_reset,
                                 security_protocol=self.security_protocol,
                                 sasl_mechanism=self.sasl_mechanism,
                                 ssl_context=context,
                                 api_version=(0,10))
```

If I run the **kinit** command normally to setup Kerberos ticket, the above code works well. However, if I specified a Kerberos lifetime such as **kinit "-l 15s"**, during 0-14s the above code worked well, but at 15s the above code failed - it stopped at "return KafkaConsumer" and did move forward.

I thought that all the Kafka parameters for "return KafkaConsumer" have been setup during 0-14s, so even though the Kerberos lifetime is 15s, "return KafkaConsumer" should work normally. However it still failed.

So how does Kerberos ticket status affect SSL and "KafkaConsumer" module? Thanks a lot!

**Comment by dpkp** [comment]
What version of kafka-python are you using? Can you provide more details (perhaps a stacktrace) on the exact error you are seeing?
