### ISSUE TITLE
How can I consume the latest offset after restarting the Kafka consumer program  ?

### ISSUE THREAD

**Issue by wql6** [dpkp/kafka-python#1408]
When I restarted the Kafka consumer program, I didn't want to consume  the offset from zookeeper ,  but wanted to consume the latest offset. What should I do?

**Comment by tvoinarovskyi** [comment]
Do you want to commit the offset anyway? If not pass `group_id=None`. See http://kafka-python.readthedocs.io/en/master/apidoc/KafkaConsumer.html. This will disable commits and consumer balancing.
If you don't want to disable group management, you can just skip to latest offset after starting consumer:
```
consumer = KafkaConsumer(...)
consumer. seek_to_end()
for msg in consumer:
   ...
```

**Comment by wql6** [comment]
According to your comments, I met this mistake:   
    consumer.seek_to_end()
  File "Anaconda2\lib\site-packages\kafka\consumer\group.py", line 717, in seek_to_end
    assert partitions, 'No partitions are currently assigned'
AssertionError: No partitions are currently assigned

**Comment by tvoinarovskyi** [comment]
Ehm, yea... We really need to make this easier. I'll get back with a workaround as soon as I get to my laptop

**Comment by dpkp** [comment]
to get this behavior, set `group_id='<your-group-name>'` `auto_offset_reset='latest'` and `enable_auto_commit=False`

**Comment by avarf** [comment]
That didn't work for me as I described at [StackOverflow](https://stackoverflow.com/questions/73689501/reading-the-last-message-from-kafka) but using `end_offsets` and `seek` solved my problem:
```python
from kafka import KafkaConsumer, TopicPartition
import json

consumer = KafkaConsumer(bootstrap_servers='localhost:9092', auto_offset_reset="earliest", enable_auto_commit=True, value_deserializer=lambda x: json.loads(x.decode("utf-8")),consumer_timeout_ms=60,)
consumer.subscribe('52.5_13.4')
partition = TopicPartition('52.5_13.4', 0)
end_offset = consumer.end_offsets([partition])
consumer.seek(partition,list(end_offset.values())[0]-1)

for m in consumer:
  msg = m.value
```
