### ISSUE TITLE
KafkaConsumer  processing same messages in parallel in case of multiple partitions 

### ISSUE THREAD

**Issue by vaibhav293** [dpkp/kafka-python#1417]
I have a kafka (1.0) setup with 3 brokers and each topic distributed in 3 partitions. 

My KafkaConsumer (kafka-python version=1.3.5)  implementation looks something like this:  

```
consumer = KafkaConsumer(config.TOPIC,\
                      bootstrap_servers=config.KAFKA_BOOTSTRAP_SERVERS,\
                      api_version=config.KAFKA_API_VERSION,\
                      group_id=config.CONSUMER_NAME + "_group")
for msg in consumer:
    if 'event_name' in message and message['event_name'] == config.TOPIC:
        with MyController() as myController:
           myController.do_something(**message) 
```

But in the log file, I see the same message getting processed multiple times. It start with first message getting processed onetime and then slowly goes upto 4 parallel processing thread which printing exact same logs. My do_something function is a heavy operation and takes times. 

I am kind of clueless about this situation. 

Here is the kafka-consumer-groups o/p:

```
kafka-consumer-groups.sh --bootstrap-server "..." --describe --group my_group
Note: This will not show information about old Zookeeper-based consumers.


TOPIC                          PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG        CONSUMER-ID                                       HOST                           CLIENT-ID
mytopic         0          152             152             0          kafka-python-1.3.5-00b0b957-65f6-4cfc-9ff9-0ddad708716d/10.31.45.230                  kafka-python-1.3.5
mytopic         1          105             105             0          kafka-python-1.3.5-00b0b957-65f6-4cfc-9ff9-0ddad708716d/10.31.45.230                  kafka-python-1.3.5
mytopic         2          147             147             0          kafka-python-1.3.5-00b0b957-65f6-4cfc-9ff9-0ddad708716d/10.31.45.230                  kafka-python-1.3.5
```

 Please help me troubleshoot this issue.

**Comment by dpkp** [comment]
when you have a "do_something function" that takes a long time you have to be careful to set your session and heartbeat timeouts. The group will mark a consumer as dead if it does not heartbeat within the configured session_timeout_ms. But the consumer will not know that it has been marked dead / kicked out until the next time it tries to heartbeat. In the meantime, the group will rebalance and a different consumer will get assigned the "dead" consumers partitions. This can look like duplicate message processing and is probably what you are seeing. In this case you will need to increase session_timeout_ms to larger than the maximum time that your "do_something function" could take.

Also note that we moved heartbeats to a background thread in kafka-python 1.4 to provide more flexibility (a large session_timeout_ms is not ideal as it makes recovery from an actual failure take much longer).

**Comment by vaibhav293** [comment]
Hello dpkp, 

Thanks for the pointer. I think tweaking session_timeout_ms, heartbeat_interval_ms, request_timeout_ms
 has solved the problem. 

Regards,
Vaibhav

**Comment by holuborhee** [comment]
> (a large session_timeout_ms is not ideal as it makes recovery from an actual failure take much longer).

A better solution to this is to not touch the `session_timeout_ms`, [this proposal KIP-62](https://cwiki.apache.org/confluence/display/KAFKA/KIP-62%3A+Allow+consumer+to+send+heartbeats+from+a+background+thread) already provided a better way; `max.poll.interval.ms`. This is the time it takes a consumer to process a batch of records, and it was separated from the `session.timeout.ms` so you can process for a longer time without the consumer being marked as dead.

An important part to be conscious of though is the `max.poll.records` which is the number of records being fetched at each poll (default is set to 500), your `max.poll.interval.ms` should be a product of time for `do_something` function to execute and the `max.poll.records`. So if 

`do_something` function time = 1 min
`max.poll.records` = 3

then you should set max.poll.interval.ms to a minimum of `180000`ms (3 minutes)
