### ISSUE TITLE
After I restart the kafka broker, the consumer can not continue consume the topic.

### ISSUE THREAD

**Issue by lvsoso** [dpkp/kafka-python#1419]
I using kafka-python(version 1.4.1) for an project , I hope the consumer and the producer can continue work normally.

But I test when the kafka broker(one node) close，what will happen to the consumer and the producer.

The situation as follow:

First, I start the zookeeper and the kafka broker.

Then, I stop the kafka broker and waiting about 1 minuter.
The producer produce slowly than before , but have not exception.
And the consumer too.

Finally I restart the kafka broker.
The producer continue produce.
But the consumer can not continue consume until I restart it.

There is the Code of consumer and producer(I copy from the kafka document):

    #consumer.py
    from kafka import KafkaConsumer
    
    # To consume latest messages and auto-commit offsets
    consumer = KafkaConsumer('my-topic',
                             group_id='my-group',
                             bootstrap_servers=['localhost:9092'])
    for message in consumer:
        # message value and key are raw bytes -- decode if necessary!
        # e.g., for unicode: `message.value.decode('utf-8')`
        print ("%s:%d:%d: key=%s value=%s" % (message.topic, message.partition,
                                              message.offset, message.key,
                                              message.value))   

----------

    # producer.py
    
    from kafka import KafkaProducer
    from kafka.errors import KafkaError
    
    producer = KafkaProducer(bootstrap_servers=['broker1:1234'])
    
    
    for _ in range(100000):
        producer.send('my-topic', b'msg')
        producer.flush()

**Comment by infecto** [comment]
@wuqize Any logs? It would be helpful to know what errors if any are present? How many nodes are being run in the cluster?

**Comment by tvoinarovskyi** [comment]
Maybe related to #1418.

**Comment by dpkp** [comment]
I am not able to reproduce this

**Comment by amitmay94** [comment]
Did you find any solution for this ? We are facing the same issue due to kafkaAdmin.
