### ISSUE TITLE
Help: consumer offset changed and then not able to get all messages

### ISSUE THREAD

**Issue by jgarnier** [dpkp/kafka-python#1421]
I'm currently using kafka python 1.3.5 and having issue with consumer offset.
I've created a topic in my cluster only containing one broker (Kafka 0.11.0.2) with one partition and I push on a regular basis message and this topic and consume them to ensure Kafka is fully operational.
What is happening so far is that I did not get all the message using KafkaConsumer whereas I get them using kafka-console-consumer.sh

here is a simplified version of my python script which run every minutes:
```python
topicpartition = TopicPartition('test', 0)
producer = KafkaProducer(bootstrap_servers=["10.0.1.7:9092"],acks='all')
consumer = KafkaConsumer(group_id='test-group',
                bootstrap_servers=["10.0.1.7:9092"],
                consumer_timeout_ms=30000)
consumer.assign([self.topicpartition])
consumer.seek_to_end(self.topicpartition)
offset = consumer.committed(topicpartition)
print("consumer new offset is [%d]",offset)

#push 10 messages
for i in xrange(10):
    #create a test message 
    producer.send(self.topic, mymessage)

for message in consumer:
    consumer.commit()
    print("consumer message [%s] - offset is [%d]",
                                 message.value,
                                 message.offset)
```

so the logic is that I put my consumer on the last offset commit to ensure the next 10 messages produced are the right ones I'm consuming.
Then what happen on a regular basis is that between the seek to end and the message in consumer, offset change so I'm not able to process all messages.
Here is an example of the output when everything is fine:
`
consumer reset new offset is [160]
consumer message [0] - offset is [160]
consumer message [1]  - offset is [161]
consumer message [2] - offset is [162]
consumer message [3] - offset is [163]
consumer message [4] - offset is [164]
consumer message [5] - offset is [165]
consumer message [6] - offset is [166]
consumer message [7] - offset is [167]
consumer message [8] - offset is [168]
consumer message [9] - offset is [169]
`

and when there is offset change:
`
consumer reset new offset is [130]
consumer message [7] - offset is [137]
consumer message [8] - offset is [138]
consumer message [9] - offset is [139]
`

As you can see, the 1rst message read is with offset 137 but it should be 130, then I've missed 7 messages...

Did anyone already saw this?
Thanks.

**Comment by tvoinarovskyi** [comment]
I don't really follow the problem. For starter your code is doing `consumer.seek_to_end(self.topicpartition)` but printing `offset = consumer.committed(topicpartition)`. Those are different offsets. You don't need the `seek_to_end` part to read from committed point, just omit it and try again.

**Comment by jgarnier** [comment]
ok the seek might not be used as this is not the same offset at the end.
Then could this cause the different offset from the committed one and the first message consume offset?
Currently performing more tests to see if I still have the issue.

**Comment by tvoinarovskyi** [comment]
> Then could this cause the different offset from the committed one and the first message consume offset?

Yes, it probably does
