### ISSUE TITLE
After set group_id can not receive any message

### ISSUE THREAD

**Issue by suai723** [dpkp/kafka-python#1427]
if I not set group_id，the code can run normally and can receive data .but after add group_id option,consumer can not receive any message  and no error messages report.have I not set other option yet ?please help Thanks!!!!!!!

```python
from kafka import KafkaConsumer
from kafka import TopicPartition

consumer = KafkaConsumer(
    group_id='a1',
    bootstrap_servers='10.10.35.5',
    auto_offset_reset='earliest'
)
partition = TopicPartition('binlogtest', 2)
consumer.assign([partition])

for message in consumer:
    # message value and key are raw bytes -- decode if necessary!
    # e.g., for unicode: `message.value.decode('utf-8')`
    print ("%s:%d:%d: key=%s value=%s" % (message.topic, message.partition,
                                          message.offset, message.key,
                                          message.value))


```

**Comment by tvoinarovskyi** [comment]
When you set `group_id` the default behaviour is to `autocommit` every n second the processed offset. In other words, you read the data once and it `committed` the last offset for data. After restarting it started reading from the committed point, not getting new data. Try to pass a new `group_id`, it will consume messages another time. With `group_id=None` the commit does not happen, so you can read data each time you start the script.
You can read about the related options on `http://kafka-python.readthedocs.io/en/master/`
