### ISSUE TITLE
Offset commit not working

### ISSUE THREAD

**Issue by gyoga99** [dpkp/kafka-python#1446]
I am trying to commit the offset upon successful completion of work after consuming the message. But the offset does not seem to be set. 

When I restart the consumer with same group_id set, it is picking messages right from the beginning.

I am using KafkaConsumer and enable_auto_commit = False,auto_offset_reset='earliest'
for msg in consumer
do something
if Success:
options = {}
options[msg.partition] = OffsetAndMetadata(msg.offset+1, None)
consumer.commit(options)

**Comment by jeffwidman** [comment]
What version of kafka-python / kafka brokers? What happens when you call commit... can you post debug logs?

**Comment by dpkp** [comment]
Set a `group_id` and it should work fine.

**Comment by gyoga99** [comment]
kafka-python - 1.4.2 
Kafka - 1.0.1
And I set the group_id as well on the consumer
group_id='sample-group'

But still Offset is not committed. When i restart the consumer it starts from first message. Is there anything I need to make sure?

**Comment by mikolaje** [comment]
> kafka-python - 1.4.2
> Kafka - 1.0.1
> And I set the group_id as well on the consumer
> group_id='sample-group'
> 
> But still Offset is not committed. When i restart the consumer it starts from first message. Is there anything I need to make sure?

So do I, a topic can't commit message whatever I set, I already set the group_id and so on. What made me confused is that another topic is absolutely normal with same way to consume!
