### ISSUE TITLE
akka producer in hang

### ISSUE THREAD

**Issue by ealfatt** [dpkp/kafka-python#1449]
Hello
I've this problem: my producer is register on 3 different topics on 3 different hosts and works fine.
But if i switch off the host of the leader, the producer goes in hang and at the end go in timeout even if a new leader was already elected
because the other 2 host are always work and running i'd like the producer could aware of the new leader  and continue to work without disruption.
what is the parameter i must to set to have this?

thanks in advance

**Comment by dpkp** [comment]
akka runs on the jvm... Are you sure you are using kafka-python ?
