### ISSUE TITLE
PyPi have kafka (1.3.5) and kafka-python (1.4.2) modules at the same time

### ISSUE THREAD

**Issue by SDxKeeper** [dpkp/kafka-python#1450]
Hi,

We have stepped into issue that installing latest kafka-python using "pip install kafka" resulted in version 1.3.5.
Small investigation shows that there are same module under 2 names in PyPi
https://pypi.python.org/pypi/kafka-python/1.4.2
https://pypi.python.org/pypi/kafka/1.3.5

Which name should we rely on in future ?

**Comment by dpkp** [comment]
`pip install kafka-python`  see #1253 and #82 for some background
