### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by mikmatko** [dpkp/kafka-python#1451]
**```async```** is a reserved keyword in Python 3.7.
**```async```** is used a bit in kafka-python, so this currently breaks Python 3.7 compatibility. See e.g. ```producer/base.py```

Using something like **```async_```** would be fine though, so quickest way to resolve this would be just to rename a few things from **```async```** to **```async_```** or something like that.

Thanks!

**Comment by dpkp** [comment]
This requires a breaking change to the `SimpleProducer` interface (renaming the public `async=True` kwarg to something else). So we will need to be careful about how we roll this out.

**Comment by tvoinarovskyi** [comment]
Just use kwargs...

**Comment by dpkp** [comment]
We wont be able to keep the `async` kwarg:
```
Python 3.7.0b2 (default, Mar 22 2018, 10:48:35)
[Clang 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> def foo(async=True):
  File "<stdin>", line 1
    def foo(async=True):
                ^
SyntaxError: invalid syntax
>>>
```

Which means we are going to have to break the current interface...

**Comment by tvoinarovskyi** [comment]
I meant something like:
```
>>> def send(self, **kwargs):
...     if 'async' in kwargs:
...         print(kwargs['async'])
... 
>>> send(1)
>>> send(1, async=True)
True
```

**Comment by dpkp** [comment]
Nice! So passing `async=True` would still work on older pythons. Great call.

**Comment by dpkp** [comment]
Fixed in #1454

**Comment by ATajadod94** [comment]
Issue persists on pip install as of today

**Comment by IgorBrehm** [comment]
> Issue persists on pip install as of today

You need to pip uninstall kafka and then pip install kafka-python
The package named kafka is still with an older version without the fix, but the package kafka-python is up to date...
