### ISSUE TITLE
Kafka client always handshakes with highest broker version

### ISSUE THREAD

**Issue by helenaut** [dpkp/kafka-python#1455]
We are trying to do a rolling upgrade of our Kafka brokers from 0.9 to 1.0, but we are running into message version incompatibility issues. These issues could be avoided if the client always handshook with the broker with the lowest version, but it seems like the client looks for the broker with the highest version and handshakes from there. Is there a way for the client to always use the lowest version amongst the brokers?

**Comment by dpkp** [comment]
Have you tried setting `api_version=(0, 9)` ?

**Comment by helenaut** [comment]
Hi @dpkp, thanks so much for the tip. We tried it and everything works smoothly now.

The auto-detection of the api_version doesn’t seem to correctly detect the highest supported version for individual brokers. It seems to be assuming a cluster is homogenous in broker version, which is not the safest assumption to make. I can see how this could be the way it is was intentionally designed, though.

Anyway, thank you again for the help! Next time I will read the documentation more carefully.

**Comment by dpkp** [comment]
Glad that worked! You are correct that the auto-detection is wonky if your cluster has brokers running different versions. I generally suggest using `api_version` anyways when going to production (assuming you control your own broker infrastructure).
