### ISSUE TITLE
KafkaProducer.send does not raise NameError in custom serializer

### ISSUE THREAD

**Issue by Po-Hsun-Su** [dpkp/kafka-python#1462]
The `KafkaProducer.send` function has a try/except clause that hides the exception in a custom serializer. This makes finding bugs inside custom serializer difficult. 
Example code:
```python
from kafka import KafkaProducer

def raiseError():
    raise NameError

producer = KafkaProducer(bootstrap_servers="localhost:9092",
                 value_serializer=lambda m: raiseError(m))
producer.send("topic", "value", "key")
```
This program will not raise error even though it should. Adding `except NameError:` in `KafkaProducer.send` can solve this no raise issue, but I am not sure if this is a good idea.

**Comment by dpkp** [comment]
I'm not able to reproduce this. KafkaProducer.send does have a try/except but it only catches protocol response errors. Exceptions raised by serializers will go to the user. Are you using an older version?

**Comment by dpkp** [comment]
see #1316
