### ISSUE TITLE
Producer `send` blocking if topic does not exist (and can not be created). [help wanted]

### ISSUE THREAD

**Issue by mmodenesi** [dpkp/kafka-python#1467]
I start up my kafka broker with configuration `auto.create.topics.enable=false` (meaning all topics must be crated explicitly using `kafka-topics.sh` tool). Assuming `my_topic` topic was crated and `non_existent` was not:

```python
In [9]: producer.send('my_topic', some_message)
Out[9]: <kafka.producer.future.FutureRecordMetadata at 0x7ff0c0463a90>

In [10]: producer.send('non_existent', some_message)
---------------------------------------------------------------------------
KafkaTimeoutError                         Traceback (most recent call last)
<ipython-input-10-f23dc2bcf23c> in <module>()
----> 1 producer.send('non_existent', some_message)

~/virtualenvs/medusa/lib/python3.5/site-packages/kafka/producer/kafka.py in send(self, topic, value, key, partition, timestamp_ms)
    541         key_bytes = value_bytes = None
    542         try:
--> 543             self._wait_on_metadata(topic, self.config['max_block_ms'] / 1000.0)
    544 
    545             key_bytes = self._serialize(

~/virtualenvs/medusa/lib/python3.5/site-packages/kafka/producer/kafka.py in _wait_on_metadata(self, topic, max_wait)
    662             if not metadata_event.is_set():
    663                 raise Errors.KafkaTimeoutError(
--> 664                     "Failed to update metadata after %.1f secs." % max_wait)
    665             elif topic in self._metadata.unauthorized_topics:
    666                 raise Errors.TopicAuthorizationFailedError(topic)

KafkaTimeoutError: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
```

**Is this the correct behavior?**

I would expect to have in front of me a different exception.

In my case, I want to test this behavior explicitly (my code trying to write to a non existent topic) but I don't want to wait so much. Maybe I can set `max_block_ms` to a lower value (Default: 60000). Even still, how can I separate a timeout due to some temporary connectivity issue from a timeout caused by inability to write to a non existen topic?

Thank you!

**Comment by rwaweber** [comment]
In my experience using the Java library(via logstash) this tends to loop and return an `UNKNOWN_TOPIC_OR_PARTITION` error. I think that this could be a handy exception to be put together and thrown. No idea how much work is required for it here though

[Cite](https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/protocol/Errors.java#L124)

**Comment by dpkp** [comment]
Use .get() to resolve the future. It will raise the exception youre looking
for.
