### ISSUE TITLE
Invalid bootstrap servers list blocks during startup

### ISSUE THREAD

**Issue by mmodenesi** [dpkp/kafka-python#1473]
```python
>>> kafka.KafkaProducer(bootstrap_servers='can-not-resolve:9092')
# never returns
```

**Comment by dpkp** [comment]
It will continue to check DNS until thr name resolves. This helps maintain
continuous performance during temporary network outages. What were you
expecting?

**Comment by mmodenesi** [comment]
I see your point. So, this is a good thing when there is a temporary problem and the name will eventually be resolved properly again. But what if the provided name is plain wrong? (say, for example, you edited some configuration files and mispelled the server fqdn).

I though "there should be an optional `timeout` argument.". I could not find it at first glance in the documentations (I should say, I am using 1.4.2).  Then, grepping the code for the warning `DNS lookup failed for not-a-valid-name:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?`) I found it is produced around

https://github.com/dpkp/kafka-python/blob/c0fddbd24269d4333e3b6630a23e86ffe33dfcb6/kafka/conn.py#L288

(Note that the presence of the named argument made me think I was on the right track)

which is called from 

https://github.com/dpkp/kafka-python/blob/c0fddbd24269d4333e3b6630a23e86ffe33dfcb6/kafka/client_async.py#L245

definitely without any arguments.

In my opinion, this should not enter the infinite loop unavoidably.

I am only starting with both kafka and your code, so I don't know the implications of this (I mean, may be this function is called on bootstrapping and then every 10 seconds for metadata refreshing, I really don't know if what I am asking is way stupid).

This is what I would expect:
```
$ docker run --rm kafka:2.11-1.1.0 kafka-console-producer.sh --topic test --broker-list con-cristina-estabamos-mejor:9092  [19:50:09]
[2018-04-12 22:50:30,316] WARN Removing server con-cristina-estabamos-mejor:9092 from bootstrap.servers as DNS resolution failed for con-cristina-estabamos-mejor (org.apache.kafka.clients.ClientUtils)
org.apache.kafka.common.KafkaException: Failed to construct kafka producer
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:456)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:303)
        at kafka.producer.NewShinyProducer.<init>(BaseProducer.scala:40)
        at kafka.tools.ConsoleProducer$.main(ConsoleProducer.scala:49)
        at kafka.tools.ConsoleProducer.main(ConsoleProducer.scala)
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
        at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:66)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:405)
        ... 4 more
```

**Comment by dpkp** [comment]
The two options here would be (1) validate that bootstrap_servers resolve via DNS to at least one IP address; (2) validate that bootstrap succeeds and we are able to get initial cluster metadata.

**Comment by svvitale** [comment]
I agree with @mmodenesi that this should be configurable, either with a timeout or a max number of retries, and should raise an exception on exhaustion of retries.  Ultimately the caller should be able to make a choice about whether to reconnect ad naseum or handle the exception in a different way.  Also, I think the `reconnect_backoff_ms` and `reconnect_backoff_max_ms` options should be honored, even when DNS resolution fails.

**Comment by svvitale** [comment]
I've started on these changes here: https://github.com/svvitale/kafka-python/commit/e60129c975b8a98fd17a0efa29addd5b86789fc6

@dpkp, let me know if you agree with this approach and I'd be happy to add documentation for these new parameters and file a pull request.

**Comment by jeffwidman** [comment]
@dpkp, I saw your PR just disabled retries.

As @svvitale noted, what do you think about making this configurable?

My day job has a flaky DNS server that's owned by another team and every few hours it will drop some queries... I'd prefer not to make my kafka-python wrapper more complex to handle this just to make sure those retries continue to happen. Fixing the root cause here ultimately will require swapping out the DNS server which is a massive project for us, so unlikely to happen anytime soon.

I also understand the perspective of folks who want this to fail loudly and immediately in case they typo'd.

So would it be possible to add a timeout config that defaults to failing quickly, but could be passed a larger value to keep retrying for a period of time?

Or as @svvitale suggested, could just inherit this retry timeout value from `reconnect_backoff_max_ms`

If you want a PR for this, I'm more than happy to do so, but I wanted to discuss the API first.

**Comment by dpkp** [comment]
That seems like a good thing to make configurable. To be clear, it only currently affects bootstrapping (once an initial metadata response is found, all future "reconnects" should continue retries after backoff even if DNS fails). But I do think that folks would prefer the default behavior be to assume DNS is functioning properly and not retry at all.
