### ISSUE TITLE
Consumer can't reconnect after brokers restart

### ISSUE THREAD

**Issue by avi-slavkin** [dpkp/kafka-python#1477]
When brokers restarted for whatever reason SOMETIME consumer entering infinite loop throwing this exception:"Give up sending metadata request since no node is available".Restart of consumer is fixing it but the problem is happening quite a lot.

**Comment by dpkp** [comment]
What version of kafka-python are you using?

**Comment by avi-slavkin** [comment]
1.4.2

**Comment by avi-slavkin** [comment]
Another thing that might be important,we use eventlet and apply monkey patch.

**Comment by Ronniexie** [comment]
we alse have this same problem. When brokers restarted ,consumer con't get message.we use 1.4.3 version. How to solve this problem？

**Comment by dpkp** [comment]
Can you try 1.4.4?
