### ISSUE TITLE
Help: Unable to bootstrap from public cloud to private network

### ISSUE THREAD

**Issue by siva5055** [dpkp/kafka-python#1479]
When trying to run producer from a public VM (aws) to a broker on our private network, I'm facing below issue. and 'Give up sending......' been printed infinite

Ports 9092 and 2181 are opened up to access from cloud

LOG:
WARNING:kafka.conn:<BrokerConnection node_id=bootstrap host=<my_IP>:9092 <connected> [IPv4 ('my_IP', 9092)]> timed out after 30000 ms. Closing connection.
INFO:kafka.conn:<BrokerConnection node_id=bootstrap host=my_IP:9092 <connected> [IPv4 ('my_IP', 9092)]>: Closing connection. [Error 7] RequestTimedOutError: Request timed out after 30000 ms
ERROR:kafka.client:Unable to bootstrap from [('my_IP', 9092, 0)]
DEBUG:kafka.metrics.metrics:Added sensor with name bufferpool-wait-time
DEBUG:kafka.metrics.metrics:Added sensor with name batch-size
DEBUG:kafka.metrics.metrics:Added sensor with name compression-rate
DEBUG:kafka.metrics.metrics:Added sensor with name queue-time
DEBUG:kafka.metrics.metrics:Added sensor with name produce-throttle-time
DEBUG:kafka.metrics.metrics:Added sensor with name records-per-request
DEBUG:kafka.metrics.metrics:Added sensor with name bytes
DEBUG:kafka.metrics.metrics:Added sensor with name record-retries
DEBUG:kafka.metrics.metrics:Added sensor with name errors
DEBUG:kafka.metrics.metrics:Added sensor with name record-size-max
DEBUG:kafka.producer.sender:Starting Kafka producer I/O thread.
DEBUG:kafka.producer.kafka:Kafka producer started
DEBUG:kafka.client:Give up sending metadata request since no node is available
DEBUG:kafka.producer.kafka:Requesting metadata update for topic alpr_entry
DEBUG:kafka.client:Give up sending metadata request since no node is available
DEBUG:kafka.client:Give up sending metadata request since no node is available
DEBUG:kafka.client:Give up sending metadata request since no node is available
DEBUG:kafka.client:Give up sending metadata request since no node is available
DEBUG:kafka.client:Give up sending metadata request since no node is available
DEBUG:kafka.client:Give up sending metadata request since no node is available
....................................

**Comment by dpkp** [comment]
Were you able to resolve this? Have you verified that you can connect a TCP socket using other networking tools and/or the official kafka command-line client?
