### ISSUE TITLE
kafka.errors.NoBrokersAvailable: NoBrokersAvailable

### ISSUE THREAD

**Issue by A-AFTAHI** [dpkp/kafka-python#1482]
i'm new with apache kafka. i created a script where i define producer and consumer functions but i'm uneable to start the broker.any help please

**Comment by siva5055** [comment]
Client might not be finding active connection or kafka server. Could you post the code and error log?

**Comment by kadnan** [comment]
@siva5055 I am also having a similar issue. Below is the code:

```
from kafka import KafkaConsumer

if __name__ == '__main__':
    consumer = KafkaConsumer('DAILY_SALES')
    for msg in consumer:
        print(msg)
```

*Kafka related Details*

Zookeeper: 0.0.0.0/0.0.0.0:2181
Producer: `bin/kafka-console-producer.sh --broker-list 0.0.0.0:9092 --topic DAILY_SALES`
Consumer: `bin/kafka-console-consumer.sh --bootstrap-server 0.0.0.0:9092 --topic DAILY_SALES`

Please help. Is there way to set IPs and Port?

**Comment by dpkp** [comment]
You cannot connect to 0.0.0.0 with kafka-python. Use `localhost` or 127.0.0.1 instead and it should work fine.

**Comment by dishashetty** [comment]
My Code:

from kafka import KafkaConsumer
consumer = KafkaConsumer('mytopic', bootstrap_servers=['localhost:9092'])
for msg in consumer:
        print(msg)


Error:
 
File "/home/ubuntu/.local/lib/python2.7/site-packages/kafka/vendor/six.py", line 561, in next
    return type(self).__next__(self)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/kafka/consumer/group.py", line 1123, in __next__
    return next(self._iterator)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/kafka/consumer/group.py", line 1067, in _message_generator
    self._client.poll(timeout_ms=poll_ms)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/kafka/client_async.py", line 561, in poll
    self._poll(timeout)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/kafka/client_async.py", line 579, in _poll
    ready = self._selector.select(timeout)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/kafka/vendor/selectors34.py", line 466, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)

**Comment by arvindeybram** [comment]
> My Code:
> 
> from kafka import KafkaConsumer
> consumer = KafkaConsumer('mytopic', bootstrap_servers=['localhost:9092'])
> for msg in consumer:
> print(msg)
> 
> Error:
> 
> File "/home/ubuntu/.local/lib/python2.7/site-packages/kafka/vendor/six.py", line 561, in next
> return type(self).**next**(self)
> File "/home/ubuntu/.local/lib/python2.7/site-packages/kafka/consumer/group.py", line 1123, in **next**
> return next(self._iterator)
> File "/home/ubuntu/.local/lib/python2.7/site-packages/kafka/consumer/group.py", line 1067, in _message_generator
> self._client.poll(timeout_ms=poll_ms)
> File "/home/ubuntu/.local/lib/python2.7/site-packages/kafka/client_async.py", line 561, in poll
> self._poll(timeout)
> File "/home/ubuntu/.local/lib/python2.7/site-packages/kafka/client_async.py", line 579, in _poll
> ready = self._selector.select(timeout)
> File "/home/ubuntu/.local/lib/python2.7/site-packages/kafka/vendor/selectors34.py", line 466, in select
> fd_event_list = self._epoll.poll(timeout, max_ev)

@dishashetty you need to add the `api_version` parameter beside the bootstrap servers while initializing the Kafka consumers. Then it would work. 
Something like 
`consumer = KafkaConsumer(
                                                      'my_favorite_topic',
                                                      bootstrap_servers='localhost:1234',
                                                      api_version=(0,10))`
