### ISSUE TITLE
Use custom Login Module other than PlainLoginModule

### ISSUE THREAD

**Issue by mddubey** [dpkp/kafka-python#1483]
Hello People,

We are using the kafka-python library to connect to our Kafka-instances. To access this we needs to be authenticated and it is not plain username/password authentication, we need to get a access_token from Identity-Service and use it to access the kafka-instances.

Can you please tell me how to configure this in kafka-python? It is same as doing something below in java:-

```
KafkaClient {
  com.mykafka.KafkaIdentityClientLoginModule required;
};
```
Where `KafkaIdentityClientLoginModule` is the name of the custom login module.

Thanks

**Comment by jeffwidman** [comment]
You need to plumb this together at your application layer--fetch the login info and then pass it through to the kafka.
