### ISSUE TITLE
OSError: [WinError 10038] An operation was attempted on something that is not a socket,while executing kafka-python code

### ISSUE THREAD

**Issue by vkvarunkapoor** [dpkp/kafka-python#1485]
from kafka import KafkaConsumer

# To consume latest messages and auto-commit offsets
consumer = KafkaConsumer('test',
                         group_id='group1',
                         bootstrap_servers=['localhost:9092'])
for message in consumer:
    # message value and key are raw bytes -- decode if necessary!
    # e.g., for unicode: `message.value.decode('utf-8')`
    print ("%s:%d:%d: key=%s value=%s" % (message.topic, message.partition,
                                          message.offset, message.key,
                                          message.value))
am executing this simple producer program
while executing my code am getting the error:

  File "C:\Users\varkapoo\AppData\Local\Programs\Python\Python35\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Users\varkapoo\AppData\Local\Programs\Python\Python35\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
OSError: [WinError 10038] An operation was attempted on something that is not a socket

My code works fine at my personal machine,but in my office machine  am getting this error.
what could be the reason for this

**Comment by jeffwidman** [comment]
This traceback looks like a bug in python's stdlb `selectors` module and how it talks to Windows.

I don't think there's anything we can do, and AFAIK none of the active maintainers use Windows so afraid we can't help much with debugging.
