### ISSUE TITLE
Scram mechanism support

### ISSUE THREAD

**Issue by diasjorge** [dpkp/kafka-python#1486]
Hi,

I'd like to implement scram support for this library, unfortunately I haven't found any specification on how to do this. I tried looking at other implementations but I can't make sense of the expected messages and order.

Can someone point me in the right direction? Or are the maintainers planning to add this support anytime soon?

Thanks :)

**Comment by jeffwidman** [comment]
Not planning to add this myself, and I doubt the others are either, but certainly open to a PR if you're interested in adding this.

**Comment by renedlog** [comment]
I would be also interested in seeing support for SCRAM-SHA-256/512.
Probably the easy way would be a port of the Confluent Kafka solution https://github.com/confluentinc/confluent-kafka-python

**Comment by diasjorge** [comment]
No longer interested in this

**Comment by Neustradamus** [comment]
It is has been added here:
- https://github.com/dpkp/kafka-python/pull/1918
