### ISSUE TITLE
Appropriately handling long running processes from causing Heartbeat session expirations

### ISSUE THREAD

**Issue by vaskokj** [dpkp/kafka-python#1491]
I have this consumer...

```
    def my_consumer(self):
      consumer = KafkaConsumer("topic", bootstrap_servers=self.kafka_server + ":" + str(self.kafka_port),
      enable_auto_commit=False,
      group_id="topic_group")
      for msg in consumer:
         dict = json.loads(msg.value.decode('UTF-8'))
         self.lots_of_work(dict["id"]) //this can last for a few seconds to 15 minutes
         consumer.commit()
```

I'll get this Warning message saying the heartbeat is timing out. This seems to indicate to me that session_timeout_ms is being hit and its being kicked out of the consumer group. Which seems to be the case because if I add session_timeout_ms=300000 into my KafkaConsumer() it doesn't time out as quickly. 

> 2018-05-09 10:19:06,607 - kafka.coordinator - WARNING - Marking the coordinator dead (node 0) for group steppart: Heartbeat session expired.

The  `self.lots_of_work(dict["id"])` is as small of unit as I can consume (it converts a single file with an external processes). This indicates that the actual heartbeat thread is timing out because my thread is possibly stopping the heartbeat thread from responding. Which seems to be the reason as indicated by this thread (https://github.com/dpkp/kafka-python/issues/1285). However, I'm not sure how to handle this to fix the issue. Is my assessment correct that the python GIL could be stopping the heartbeat thread from responding? Any suggestions on how to fix this?

**Comment by dpkp** [comment]
What version of kafka-python are you using? Background thread for
heartbeating was introduced in 1.4

**Comment by dpkp** [comment]
Feel free to reopen if you are already on 1.4. Otherwise I assume this is solved via upgrade.

**Comment by Richard-Mathie** [comment]
@vaskokj, @dpkp 

I have this same issue in 1.4.3 if the task in the consumption loop takes longer than `max_poll_interval_ms` the heartbeat times out.

I got round this by putting the long running task into another thread and using queues to broker the records and the commits to the Kafka consumer

see here

https://gist.github.com/Richard-Mathie/c1202e23bb60c369b6e8e8f58f29527b

is there a simpler way?

**Comment by Richard-Mathie** [comment]
Example code to cause the bug btw
```python
import logging
import time
from kafka import KafkaConsumer, KafkaProducer

logger = logging.getLogger(__name__)

hosts = "localhost:29092"
topic = "test_toppic"

consumer = KafkaConsumer(
        topic,
        group_id='test1',
        bootstrap_servers=hosts,
        auto_commit_interval_ms=1000,
        max_poll_interval_ms=2000
    )

producer = KafkaProducer(
        bootstrap_servers=hosts,
        key_serializer=lambda x: x.encode(),
        value_serializer=lambda x: x.encode()
    )

for i in range(100):
    producer.send(topic, key=f'{i}', value=f'hello {i}')

logging.basicConfig(level=logging.INFO)

for record in consumer:
    logger.info(f'processing message {record}')
    time.sleep(3)
```

**Comment by omriShneor** [comment]
Why is this closed? what is the solution for this bug? My team is running on kafka version 2.2.0
and we still suffer from this error.

**Comment by jeffwidman** [comment]
Please open a new ticket, this one is closed.

**Comment by dpkp** [comment]
I believe this is fixed in the latest release. If you have problems w
version 2.0, please open a new ticket.
