### ISSUE TITLE
ensure_coordinator_ready loops indefinitely if coordinator not ready

### ISSUE THREAD

**Issue by MichaelBehnke** [dpkp/kafka-python#1493]
Hello,

I'm neither experienced with kafka in general nor with kafka-python in particular, so bear with me if there is already an obvious solution to that problem.

We are using kafka in a kubernetes environment, so far only for staging experiments. We are using the robot framework for integration testing. We have some tests that check if logs have been successfully written to kafka, for that we are using kafka-python and a consumer to consume the corresponding topics. Normally this works as expected, but apparently there are still some bugs in our kubernetes setup, that is to say something can go wrong with kafka and/or zookeeper without liveness probes indicating any problem (but actually that's beside the point, we need to fix that as well of course). In that case the robot tests run indefinitely without any indication of a problem (might be because we do not see kafka-python logs because of the robot framework in between). After some debugging it turns out that the method ensure_coordinator_ready in coordinator/base.py goes into an endless loop if there is no coordinator available. As far as I can tell there is no timeout for this method, even if already the initial creation failed.

There were a few issues already with similar problems, but I haven't seen any of those specifically about this method. Is there already a solution to that problem, or does it make sense to add a timeout to this method as well (as there are already quite a few timeouts for different parts of the library).

Kind regards,
Michael

**Comment by robgolding** [comment]
I experienced this issue too, but it was fixed by in 1.4.3 by https://github.com/dpkp/kafka-python/pull/1464.

**Comment by jeffwidman** [comment]
@MichaelBehnke please try 1.4.3 and see if the issue still re-appears.

**Comment by chengdianxuezi** [comment]
I  also encoutered this problem, sometimes the kafka reader hang after print out the log:
Heartbeat failed for group groupid because it is rebalancing

**Comment by chengdianxuezi** [comment]
I also encoutered this problem, sometimes the kafka reader hang after print out the log:
Heartbeat failed for group groupid because it is rebalancing

the kafka version is :kafka-python   1.4.3

**Comment by chengdianxuezi** [comment]
@MichaelBehnke Have you solved this problem
