### ISSUE TITLE
NoBrokersAvailable

### ISSUE THREAD

**Issue by kadnan** [dpkp/kafka-python#1496]
Hi
Like many, I am also having the same issue. I tried everything yet the same issue. Below are the details.

```
from kafka import KafkaConsumer

if __name__ == '__main__':
    consumer = KafkaConsumer('DAILY_SALES', bootstrap_servers=['0.0.0.0:9092'])
    for msg in consumer:
        print(msg)
```
Error Details:

```
    consumer = KafkaConsumer('DAILY_SALES', bootstrap_servers=['0.0.0.0:9092'])
  File "/anaconda3/anaconda/lib/python3.6/site-packages/kafka/consumer/group.py", line 340, in __init__
    self._client = KafkaClient(metrics=self._metrics, **self.config)
  File "/anaconda3/anaconda/lib/python3.6/site-packages/kafka/client_async.py", line 219, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/anaconda3/anaconda/lib/python3.6/site-packages/kafka/client_async.py", line 839, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
```
*Kafka related Details*

Zookeeper: 0.0.0.0/0.0.0.0:2181
Producer: `bin/kafka-console-producer.sh --broker-list 0.0.0.0:9092 --topic DAILY_SALES`
Consumer: `bin/kafka-console-consumer.sh --bootstrap-server 0.0.0.0:9092 --topic DAILY_SALES`

**Comment by dpkp** [comment]
`'0.0.0.0:9092'` is not a supported IPv4 address. Try using something more specific, perhaps 127.0.0.1?

**Comment by kadnan** [comment]
`.0.0.0.0` is a  valid address and it [worked](https://en.wikipedia.org/wiki/0.0.0.0) for me.

**Comment by dpkp** [comment]
Correct, but I am saying that 0.0.0.0 is unsupported in kafka-python.
