### ISSUE TITLE
Documentation mismatch

### ISSUE THREAD

**Issue by louisLouL** [dpkp/kafka-python#1505]
Hi,

Seems like the documentation mismatches the actual implementation. 

For instance, in the doc ( http://kafka-python.readthedocs.io/en/master/simple.html), it says SimpleClient is deprecated. However, according to the code, it is KafkaClient that is deprecated. 

```python
import warnings
class KafkaClient(SimpleClient):
    def __init__(self, *args, **kwargs):
        warnings.warn('The legacy KafkaClient interface has been moved to'
                      ' kafka.SimpleClient - this import will break in a'
                      ' future release', DeprecationWarning)
        super(KafkaClient, self).__init__(*args, **kwargs)
```

Also, according to the doc, there is a "check_version" for the kafka client which actually doesn't exist.

**Comment by dpkp** [comment]
The old KafkaClient was renamed to SimpleClient and is deprecated (it is currently in kafka/client.py). The new KafkaClient is not deprecated and that is where you will find check_version() (currently in kafka/client_async.py)
