### ISSUE TITLE
how does kafka combine with avro  to produce msg and consum msg?

### ISSUE THREAD

**Issue by miaojianxin** [dpkp/kafka-python#1510]
i find an example how avro used in pyton to serialize and deserialize with file. but i dont't know how it
work with the kafka client  to produce and consum msg,  in internet , there are lots of examples in java.
thank you

**Comment by StephenSorriaux** [comment]
Not sure if I am very helpful but you can find a very good example on how to use kafka-python and an avro schema registry here: https://github.com/thanhson1085/python-kafka-avro

Also, Confluent has a Python client available that let you use avro: https://github.com/confluentinc/confluent-kafka-python

**Comment by jeffwidman** [comment]
Thx @StephenSorriaux very helpful, I hadn't seen that example repo before.
