### ISSUE TITLE
auto_offset_reset enhancement 

### ISSUE THREAD

**Issue by louisLouL** [dpkp/kafka-python#1511]
Hi Team

I understand Kafka only supports [latest, earliest, none] for auto_offset_reset options. 

When I use "earliest", my position is last committed offset, I have to manually add 1 to that offset to try to ensure exactly once process. Usually I will do  

```python
consumer = KafkaConsumer(TOPIC_2, bootstrap_servers=HOST, enable_auto_commit=False, group_id=CLIENT_GROUP, auto_offset_reset="earliest")
consumer.poll()
for partition in consumer.assignment():
    committed = consumer.committed(partition)
    if committed:
        consumer.seek(partition, committed + 1)
```

Could you add one more function (or already have it?) that does the similar thing?

**Comment by louisLouL** [comment]
Thank you so much. 
Yes, I am committing the last processed offset manually. I get the idea, committing the next one is a good choice (though a little bit counter-intuitive :) ).

**Comment by jeffwidman** [comment]
The counter-intuitive part comes directly from Kafka protocol, not a design choice by this library. 

While we could hide it by auto-adding 1, that would create confusion for folks used to the Kafka protocol/other clients.
