### ISSUE TITLE
Support for kafka 1.1.0 inside kafka-python

### ISSUE THREAD

**Issue by 88manpreet** [dpkp/kafka-python#1512]
We are planning to upgrade our clusters to use latest kafka [confluent-kafka 1.1.0](https://docs.confluent.io/current/installation/upgrade.html). Would the latest version of kafka-python be compatible with kafka broker-protocol version and message-format version 1.1? Are there any plans to support kafka 1.1.0 test-fixtures in upcoming version?

**Comment by 88manpreet** [comment]
@ryarnyah thanks :)
@dpkp @jeffwidman Are there plans to support kafka 1.1 in near future?

**Comment by dpkp** [comment]
Old clients (of all languages) should generally continue to work with new brokers as expected. kafka-python is no different. It will work with 1.1 clusters. But new features added to the 1.1 brokers wont be available immediately / until someone adds them to the driver.

**Comment by 88manpreet** [comment]
@dpkp Thanks for the prompt response! I believe the same holds for kafka-python 1.3.3 version as well, except that the support for kafka 1.0.0 protocol changes as part of issue "Add Request/Response structs for kafka broker 1.0.0 #1368", won't be relevant?

**Comment by dpkp** [comment]
correct

**Comment by 88manpreet** [comment]
cool. We are also looking forward to use the implementation of idempotent producer as part of #1396 in future kafka-python upgrades :)
