### ISSUE TITLE
Should we proactively raise an error in producer/consumer if gevent is monkeypatching threading?

### ISSUE THREAD

**Issue by jeffwidman** [dpkp/kafka-python#1515]
We use `gevent` at my day job, and I hit a tricky issue where gevent was starving the `KafkaConsumer` threads, so they were timing out of the consumer groups. (There's more to it, but that's the gist.)

As a result, I am adding the following to my internal wrapper code:

    try:
        from gevent.monkey import is_module_patched
        if is_module_patched('thread'):
            raise RuntimeError("""gevent is reporting that the thread/threading
                modules are patched. This can lead to starvation of the
                kafka-python background heartbeat thread, ultimately resulting in
                the consumer being evicted from the kafka consumer group. To
                prevent this, explicitly skip monkey patching thread:
                    from gevent import monkey
                    monkey.patch_all(thread=False)
                """)
    except ImportError:  # they aren't using gevent
        pass

Wondering if we should add this directly to kafka-python as well?

We could lower it to a warning rather than a full-blown exception, in case someone has a valid reason for doing this.

This would probably be useful on `KafkaProducer` in addition to `KafkaConsumer` to minimize the chances of unexpected behavior (and subtle bugs being reported on the issue tracker).

But before I put up a PR, I thought I'd check what folks think of doing this...??

**Comment by tvoinarovskyi** [comment]
Omg, that adds up... How come I never thought of it)

**Comment by dpkp** [comment]
Agree. Strong hypothesis!

**Comment by jeffwidman** [comment]
So what's confusing me currently is that we changed to `from gevent import monkey;         monkey.patch_all(thread=False)` and now I'm getting some rather obtuse errors from gevent:

    Traceback (most recent call last):
    File "/opt/ns/nsenv/lib/python2.7/site-packages/gevent/_socket2.py", line 271, in recv
        sock = self._sock  # keeping the reference so that fd is not closed during waiting
    AttributeError: 'function' object has no attribute '_sock'
    <io at 0x7fb6f81f6c08 fd=5 events=READ> failed with AttributeError

    Traceback (most recent call last):
    File "/usr/lib/python2.7/threading.py", line 65, in _note
        if self.__verbose:
    AttributeError: 'function' object has no attribute '_Verbose__verbose'
    <io at 0x7fb6f857de60 fd=10 events=READ active callback=<bound method PollResult.add_event of <gevent.select.PollResult object at 0x7fb6f4a5d1d0>> args=(gevent.core.EVENTS, 10)> failed with AttributeError

I think these are gevent bugs that are only triggered in certain conditions, but I'm not understanding why `kafka-python` is triggering them.

**Comment by tvoinarovskyi** [comment]
Well, as far as I'm aware its not ok to just use native threads with gevent code. We share the socket with a different thread, so the behaviour can be quite strange. 
We had some bugs with similar behaviour using gevent, maybe it's related.

**Comment by jeffwidman** [comment]
At work, we have a thin-wrapper around kafka-python. So I am planning to make it detect if running within a gevent monkey-patched environ, and in that case, increase the default `session_timeout_ms` to the length of the `max_poll_interval_ms`. Essentially, this would default to disabling the background heartbeat from the broker perspective.  It loses the benefits of the heartbeat, but only for gevent-based services, and users still have the option to override and re-enable if they want. I haven't implemented it yet, but in theory it should be a viable workaround.

**Comment by dpkp** [comment]
#1867 suggests that gevent works fine as long as monkeypatching is done early enough (before kafka-python is imported).
