### ISSUE TITLE
Creating topics using kafka-python

### ISSUE THREAD

**Issue by gerovermaas** [dpkp/kafka-python#1518]
Hi,

Using kafka-python, is it possible to create new topics and specify number of partitions and replication factor?

Regards,
Gero

**Comment by jeffwidman** [comment]
Yes, but currently we have no AdminClient (#935) to add this to (#1104).

So to accomplish this today, you'll need to directly use the `KafkaClient` class to send the protocol structs yourself.

I'm going to close this in favor of #1104.
