### ISSUE TITLE
commit not work 

### ISSUE THREAD

**Issue by whc9527** [dpkp/kafka-python#1521]
In [3]: print kafka.version.__version__
1.3.5

`#!/usr/bin/python

from kafka import KafkaConsumer

consumer = KafkaConsumer('click_logs_tmp',
        group_id='my-group',
        bootstrap_servers=['kafka-broker2.tb.local:9092'],
        enable_auto_commit=True
        )

i = 0
for message in consumer:
    i = i + 1
    print i
    print ("%s %s" % (message.partition,message.offset))`

Question Description:
The above is my consumer code. The problem is that I only inserted 500 data. After running the above script many times, I get the same data (offset+partition). After many times, there is no output. Was the commit failed to submit successfully in the previous few times?

**Comment by whc9527** [comment]
@dpkp

**Comment by jeffwidman** [comment]
This is probably a better fit for StackOverflow as it's more of a Kafka usage question, and not a feature request or bug against kafka-python.
