### ISSUE TITLE
Mocking kafka consumer

### ISSUE THREAD

**Issue by javixeneize** [dpkp/kafka-python#1524]
Hi

Is there any way to mock the call to the kafka consumer when doing unit tests? Im just mocking the method that returns the data extracted from the queue, but i would like to mock the KafkaConsumer call itself

Thanks

**Comment by jeffwidman** [comment]
You can mock all kinds of things manually, but there's no pre-built fixture though that I'm aware of.

**Comment by andjedani** [comment]
:(
