### ISSUE TITLE
Validating kafka configuration - KafkaConsumer

### ISSUE THREAD

**Issue by javixeneize** [dpkp/kafka-python#1525]
Hi

Is there any way to validate connectivity in KafkaConsumer without consuming the messages? It is, i have a configuration, and i would like to know if the topic exists, if the server is listening, etc...

Thanks

**Comment by kmoza** [comment]
@javixeneize you could use `partitions_for_topic` api of the `KafkaConsumer` which returns metadata to check if the topic exists. e.g. `self.consumer.partitions_for_topic(message.topic)`. Let us know if this works for you.

**Comment by jeffwidman** [comment]
Thanks @kmoza good suggestion.
