### ISSUE TITLE
Best way to check that a topic is working and able to receive requests.

### ISSUE THREAD

**Issue by Proto-nerd** [dpkp/kafka-python#1526]
I am currently writing automated smoke-tests for an application which has Kafka interaction and one of the scenarios I need the tests to check is that a specific topic is able to receive messages. I am new to Kafka and  had been attempting to make a solution with sub-processes before I stumbled onto this module, which I'm hoping will be able to provide a simpler solution. Any help would be greatly appreciated.

**Comment by jeffwidman** [comment]
By receive, do you mean you can successfully produce to the topic or successfully consume from the topic?

**Comment by Proto-nerd** [comment]
Successfully produce to the topic.

**Comment by jeffwidman** [comment]
These (and related) errors are probably what you're looking for: https://github.com/dpkp/kafka-python/blob/f00016e7cec64cfc9697b233809cd37e0e19cc64/kafka/errors.py#L144-L162

Note that the `KafkaProducer` will silent retry transient errors. If you want to have these transient errors thrown to the test application, then use `KafkaClient`.
