### ISSUE TITLE
How to reset offset (or re-insert messages) in Kafka-python?

### ISSUE THREAD

**Issue by javixeneize** [dpkp/kafka-python#1528]
Hi

I want to read data from a Kafka queue, and insert it in a database

There might be a chance that the database where i try to insert the data is down, so, i would need to reset the index back to the previous position, or re-insert the messages i have read from Kafka back to it
Can this be done with Kafka-Python library? What is the preferred option?

Thanks

**Comment by aswinjoseroy** [comment]
To re-read the consumed messages, you will have to reset the offsets of the consumer group manually on the server.

**Comment by jeffwidman** [comment]
Manually committing offsets is likely your best option.
