### ISSUE TITLE
ImportError: No module named kafka

### ISSUE THREAD

**Issue by nitishkhune** [dpkp/kafka-python#1530]
I have installed kafka package with below command succcessfully.
 sudo pip install kafka

But when i try to import kafka from a script it gives below error.

Python 2.7.14 (default, Sep 30 2017, 11:56:16) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from kafka import KafkaProducer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named kafka

The same script works on other machines.

What could be the probable cause? A version issue ?

**Comment by skaggar** [comment]
You should install kafka-python package.
`pip install kafka-python`

**Comment by nitishkhune** [comment]
I already have it installed. that is what is puzzling me. Still gives me the same error

**Comment by skaggar** [comment]
Do you have msgpack installed?

**Comment by nitishkhune** [comment]
No. Would that help

**Comment by skaggar** [comment]
I am new to this package as well. But what worked for me was the following:
`pip install msgpack
pip install kafka-python`

I was prompted that kafka-python can't be installed without msgpack.

**Comment by dpkp** [comment]
kafka-python does not depend on msgpack. This seems like a low level python
environment issue. Have you tried using virtualenv?

**Comment by nitishkhune** [comment]
@dpkp  Yes.I suspected the same. My script works on the virtual environment on a Centos VM but not on macbook.

**Comment by kmoza** [comment]
Just tried installing kafka using `pip install kafka` on Windows and it works fine. The version installed was `kafka-1.3.5` and import works fine.

**Comment by jeffwidman** [comment]
This is likely because you installed using `sudo` but then created a virtualenv that didn't have access to the global site packages.

**Comment by mrb-github** [comment]
my problem and solutions to this are explained at: https://github.com/dpkp/kafka-python/wiki/kafka-import-error
