### ISSUE TITLE
How to host Kafka Broker

### ISSUE THREAD

**Issue by skaggar** [dpkp/kafka-python#1532]
I have been using confluent Kafka. But because of switch to Windows for producer and consumer, I am not able to transfer files over that (it is only Linux and iOS enabled). I have made changes to the producer script in sync with kafka-python and it is running without errors. But I am not receiving anything in my kafka broker. The kafka broker is the same one I had while using confluent Kafka. Should I make any changes to my broker server for it to get the messages?
My producer, Kafka and consumer are all on different systems.

**Comment by skaggar** [comment]
Can someone please help me with this? I am able to create producer and consumer files but hosting kafka is something I am not understanding? How do I run the broker?

**Comment by kmoza** [comment]
@skaggar did changing to `kafka-python` affected your working environment.

**Comment by skaggar** [comment]
@kmoza No. But I am not sure I changed to kafka-python right. I have installed kafka-python packages on producer and consumer end. I haven't set up a broker. How do I set up a broker for kafka-python? Or is it okay to continue with the kafka broker I used for Confluent?

**Comment by StephenSorriaux** [comment]
I would say it is OK to continue using your previous Kafka broker with kafka-python.

Can you tell us more about the problem? What is your current configuration of your Kafka broker? How did you parameterized your consumer and producer with kafka-python?

**Comment by skaggar** [comment]
`
from kafka import KafkaProducer
import base64
import os
import shutil
p=KafkaProducer(bootstrap_servers='130.127.55.239:9092')
f1=open(metafile, "r")
for data in f1.read():
	p.send('meta', data.encode('utf-8'))
	print(data)
p.flush()`
