### ISSUE TITLE
Update kafka on PyPI package to support python 3.7

### ISSUE THREAD

**Issue by vsel** [dpkp/kafka-python#1534]
Could you please update kafka package(https://pypi.org/project/kafka/) on PyPI to support python 3.7
1.3.5 - no support(because of self.async variable)
1.4.3 - full support(it works)

**Comment by dpkp** [comment]
please use https://pypi.org/project/kafka-python/ . I am no longer updating https://pypi.org/project/kafka/ (see https://github.com/dpkp/kafka-python/issues/1253)
