### ISSUE TITLE
Multithreading/processing KafkaProducer and KafkaConsumer

### ISSUE THREAD

**Issue by Proto-nerd** [dpkp/kafka-python#1536]
What is the correct way, if there is one, to run a KafkaProducer function while a KafkaConsumer function is running? I have tried using Thread from multithreading and Pool.map_async from multiprocessing, but in both cases it simply runs the functions one after another, presumably due to the way kafka works but I'm not sure.

Barring this, is it possible to have a KafkaConsumer read messages sent in the last few seconds so I can just run them one after another?

**Comment by kmoza** [comment]
@Proto-nerd could elaborate more on _is it possible to have a KafkaConsumer read messages sent in the last few seconds so I can just run them one after another?_ to understand the requirement better.

**Comment by Proto-nerd** [comment]
The purpose of all of this is to write a function which will test that a kafka topic is functioning and messages can be sent to and read from it. What I meant by that statement is that if there is an argument I can pass into KafkaConsumer to check for messages sent to the topic a few seconds before KafkaConsumer ran then they wouldn't need to be done simultaneously, which would remove the need for multithreading. Hopefully this clarifies the issue.

**Comment by jeffwidman** [comment]
You can use the `KafkaAdminClient` class to check the highwater mark on the broker of the topic, which would let you see if there's new messages. From there you can then consume them.
