### ISSUE TITLE
Assigning partition while sending message is causing error

### ISSUE THREAD

**Issue by lijose** [dpkp/kafka-python#1537]
I am trying to insert data to different partition for same topic. I am using python-kafka 1.4.3 on a linux machine

```
from kafka import KafkaProducer
producer = KafkaProducer() 
producer.send(topic='test', value=b'test', partition=1)
```
Error : AssertionError: Unrecognized partition 

If I pass partition=0 it will be succeeded

**Comment by rafales** [comment]
I would guess that's because topic you're sending to is configured with a single partition?

**Comment by lijose** [comment]
Is it possible to specify that using python-kafka ?

**Comment by dpkp** [comment]
This is a normal error and not a bug.
