### ISSUE TITLE
For enable_auto_commit False, no automatic re-join ; Error Heartbeat: local member_id was not recognized; this consumer needs to re-join

### ISSUE THREAD

**Issue by silwalprabin** [dpkp/kafka-python#1544]
I create consumer as:
consumer = KafkaConsumer(group_id="my_group_id", bootstrap_servers="192.168.10.45:9092",
auto_offset_reset='latest',
enable_auto_commit=False,
consumer_timeout_ms=1000)
consumer.subscribe("myTopic")

After some days, I am getting this error:
2018-07-11_05:04:07.75431 WARNING: Marking the coordinator dead (node 0) for group my_group_id: Heartbeat session expired.
2018-07-11_05:04:10.87000 WARNING: Heartbeat: local member_id was not recognized; this consumer needs to re-join

Above error continues to repeat until I stop and run code again.

What I figure-out:
I see code to rejoin while polling is done (with enable_auto_commit set to True) in line 250 of https://github.com/dpkp/kafka-python/blob/master/kafka/coordinator/consumer.py
(function named poll(self)) , but I cannot see code to re-join when enable_auto_commit is set to False.

NOTE: I also see similar issue commented by [@NoneGG](https://github.com/NoneGG)  under different issue ticket (https://github.com/dpkp/kafka-python/issues/1435). I am pasting his message down:
 [@NoneGG](https://github.com/NoneGG) 
I have a similar problem with a consumer(session_timeout & max_poll_interval are set to default value) disable auto-commit (each msg is proceeded in about 3 ms)

This app depends on kafka-python v1.3.1 and is update to kafka-python v1.4.2 recently.
I doubt if it is caused by the backend heartbeat thread.

log
 Marking the coordinator dead (node 1) for group bvc_disp_cache: Heartbeat session expired.
[I 180612 21:10:21 cluster         : 349] Group coordinator for bvc_disp_cache is BrokerMetadata(nodeId=1, host=host, port=port, rack=None)
[I 180612 21:10:21 base            : 676] Discovered coordinator 1 for group bvc_disp_cache
[W 180612 21:10:25 base            : 823] Heartbeat: local member_id was not recognized; this consumer needs to re-join

Then the log stock here, no more messages are proceeded and so i have to stop the process.
From 

[I 180613 07:36:40 prism_charger   :  93] Catch SIGNAL:15, resign heartbeat and release redis lock.
[I 180613 07:36:40 messages        :  83] Ready to exit
[I 180613 07:36:40 base            : 731] Stopping heartbeat thread
[I 180613 07:36:40 conn            : 710] <BrokerConnection node_id=1 host=host<connected> [IPv4 (host, port)]>: Closing connection.

**Comment by xvlvzhu** [comment]
I meet the same problem

WARNING:kafka.coordinator:Heartbeat session expired, marking coordinator dead
WARNING:kafka.coordinator:Marking the coordinator dead (node 2) for group XX : Heartbeat session expired.
WARNING:kafka.coordinator.consumer:Auto offset commit failed for group XX: CommitFailedError: Commit cannot be completed since the group has already
            rebalanced and assigned the partitions to another member.
            This means that the time between subsequent calls to poll()
            was longer than the configured max_poll_interval_ms, which
            typically implies that the poll loop is spending too much
            time message processing. You can address this either by
            increasing the rebalance timeout with max_poll_interval_ms,
            or by reducing the maximum size of batches returned in poll()
            with max_poll_records.

**Comment by bpoti** [comment]
I meet the same problem: 

I am using 1.4.3
when auto_commit is false 
```
[2018-09-14 21:26:16,705|kafka.cluster|INFO]: Group coordinator for dev_scheduler_segment_analysis_chief is BrokerMetadata(nodeId=2898720, host='10.198.6.244', port=9092, rack=None)
[2018-09-14 21:26:16,710|kafka.coordinator|INFO]: Discovered coordinator 2898720 for group dev_scheduler_segment_analysis_chief
[2018-09-14 21:26:20,174|kafka.coordinator|WARNING]: Heartbeat: local member_id was not recognized; this consumer needs to re-join
```
when set to true:
```
[2018-09-14 23:54:12,779|kafka.coordinator.consumer|ERROR]: Offset commit failed: This is likely to cause duplicate message delivery
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kafka/coordinator/consumer.py", line 515, in _maybe_auto_commit_offsets_sync
    self.commit_offsets_sync(self._subscription.all_consumed_offsets())
  File "/usr/local/lib/python3.6/dist-packages/kafka/coordinator/consumer.py", line 508, in commit_offsets_sync
    raise future.exception # pylint: disable-msg=raising-bad-type
kafka.errors.CommitFailedError: CommitFailedError: Commit cannot be completed since the group has already
            rebalanced and assigned the partitions to another member.
            This means that the time between subsequent calls to poll()
            was longer than the configured max_poll_interval_ms, which
            typically implies that the poll loop is spending too much
            time message processing. You can address this either by
            increasing the rebalance timeout with max_poll_interval_ms,
            or by reducing the maximum size of batches returned in poll()
            with max_poll_records.
```

**Comment by zhgjun** [comment]
I meet the same problem and i get the stack trace, it's dead lock:
**stack 1:**
`/opt/cloud/services/network-agent/venv/lib/python2.7/site-packages/kafka/coordinator/base.py:914 in run
    'self._run_once()'

/opt/cloud/services/network-agent/venv/lib/python2.7/site-packages/kafka/coordinator/base.py:982 in _run_once
    'with self.coordinator._client._lock, self.coordinator._lock:'

/usr/lib64/python2.7/threading.py:285 in __enter__
    'return self.__lock.__enter__()'

/usr/lib64/python2.7/threading.py:173 in acquire
    'rc = self.__block.acquire(blocking)'

/opt/cloud/services/network-agent/venv/lib/python2.7/site-packages/eventlet/semaphore.py:113 in acquire
    'hubs.get_hub().switch()'

/opt/cloud/services/network-agent/venv/lib/python2.7/site-packages/eventlet/hubs/hub.py:294 in switch
    'return self.greenlet.switch()'`

**stack 2:**
`/opt/cloud/services/network-agent/venv/lib/python2.7/site-packages/kafka/consumer/group.py:609 in poll
    'records = self._poll_once(remaining, max_records)'

/opt/cloud/services/network-agent/venv/lib/python2.7/site-packages/kafka/consumer/group.py:629 in _poll_once
    'self._coordinator.poll()'

/opt/cloud/services/network-agent/venv/lib/python2.7/site-packages/kafka/coordinator/consumer.py:281 in poll
    'self.ensure_active_group()'

/opt/cloud/services/network-agent/venv/lib/python2.7/site-packages/kafka/coordinator/base.py:373 in ensure_active_group
    'while not self.coordinator_unknown():'

/opt/cloud/services/network-agent/venv/lib/python2.7/site-packages/kafka/coordinator/base.py:227 in coordinator_unknown
    'return self.coordinator() is None'

/opt/cloud/services/network-agent/venv/lib/python2.7/site-packages/kafka/coordinator/base.py:236 in coordinator
    'elif self._client.is_disconnected(self.coordinator_id):'

/opt/cloud/services/network-agent/venv/lib/python2.7/site-packages/kafka/client_async.py:433 in is_disconnected
    'with self._lock:'

/usr/lib64/python2.7/threading.py:173 in acquire
    'rc = self.__block.acquire(blocking)'

/opt/cloud/services/network-agent/venv/lib/python2.7/site-packages/eventlet/semaphore.py:113 in acquire
    'hubs.get_hub().switch()'

/opt/cloud/services/network-agent/venv/lib/python2.7/site-packages/eventlet/hubs/hub.py:294 in switch
    'return self.greenlet.switch()'`


when stack 2 get the lock 
`def ensure_active_group(self):
        """Ensure that the group is active (i.e. joined and synced)"""
        with self._lock:
            if self._heartbeat_thread is None:
                self._start_heartbeat_thread()`
and run this code,which will need the _client._lock()
`while not self.coordinator_unknown():
                    if not self._client.in_flight_request_count(self.coordinator_id):
                        break
                    self._client.poll(timeout_ms=5000)`

but at this time stack 1 got _client._lock() and acquire coordinator._lock()
`with self.coordinator._client._lock, self.coordinator._lock:`

and finally dead lock happen.

**Comment by zhgjun** [comment]
I open new issue for this problem, https://github.com/dpkp/kafka-python/issues/1623

**Comment by jeffwidman** [comment]
Closing as #1623 has been fixed.
