### ISSUE TITLE
BrokerConnection blocks forever while receiving

### ISSUE THREAD

**Issue by wvxvw** [dpkp/kafka-python#1545]
I have a slightly older version of `kafka-python`, but the code in master seems like it should still have this problem.

https://github.com/dpkp/kafka-python/blob/master/kafka/conn.py#L811

    def _recv(self):
        responses = []
        SOCK_CHUNK_BYTES = 4096
        while True:
            try:
                if self._sock.gettimeout() is None:
                    raise Exception('This operation will never succeed')
                data = self._sock.recv(SOCK_CHUNK_BYTES)
                # We expect socket.recv to raise an exception if there is not
                # enough data to read the full bytes_to_read
                # but if the socket is disconnected, we will get empty data
                # without an exception raised
                if not data:
                    ...

And this exception actually gets thrown in my setup.  Obviously, if you are trying to receive on blocking socket a number of bytes less than Kafka actually sent, this will not work.  In my case, what seems to be happening is Kafka gives up after its own timeout, and this receive errors and breaks from the loop.

I see there a lot of code around this code that flips timeout / blocking flags on this socket and it feels like this is some sort of race condition, but I didn't dig deeper.

**Comment by dpkp** [comment]
Until this is verified on master / recent-release, I don't think it is worth spending time investigating further. Upgrade recommended.
