### ISSUE TITLE
Specify SSL details for Kafka brokers in Consumer

### ISSUE THREAD

**Issue by lijose** [dpkp/kafka-python#1550]
I need to connect to kafka instance which has multiple brokers with SSL. I am using kafka-python to consume and process data.

I have seen link where they used kafka-python to connect to single broker with SSL.

Link : http://maximilianchrist.com/python/databases/2016/08/13/connect-to-apache-kafka-from-python-using-ssl.html

Specific code

```
consumer = KafkaConsumer(bootstrap_servers='my.server.com',
                          security_protocol='SSL',
                          ssl_check_hostname=True,
                          ssl_cafile='CARoot.pem',
                          ssl_certfile='certificate.pem',
                          ssl_keyfile='key.pem')
```
I need to know since there are multiple brokers how to specify multiple ssl_ca, ssl_cert, ssl_key in constructor ??

**Comment by rafaelmnatali** [comment]
Hello @lijose did you get this solved? I'm exactly on the same point.

The workaround I found was to set `ssl_check_hostname` as `False`.

Thanks
