### ISSUE TITLE
passing key for log compaction

### ISSUE THREAD

**Issue by doramir** [dpkp/kafka-python#1551]
Is there a way to pass a key for log compaction so Kafka can know which event to override?

**Comment by dpkp** [comment]
yes. pass `key=b'foo'` (as bytes) to producer.send . If needed, also configure a key_serializer to encode keys as bytes . More docs are available at https://kafka-python.readthedocs.io/en/latest/apidoc/KafkaProducer.html#kafka.KafkaProducer.send

**Comment by doramir** [comment]
@dpkp the key is not for choosing a partition?

**Comment by dpkp** [comment]
It is used to choose the partition as well, yes. This guarantees that all messages with the same key are routed to the same partition. Once all keys are on a single partition, the broker can do compaction per-partition.

**Comment by doramir** [comment]
@dpkp  thanks for the fast answers, 
is there a way to use this key and to use a different key to choose the partition? 
I have 1 key as the event key and 1 partition key with a logic on it

**Comment by dpkp** [comment]
No, there is not. Some other options might be: (1) do partitioning yourself and manually assign each message via `partition=123`, (2) use a custom `partitioner` that can choose the partition you want based on the event key.
