### ISSUE TITLE
Speed improvements for pack/unpack functions in protocol/types.py

### ISSUE THREAD

**Issue by billyevans** [dpkp/kafka-python#1555]
I noticed that pack/unpack functions from https://github.com/dpkp/kafka-python/blob/master/kafka/protocol/types.py might be slightly improved. I made pre-compilation for them. It gives about 10% better performance compared to the current implementation.
Consumption of 100msg:
```
239884    0.187    0.000    0.287    0.000 types.py:18(_unpack) # new version
239884    0.192    0.000    0.323    0.000 types.py:17(_unpack)
```
I also made some profiling for producers/consumers. It gives about 1-1.5% time savings.
My changes https://github.com/billyevans/kafka-python/commit/99bf02113bdbddcb377796f9e5dd470c4de5f194

Should I make a PR?

**Comment by jeffwidman** [comment]
I am not super familiar with the `struct` interfaces, but at first glance, this looks like a straightforward change with an obvious performance win. 

So yes, I'd appreciate a PR @billyevans

**Comment by tvoinarovskyi** [comment]
Seems nice to me

**Comment by jeffwidman** [comment]
I created the PR and cherry-picked the commit in https://github.com/dpkp/kafka-python/pull/1619 so that we don't forget to add this.
