### ISSUE TITLE
Kafka Messages were not received after rebalancing

### ISSUE THREAD

**Issue by Reallychel** [dpkp/kafka-python#1556]
I have the below consumer code and executing
topic='my_topic'
kafka= 9.0.1
kafka-python=1.3.1
we create consumer as-
	consumer = KafkaConsumer(self.topic, bootstrap_servers=self.server_url,
                             group_id=self.group_id,
                              auto_offset_reset=self.offset)
			
This works fine when we run on single host. But when it goes on multi host environment, after subscribing we notice rebalance  ~60 partitions for my topic. After Some time we don't receive any event. But when manually we try to perform some operation due to which event is produced, we actually receive event. My Question - is there any parameters I am missing here while creation of consumer? why I am not able to get message when producer send message in multi host enviornment.

**Comment by tvoinarovskyi** [comment]
Consumer store's it's position after consumption. You are not getting old messages because you already processed them. This does not seem like a bug, so closing it. If you think it's a bug create a new one please
