### ISSUE TITLE
Kafka Consumer not fetching proper offsets

### ISSUE THREAD

**Issue by slamice** [dpkp/kafka-python#1558]
I've been trying to connect to Kafka after sending a bunch of messages to it. I only have one topic and only one Kafka cluster running.

Given a timestamp, I want to fetch all messages starting from that time. So I fetch the offset using the offsets_for_times method, seek to there and then loop through the messages. This example hardcodes the timestamp.

````
kafka_consumer = KafkaConsumer(bootstrap_servers='localhost:9000', group_id=None, request_timeout_ms=1000)

topic_partition = TopicPartition('topic_example', 0)
offset_dict = self.kafka_consumer.offsets_for_times({self.topic_partition: 1532712993})

# fetches first partition's timestamp, only have one
from_offset = next(iter(offset_dict.values())).offset

kafka_consumer.seek(topic_partition, from_offset)
kafka_consumer.poll()

for message in kafka_consumer:
    ...
````

However, it seems offsets_for_times doesn't work as expected. The messages I'm receiving are always the very first messages added to the topic, regardless of the timestamp I send it.

I'm wondering if there is a specific configuration I'm missing?

**Comment by dpkp** [comment]
Strange. What is the difference between `kafka_consumer` and `self.kafka_consumer` in your script?

**Comment by slamice** [comment]
@dpkp oh sorry, I extracted this from a class. It's the same. Let me fix that typo.

**Comment by tvoinarovskyi** [comment]
@jeffwidman  Thanks for pointing this one to me. Yes, it is strange to a Python developer, but timestamps are defined as:

```
        Arguments:
            timestamps (dict): ``{TopicPartition: int}`` mapping from partition
                to the timestamp to look up. Unit should be milliseconds since
                beginning of the epoch (midnight Jan 1, 1970 (UTC))
```
See https://kafka-python.readthedocs.io/en/master/apidoc/KafkaConsumer.html#kafka.KafkaConsumer.offsets_for_times

In other words the proper timestamp would be `{self.topic_partition: 1532712993000}` in the code above
