### ISSUE TITLE
Example file (example.py) uses process instead of thread

### ISSUE THREAD

**Issue by pengnam** [dpkp/kafka-python#1563]
(https://github.com/dpkp/kafka-python/blob/master/example.py)

Consumer is a subclass of multiprocessing.Process. 

The print statement in the run function will never print to the terminal as processes shares a different memory space.

**Comment by dpkp** [comment]
PRs welcome!

**Comment by jeffwidman** [comment]
nudge @pengnam you interested in submitting a PR? Should be a simple change...
