### ISSUE TITLE
KafkaProducer hangs on creation inside Openstack Neutron ML2 Plugin

### ISSUE THREAD

**Issue by gubouvier** [dpkp/kafka-python#1564]
I'm trying to code an Openstack Neutron ML2 Plugin (api.MechanismDriver) that will send events on a Kafka server.

My code works fine when I run it directly inside a python script, but when I add the same code to the ML2 Plugin, the KafkaProducer creation never returns.

This will hang forever when called inside an ML2 Plugin:
``producer = KafkaProducer(bootstrap_servers=['my_server_ip'])``

The creation of a Consumer works fine.

I was able to find a workaround by creating a SimpleProducer instead, but as it is marked as deprecated, I would like to change it back to a KafkaProducer.

This works fine:
``client = SimpleClient(KAFKA_SERVERS[0])``
``producer = SimpleProducer(client, async_send=False)``

The ML2 Plugin is a class, with methods that will get called on certain events.  The KafkaProducer would get created when those methods get called.

I understand this is not an Openstack project, but I was wondering if someone would see a major difference between the way the KafkaProducer gets created compared to a KafkaConsumer or SimpleProducer.

Thanks !

**Comment by jeffwidman** [comment]
If you try pinning the broker version, does that fix it? 

Also, are you passing an IP or a DNS address (which must match what your cluster has in `advertised.listeners`)?
