### ISSUE TITLE
Python 3.7 compatibility issue

### ISSUE THREAD

**Issue by jerry73204** [dpkp/kafka-python#1566]
In Python 3.7, `async` becomes a keyword. Variables with name `async` is forbidden.

Unfortunately, Arch Linux switches to Python 3.7 and I encounter the issue with the error message raised from [here](https://github.com/dpkp/kafka-python/blob/9ac3cb1ec220ff9968a8b003b02e98dd11cc486b/kafka/producer/simple.py#L54). It's better to change it.
```
Traceback (most recent call last):
  File "./websocket_server.py", line 9, in <module>
    from aiokafka import AIOKafkaConsumer
  File "/usr/lib/python3.7/site-packages/aiokafka/__init__.py", line 3, in <module>
    from .abc import ConsumerRebalanceListener
  File "/usr/lib/python3.7/site-packages/aiokafka/abc.py", line 2, in <module>
    from kafka import ConsumerRebalanceListener as BaseConsumerRebalanceListener
  File "/usr/lib/python3.7/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/usr/lib/python3.7/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/usr/lib/python3.7/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                                  ^
SyntaxError: invalid syntax
```

**Comment by roerd** [comment]
I ran into the same problem yesterday. The answer is that this problem is actually fixed in the current version, but in PyPI, the package name "kafka" uses an older version. To get the current version, you need to switch to the package name "kafka-python".

**Comment by jerry73204** [comment]
I works for me. Thanks @roerd .

**Comment by jerry73204** [comment]
The issue is solved. Please close this issue.

**Comment by tvoinarovskyi** [comment]
Cool!

**Comment by zemtsov-artem** [comment]
@roerd you saved my day!
Thanks a lot!

**Comment by RongrongSu** [comment]
Can someone explain how to switch to the package name "kafka-python"? Thank you!

**Comment by jerry73204** [comment]
You can install the package by `pip install kafka-python`. If you already install `kafka`, make sure you remove it beforehand by `pip uninstall kafka`.

**Comment by arvindeybram** [comment]
> Can someone explain how to switch to the package name "kafka-python"? Thank you!
`pip install kafka-python`

**Comment by theabhisheksinha** [comment]
I am presently running on:

PS C:\Apache\Kafka\kafka_2.13-2.4.0\bin\windows> pip install kafka-python
Requirement already satisfied: kafka-python in c:\python3.8.1\lib\site-packages (2.0.1)

yet I face this issue : 

PS C:\Apache\Kafka\kafka_2.13-2.4.0\bin\windows> python .\test.py
Traceback (most recent call last):
  File ".\test.py", line 5, in <module>
    from kafka import KafkaConsumer
  File "C:\python3.8.1\lib\site-packages\kafka\__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "C:\python3.8.1\lib\site-packages\kafka\producer\__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "C:\python3.8.1\lib\site-packages\kafka\producer\simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^

Any thoughts on how to fix this?

**Comment by arvindeybram** [comment]
> I am presently running on:
> 
> PS C:\Apache\Kafka\kafka_2.13-2.4.0\bin\windows> pip install kafka-python
> Requirement already satisfied: kafka-python in c:\python3.8.1\lib\site-packages (2.0.1)
> 
> yet I face this issue :
> 
> PS C:\Apache\Kafka\kafka_2.13-2.4.0\bin\windows> python .\test.py
> Traceback (most recent call last):
> File ".\test.py", line 5, in
> from kafka import KafkaConsumer
> File "C:\python3.8.1\lib\site-packages\kafka__init__.py", line 23, in
> from kafka.producer import KafkaProducer
> File "C:\python3.8.1\lib\site-packages\kafka\producer__init__.py", line 4, in
> from .simple import SimpleProducer
> File "C:\python3.8.1\lib\site-packages\kafka\producer\simple.py", line 54
> return '' % self.async
> ^
> 
> Any thoughts on how to fix this?

So Kafka with python3 versions use `asynchronous` in place of `async` as in python2. You are getting this error because your python3 is trying to compile Kafka for python2.
First: `pip uninstall kafka-python` (to remove python2 version of kafka) followed by
Kafka Installation using `python3.7 -m pip install kafka-python` should do the magic.

**Comment by dhirajgolhar376-cmd** [comment]
-------------------------------------------------------------------------------------------------------------------
First: pip uninstall kafka-python (to remove python2 version of kafka) followed by
Kafka Installation using python3.8 -m pip install kafka-python should do the magic.
-------------------------------------------------------------------------------------------------------------------
Above steps are solving my issue    ` return '<SimpleProducer batch=%s>' % self.async
`
But then i am getting below error
`ModuleNotFoundError: No module named 'beam_nuggets'`

**Comment by Faisalnb** [comment]
> > I am presently running on:
> > PS C:\Apache\Kafka\kafka_2.13-2.4.0\bin\windows> pip install kafka-python
> > Requirement already satisfied: kafka-python in c:\python3.8.1\lib\site-packages (2.0.1)
> > yet I face this issue :
> > PS C:\Apache\Kafka\kafka_2.13-2.4.0\bin\windows> python .\test.py
> > Traceback (most recent call last):
> > File ".\test.py", line 5, in
> > from kafka import KafkaConsumer
> > File "C:\python3.8.1\lib\site-packages\kafka__init__.py", line 23, in
> > from kafka.producer import KafkaProducer
> > File "C:\python3.8.1\lib\site-packages\kafka\producer__init__.py", line 4, in
> > from .simple import SimpleProducer
> > File "C:\python3.8.1\lib\site-packages\kafka\producer\simple.py", line 54
> > return '' % self.async
> > ^
> > Any thoughts on how to fix this?
> 
> So Kafka with python3 versions use `asynchronous` in place of `async` as in python2. You are getting this error because your python3 is trying to compile Kafka for python2. First: `pip uninstall kafka-python` (to remove python2 version of kafka) followed by Kafka Installation using `python3.8 -m pip install kafka-python` should do the magic.

please can you tell, what exactly is the version needed .Because python3.8 does not work in my system.
