### ISSUE TITLE
Documentation: Info about the ability to reconnect to Kafka in case of reaped connection or Kafka restart.

### ISSUE THREAD

**Issue by devspyrosv** [dpkp/kafka-python#1567]
Hello!

I am using kafka-python for some time now and I had a thought about what would the library do in case of a broker or cluster unavailability, a possibly reaped connection by the broker especially in applications that might sleep between kafka operations.

I conducted a little test and opened a connection, produced some messages, slept for more than the broker's **connections.max.idle.ms** and then produced some more messages.

I was happy to see that it was successful and only with debug output enabled, would someone know that a new connection was opened. 

Then I did the same but while the process was sleeping, I restarted the broker (single broker cluster). The process continued to function without an error again.

I believe that a small hint about this feature could improve the docs.

Thank you!

**Comment by jeffwidman** [comment]
We'd be more than happy to merge a PR that added a sentence or two to the docs stating that it's resilient against connection/broker failure.

I'm going to close for now, but happy to take a look at a PR @devspyrosv if you want to submit one.
