### ISSUE TITLE
The parallel model of MultiConsumer 

### ISSUE THREAD

**Issue by weikai-booodl** [dpkp/kafka-python#157]
It seems to me the parallel model of current MultiConsumer is that multiple child processes fetch messages to a centralized queue, and then the parent process dispatches the messages from this queue to the application via MultiConsumer.get_messages() API. 

I was wondering whether there is any provision in current code to support another kind of parallel model where the parent process fetches messages into a queue and multiple child processes dispatches the messages from this queue to application? The reason is that in our application, the processing of each message is CPU-intensive, so we want to have multiple processes to processing the messages.

**Comment by dpkp** [comment]
The new KafkaConsumer w/ group coordination using 0.9.0.0 kafka brokers provides a much improved parallel consumption model. MultiConsumer now deprecated.
