### ISSUE TITLE
why KafkaConsumer not pull data

### ISSUE THREAD

**Issue by jgshzy** [dpkp/kafka-python#1570]
class KafkaCon(object):
    def __init__(self, host_ip, host_port, topic, groupid):
        self.kafkahost = host_ip
        self.kafkaport = host_port
        self.kafkatopic = topic
        self.groupid = groupid
        self.consumer = KafkaConsumer(self.kafkatopic,
                                      group_id='my-group',
                                      bootstrap_servers=['192.168.0.162:9092',
                                                         '192.168.0.164:9092',
                                                         '192.168.0.166:9092'],
                                      auto_offset_reset='earliest'
                                      )

    def pull_data(self):
        print('Start consumer data')
        for message in self.consumer:
            data = message.value
            print(data.decode('utf-8'))

if  set 'group_id'   Can't pull data

if not set '' can pull data

why??

**Comment by stigok** [comment]
Maybe the consumer you are using has already consumed the data once and the offset of the consumer group is set to *n*+1, hence not giving you any more data until more is produced.
