### ISSUE TITLE
Consumer doesn't subscribe by regex until calling consumer.topics()

### ISSUE THREAD

**Issue by dmcollom** [dpkp/kafka-python#1573]
I'm seeing some strange intermittent behavior when subscribing to a set of topics by regex. The subscription doesn't appear to take until calling consumer.topics(), as seen below, though it appears to work just fine when subscribing using a list:

`>>> from kafka import KafkaConsumer
>>> consumer = KafkaConsumer(bootstrap_servers=f'{PRODUCER_HOST}:{PRODUCER_PORT}', group_id=GROUP_ID, auto_offset_reset='earliest')
>>> consumer.subscribe(['ztf_20180811_programid1'])
>>> consumer.subscription()
{'ztf_20180811_programid1'}
>>> consumer.subscribe(pattern=TOPIC)
>>> consumer.subscription()
set()
>>> consumer.topics()
{'ztf_20180606_programid1', 'ztf_20180722_programid1', 'ztf_20180741_programid1', 'ztf_20180628_programid1', 'ztf_20180604_programid1', 'ztf_20180718_programid1', 'ztf_20180618_programid1', 'ztf_20180613_programid1', 'ztf_20180711_programid1', 'ztf_20180608_programid1', 'ztf_20180729_programid1', 'ztf_test', 'ztf_20180726_programid1', 'ztf_20180810_programid1', 'ztf_20180811_programid1', 'ztf_20180803_programid1', 'ztf_20180813_programid1','ztf_20180626_programid1', 'ztf_20180804_programid1', 'ztf_20180528_programid1', 'ztf_20180728_programid1', 'ztf_20180620_programid1', 'ztf_20180707_programid1', 'ztf_20180706_programid1', 'ztf_20180616_programid1', 'ztf_20180617_programid1', 'ztf_20180615_programid1', 'ztf_20180704_programid1', 'ztf_20180715_programid1', 'ztf_20180712_programid1', 'ztf_20180716_programid1', 'ztf_20180629_programid1', 'ztf_20180807_programid1', 'ztf_20180709_programid1', 'ztf_20180603_programid1', 'ztf_mjuric', 'ztf_20180713_programid1', 'ztf_20180607_programid1', 'ztf_20180714_programid1', 'ztf_20180621_programid1', 'ztf_20180720_programid1', 'ztf_20180611_programid1', 'ztf_20180806_programid1', 'ztf_20180630_programid1', 'ztf_20180609_programid1', 'ztf_20180719_programid1', 'ztf_20180623_programid1', 'ztf_20180612_programid1', 'ztf_20180627_programid1', 'ztf', 'ztf_20180725_programid1', 'ztf_20180602_programid1', 'ztf_20180802_programid1', 'ztf_20180619_programid1', 'ztf_20180809_programid1', 'ztf_20180601_programid1', 'ztf_20180812_programid1', 'ztf_20180717_programid1', 'ztf_20180625_programid1', 'ztf_20180614_programid1', 'ztf_20180701_programid1', 'ztf_20180723_programid1', 'ztf_20180708_programid1', 'ztf_201807056_programid1', 'ztf_20180610_programid1', 'ztf_20180703_programid1', 'ztf_20180724_programid1', 'ztf_20180531_programid1', 'ztf_20180702_programid1', 'ztf_20180622_programid1', 'ztf_20180624_programid1', 'ztf_20180730_programid1', 'ztf_20180721_programid1', 'ztf_20180727_programid1', 'ztf_20180805_programid1', 'ztf_20180705_programid1', 'ztf_20180808_programid1', 'ztf_20180605_programid1', 'ztf_20180710_programid1', 'ztf_20180731_programid1', 'ztf_20180801_programid1'}
>>> consumer.subscription()
{'ztf_20180606_programid1', 'ztf_20180722_programid1', 'ztf_20180741_programid1', 'ztf_20180604_programid1', 'ztf_20180628_programid1', 'ztf_20180618_programid1', 'ztf_20180718_programid1', 'ztf_20180613_programid1', 'ztf_20180711_programid1', 'ztf_20180608_programid1', 'ztf_20180729_programid1', 'ztf_20180726_programid1', 'ztf_20180810_programid1', 'ztf_20180811_programid1', 'ztf_20180803_programid1', 'ztf_20180813_programid1', 'ztf_20180804_programid1', 'ztf_20180626_programid1', 'ztf_20180528_programid1', 'ztf_20180728_programid1', 'ztf_20180620_programid1', 'ztf_20180707_programid1', 'ztf_20180706_programid1', 'ztf_20180616_programid1', 'ztf_20180617_programid1', 'ztf_20180615_programid1', 'ztf_20180704_programid1', 'ztf_20180715_programid1', 'ztf_20180712_programid1', 'ztf_20180716_programid1', 'ztf_20180629_programid1', 'ztf_20180807_programid1', 'ztf_20180709_programid1', 'ztf_20180603_programid1', 'ztf_20180713_programid1', 'ztf_20180607_programid1', 'ztf_20180714_programid1', 'ztf_20180621_programid1', 'ztf_20180720_programid1', 'ztf_20180611_programid1', 'ztf_20180806_programid1', 'ztf_20180630_programid1', 'ztf_20180609_programid1', 'ztf_20180719_programid1', 'ztf_20180623_programid1', 'ztf_20180612_programid1', 'ztf_20180627_programid1', 'ztf_20180725_programid1', 'ztf_20180602_programid1', 'ztf_20180802_programid1', 'ztf_20180619_programid1', 'ztf_20180809_programid1', 'ztf_20180601_programid1', 'ztf_20180812_programid1', 'ztf_20180717_programid1', 'ztf_20180625_programid1','ztf_20180614_programid1', 'ztf_20180701_programid1', 'ztf_20180723_programid1', 'ztf_20180708_programid1', 'ztf_20180610_programid1', 'ztf_20180703_programid1', 'ztf_20180724_programid1', 'ztf_20180531_programid1', 'ztf_20180702_programid1', 'ztf_20180622_programid1', 'ztf_20180624_programid1', 'ztf_20180730_programid1', 'ztf_20180721_programid1', 'ztf_20180727_programid1', 'ztf_20180805_programid1', 'ztf_20180705_programid1', 'ztf_20180808_programid1', 'ztf_20180605_programid1', 'ztf_20180710_programid1', 'ztf_20180731_programid1', 'ztf_20180801_programid1'}`

Note that the set of topics returned by consumer.subscription() is a subset of the topics returned by consumer.topics(). Is there some call that takes place in consumer.topics() that I need to do manually when subscribing with a pattern?

**Comment by dpkp** [comment]
When you use a pattern, the actual subscription list will not populate until a full metadata refresh. This will process asynchronously when you call poll() (or use the iterator). When you call consumer.topics() you are blocking until this call returns and therefore you'll see the new subscription list when it is done.
