### ISSUE TITLE
Cannot produce message with a long idle time

### ISSUE THREAD

**Issue by tanmq** [dpkp/kafka-python#1575]
I have a task which only will run at 23:00. This task will use KafkaProducer to send message to Kafka.
But I can not get any messages from Kafka and KafkaProducer did not throw any exception or err message.
Is there any problem for KafkaProducer with a long idle time?

By the way, my version is 1.3.5.

**Comment by tanmq** [comment]
OK,I think the problem is for celery.

**Comment by lzskyline** [comment]
You can put KafkaClient instantiation code in celery task function to solve it
