### ISSUE TITLE
working with Kafka v2

### ISSUE THREAD

**Issue by ej2015** [dpkp/kafka-python#1578]
I've installed Kafka v2 on Mac with homebrew. Seems the current version doesn't work with v2 yet. Any guidelines to get it to work or I'll need to downgrade my broker?

**Comment by tvoinarovskyi** [comment]
Any errors? It should just work if broker is backword compatible...

**Comment by dpkp** [comment]
I don't know of a reason it shouldn't just work (though you will only have access to the v1 feature set). If there are specific v2 features you think should be implemented, you can file as separate feature requests.
