### ISSUE TITLE
Lost message when one broker offline in Kafka cluster

### ISSUE THREAD

**Issue by Toplife** [dpkp/kafka-python#1579]
Hi smart guys,
please help me about below case:

I have a Kafka cluster(3 broker),

**producer sample code:**
```python
from kafka import KafkaProducer
import time
import random

KAFKA_TOPIC = 'demo'
KAFKA_BROKERS = 'xxx:9092,xxx:9093,xxx:9094'

def producer():
    # To send messages asynchronously
    p = KafkaProducer(bootstrap_servers=KAFKA_BROKERS)
    for idx in range(10000):
        time.sleep(3)
        pt = random.randint(0, 9)
        print("send data to partition" + str(pt))
        p.send(KAFKA_TOPIC, key=str(pt).encode('utf-8'), partition=pt, value=str(idx).encode('utf-8'))


if __name__ == '__main__':
    producer()
```

**consumer sample code**
```python
from __future__ import print_function
from kafka import KafkaConsumer
import sys
KAFKA_TOPIC = 'demo'
KAFKA_BROKERS = 'xxx:9092,xxx:9093,xxx:9094'
def consumer():

    c = KafkaConsumer(KAFKA_TOPIC, bootstrap_servers=(KAFKA_BROKERS), group_id='demo')
    print(consumer)
    try:
        for message in c:
            print(message.value)
    except KeyboardInterrupt:
        sys.exit()


if __name__ == '__main__':
    consumer()
```

**case:**
send message, when I try kill one broker, I find will loss message in that time.

![2018-08-23 16_30_43-root hkgcfdv01376__home_csapp_kafka_kafka_2 11-1 0 0](https://user-images.githubusercontent.com/10285243/44514347-6fa23d00-a6f2-11e8-84c7-63faf3ddf7f6.png)

![2018-08-23 16_29_04-kafka-cluster d__opensource_pythonspace_kafka-cluster - _consumer py kafka](https://user-images.githubusercontent.com/10285243/44514398-96607380-a6f2-11e8-9b74-dcbf798973ee.png)

Thanks

**Comment by dpkp** [comment]
By default the KafkaProducer does not retry failures -- it is fire + forget. If you want more reliability, consider configuring `retries` > 0 and/or check the return value of the producer futures.

```
p.send(....).get(timeout=10) # get() will raise exception if unable to process send w/i timeout
```
