### ISSUE TITLE
Figuring out a Consumer is 'Ready'?

### ISSUE THREAD

**Issue by amit-traiana** [dpkp/kafka-python#1585]
Hello,

We using `kafka-python` in couple of our integration tests.  The application we test consume a message from topic named 'in', modify the message, and output the modified message into topic named 'out'. So a standard test will look like so:

1. Subscribe to topic `out` and start consuming (happening on a dedicated process).
2. Produce a message on topic `in`
3. When the message show on the consumer, verify the message was indeed modified.

Now, sometimes the above fail. The reason is because it takes the consumer some time to start consuming (and the consumer is running async on a different process). So sometimes the message reach the `out` topic before the consumer is ready to consume, so I basically 'miss' the message and the test fail.

And easy solution would be just adding `sleep`, but we found that on some computers you will need 0.5ms and on some 3 seconds (depends on the connection). So sleep is not a good solution for us.

Is there any way to know the consumer object is 'ready' to consume and message I will send from now on to that specific topic? we have couple of more complicated ideas (like sending an `init` message and flag it - but this also means we probably need to send couple of 'init' message because we don't know which one will get picked and when).

Thanks!

**Comment by tvoinarovskyi** [comment]
Are the topics purged for the purpose of that test. If they are you may just set 'offset_reset_policy=earliest' and the consumer will restart from start even if some messages were sent before consumer start

**Comment by amit-traiana** [comment]
@tvoinarovskyi Sadly the topics are not being purged per test (too complex with the current infrastructure).

**Comment by tvoinarovskyi** [comment]
You can just seek to the needed offset of the message after consumer start (let producer remember the first message timestamp and seek to it). You could seek to a specific timestamp if the tests are run within a more-or-less separate time.

**Comment by amit-traiana** [comment]
@tvoinarovskyi So, if I understand you correctly:

1. Produce a message with unique string/time-stamp.
2. Start the consumer with `earliest` attribute and consume until you reach the correct message.

You mentioned 'seek'. Is there an option to seek to a specific offset (where the message is) just by the message string/time-stamp? or I have to consume them one by one? because in a system where everyone use the same Kafka - this might take a bit of time (depending on how many messages are in the topic since 'earliest').

**Comment by amit-traiana** [comment]
Did some research and came out with this:

```
import logging
import multiprocessing

from kafka import KafkaConsumer

log = logging.getLogger(__name__)


class Consumer(multiprocessing.Process):
 
    def __init__(self, topics, **consumer_kwargs):
        multiprocessing.Process.__init__(self)
        self.is_ready_event = multiprocessing.Event()
        self.stop_event = multiprocessing.Event()

        self.topics = topics
        self.consumer_kwargs = consumer_kwargs

        self.queue = multiprocessing.Queue()

    def run(self):
        consumer = KafkaConsumer(**self.consumer_kwargs)
        consumer.subscribe(self.topics)
        self.is_ready_event.set()

        while not self.stop_event.is_set():
            message = consumer.poll(max_records=1)

            if message:
                log.debug('Message consumed: %s', message)
                self.queue.put(next(iter(message.values()))[0])

        consumer.close()

    def is_ready(self):
        return self.is_ready_event.is_set()

    def stop(self):
        self.stop_event.set()
```

Then, In my test I can just:

```
consumer = Consumer('my_topic')
consumer.start()
```

Poll if my consumer for when `is_ready` is ready, and if so - produce a message and accessing it from the `consumer.queue`. It's super hacky, but this allow me to control what happening. 

Will be happy if someone has a better idea on how to approach it - but for now, I guess it works and it's enough for tests...
