### ISSUE TITLE
Behavior of consumer.subscribe('non-existent-topic') when topic auto-creation is disabled

### ISSUE THREAD

**Issue by xbabinec** [dpkp/kafka-python#1588]
I'm wondering, why `KafkaConsumer` on `consumer.subscribe()` when subscribed to non-existent topic does not raise any kind of exception or error, while in kafka configuration auto-creation of topics is disabled by setting `auto.create.topics.enable=false`.

In my case I'm using kafka inside [docker container](https://hub.docker.com/r/confluentinc/cp-kafka/) with auto-creation disabled by setting enviromental variable `KAFKA_AUTO_CREATE_TOPICS_ENABLE=false` inside docker.

When I run following code:
```python
# Try to connect to kafka broker while not successful
while True:
    try:
        consumer = KafkaConsumer(bootstrap_servers=[self._conn_str],
                                 auto_offset_reset='latest',
                                 consumer_timeout_ms=1000)
        consumer.subscribe(['non-existent-topic'])
        break
    except NoBrokersAvailable as e:
        print('Broker not available')
        time.sleep(1)

# Start consuming
for message in consumer:
        msg_dict = json.loads(message.value.decode('utf-8'))
        print(msg_dict)
        . . .
```
I don't get any kind of exception or error even when no topic was created (as auto-creation is disabled) and my python process just continues to run (i. e. consumer is subscribed to non-existent topic).

Is this expected behavior? If so, what's the reason behind such behavior?

**Comment by dpkp** [comment]
Yes, this is expected. Your consumer can continue to run and will get messages when the topic is created. If you want to verify that the topic exists already, you can do something like:
```
if 'non-existent-topic' not in consumer.topics():
    raise NonExistentTopic
```
