### ISSUE TITLE
msg.key seems not to be provided in correct order to the stream

### ISSUE THREAD

**Issue by tLupus1978** [dpkp/kafka-python#1593]
- using latest github kafka-python

    producer = KafkaProducer(bootstrap_servers=PYTHONWORKER_KAFKA_SENDURL)
    producer.send('jobevents', key.encode(), data.encode())

this results e.g. in msg (GUID is my Key):
{"JobFinished": {"timestamp": 1538142366299}}   ac71cfcf-ba38-40ce-a687-c6ee9fba1d76

but it should be:
ac71cfcf-ba38-40ce-a687-c6ee9fba1d76  {"JobFinished": {"timestamp": 1538142366299}}   

this results in problems when using Confluent.Kafka.Serialization in c# or kafka on JAVA as the standard serializer is not able to read the message correctly.

Is there a possibility to change key/data order?

**Comment by tvoinarovskyi** [comment]
You provide arguments in the wrong order. ```send(topic, value=None, key=None, headers=None, partition=None, timestamp_ms=None)```
You need to pass `data.encode` first

**Comment by tLupus1978** [comment]
Thanks, this solves my issue!
