### ISSUE TITLE
comsumer receive message very slow

### ISSUE THREAD

**Issue by gzliudan** [dpkp/kafka-python#1597]
kafka-python is 1.4.3, and kafka is 1.0.0. The topic has 6 partitions with 6 consumers on 2 hosts, each host has 3 consumers. But consumers receive messages very slow, the lag time is about 20 minutes. Every message is no longer than 135 chars. And the count of messages is less than 5 in an hour.  Below is consumer's config:

enable_auto_commit=True, 
auto_commit_interval_ms=5000,
heartbeat_interval_ms=5000, 
session_timeout_ms=50000, 
request_timeout_ms=60000,
max_poll_interval_ms=55000

**Comment by jeffwidman** [comment]
Can you post debug logs?

Also, how do you know that the producer isn't sending them slowly? Are you running a console consumer or some other consumer to verify that the problem is with `kafka-python`, and not with your brokers/producers?

**Comment by gzliudan** [comment]
I tested confluentinc/confluent-kafka-python today, the consumer's speed is normal. Instead dpkp/kafka-python  receive message sometimes even after 8 hours. But my message count in one day is less than 20.

**Comment by jeffwidman** [comment]
Hmm, I don't see anything obvious in your config that's wrong.

At this point, to really solve this, I'd need debug logs + knowing the time when a message was produced to compare that with when it showed up and what happened before that point. If you can provide that, great, if not, I understand.

**Comment by dpkp** [comment]
Recommend trying w/ 1.4.4 -- fixed a major consumer deadlock bug.

**Comment by gzliudan** [comment]
I tested Release 1.4.4 just now, the speed problem is not disapper. I use kafka-console-producer.sh to send 2 messages, the KafkaConsumer use more than 3 minutes receive this messages.
