### ISSUE TITLE
Create benchmark tests

### ISSUE THREAD

**Issue by yefremov** [dpkp/kafka-python#16]
It would be great to have benchmark/performance tests to compare Kafka client implementations and make a decision which one to use.

**Comment by dpkp** [comment]
pykafka has a few benchmark scripts at https://github.com/Parsely/pykafka/tree/master/benchmark

**Comment by dpkp** [comment]
here's another potential source for benchmark code: https://github.com/mrafayaleem/kafka-jython/tree/master/benchmarks

**Comment by dpkp** [comment]
rudimentary benchmarking scripts are now in `benchmarks/` -- see #754
