### ISSUE TITLE
How to detect the topic is not receiving the Kafka message from the producer

### ISSUE THREAD

**Issue by Atusshi** [dpkp/kafka-python#1600]
I'm doing the video streaming project using Apache Kafka.
one camera will send to one Kafka Broker (broker A) in one cluster. if the broker is down it will send to another broker (broker B) in another cluster. That part is already done.
But for the consumer how can he know the camera is sending to broker A or broker B. assume consumer is pulling from Broker A initially. Later on, camera sends to broker B and consumer have to consume from the broker B. Note that Broker A and B are in the different cluster.

**Comment by stigok** [comment]
Sounds like you are trying to solve what a Kafka cluster has already solved -- namely broker redundancy. Having a redundant broker in a separate cluster defeats the purpose of having clustered Kafka at all. Maybe I am misunderstanding your use-case?
If they are in the same cluster, your consumer doesn't have to care about where the producer has sent messages. If one broker is down, it can automatically connect to the other broker in the list of bootstrap servers you have set up.

**Comment by Atusshi** [comment]
yes But I don't want to use as a cluster. because if the leader partition of the broker is down, another broker in the cluster take it place. so that consumer has to consume from the new leader partition. In my case, I just want to consume from at most 2 brokers.

**Comment by jeffwidman** [comment]
This sounds like a general question about kafka and not specific to this library, so I suggest you ask it over on stackoverflow.

**Comment by Atusshi** [comment]
Thank you for the reply

It can be using consumer_timeout_ms at the consumer and it will quite from the iteration and we can detect no message is coming from producer
