### ISSUE TITLE
Should `KafkaAdmin` be renamed to `KafkaAdminClient`?

### ISSUE THREAD

**Issue by jeffwidman** [dpkp/kafka-python#1621]
Should `KafkaAdmin` be renamed to `KafkaAdminClient`?

The Java world typically calls it the `AdminClient`. And I can visualize a world where `Admin` could refer to a user, an ACL flag governing whether an application has admin permissions, or this client.

Thoughts @dpkp  / @tvoinarovskyi ?

**Comment by jeffwidman** [comment]
Any feedback @dpkp / @tvoinarovskyi ?

**Comment by tvoinarovskyi** [comment]
Yup, sure, that makes sense to me. Matches Java's name too.

**Comment by dpkp** [comment]
Makes sense to me!

>
