### ISSUE TITLE
Error in close connection - KafkaConsumer 

### ISSUE THREAD

**Issue by javixeneize** [dpkp/kafka-python#1649]
Hi

I am trying to close a kafka consumer i have previously started. However, it does not seem to be working fine

    KafkaConsumer.close()
TypeError: close() missing 1 required positional argument: 'self'

According to the documentation, it does not need any attribute apart from autocommit, which is True by default

https://kafka-python.readthedocs.io/en/master/apidoc/KafkaConsumer.html#kafka.KafkaConsumer.close

I have tried this as well with the same result

    KafkaConsumer.close(autocommit=True)
TypeError: close() missing 1 required positional argument: 'self'

Any idea on what i am doing wrong?

Thanks

**Comment by dpkp** [comment]
You are calling an instance method on a class. You need to create a
consumer and then call close() using that consumer instance.

**Comment by javixeneize** [comment]
Hi. Yes, i have tried that as well. I have initialised a KafkaConsumer and also called to close(). All the other methods for kafkaconsumer work fine there

**Comment by dpkp** [comment]
Google search for "missing 1 required positional argument: 'self'" and you'll find many helpful articles discussing this problem.
