### ISSUE TITLE
Error 'too many values to unpack' in KafkaAdminClient: _send_request_to_controller  

### ISSUE THREAD

**Issue by PabloInnocenti** [dpkp/kafka-python#1657]
Dear kafka-python team,

We start using the API KafkaAdminClient (1.4.4) to create a Topic on a kafka version 1.1 (0.11.0 protocol). We use the following code:
`kac_dst = KafkaAdminClient(bootstrap_servers=bootstrap_servers,client_id='data')`
`logger.info("Creating topic {}".format(topic_name))`
`topic_list = []`
`topic = NewTopic(name=topic_name, num_partitions=2, replication_factor=3)`
`topic_list.append(topic)`
`response = kac_dst.create_topics(new_topics=topic_list, validate_only=True)`

The following error occur while executing create_topics function:

`kafka/admin/client.py", line 398, in create_topics`
`    return self._send_request_to_controller(request)`
`  kafka/admin/client.py", line 335, in _send_request_to_controller`
`    for topic, error_code in getattr(response, "topic_errors", response.topic_error_codes):`
`ValueError: too many values to unpack (expected 2)`

If we set validate_only=False, using one element or few,the same error occur, but the topic/s are created .

Regards,
Pablo.

**Comment by dpkp** [comment]
This is a bug, thanks!

**Comment by jeffwidman** [comment]
Hmm... I had tested sending the CreateTopic calls to the wrong controller and the code as written correctly handled the error... so unless I fat-fingered the commit, I want to play with this a little to better understand what's happening.

**Comment by mooperd** [comment]
+1

**Comment by jeffwidman** [comment]
Yeah, I haven't forgotten about this, just been a busy week... it's on my todo list to play with this and a few more pieces of the `AdminClient`, although I'm traveling this next week so may be a little longer.

**Comment by Vijay-P** [comment]
Related: when using create_partitions, you get ```AttributeError: 'CreatePartitionsResponse_v0' object has no attribute 'topic_error_codes'```.

**Comment by kiblik** [comment]
+1

**Comment by chenhuayi83** [comment]
+1

**Comment by jeffwidman** [comment]
This is now fixed in `master` by https://github.com/dpkp/kafka-python/pull/1658.

**Comment by nmvega** [comment]
I just got this exception, too, using `kafka-python==1.4.4` I couldn't tell from the above conversation if this was corrected. Has it been corrected? The latest available version via `pip` is `v1.4.4`.

Thank you! :)

**Comment by jeffwidman** [comment]
Yes, this is fixed on `master`. So just use that (`pip` supports installing directly from master/specific commits).

Hopefully we can get a new release out sooner rather than later.

**Comment by nmvega** [comment]
Hi Jeff. Thank you. I'll install from `github`.

**Comment by jlcontreras** [comment]
Confirming that installing from `master` works, thanks for the tip!
(Using kafka-python 1.4.6 didn't work for me though, I'm surprised this fix didn't make it into the release)

**Comment by jeffwidman** [comment]
> Using kafka-python 1.4.6 didn't work for me though, I'm surprised this fix didn't make it into the release.

This fix was released in `1.4.5`, so it should be available in `1.4.6`... are you positive you tested this correctly? I would start with a fresh virtualenv to doublecheck.
