### ISSUE TITLE
kafka-python deadlock,when kafka abnormal restart.

### ISSUE THREAD

**Issue by Ronniexie** [dpkp/kafka-python#1671]
When kafka abnormal restart(e.g linux server power off restart),server deadlock and consumer can't get message.
Analyze：
1.kafka/coordinator/base.py "def coordinator_dead(self, error):"
  coordinator can't dead,because self._lock is work in HeartbeatThread.
2.why heartbeatThread deadlock.
   kafka/coordinator/base.py
  with self.coordinator._lock:
  self.coordinator._client.poll(timeout_ms=0)
  because heartbeatThread use self.coordinator._lock,so coordinator can't dead,when "self.coordinator._client.poll" socket reset and deadlock.

https://github.com/dpkp/kafka-python/issues/1664

**Comment by dpkp** [comment]
What version of kafka-python are you using? This doesn't seem to reflect the current code / locks.

**Comment by dpkp** [comment]
Please upgrade to the latest 1.4.4 and/or try master. There have been several patches to address deadlocks. Feel free to reopen if you've verified this behavior remains on the latest kafka-python code.
