### ISSUE TITLE
SyntaxError: EOL while scanning string literal via Spark Zipfile

### ISSUE THREAD

**Issue by bharat-gera** [dpkp/kafka-python#1674]
Dear Team,

I was trying to publish the data on kafka topic using Spark Streaming. While importing "KafkaProducer" class in Spark python script, It gives me the following error:

File "./libs.zip/kafka/__init__.py", line 22, in <module>
    from kafka.consumer import KafkaConsumer
  File "./libs.zip/kafka/consumer/__init__.py", line 5, in <module>
  File "./libs.zip/kafka/consumer/group.py", line 360
    if 'max_po
             ^
SyntaxError: EOL while scanning string literal

Any help would be appreciated.

Thanks,

**Comment by jeffwidman** [comment]
Your issue mentions `KafkaProducer`, but the exception refers to `KafkaConsumer`, which is it?

And can you include a code snippet showing how you call this?

**Comment by dpkp** [comment]
It looks like you are shipping python modules in a zip file for spark. Can you check your zip file for corruption?
