### ISSUE TITLE
Headers Support not found in  kafka 1.3.1 and 1.4.1 

### ISSUE THREAD

**Issue by saurabh3737** [dpkp/kafka-python#1676]
Hello Sir,
i cannot find headers support in send method of kafkaproducer, can you please help, i can see that support on older version 0.11.02 and kafka master version as show in below kafka docs
Not Found: https://kafka-python.readthedocs.io/en/1.3.1/apidoc/KafkaProducer.html

(Pdb) import kafka
(Pdb) kafka.__version__
'1.3.1'
(Pdb) import inspect
(Pdb) inspect.getargspec(cd.send)
ArgSpec(args=['self', 'topic', 'value', 'key', 'partition', 'timestamp_ms'], varargs=None, keywords=None, defaults=(None, None, None, None))

**Found in master:** : https://kafka-python.readthedocs.io/en/master/apidoc/KafkaProducer.html
Found in Doc: https://media.readthedocs.org/pdf/kafka-python/stable/kafka-python.pdf
https://pypi.org/project/kafka-python/

Please help how can i use it in 1.3.1 version or is there any alternative for similar functionality.

Thanks
Saurabh

**Comment by tvoinarovskyi** [comment]
You have to update the library, no good way to use headers in 1.3.1. They were only added to parser to support consumption of messages with headers, but not exposed until recently.

**Comment by saurabh3737** [comment]
Thanks for your quick reply, can you please suggest which version of kafka I can use now to support headers and the link to download that.

Thanks
Saurabh

**Comment by tvoinarovskyi** [comment]
Sure, available sinse latest version 1.4.4. Download https://github.com/dpkp/kafka-python/releases/tag/1.4.4 or ``pip install kafka-python==1.4.4``
