### ISSUE TITLE
Verify these timeouts are in descending order on KafkaConsumer instantiation

### ISSUE THREAD

**Issue by jeffwidman** [dpkp/kafka-python#1680]
When we create a `KafkaConsumer`, we should validate that the following timeouts are in descending order:
1. `connections_max_idle_ms`
2. `request_timeout_ms`
3. `session_timeout_ms` (or equivalent, depending on pre/post 0.10.1 broker)

If they are not, then raise an error... otherwise the consumer can end up in weird states.

**Comment by tvoinarovskyi** [comment]
Sounds reasonable. I wonder does Java client do that, never saw it in the code...
