### ISSUE TITLE
can't reconnect if brokers go down and bootstrap servers change IP

### ISSUE THREAD

**Issue by dedsm** [dpkp/kafka-python#1683]
Similar to https://github.com/dpkp/kafka-python/issues/1083, except that if the bootstrap servers also change IP (a kubernetes kafka deployment deleted and re-applied triggers this) then the client will keep trying to connect to the old bootstrap server IPs and never try to resolve the DNS again, I fixed it by monkeypatching _maybe_connect to always re-bootstrap in case of disconnection, but maybe it's not the best way to do it?

```python
mc = client_async.KafkaClient._maybe_connect


def maybe_connect(kc, node_id):
    with kc._lock:
        connection = kc._conns.get(node_id)
        if connection and connection.disconnected():
            kc._conns.pop(node_id)
            kc._bootstrap(conn.collect_hosts(kc.config['bootstrap_servers']))
    return mc(kc, node_id)


client_async.KafkaClient._maybe_connect = maybe_connect
```

**Comment by tvoinarovskyi** [comment]
Please try to configure the broker to have your dns in `advertised_listener`. It should be able to reconnect that way.

**Comment by dedsm** [comment]
huh now I see, the helm chart I was using used the IPs as advertised listeners, setting the DNS manually in the advertised listeners works. I still wouldn't mind to have a failsafe in case of IP only, like fail after a while or something else than keep running forever. But feel free to close the issue as the main issue is solved by advertising DNS names.

Thanks!
