### ISSUE TITLE
Got lots Error Messages while connecting kafka

### ISSUE THREAD

**Issue by lusheldon** [dpkp/kafka-python#1684]
Hi,

I'm using kafka client for autotest. But while connecting to kafka, I always got lots error messages like below:

> 

20181226 10:06:16.794 | ERROR | Topic LU33_A_CMB03_VBSDTA_PLLONAMTP_SRC_SH is not authorized for this client |  
-- | -- | -- | --
20181226 10:06:16.794 | ERROR | Topic TOPIC_3_NEW_FLUME_TEST_4docker is not authorized for this client |  
20181226 10:06:16.794 | ERROR | Topic RDP_ALI08_AGA_TRSDAT_SZ is not authorized for this client |  
20181226 10:06:16.794 | ERROR | Topic LH19_A_CMB03_VBSDTA_FPCRDDTAP_SRC_SH is not authorized for this client

I traced the code, and found it was raised by  update_metadata method in cluster.py

`elif error_type is Errors.TopicAuthorizationFailedError:`

My question is, why update_metadata should be called when connecting to kafka? How could I get rid of this?

thanks for any advise.

**Comment by jeffwidman** [comment]
This looks like a cluster-level error. `kafka-python` is merely telling you what the cluster is telling it, namely that your client is not authorized to talk to that topic. 

I assume you've enabled topic-level ACLs? 

Closing, as not a `kafka-python` issue`, happy to re-open if it is.
