### ISSUE TITLE
Cannot define kerberos principal name correctly

### ISSUE THREAD

**Issue by perrefe** [dpkp/kafka-python#1685]
I'm facing a problem trying to use kerberos authentication, probably I missconfigured something but I cannot realize where is the problem.

In KDC I've created this principal:

`addprinc -randkey kafkaclient/server1@MY.CORP`

Then, in the producer program, I instantiate the producer this way:

```
producer = KafkaProducer(bootstrap_servers=['server2:9093'],
                         retries=2,
                         api_version=(0, 11, 0),
                         value_serializer=lambda v: json.dumps(v).encode('utf-8'),
                         security_protocol='SASL_PLAINTEXT',
                         sasl_mechanism='GSSAPI',
                         sasl_kerberos_service_name='kafkaclient',
                         sasl_kerberos_domain_name='MY.CORP')
```

Before launching the program, I execute kinit to get a valid kerberos ticket

`kinit kafkaclient/server1`

Now, when I launch the program, it says

`Minor code may provide more information, Minor (2529638919): Server kafkaclient/my.corp@MY.CORP not found in Kerberos database`

I didn't find why the server part of the principal is **my.corp** instead of **server1**.

Can you please help me?

**Comment by dpkp** [comment]
Sorry -- the kerberos support in kafka-python was a patch from the community. I don't have any insight into how to debug kerberos issues.

**Comment by tvoinarovskyi** [comment]
@perrefe Did you try to use a different driver with that configuration? Like ``confluent-kafka-python``.
@dpkp We definitely have to have a setup to test this. I will be working on Docker-based Kerberos setup for testing this feature in ``aiokafka``, hope will be able to port it afterwards to kafka-python.

**Comment by tvoinarovskyi** [comment]
Hmm, maybe your sasl_kerberos_service_name should be `server1`?)
