### ISSUE TITLE
Cleanup Travis Matrix

### ISSUE THREAD

**Issue by jeffwidman** [dpkp/kafka-python#1699]
Research whether we could use this kind of Travis setup here for better performance: https://github.com/FactoryBoy/factory_boy/pull/553

**Comment by dpkp** [comment]
Can you elaborate?

**Comment by jeffwidman** [comment]
Compare https://travis-ci.org/dpkp/kafka-python/builds/478934309 to https://travis-ci.org/FactoryBoy/factory_boy/builds/477871708

Basically the latter has only one Travis container per Python Env, even though it's running against multiple Django versions.

I wonder if we could use the same thing to re-use a Travis container against multiple Kafka versions.

I don't know for sure, this may not be possible since Kafka is Java vs Django is easily wiped out with a new `tox` environment... but thought it worth looking into and I don't have the time to right now so filed a ticket.

**Comment by wbarnha** [comment]
Travis is deprecated!
