### ISSUE TITLE
Pass properties to producer

### ISSUE THREAD

**Issue by giyama** [dpkp/kafka-python#1706]
I'd like to start a prodeucer passing this properties: 

`--property "parse.key=true" --property "key.separator=:"`

How can I achieve that?

**Comment by dpkp** [comment]
All configuration options are documented here: https://kafka-python.readthedocs.io/en/master/apidoc/KafkaProducer.html

All options are passed as standard python kwargs, so `KafkaProducer(foo='bar')`
