### ISSUE TITLE
How to know which partitions I'm listening?

### ISSUE THREAD

**Issue by sneko** [dpkp/kafka-python#1708]
Hi

I saw that in my event I could get some information about offset and partition of this event. But how can I know which partitions my consumer will consume since I'm using a group_id so that Kafka assigns partitions per consumer on its own?

Thank you,

**Comment by jeffwidman** [comment]
This method should provide the info you're looking for: https://kafka-python.readthedocs.io/en/master/apidoc/KafkaConsumer.html#kafka.KafkaConsumer.assignment
