### ISSUE TITLE
Usage of consumer_timeout_ms

### ISSUE THREAD

**Issue by dnlwgnd** [dpkp/kafka-python#1709]
Hi there,

I seem to have a problem in correctly implementing a consumer.
In my sceneario I have a topic with 8 partitions into which a producer sends a number of messages about every second.
I want my consumer to run only once in a while (say every hour) and then consume all the messages that are waiting in the log, but not wait for more messages. I will then batch-process all those messages and commit their offsets. This works mostly as expected. 

`KafkaConsumer('topic',group_id='group', bootstrap_servers=[KAFKA_SERVER], enable_auto_commit=False, auto_offset_reset='earliest', value_deserializer=lambda v: json.loads(v.decode('utf-8')), key_deserializer=lambda k: k.decode('utf-8'), api_version=(1, 0, 0), consumer_timeout_ms=500))`

Now to not wait infinitely for more messages, I setup the consumer with consumer_timeout_ms = 500 to stop the iterator when all "old" messages in the log have been consumed.

However in most cases this doesn't work and will return no messages at all, althouhg thousands of messages are available and uncommitted. When I increase the timeout to something like 2000 ms, I do get all the messages.
Also it sometimes does work with 500ms, when I have consumed messages shortly (few seconds) before (with larger timeout). The server is in the local network.

Why do I experience this behaviour, is there anything I can do about it?
Any hints appreciated :-)

**Comment by tvoinarovskyi** [comment]
500 miliseconds is not enough time to join the group. You can either set the timeout to say 5mins or just use poll() API instead. That way you will be sure the timeout will count against data fetch, not rebalance.

**Comment by dpkp** [comment]
For this type of consumer pattern you might also try grabbing the highwater
offset for each partition and stop consuming once you get to offset =
(highwater - 1) . See KafkaConsumer.highwater(partition)

>
>

**Comment by dpkp** [comment]
I'd recommend using consumer.poll() with a timeout_ms . To avoid consumer rebalancing I would avoid using a group_id, but you probably do want to commit offsets with `consumer.commit()`
