### ISSUE TITLE
Support OAuthBearer Authentication

### ISSUE THREAD

**Issue by psycotica0-shopify** [dpkp/kafka-python#1710]
With [KIP-255 OAuth Authentication via SASL/OAUTHBEARER](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=75968876), Kafka now supports OAuth tokens as a method of authentication.

For us to use it on the brokers requires the library to support it, so I'm creating this issue here in case someone beats us to it (or it's already done somewhere I haven't found)

**Comment by jeffwidman** [comment]
A PR would be very welcome!

**Comment by shawnsarwar** [comment]
Is anyone actively working on this? I'd hate to duplicate effort. 

If not, there's some helpful prior art in [this article](https://medium.com/@jairsjunior/how-to-setup-oauth2-mechanism-to-a-kafka-broker-e42e72839fe), which describes a java implementation. The repo for the example is [available here](https://github.com/jairsjunior/kafka-playground) and would be a useful reference to work against if you don't already have a broker running `OAUTHBEARER`.

**Comment by psycotica0-shopify** [comment]
We aren't _yet_, but we will be shortly, probably, if no one beats us to it (which would be great, TBH)
There's also https://github.com/zendesk/ruby-kafka/pull/710 and https://github.com/Shopify/sarama/pull/1240 if you're looking for other references.

**Comment by pt2pham** [comment]
@shawnsarwar just wondering if you're currently doing work on this or if it would be okay for me to do it!

**Comment by pt2pham** [comment]
I am now working on this!

**Comment by pt2pham** [comment]
This issue can be closed now

**Comment by dpkp** [comment]
Woot!
