### ISSUE TITLE
NoBrokersAvailable Error when using kafka in docker

### ISSUE THREAD

**Issue by LukasM7** [dpkp/kafka-python#1713]
Hi,

I am using kafka as part of the confluent platform in docker on windows. I have tried running kafka on windows without docker and successfully sent messages using a python producer. However when I am using docker to run kafka I can't send messages and get the NoBrokersAvailable error message.

`
  File "C:\ProgramData\Anaconda3\lib\site-packages\kafka\client_async.py", line 872, in check_version
    raise Errors.NoBrokersAvailable()`

I have tried setting API version and setting API version timeout to a higher value but both things did not work.

When using the console producer sendig messages works fine however it only works when bootstrapping to localhost:29092 and not with localhost:9092

**Comment by jeffwidman** [comment]
TBH, this sounds like a user configuration error. Especially if you have to pick a non-standard port... try configuring `kafka-python` using whatever bootstrap address (including custom port) that you use for the console consumer/producer.
