### ISSUE TITLE
Consumer drops messages posted to kafka.

### ISSUE THREAD

**Issue by vkjv** [dpkp/kafka-python#1716]
My kafka consumer do not receive all the messages posted to kafka topic. If I look at the kafka logs of the topic, I see more messages than what was received by consumer.
For some of the messages, the time taken for processing is going beyond request_timeout. And there were warnings in the logs saying, Hearbeat session expired, and
WARNING:kafka.coordinator.consumer:Auto offset commit failed for group 45e933de-33b1-11e7-a919-92ebcb67fe33: CommitFailedError: Commit cannot be completed since the group has already
            rebalanced and assigned the partitions to another member.
            This means that the time between subsequent calls to poll()
            was longer than the configured max_poll_interval_ms, which
            typically implies that the poll loop is spending too much
            time message processing. You can address this either by
            increasing the rebalance timeout with max_poll_interval_ms,
            or by reducing the maximum size of batches returned in poll()
            with max_poll_records.
This is log for Heartbeat session expired.
WARNING:kafka.coordinator:Heartbeat session expired, marking coordinator dead
WARNING:kafka.coordinator:Marking the coordinator dead (node 1) for group 45e933de-33b1-11e7-a919-92ebcb67fe33: Heartbeat session expired.

We are using iterator interface to retrieve messages. And kafka-python version is 1.4.4
Any help is much appreciated.

**Comment by jeffwidman** [comment]
This isn't a problem with `kafka-python`, the problem is your configuration isn't appropriate for your workload... The error message explains it--try increasing `max_poll_interval_ms` so that you don't get rebalances. If this doesn't make sense, I suggest reading up on how kafka group rebalancing works and that provide a bit more context here...
