### ISSUE TITLE
Getting StaleLeaderEpochCodeError while committing the offset 

### ISSUE THREAD

**Issue by jamoham** [dpkp/kafka-python#1719]
While committing the offsets, we are sometimes getting the following exception:
```
  File "/usr/local/lib/python2.7/dist-packages/mdl_kafka_shared/core/core_kafka_consumer.py", line 246, in commit_offsets_on_batch_completion
    self.commit()
  File "/usr/local/lib/python2.7/dist-packages/kafka/consumer/group.py", line 515, in commit
    self._coordinator.commit_offsets_sync(offsets)
  File "/usr/local/lib/python2.7/dist-packages/kafka/coordinator/consumer.py", line 513, in commit_offsets_sync
    raise future.exception # pylint: disable-msg=raising-bad-type
kafka.errors.StaleLeaderEpochCodeError: [Error 13] StaleLeaderEpochCodeError
```

The code here mentions a TODO asking if this particular exception is deprecated:
https://github.com/dpkp/kafka-python/blob/f3105a434f3bd2fb3f8899e4861e187e786b03da/kafka/errors.py#L213

**Question:**
- How do we handle this exception? 
In case of `CommitFailedError`,  we know that it is ok to drop the message because this message will be picked up again by the consumer which now owns the partition to which this message originally belongs. But could you please explain what is the reason for getting `StaleLeaderEpochCodeError` and how we should handle it? We could not find any documentation or explanation about this exception.

- Is this exception `StaleLeaderEpochCodeError` deprecated?
If yes, then how do you think we are hitting it? We are using kafka-python 1.4.3

**Comment by dpkp** [comment]
This is a pass through of a low-level kafka server error. Have you checked
the server logs? I suspect it is related to your brokers' connections with
your zookeeper cluster. The deprecation warning relates only to the kafka
broker. What kafka broker version are you using?

>
>

**Comment by arerlend** [comment]
https://kafka.apache.org/protocol#protocol_error_codes

Error code 13 should be a network exception.

**Comment by dpkp** [comment]
That network exception is generated client-side by the java client. The error here is generated by the server. Not the same.

**Comment by tvoinarovskyi** [comment]
@arerlend What broker version do you use? I feel like the broker is old enough to generaye this exception.

**Comment by jamoham** [comment]
Closing this issue as this is related to older versions of broker
