### ISSUE TITLE
could i use the admin client to set acl/quota now?

### ISSUE THREAD

**Issue by foolcage** [dpkp/kafka-python#1727]
could i use the admin client to set acl/quota now?
I check the admin api and source code,it seems not implemented yet?

**Comment by ulrikjohansson** [comment]
There is nothing that uses the ACL protocol in the admin client yet.
If you would like to set/get acls through kafka-python right now you would have to use the protocols directly, which is doable but a bit messy.

I've been fiddling with getting ACL functionality in the client properly, but haven't had much time lately. There is a branch in a personal fork with my test code if you're interested in building off of that: https://github.com/dpkp/kafka-python/compare/master...ulrikjohansson:acl_api

I have to stress though that this is just my own play code, it might look very different in a possible PR against kafka-python further down the road, and this code is not used in production in any form.

**Comment by jeffwidman** [comment]
Closing as the question is answered... #1638 tracks the underlying issue.
