### ISSUE TITLE
Judge request timeout by conn.requests_timed_out()

### ISSUE THREAD

**Issue by Stephan14** [dpkp/kafka-python#1734]
Why do you judge request timeout by `conn.requests_timed_out()` in `client_async.py`? I see you have used `select` and `timeout`

**Comment by dpkp** [comment]
The client manages a set of connections, each of which has its own request/response pipeline. Delegating to `conn.requests_timed_out()` allows us to let each connection to manage its own timeouts for its pipeline. The select timeout is a higher-level I/O timeout to check for available data on one or more of the connections, and if nothing is available immediately then wait for up to timeout seconds until breaking and doing other client work.
