### ISSUE TITLE
github releases page lists 1.4.5 as latest

### ISSUE THREAD

**Issue by jeffwidman** [dpkp/kafka-python#1779]
https://github.com/dpkp/kafka-python/releases lists 1.4.5 as `latest` release.

I poked around in the UI for how to change this, but not seeing anything and a quick google search isn't turning up much... could be because it's 3am 😉 

I can look at tomorrow perhaps, but filing the ticket so we don't forget

**Comment by jeffwidman** [comment]
Looks like Pypi also missing 1.4.6?

Maybe Dana tagged the release but didn't push the artifacts yet?

**Comment by dpkp** [comment]
Pushed to get a travis test run, then went to bed for the night ;)

Release is published!

**Comment by jeffwidman** [comment]
Ah, yes, definitely something I overlooked at 3am. Sorry about that.

Thank you again for putting in all the extra time to get this out on the short time turnaround
