### ISSUE TITLE
KafkaConsume poll return just one record when there are plenty of message in the kafka

### ISSUE THREAD

**Issue by shllove** [dpkp/kafka-python#1794]
when I call the method poll of the KafkaConsumer, I can only get 1 record from it.
I try the version 1.1.0 and 2.1.0,  and the result seems the same. Any help may be appreciated. Thanks.

this is my client config:
Properties props = new Properties();
			props.put("bootstrap.servers", Config.getKafkaWebServicePushServers());
			props.put("group.id", Config.getKafkaWebServicePushGroupId());
			props.put("enable.auto.commit", "false");
			props.put("key.deserializer", "org.apache.kafka.common.serialization.StringDeserializer");
			props.put("value.deserializer", "org.apache.kafka.common.serialization.StringDeserializer");
			props.put("max.poll.interval.ms", Integer.MAX_VALUE);
			props.put("auto.offset.reset", "earliest");
			props.put("max.poll.records", 5000);

**Comment by dpkp** [comment]
Those look like Java client properties. Are you using kafka-python?
