### ISSUE TITLE
Load default certs for SSL

### ISSUE THREAD

**Issue by 5tingray** [dpkp/kafka-python#1795]
Hi there,

I'm using a valid SSL certificate signed by Amazon for my Kafka connection and I made the following change to conn.py to pull in the default CA database if the user is validating the hostname but did not provide a CA cert.

```
[line 462 kafka/conn.py]
    if self.config['ssl_cafile']:
        log.info('%s: Loading SSL CA from %s', self, self.config['ssl_cafile'])
        self._ssl_context.load_verify_locations(self.config['ssl_cafile'])
        self._ssl_context.verify_mode = ssl.CERT_REQUIRED
+   if (not self.config['ssl_cafile']) and self.config['ssl_check_hostname']:
+      self._ssl_context.load_default_certs()
```
I would like to propose this change to allow users to use valid certs. Thanks!

**Comment by dpkp** [comment]
Sounds good. Do you know how to submit a PR?
