### ISSUE TITLE
consumer log: Auto offset commit failed 

### ISSUE THREAD

**Issue by gjysm** [dpkp/kafka-python#1797]
I am implementing kafka-python consumer class to receive messages. There are 10 consumers in a group to consume 50 partitions. Everything was normal when consumers started. But sometimes latter, some consumers start printing log: 
09:49:13,218  kafka/coordinator/consumer.py[line:787] WARNING Auto offset commit failed for group video-upload-service: CommitFailedError: Commit cannot be completed since the group has already
09:49:18,278  kafka/coordinator/consumer.py[line:787] WARNING Auto offset commit failed for group video-upload-service: CommitFailedError: Commit cannot be completed since the group has already
09:49:23,401  kafka/coordinator/consumer.py[line:787] WARNING Auto offset commit failed for group video-upload-service: CommitFailedError: Commit cannot be completed since the group has already
09:49:28,436  kafka/coordinator/consumer.py[line:787] WARNING Auto offset commit failed for group video-upload-service: CommitFailedError: Commit cannot be completed since the group has already
09:49:33,410  kafka/coordinator/consumer.py[line:787] WARNING Auto offset commit failed for group video-upload-service: CommitFailedError: Commit cannot be completed since the group has already
09:49:38,589  kafka/coordinator/consumer.py[line:787] WARNING Auto offset commit failed for group video-upload-service: CommitFailedError: Commit cannot be completed since the group has already
09:49:43,628  kafka/coordinator/consumer.py[line:787] WARNING Auto offset commit failed for group video-upload-service: CommitFailedError: Commit cannot be completed since the group has already

At the same time, these consumers are still consuming, but the partitions which these consumers consume have be rebalanced to other consumers.

eg:
At the beginning:
partition1   -->  consumer1
partition2   -->  consumer1
partition3   -->  consumer2
partition4   -->  consumer2
partition5   -->  consumer3
partition6   -->  consumer3
some times latter consumer2 auto offset commit failed, and then kafka server rebanced:
partition1   -->  consumer1
partition2   -->  consumer1
partition3   -->  consumer1
partition4   -->  consumer3
partition5   -->  consumer3
partition6   -->  consumer3
but consumer2 still consume partition3 and partition4, at the same time, consumer1 is consuming partition1~3 and consumer3 is consuming partition4~6. 

my clinet:
consumer = KafkaConsumer(
        topic, bootstrap_servers=bootstrap_servers, group_id=group_id, client_id=client_id,
        auto_commit_interval_ms=5000,
        session_timeout_ms=30000, request_timeout_ms=40000, max_poll_records=50,
        value_deserializer=value_deserializer,
    )

**Comment by jeffwidman** [comment]
These consumers have rebalanced... what you're reading is just the rest of the existing batch that's already been fetched client side. When you next call `poll()` it should reset itself (although possibly trigger other consumers to change their partitions)
