### ISSUE TITLE
Consumer poll() skips messages when using timeout_ms option

### ISSUE THREAD

**Issue by miteshvp** [dpkp/kafka-python#1802]
I want to consume messages in a consumer group from the last committed offset.
Consumer poll() works as expected if atleast one consumer is already up and running before producer sends any message. Problem arises if all the consumers in a particular group are dead or inactive, and producer is still pushing messages. During the next consumer start up or poll(), consumer does not pick those messages but it starts polling from the newest message produced by the producer.
I am using `auto_offset_reset=latest`,  `auto_commit_interval_ms=1000` and `enable_auto_commit=True`.
Is there any wrong configurations?
Producer Snippet
```
producer = KafkaProducer(bootstrap_servers='localhost:9092', client_id='some-id')
while True:
    producer.send('some-topic', value='some-message').get()
```

Consumer Snippet
```
consumer = KafkaConsumer(bootstrap_servers='localhost:9092', group_id='group-1')
consumer.subscribe(topics=['some-topic'], listener=ConsumerRebalanceListener())
consumer.poll(timeout_ms=5000)

for msg in consumer:
    print(msg.value)
```

UPDATED Consumer Snippet works without any timeout_ms. I am confused as to why such behaviour? Can someone please help me understand?
```
consumer = KafkaConsumer(bootstrap_servers='localhost:9092', group_id='group-1')
consumer.subscribe(topics=['some-topic'], listener=ConsumerRebalanceListener())
consumer.poll()

for msg in consumer:
    print(msg.value)
```

**Comment by dpkp** [comment]
I would recommend `auto_offset_reset=earliest` for this configuration. If you choose `latest` you are requesting that the consumers restart at the newest message produced by the producer whenever consumers cannot find or use a previously committed offset.

**Comment by miteshvp** [comment]
Sorry for being naive here, but would not `auto_offset_reset=earliest` picks from the first offset all the times?

**Comment by jeffwidman** [comment]
`auto_offset_reset` only gets applied if there is no known valid offset. So if you have a previously committed offset that is still valid (ie, topic retention policies haven't deleted it under your feet) then that should be used by your consumers.

Can you try the following sequence:
1. consume
2. commit
3. kill your consumers
4. as soon as the consumer group has no listed members (empty), then produce a few messages
5. start a consumer in the group and see where it picks up. This needs to happen before the old offset becomes invalid or gets expired/deleted.

Let us know what happens?

**Comment by miteshvp** [comment]
Thanks a lot to clear my confusion. Yes, it works as expected using `auto_offset_reset=earliest`. Closing this issue.
