### ISSUE TITLE
how to override default config in the file kafka.py

### ISSUE THREAD

**Issue by viveksinghggits** [dpkp/kafka-python#1818]
How can we modify the default values that are there for DEFAULT_CONFIG of 

```
'sasl_mechanism': None,
'sasl_plain_username': None,
'sasl_plain_password': None,
```
Thee kafka cluster that I am access is secure through SASL, PLAIN using below configuration

```
security.inter.broker.protocol=SASL_PLAINTEXT
sasl.mechanism.inter.broker.protocol=PLAIN
sasl.enabled.mechanisms=PLAIN
```

https://github.com/dpkp/kafka-python/blob/cee4d17df7858439e0dbdf3914ca0107e080af7d/kafka/producer/kafka.py#L287

**Comment by dpkp** [comment]
Docs are available here: https://kafka-python.readthedocs.io/en/master/

TLDR: pass config options to `KafkaProducer(sasl_mechanism='PLAIN')`
