### ISSUE TITLE
how can i get all ACLs using kafka-python

### ISSUE THREAD

**Issue by pnenov** [dpkp/kafka-python#1819]
how can i get all existing ACLs using kafka-python ?

**Comment by jeffwidman** [comment]
See https://github.com/dpkp/kafka-python/issues/1638

We'd welcome PR's!

**Comment by pnenov** [comment]
this is not the answer i expected !

following the link you gave above, i found a bunch of empty talks only

**Comment by pnenov** [comment]
kafka/admin/client.py

453    # describe_acls protocol not yet implemented
    # Note: send the request to the least_loaded_node()

    # create_acls protocol not yet implemented
    # Note: send the request to the least_loaded_node()

    # delete_acls protocol not yet implemented
460    # Note: send the request to the least_loaded_node()


why dont you simply say that kafka-python CAN NOT process any ACL requests instead to test our patience !?

**Comment by jeffwidman** [comment]
This is a volunteer project. You are welcome to help out and improve things.

**Comment by hanischandrew** [comment]
For anyone interested in retrieving **_ALL_** ACLs from a cluster.

```

resource_pattern_filter_group = ResourcePatternFilter(
    resource_type=ResourceType.ANY,
    resource_name=None,
    pattern_type=ACLResourcePatternType.ANY,
)

acl_filter = ACLFilter(
    principal=None,
    host=None,
    operation=ACLOperation.ANY,
    permission_type=ACLPermissionType.ANY,
    resource_pattern=resource_pattern_filter_group,
)

existingAcls = admin.describe_acls(acl_filter)

for acl in  existingAcls:
    print(acl)
```
