### ISSUE TITLE
Send only works with sleep

### ISSUE THREAD

**Issue by shalev123d** [dpkp/kafka-python#1826]
Hi guys,

I'm only able to produce messages with using the sleep method after sending.

```
from kafka import KafkaConsumer,KafkaProducer
from time import sleep
value = 'TestValue'
topic = 'myTopic'
producer = KafkaProducer(bootstrap_servers='IP_ADDR')
result = producer.send(topic,value.encode())
sleep(0.05)
if result.is_done:
    print('Successfully sent \'' + value + '\' to topic ' + topic)
else:
    print('Erro r sending')
```

When I remove the 'sleep(0.05)' line, it doesn't work and prints 'Error sending'

Thank you!

**Comment by dpkp** [comment]
Have you tried .get() ?

**Comment by shalev123d** [comment]
I'm pretty new to Python, do you mind explaining a bit further?

**Comment by arerlend** [comment]
https://github.com/dpkp/kafka-python/blob/master/kafka/producer/future.py#L59

producer.send() returns a FutureRecordMetadata, where calling result.get() will wait for _produce_future to be set.  In other words, script execution will block until result.get() returns.

https://kafka-python.readthedocs.io/en/master/usage.html

**Comment by jianglijie** [comment]
I have the same problem. use result.get() means send message sync. how can I send async?

**Comment by jeffwidman** [comment]
Sending async is possible by just firing off messages w/o calling `get()`... they will be fired, it just might be a little while if it's buffered internally.

I'm going to close as the linked docs above (thanks @arerlend!) should be helpful, especially if you're familiar with the programming concept of futures.
