### ISSUE TITLE
No exception is thrown when producer is timing out (request_timeout_ms)

### ISSUE THREAD

**Issue by suri70** [dpkp/kafka-python#1827]
When we send lot of large messages (100KB message size) to kafka we noticed that we don't receive all the messages, but no exception has been thrown either. After enabling the INFO logging we see lot of WARNING like this 

WARNING:kafka.producer.record_accumulator:Produced messages to topic-partition TopicPartition(topic='suritest', partition=1) with base offset -1 and error KafkaTimeoutError: Batch for TopicPartition(topic='suritest', partition=1) containing 1 record(s) expired: 30 seconds have passed since last append.
WARNING:kafka.producer.record_accumulator:Expired 1 batches in accumulator
WARNING:kafka.producer.record_accumulator:Produced messages to topic-partition TopicPartition(topic='suritest', partition=1) with base offset -1 and error KafkaTimeoutError: Batch for TopicPartition(topic='suritest', partition=1) containing 1 record(s) expired: 30 seconds have passed since last append.
WARNING:kafka.producer.record_accumulator:Expired 1 batches in accumulator
WARNING:kafka.producer.record_accumulator:Produced messages to topic-partition TopicPartition(topic='suritest', partition=7) with base offset -1 and error KafkaTimeoutError: Batch for TopicPartition(topic='suritest', partition=7) containing 1 record(s) expired: 30 seconds have passed since last append.

After increasing the request_timeout_ms those WARNINGs are gone and all messages are received. 

Why are there no exceptions thrown when the producer request is timing out? It should throw an exception, right?

**Comment by dpkp** [comment]
The producer interface is asynchronous and returns futures. Errors are
delivered to the futures and can be accessed via .get(). Exceptions will be
raised there.

**Comment by jeffwidman** [comment]
A somewhat common pattern is to keep track of the futures in the main thread and do a `raise future.exception` or `raise future.result.exception` (depending on whether it's a producer future or client future)...
