### ISSUE TITLE
Auto commit warning and error messages in log even when we set enable_auto_commit=False

### ISSUE THREAD

**Issue by p2jindia** [dpkp/kafka-python#1834]
We are seeing errors and warnings related to auto commit in our application log even though we set enable_auto_commit=False explicitly. PFB some example logs messages.

Python 3.6.8
kafka-python    1.4.3

------------- Example 1 --------------

2019-06-04 01:45:15,974 WARNING _run_once (964) Heartbeat session expired, marking coordinator dead
2019-06-04 01:45:15,974 WARNING coordinator_dead (698) Marking the coordinator dead (node 1) for group services_tac_ks_cgcqirePrd: Heartbeat session expired.
2019-06-04 01:45:15,981 WARNING _commit_offsets_async_on_complete (782) Auto offset commit failed for group services_tac_ks_cgcqirePrd: NodeNotReadyError: 1
2019-06-04 01:45:15,982 INFO add_group_coordinator (353) Group coordinator for services_tac_ks_cgcqirePrd is BrokerMetadata(nodeId=1, host='eds-kafka-stg-001', port=9093, rack=None)
2019-06-04 01:45:15,982 INFO _handle_group_coordinator_response (676) Discovered coordinator 1 for group services_tac_ks_cgcqirePrd
2019-06-04 01:45:15,987 INFO <module> (129)  -- No messages available. Will sleep for 5 seconds and retry.
2019-06-04 01:45:15,987 INFO <module> (131)  -- The counter value is 342 --
2019-06-04 01:45:20,990 WARNING _commit_offsets_async_on_complete (782) Auto offset commit failed for group services_tac_ks_cgcqirePrd: CommitFailedError: Commit cannot be completed since the group has already
            rebalanced and assigned the partitions to another member.
            This means that the time between subsequent calls to poll()
            was longer than the configured max_poll_interval_ms, which
            typically implies that the poll loop is spending too much
            time message processing. You can address this either by
            increasing the rebalance timeout with max_poll_interval_ms,
            or by reducing the maximum size of batches returned in poll()
            with max_poll_records.

2019-06-04 01:45:20,993 ERROR _maybe_auto_commit_offsets_sync (526) Offset commit failed: This is likely to cause duplicate message delivery
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/kafka/coordinator/consumer.py", line 515, in _maybe_auto_commit_offsets_sync
    self.commit_offsets_sync(self._subscription.all_consumed_offsets())
  File "/usr/lib/python3.6/site-packages/kafka/coordinator/consumer.py", line 508, in commit_offsets_sync
    raise future.exception # pylint: disable-msg=raising-bad-type
kafka.errors.CommitFailedError: CommitFailedError: Commit cannot be completed since the group has already
            rebalanced and assigned the partitions to another member.
            This means that the time between subsequent calls to poll()
            was longer than the configured max_poll_interval_ms, which
            typically implies that the poll loop is spending too much
            time message processing. You can address this either by
            increasing the rebalance timeout with max_poll_interval_ms,
            or by reducing the maximum size of batches returned in poll()
            with max_poll_records.

------------- Example 2 --------------

019-06-04 07:49:54,257 WARNING _commit_offsets_async_on_complete (782) Auto offset commit failed for group services_tac_ks_cgcqirePrd: CommitFailedError: Commit cannot be completed since the group has already
            rebalanced and assigned the partitions to another member.
            This means that the time between subsequent calls to poll()
            was longer than the configured max_poll_interval_ms, which
            typically implies that the poll loop is spending too much
            time message processing. You can address this either by
            increasing the rebalance timeout with max_poll_interval_ms,
            or by reducing the maximum size of batches returned in poll()
            with max_poll_records.

**Comment by jeffwidman** [comment]
How do you instantiate your Consumers?

**Comment by jmilagroso** [comment]
same here

```
consumer = KafkaConsumer(
    # Kafka topic
    #env.get('KAFKA_TOPIC'),
    # Broker/server info
    bootstrap_servers=[env.get('KAFKA_BROKER')], 
    # Auto offset reset, what do we do when there is no initial offset or
    # current offset does not exists?
    # earliest: automatically reset the offset to the earliest offset
    # latest: automatically reset the offset to the latest offset
    auto_offset_reset=env.get('KAFKA_AUTO_OFFSET_RESET'), # value is 'earliest'
    # This makes sure that we won't lose any data in case of crash
    # We will commit data as soon as we are done processing
    enable_auto_commit=False,
    # Decodes raw bytes to JSON
    value_deserializer=lambda m: json.loads(m.decode('ascii')),
    # Kafka group id, need to specify as prerequisite of commit()
    group_id=env.get('KAFKA_GROUP_ID')
)

consumer.assign(
    [
        TopicPartition(
            env.get('KAFKA_TOPIC'), 
            i
        ) for i in [0]
    ]
)

for i in range(5):
    for message in consumer:
        print("=============================================")
        print(message.value['payload'])

        #consumer.commit({TopicPartition(env.get('KAFKA_TOPIC'), message.partition): OffsetAndMetadata(message.offset + 1, None)})
        consumer.commit()
        print("finished")
```

python 3.6.7
kafka 0.8/0.9

**Comment by jmilagroso** [comment]
@p2jindia @jeffwidman 

For now, I am tracking next offset, using consumer's `seek()` function before listing the messages.

But please, if we can fix this error above, would be of great help!

**Comment by jeffwidman** [comment]
Thanks, and sorry for the slow turnaround here. 

Some of this code paths internally have changed quite a bit since `1.4.3`... do you mind upgrading to the latest release of `1.4.7` to see if this is still happening?

**Comment by jeffwidman** [comment]
Nudge @jmilagroso / @p2jindia

**Comment by p2jindia** [comment]
Hi @jeffwidman 
Recently we are facing a lot of issues same as issue 
Heartbeat failed for group xxxWorker because it is rebalancing
#1418   
So thinking of upgrading to `2.0.0`. will try it out and update this thread. Thank you

**Comment by jeffwidman** [comment]
K, I'm going to close as this was against old code that has changed significantly... if you hit problems with the new version, please open a new issue instead of continuing this one.
