### ISSUE TITLE
How commit offset ?

### ISSUE THREAD

**Issue by Testudinate** [dpkp/kafka-python#1836]
Hello,

I am using this code

`parsed_topic_name = 'orderSummary'

    consumer = KafkaConsumer(parsed_topic_name, auto_offset_reset='earliest',
                             bootstrap_servers=['test:9092'],
                             value_deserializer=lambda x: loads(x.decode('utf-8'))
                             )
    timeout = 20
    max_len = 10
    res = []
    t1 = dt.now()
    while (dt.now()-t1).seconds < timeout or len(res) < max_len:
        msgs = consumer.poll()
        print(msgs)
        for v in msgs.values():
            res += v

    with vertica_python.connect(**conn_to) as conn_2:
        curs2 = conn_2.cursor()
        if res:
            curs2.executemany('''
                INSERT INTO stage.FS_Orders_from_kafka_2 (load_dtm,topic_name, partition_id, "offset", value)  
                VALUES (?, ?, ?, ?, ?)''', [(r.timestamp, r.topic, r.partition, r.offset, r.value) for r in res])
            curs2.execute('COMMIT')
        else:
            print('Nothing!')

    consumer.close()`

How to commit offset ?

**Comment by aswinjoseroy** [comment]
are you trying to commit your offsets in a separate DB called vertica? If so, I think you are looking for the query to save it to the DB. Please write this query in a thread or repo related to that DB maybe?

**Comment by jeffwidman** [comment]
If you want to use normal kafka commiting semantics, than `consumer.commit()` is probably what you're looking for. 

If you want to commit to Vertica, then you'll need to figure that out yourself as that's far beyond the scope of this library.

PS: Thanks @aswinjoseroy for chiming in here!
