### ISSUE TITLE
kafka client warning unable to send to wakeup socket (Endless loop)

### ISSUE THREAD

**Issue by liho00** [dpkp/kafka-python#1842]
I cannot force close my crawler, it trapped in an endless loop because kafka client warning unable to send to wakeup socket 

![Screenshot from 2019-06-10 17-01-51](https://user-images.githubusercontent.com/34411102/59184828-88a4ad80-8ba1-11e9-8752-1936b252ad49.png)

**Comment by dpkp** [comment]
I believe this is fixed in the latest release, 1.4.7.  Please reopen if the issue persists.

**Comment by Prometheus3375** [comment]
Have run into the same issue with version 2.0.1.
Attached log file. I stopped spider by killing its process.

[spider.log](https://github.com/dpkp/kafka-python/files/4864212/spider.log)

**Comment by shimon-armis** [comment]
We see a sort of that issue also with version 2.0.2.

**Comment by Prometheus3375** [comment]
@shimon-armis look mentioned issue for solution.

**Comment by shimon-armis** [comment]
@Prometheus3375 I actually saw it but I still wonder:
Why should we apply the a WA (as you suggested [here](https://github.com/dpkp/kafka-python/issues/2073#issuecomment-963024808)) for each and every consumer app, rather than handling it where it actually happens?

**Comment by Prometheus3375** [comment]
> as you suggested [here](https://github.com/dpkp/kafka-python/issues/2073#issuecomment-963024808)

That was another user, @NitroCao. Ask them for details in linked issue

There is a new kafka version on PyPI, `kafka-python3`. Probably there is no such problem.
