### ISSUE TITLE
Can't deal message for consumer use group_id

### ISSUE THREAD

**Issue by jianglijie** [dpkp/kafka-python#1843]
I run producer and consumer success when  the consumer without group_id .But after I add group_id for the consumer, it never print message, I can see the producer print message always

**Comment by jeffwidman** [comment]
Sorry, we can't really debug with this little info... Can you please provide example code as explained here: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by jianglijie** [comment]
thank you for your reply. I build the kafka and zookeeper environment in docker. It work well after I rebuild
