### ISSUE TITLE
test failure indicating legit problem

### ISSUE THREAD

**Issue by jeffwidman** [dpkp/kafka-python#1846]
https://travis-ci.org/dpkp/kafka-python/jobs/547927009

This appears to be a legit bug of some sort, unrelated to the actual PR. Dinnertime, so I don't have time to investigate so creating this ticket so I don't lose track of it.

cc @Baisang any ideas? Since you wrote this test, although my hunch is that the failure is unrelated to the test itself...

**Comment by jeffwidman** [comment]
Shoot, looks like restarting the job didn't create a new one, but instead overwrote the old one... my bad.

The reported problem was that a topic the test expected to exist wasn't returned by `topics()`.

**Comment by Baisang** [comment]
Was this introduced as part of https://github.com/dpkp/kafka-python/pull/1845 ? maybe we just forgot  to wait for a future in there or something.

**Comment by Baisang** [comment]
For reference, the test in question was introduced in https://github.com/dpkp/kafka-python/pull/1829

**Comment by jeffwidman** [comment]
I'd considered that, except that PR #1845 only touches the `KafkaAdminClient` which is currently completely untested... (I'm planning to add tests for it once #1193 is complete as that will greatly simplify the test harness.) 

So it wouldn't have affected it at all... 

I'm guessing it was some sort of race condition that rarely manifests, and I suspect the problem is in core, not in the test.

**Comment by jeffwidman** [comment]
Closing as unable to replicate for now.
