### ISSUE TITLE
TypeError: not enough arguments for format string

### ISSUE THREAD

**Issue by dmitry-moroz** [dpkp/kafka-python#1855]
This code causes error due to lack of arguments:
https://github.com/dpkp/kafka-python/blob/1.4.6/kafka/consumer/fetcher.py#L128
```
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not enough arguments for format string
```

**Comment by jeffwidman** [comment]
Hmm... an initial scan of the code looks like that final `%s` is populated by `self.exception` here: https://github.com/dpkp/kafka-python/blob/fb87a353d99b3271105d0941f39ee64bf2ab6858/kafka/future.py#L61

I haven't worked much with `functools.partial()`, so maybe I'm misunderstanding something?

**Comment by dmitry-moroz** [comment]
I have found problem in logger. This is not a problem of kafka-python. Issue can be closed.
