### ISSUE TITLE
producer of 1.4.2 memory leak

### ISSUE THREAD

**Issue by csbs** [dpkp/kafka-python#1862]
when I close KafkaProducer,  then gc.collect , KafkaClient and KafkaConnection is unreachable and uncollectable  

![image](https://user-images.githubusercontent.com/12590105/60794214-da8a2480-a19b-11e9-8c8d-6534f647f5d7.png)

```
def test(message):
     system_message_producer = KafkaProducer(bootstrap_servers=["192.168.190.172:9092","192.168.190.173:9092","192.168.190.171:9092"], linger_ms=1000,
                                               batch_size=500)
     for i in range(5):
          result = system_message_producer.send("xxx_message", json.dumps(message))
          result.get(10)

     system_message_producer.close()
     print id(system_message_producer._sender)
def main():

    message = {
        "type":"sys",
        "sub_type":"exception"
    }
    while True:

        test(message)
        print gc.collect()
        print "gc1", gc.garbage
        time.sleep(30)
```
refer to  kafkaClient is
![image](https://user-images.githubusercontent.com/12590105/60794285-06a5a580-a19c-11e9-8e67-4f147775c7e2.png)

then I modify  client_async.py  KafkaClient
```   
 def close(self, node_id=None):
        """Close one or all broker connections.

        Arguments:
            node_id (int, optional): the id of the node to close
        """
        with self._lock:
            if node_id is None:
                self._close()
                for conn in self._conns.values():
                    conn.close()
                self._conns = None
            elif node_id in self._conns:
                self._conns[node_id].close()
                self._conns = None
            else:
                log.warning("Node %s not found in current connection list; skipping", node_id)
                return
```
KafkaBrokerConnection is collected ， Client still can't be gc 

Python 2.7.5

**Comment by jeffwidman** [comment]
Can you try the latest version and see if this is still an issue? 

We have very limited volunteer hours so don't really have time to debug old versions and then see if the bug still applies in the current version... If you can test the latest version, then if it still exists happy to look further into it
