### ISSUE TITLE
Help : KafkaConsumer is too transparent when Broker fails

### ISSUE THREAD

**Issue by fc193** [dpkp/kafka-python#1863]
Hello,

I am using Kafkaconsumer to retrieve messages of a distant broker.
I successfully connect the broker and receive the messages.

I would like to be notified when the connection to the broker fails and when it is restored, so I can raise an alarm to final user.

how can I achieve this ?

BR,
Franck.

**Comment by jeffwidman** [comment]
From a code perspective, this should be somewhat transparently handled under the covers.

However, it will be emitted as an event to the logs so you could scrape those and generate alerts... most logging infra tools should support this.
