### ISSUE TITLE
kafkaConsumer hangs when use gevent worker with gunicorn

### ISSUE THREAD

**Issue by mohammedvaghjipurwala** [dpkp/kafka-python#1866]
> Use Case : I want consumer to run Continuously even if no data is being sent to the topic for few days.

I am using kafka-python 1.4.6, Tech stack used is Gunicorn with gevent worker with Flask and kafka-python.
my consumer becomes dead/idle and cannot receive messages.

```
Below is the consumer

consumer = KafkaConsumer(
            topic,
            group_id='grp_id',
            bootstrap_servers=['broker_list'],
            enable_auto_commit=False,
            auto_offset_reset=earliest,
            consumer_timeout_ms=float('inf'),
            max_poll_interval_ms=300000,
            max_poll_records=3,
            session_timeout_ms=9000
            )
```

**Comment by mohammedvaghjipurwala** [comment]
I have tried using the solution provided in the issue # [1687](https://github.com/dpkp/kafka-python/issues/1687).
But still facing the same issue.
please help.

**Comment by jeffwidman** [comment]
Can you try this under `1.4.7`?

**Comment by mohammedvaghjipurwala** [comment]
@jeffwidman  Thanks For the Solution. Upgrading to 1.4.7 worked. However, It introduced a new issue.

> Issue: When I try creating more than three or more consumers in a Container/Pod, It gives "NoBrokersAvailable" error.  Even this error is occurring for the producer object.

Can you please help.

**Comment by thirupala-infinote** [comment]
I am getting  issue even under 1.4.7 while starting the consumer worker inside the gunicorn:
consumer = KafkaConsumer(bootstrap_servers=config.kafka_brokers_list,\
                     group_id=config.kafka_consumer_group, enable_auto_commit=config.kafka_enable_auto_commit,\
                     auto_offset_reset=config.kafa_auto_offset_reset)
    worker = Worker(topic=config.kafka_topic_name, consumer=consumer, callback=callback, deserializer=deserializer)
    worker.start()


can some one help me , thanks in advance

**Comment by dpkp** [comment]
See discussion in #1867 for advice on how to do gevent monkeypatching for kafka-python.
