### ISSUE TITLE
KafkaClient returns no topics on 1.4.5+

### ISSUE THREAD

**Issue by andystanley** [dpkp/kafka-python#1868]
I'm upgrading from `1.4.4` to `1.4.6` and `KafkaClient` on `1.4.5` and `1.4.6` is returning an empty set of topics.
```
from kafka.client_async import KafkaClient

client_config = {
    'bootstrap_servers': 'servers',
    'api_version': (2, 0)
}
kafka_client = KafkaClient(**client_config)

assert len(kafka_client.cluster.topics()) > 0
# 1.4.4 True
# 1.4.5 False
# 1.4.6 False
```

Any idea what could be causing the discrepancy? Thanks!

**Comment by Baisang** [comment]
See https://github.com/dpkp/kafka-python/issues/1873, I think it will get fixed in 1.4.7 but you can cherry-pick the two commits I mentioned in that stream to a fork for now. Or just call e.g. `kafka_consumer.topics()` to force it to make a blocking metadata call before using partitions_for_topic
