### ISSUE TITLE
Delay in receiving messages after network block

### ISSUE THREAD

**Issue by raveendrahegde** [dpkp/kafka-python#1870]
I am trying to cover a scenario where if the network is down and the consumer has to start receiving messages after the network is back online. Although the consumer seems to receive the message after the network is back, there is a long (in minutes) delay in receiving messages. Some of the messages are not even received. It works fine if the network is not interrupted. Can someone help me to understand what I am doing wrong? 

I am using kafka-python==1.4.4

Code snippet:

```
def run(self):
    consumer = KafkaConsumer(bootstrap_servers=self.server,
                             sasl_mechanism="PLAIN",
                             security_protocol="SASL_PLAINTEXT",
                             sasl_plain_username=self.username,
                             sasl_plain_password=self.password,
                             group_id=self.group_id,
                             auto_offset_reset='latest',
                             consumer_timeout_ms=10000,
                             api_version=(0, 10)
                             )
    consumer.subscribe(self.topics)

    while True:
        try:
            for message in consumer:
                try:
                    process_message(message)
                except Exception:
                    print('Unable to consume the message.')

        except TimeoutError:
            print('Consumer Timed Out.')
```

**Comment by jeffwidman** [comment]
Can you try this with `1.4.7`? There were a number of changes to the networking stack, including fixing some hanging problems caused by network disconnects (under a particular race scenario).

**Comment by raveendrahegde** [comment]
No longer working on this, so closing the issue hoping it is resolved in the later version.
