### ISSUE TITLE
Kafka shutdown __del__ log issue

### ISSUE THREAD

**Issue by danncoba** [dpkp/kafka-python#1872]
I've read couple of issues regarding this bug in these discussions, and i've seen that there is resolved and closed issue in march/april 2018 regarding this, but it's still happening to me using pip.

I'm using pip kafka-python package version 1.4.6 and there is still __del__ log issue when shutting down application aldo i've found here that complete __del__ method was erased

Could you please help me with this

**Comment by dpkp** [comment]
Can you explain the behavior you are seeing, the behavior you are expecting, and the impact?

**Comment by Guanpx** [comment]
You mean that log info looks like “Closing the Kafka producer with 0 secs timeout.” ？？？
