### ISSUE TITLE
Writing data using KafkaProducer is too slow? It's only 5000  record/s

### ISSUE THREAD

**Issue by nohunt** [dpkp/kafka-python#1877]
Environmental configuration：
kafka-python version:1.4.6
Memory：256G
kafka version:2.11

Problem Description：
I use kafka's own tools（kafka-console-consumer.sh）to import more than 5 million data from files. It takes less than a minute.

It took me a long time to use KafkaProducer.Here are some examples
```
producer = KafkaProducer(bootstrap_servers = ['%s:%d'%(ip,port)],buffer_memory=67108864,batch_size=2097152,max_request_size=5242880,send_buffer_bytes=131072,compression_type='gzip')
with open(path) as rf:
    for line in rf.readlines():
        producer.send("test", line.encode('utf-8'))
```

**Comment by nohunt** [comment]
I use Java very quickly for the same function, but I want to use Python

I searched for issues and found problems similar to mine, so I returned the version to 1.3.5. The problem was still unresolved.

**Comment by jeffwidman** [comment]
What was the code you used to produce using the `kafka-console-producer.sh`? For example, did you use `gzip`?

**Comment by dpkp** [comment]
One useful tool I've found for debugging performance issues is https://github.com/evanhempel/python-flamegraph

Try to get a flamegraph of your usecase and see if you can find a codepath that looks like it could be optimized or improved.

**Comment by jeffwidman** [comment]
Closing as there's nothing we can do here without more info.
