### ISSUE TITLE
Multiple Brokers, Single Machine

### ISSUE THREAD

**Issue by kenrubiooo** [dpkp/kafka-python#1878]
Hi,

I am trying to understand how multiple brokers work in a single machine. Imagine that I have 2 brokers. I have the first script which produces an image, the second script to process the image, and a third script to show the image. I have an understanding that what broker 1 (B1), broker 2 (B2) will also have. So, if I send the image to B1 and wants to get the image from B2 for processing, then get the processed image for showing through B1 again. Where do I configure the broker connection such that I know that the two brokers are sharing information?

Thank you!

**Comment by georgepsarakis** [comment]
You can use [this Docker Compose file](https://github.com/simplesteph/kafka-stack-docker-compose/blob/master/zk-single-kafka-multiple.yml) in order to try a multiple Broker setup.

As far as I understand configuring multiple brokers means that topic partitions are distributed among them. The cluster configuration would help more with scaling (large partition number per topic) and fault-tolerance (if each broker is started on a different machine).

Some related articles:
- https://www.confluent.io/blog/how-choose-number-topics-partitions-kafka-cluster
- https://sookocheff.com/post/kafka/kafka-in-a-nutshell/#partitions-and-brokers

**Comment by kenrubiooo** [comment]
> You can use [this Docker Compose file](https://github.com/simplesteph/kafka-stack-docker-compose/blob/master/zk-single-kafka-multiple.yml) in order to try a multiple Broker setup.
> 
> As far as I understand configuring multiple brokers means that topic partitions are distributed among them. The cluster configuration would help more with scaling (large partition number per topic) and fault-tolerance (if each broker is started on a different machine).
> 
> Some related articles:
> 
> * https://www.confluent.io/blog/how-choose-number-topics-partitions-kafka-cluster
> * https://sookocheff.com/post/kafka/kafka-in-a-nutshell/#partitions-and-brokers

Thank you, @georgepsarakis!

I am having a hard time doing multi-brokers using Docker, with the environment parameter and all. Hope this will help answer my problem. Thank you again!

**Comment by kenrubiooo** [comment]
Hi @georgepsarakis,

I am still unable to pass the information from broker 1 to broker 2. I send the image to B1 and plans to get the image from B2 for processing, that is, the topic (T1) from B1 should be replicated to B2, then the processing script sends the processed data to B2 using a different topic (T2), afterwards T2 should be replicated to B1, then the show script gets the processed image from T2 of B1.

This is how I understand multi-broker kafka. That even if the information is not passed to broker 1 directly, the consumer will still be able to get the information from broker 2 where the information was replicated.

Am I understanding this correctly?

**Comment by georgepsarakis** [comment]
I am not an expert and not sure what you mean by passing information between brokers. As far as I understand, clients do not need to be aware of the cluster topology, as can be seen in the documentation for the client connection settings (see [bootstrap_servers](https://kafka-python.readthedocs.io/en/master/apidoc/KafkaClient.html?highlight=bootstrap_servers)). Thus you do not have to connect to each broker separately.

**Comment by jeffwidman** [comment]
This is a question about how to setup/run a multi-node Kafka cluster, not about this library. So StackOverflow or the Kafka Users email list is probably a better fit.
