### ISSUE TITLE
Help: Consumer has not stopped after rebalance

### ISSUE THREAD

**Issue by Lywane** [dpkp/kafka-python#1880]
My topic owns 1 partition.I have one group which owns two consumers. When I start the first consumer, it can work normally, then I start the second consumer. I want watching rebalance happen and one of two consumers block and another consume. But now both them consume.

group: "my-group"
topicName: "my-test"
partitions: 1
kafka: 2.0.1
kafka-python: 1.4.6

**Comment by dpkp** [comment]
I'm not able to reproduce this. Can you provide any more details and/or reproducible scripts?
