### ISSUE TITLE
Is it possible to merge two topics? 

### ISSUE THREAD

**Issue by sungreong** [dpkp/kafka-python#1881]
Hello, I have a question. 
For example, i have three topics. One topic role is consumer.
And the others role is producer.
Consumer subscribe a message and the others are going to process it individually. 
And send to producer.
So i want to merge the others topic.
How to merge it?

**Comment by jeffwidman** [comment]
I'm sorry, I don't understand what you're asking.

Can you provide some example code or a rough drawing outlining what you're trying to do?
