### ISSUE TITLE
Support for sasl mechanism: SCRAM-SHA-256

### ISSUE THREAD

**Issue by mlepicka** [dpkp/kafka-python#1882]
Is there any chance for having SCRAM-SHA-256 mechanism supported in kafka-python?

**Comment by akki** [comment]
+1

**Comment by jeffwidman** [comment]
We'd be more than happy to review a PR adding this. AFAIK, none of the current maintainers work much with Kafka clusters using SASL, so unlikely to be added by any of us.

**Comment by Neustradamus** [comment]
It is has been added here:
- https://github.com/dpkp/kafka-python/pull/1918
