### ISSUE TITLE
Help: can‘t get data from kafka 2.0.0

### ISSUE THREAD

**Issue by qishengle** [dpkp/kafka-python#1884]
the consumer can connet with kafka 2.0， but cannot get any data from it

**Comment by qishengle** [comment]
the consumer can connet with kafka 2.0， but cannot get any data from  it

**Comment by wangzhe3224** [comment]
any news?

**Comment by jeffwidman** [comment]
Can you provide the example code you're using to try to consume?

With this little data, there's pretty much nothing to go on

**Comment by qishengle** [comment]
from kafka import KafkaProducer
from kafka import KafkaConsumer

consumer = KafkaConsumer(bootstrap_servers=['10.20.1.101:9092','10.20.1.107:9092','10.20.1.109:9092'], group_id="sms1sp",
                         auto_offset_reset='latest', enable_auto_commit=True)
consumer.subscribe(["test"])

if __name__ == "__main__":
    for message in consumer:
        print(message.value)

**Comment by dpkp** [comment]
What happens when you run this code that you do not expect and what do you
expect to happen that isn't?

**Comment by qishengle** [comment]
When the kafka cluster is version 0.10, this code works normally, and I can get data from it; but when the version is upgraded to 2.0, the consumer progress can't read the data (the program has no error message; there is data in kafka)

**Comment by dpkp** [comment]
I'm not able to reproduce this locally -- my consumer is able to consume from a 2.0.0 cluster as expected.

Do you have any additional information? Can you provide debug logs?

**Comment by qishengle** [comment]
sorry, there is noo log output. My development environment is centos7+python2.7. The gateway may have some problems. But
