### ISSUE TITLE
KafkaAdminClient.list_consumer_groups() is slow

### ISSUE THREAD

**Issue by nbommu1** [dpkp/kafka-python#1889]
similar issue has been fixed in single node broker #1798, issue still exist in cluster.

Single node broker:

```
from kafka.admin.client import KafkaAdminClient
import time
admin_client = KafkaAdminClient(bootstrap_servers='127.0.0.1')
start = time.time()
print(len(admin_client.list_consumer_groups()))
end = time.time()
print(end-start)
```
Single node 

12
0.000765085220337

Cluster
12
60.0666730404

**Comment by nbommu1** [comment]
this works perfect!

in the cluster

```
from kafka.admin.client import KafkaAdminClient
import time
admin_client = KafkaAdminClient(bootstrap_servers='127.0.0.1', request_timeout_ms=300)
start = time.time()
print(len(admin_client.list_consumer_groups()))
end = time.time()
print(end-start)
```
0.608502149582

**Comment by jeffwidman** [comment]
I think this is likely a problem where one of your brokers is not responding quickly enough, so it causes the client to hang waiting for a response from that broker.
