### ISSUE TITLE
kafka connection storm

### ISSUE THREAD

**Issue by Pushking4real** [dpkp/kafka-python#1892]
when our kafka cluster disk is full,it rejected the request from kafka-python client.And later it create an connection storm which break down our firewall  with version1.3.4.  Why the client create so many syn connection?Can i upgrade it to version1.4.0 to solve the problem?

**Comment by dpkp** [comment]
I wrote and implemented KIP-144 for this purpose. Please take a look at the various configuration values available, including `reconnect_backoff_max_ms`

```
reconnect_backoff_max_ms (int) – The maximum amount of time in milliseconds to wait when reconnecting to a broker that has repeatedly failed to connect. If provided, the backoff per host will increase exponentially for each consecutive connection failure, up to this maximum. To avoid connection storms, a randomization factor of 0.2 will be applied to the backoff resulting in a random range between 20% below and 20% above the computed value. Default: 1000.
```
