### ISSUE TITLE
KafkaConsumer dropping messages at random

### ISSUE THREAD

**Issue by Matshakan** [dpkp/kafka-python#1893]
This code is more or less taken from the README and has issues:
```
consumer = KafkaConsumer('testx',bootstrap_servers='192.168.99.100:9092',group_id='my-group',auto_offset_reset = 'latest')
for message in consumer:
    print (message)

```
I tested it with a **KafkaProducer** generating one message at a time concurrently. Works fine for a random number of messages and then freezes. When i restart the **KafkaConsume**r program with the above code the previously sent messages from the producer shows up. Then the **KafkaProducer** works for a while and gets all grumpy again. I found this post describing somewhat the same problem I have. [A tale of two Kafka Clients](https://blog.datasyndrome.com/a-tale-of-two-kafka-clients-c613efab49df)

Hopefully it´s me being stupid.

**Comment by dpkp** [comment]
The autocommit interval is 5 seconds by default so I would expect a restarted consumer to receive duplicate / previously processed messages up to that amount of time.

If this doesn't sound like the issue you are having, feel free to post a script that I could use to reproduce your error.
