### ISSUE TITLE
How can I continue to get message from kafka after session timeout?

### ISSUE THREAD

**Issue by just-OneKey** [dpkp/kafka-python#1900]
I built one kafka queue, which has only one topic and one partition.
My producers will push message in it irregularly. And usually it pushed lots of messages at one time.
Then, consumers start to consume those messages. But the speed of consuming is not certain. In some case, therefore, time of consuming message will be larger than 'consumer.session_timeout_ms'.
When this happens, consumer cannot poll any message from broker. How can I get original offset to continue to consume the rest messages?

Here is some code
producer:
![image](https://user-images.githubusercontent.com/42026869/64681307-0c787980-d4b2-11e9-801e-bb580eede70a.png)
consumer:
manually assign:
![image](https://user-images.githubusercontent.com/42026869/64681575-8b6db200-d4b2-11e9-951d-bbca0c172e08.png)

modified process
![image](https://user-images.githubusercontent.com/42026869/64681602-9aecfb00-d4b2-11e9-8098-534627b406d8.png)

**Comment by jeffwidman** [comment]
If you are using `assign()` then the consumer's session timeout won't actually matter as the Kafka consumer group balancing/HA features wont be used.

Closing, as this isn't a bug in the library, but rather a misunderstanding of how Kafka consumer groups work.
