### ISSUE TITLE
Why can't I get the correct function return?

### ISSUE THREAD

**Issue by just-OneKey** [dpkp/kafka-python#1901]
Hi, my kafka consumer does not seem to get any message from kafka broker.
Then, I got beginning, current and end offset of the queue. But I find that those offsets which return from funstions(beginning_offsets(), position(),end_offsets()) did not match the actual situation.

Here is the status of my queue:
`TOPIC       PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG         CONSUMER-ID HOST        CLIENT-ID`
`taskQueue       0          62211           62276           65              -               -               -`
But at the same time, offset I got is:
`begin offset:{TopicPartition(topic='taskQueue', partition=0): 62276}`
`current offset:62277`
`end offset:{TopicPartition(topic='taskQueue', partition=0): 62276}`

What's the problem?
How can I get the correct return and poll the true message?

**Comment by jeffwidman** [comment]
Hmm... the only thing that looks amiss is the beginning offset. The current offset that's committed to the broker is not guaranteed to match the current offset in the client... ie, the client may be a lot further along but not yet have committed it's offset back to the broker.

Can you provide example code of how you instantiate teh consumer and then call poll and then beginning offset?
