### ISSUE TITLE
polling time wile using consumer iterator interface

### ISSUE THREAD

**Issue by mirko0x5f** [dpkp/kafka-python#1905]
Hello,  
I'm pretty new to kafka-python, I'm currently using the kafka-python consumer with the iterator interface.  
I'm trying to understand if there is a way to change the time between poll() calls while using the iterator interface, or if this time is influenced by any setting in the consumer initialization. Can someone help?  
Thank you in advance!

**Comment by dpkp** [comment]
I am going to land a large change to the iterator interface for the upcoming 1.4.7 release. With that change you can set `consumer_timeout_ms` to alter the timeout passed to `poll()` and use `max_poll_records` to set the maximum number of records to process via iteration between calls to poll(). So, for example, if your iteration process takes 1 second to process a single message (obviously unlikely, but it's a round number) and you set max_poll_records=10 then you should expect that consumer.poll() will be called once every 10 seconds during iteration. Does that make sense? See #1902

**Comment by mirko0x5f** [comment]
That makes sense, thank you for your work!
