### ISSUE TITLE
The Source is conflict with doc for KafkaClient and SimpleClient

### ISSUE THREAD

**Issue by kingname** [dpkp/kafka-python#1910]
in Source Code of `kafka/__init__.py`：

```python
class KafkaClient(SimpleClient):
    def __init__(self, *args, **kwargs):
        warnings.warn('The legacy KafkaClient interface has been moved to'
                      ' kafka.SimpleClient - this import will break in a'
                      ' future release', DeprecationWarning)
        super(KafkaClient, self).__init__(*args, **kwargs)
```

the code tells me that I should use `kafka.SimpleClient`. 

However, in the doc: https://kafka-python.readthedocs.io/en/master/simple.html

it tells me that the `SimpleClient` is `DEPRECATED`:

![image](https://user-images.githubusercontent.com/5440523/65825624-c130da00-e2ab-11e9-82a3-abc54a5e320d.png)

so what should I use??

**Comment by Baisang** [comment]
You probably want to use either the high level [KafkaConsumer](https://kafka-python.readthedocs.io/en/master/apidoc/KafkaConsumer.html) or [KafkaProducer](https://kafka-python.readthedocs.io/en/master/apidoc/KafkaProducer.html) APIs, which use the new `KafkaClient` (https://github.com/dpkp/kafka-python/blob/master/kafka/client_async.py#L43)

**Comment by kingname** [comment]
no, I want to use KafkaClient to create topic instead of sending datas to some exists topic.

**Comment by Baisang** [comment]
If you want to create topics, I think you probably want to use the KafkaAdminClient https://github.com/dpkp/kafka-python/blob/master/kafka/admin/client.py#L415

**Comment by kingname** [comment]
Yes. I do use it.

but why don't they recorrect the conflict?

**Comment by dpkp** [comment]
The library is still supporting an old interface that was generally
prefixed with Simple* . Unfortunately the old client interface did not
follow that pattern and was called just KafkaClient. We renamed the class
to SimpleClient, but to avoid breaking any existing users we continue to
support the original name. This compatibility is scheduled to be removed in
the 2.0 release.

**Comment by kingname** [comment]
thanks
