### ISSUE TITLE
unable to connect to remote kafka server

### ISSUE THREAD

**Issue by harun86** [dpkp/kafka-python#1913]
SERVER:-
=======
i have installed kafka 2.1.1 on centos-7 server IP(192.168.3.120)
config/server.properties
listeners=PLAINTEXT://192.168.3.120:9092
advertised.listeners=PLAINTEXT://192.168.3.120:9092
firewall disabled

CLIENT:- (Centos-7 and IP-192.168.3.121)
=========
from kafka import KafkaProducer
producer = KafkaProducer(bootstrap_servers='192.168.3.120:9092')

client not able to send message to kafka broker.
kafka.errors.NoBrokersAvailable: NoBrokersAvailable

Please Help Me.

**Comment by dpkp** [comment]
This seems like a simple networking issue. Double check that you are able to connect to your kafka cluster: `telnet 192.168.3.120 9092` . Does that connect? If not, you will need to adjust your networking setup.

**Comment by Athuliva** [comment]
```
Trying 192.168.1.100...
Connected to 192.168.1.100.
Escape character is '^]'.



Connection closed by foreign host.

```
kafka-python installed in a jetson nano is not working. In other systems its working.
