### ISSUE TITLE
Problem to Publish topic in one machine and subscribe same topic on another Kafka server machine

### ISSUE THREAD

**Issue by rohitsingh23july1986** [dpkp/kafka-python#1919]
Hi
Subject : data sending problem from one machine to another machine using Kafka python

Dear ,

We are facing problem when we send one topic data from one machine to another (Kafka server) ,
Actually my requirement is create topic in one machine send this topic via Kafka producer in another Kafka server

When we create topic and send this topic on same machine then we are able to subscribe this topic on same machine

But as per my requirement when we send this topic from one machine to another Kafka server then we are not able to subscribe this topic and when we try to send this topic then only topic name is showing in lenses GUI tool,but inside this topic no data is comming

Please provide me dummy code. In Kafka python  and other file setting which is required for solving this problem

We are suffering this problem since from last week
We also take help from Kafka forum
But are not successful to solve this problem 

Please help to solve this problem
And send one dummy code in python Kafka and other setting which is required to solve this problem

We are using CentOS operating system

**Comment by dpkp** [comment]
This sounds like a networking problem. I'd suggest enabling DEBUG logs and
checking the connection traces / errors. Could be your dns or your ip
routing.

**Comment by rohitsingh23july1986** [comment]
I already checked,this is not network problem

**Comment by rohitsingh23july1986** [comment]
I produce data from server A and consume data from Server B using python script
But consumer from server B not able to consume data
Both server A and server B kafka

**Comment by 123nishant** [comment]
Also, great work on the library !!
