### ISSUE TITLE
Is it possible to run interactive queries using kafka-python?

### ISSUE THREAD

**Issue by elmehalawi** [dpkp/kafka-python#1922]
Confluent has [these 'interactive queries'](https://docs.confluent.io/current/streams/developer-guide/interactive-queries.html) that allow one to query the local state store.

Can I do this with kafka-python? If not, is there a recommended alternative?

**Comment by dpkp** [comment]
I haven't used that feature directly, but, based on a quick read of the
confluent webpage you linked, I think that this is just a query for
consumer group metadata that can be stored along with offsets. Try
KafkaAdminClient.list_consumer_group_offsets and look at the `.metadata`
attribute. If you are querying the state of a Kafka Streams application
then you would also need to know how to decode the metadata, which will
likely be given to you as opaque bytes that represent some serialized data
structure. Good luck and report back what you find!

**Comment by jeffwidman** [comment]
Metadata can now be queried using the `KafkaAdminClient` for a number of things. 

As far as the actual messages, you'd need to run a consumer.

For doing aggregates on the data like Kafka streams, well, we don't have that. You might try https://github.com/robinhood/faust although I haven't personally played with it.
