### ISSUE TITLE
KafkaAdminClient:  cannot pin version

### ISSUE THREAD

**Issue by simpleistao** [dpkp/kafka-python#1924]
I cannot set "api_version"  for the KafkaAdminClient.   

when api_version is not set, it would say, 
"Broker version identified as 1.0.0.  Set configuration api_version=(1,0,0) to skip auto check..."

So I tried to set "api_version: (1,0,0)" in the config.  It would say, 

Error message is:
IncompatibleBrokerVersion: Kafka Broker does  not support the "MetadataRequest_v0" Kafka protocol.  (this is from __matching_api_version()  <==   refresh_controller_id()  in admin/client.py)

I started it pdb, and see that broker_api_versions returned is none (see attached screenshot). 

I tried setting it to many other versions it would not work.  However, I tried the same config for a consumer, and it would connect (but looks like it does not need to call __matching_api_version()).    Could you please help?

Background:
1.  The only reason I want to pin the version is because I need to make sure I am parsing DescribeConfigResponse correctly, so I would like to pin to version.   Please let me know if there is alternative.

2.  Kafka cluster version  2.3.0.  
3.  kafka-python version 1.4.7

![IMG_20191009_235325](https://user-images.githubusercontent.com/42440018/66537901-2d071400-eaf0-11e9-8c93-5207b653f4bc.jpg)

**Comment by ian28223** [comment]
made a PR about it but not getting traction. See if you can patch yours and test 
https://github.com/dpkp/kafka-python/pull/1953

**Comment by GarrettHoffman** [comment]
+1

**Comment by jeffwidman** [comment]
I think this is fixed by #1953 which landed in the recent 2.0 release.
