### ISSUE TITLE
1.4.7 not backwards compatible: parameter changed

### ISSUE THREAD

**Issue by DieterDePaepe** [dpkp/kafka-python#1930]
In 1.4.6, one of the consumer parameters was `max_poll_record`:

```python
kafka.KafkaConsumer(max_poll_record=100)
```

In 1.4.7, it seems this was changed to `max_poll_records`, thereby breaking code using older versions.

This can be easily fixed, but I wanted to bring this to attention.

**Comment by DieterDePaepe** [comment]
This issue was an error from my side. Apologies.

**Comment by jeffwidman** [comment]
No worries, thanks for letting us know you figured it out.
