### ISSUE TITLE
KafkaClient not loading metadata upon creation

### ISSUE THREAD

**Issue by zarnovican** [dpkp/kafka-python#1932]
## Problem

When instantiated, `KafkaClient` does not have any meta-data about the cluster. This used to work prior to 1.4.5 version.

```
from kafka.client_async import KafkaClient

c = KafkaClient(bootstrap_servers='localhost:9092')
print(c.cluster.partitions_for_topic('data.messages'))
```

## Expected Result

```
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11}
```

## Actual Result

```
None
```

## More Info

I have a Python script that is checking the health of Kafka cluster. It is neither Kafka Producer, nor Consumer. It just connects to broker node via localhost, reads the metadata and produce alerts/metrics etc. Class `KafkaClient` exactly fit the bill..

Between 1.4.4, 1.4.5 version (commit 812de351f75beefe73bd9bef55847ab61ccc951d) it stopped working. Reading the commit, it looks like metadata are not fetched at startup anymore. I tried calling various methods of KafkaClient to trigger metadata load, with little success.

I admit, that `KafkaClient` is a bit low-level and poorly documented, but it seems "public", so I used it. Feel free to close this issue, if you think that this is not a bug.

**Comment by jeffwidman** [comment]
Use `KafkaConsumer.partitions_for_topic()`. You don't need to have the consumer setup a subscription during init, so it should be nearly as fast/simple as `KafkaClient`.

The behavior was changed to a read-through cache: https://kafka-python.readthedocs.io/en/master/apidoc/KafkaConsumer.html#kafka.KafkaConsumer.partitions_for_topic

See also https://github.com/dpkp/kafka-python/pull/1781

**Comment by zarnovican** [comment]
Hey @jeffwidman thanks a lot for the hint. I will use `KafkaConsumer`.
