### ISSUE TITLE
does this lib have built-in confluent-schema-register support 

### ISSUE THREAD

**Issue by hackrole** [dpkp/kafka-python#1937]
this  lib [confluent-kafka-python usage](https://github.com/confluentinc/confluent-kafka-python#usage) seems have confluent-schema-register built-in support.

I check the doc and the code for this lib, not find any signs like this.

so I wander does it support this or have plan to support this?

**Comment by jeffwidman** [comment]
Not currently supported. I doubt any of the maintainers plan to add it. Possibly open to a PR if you wanted to add it, but not sure how the others feel... I'm personally hesitant unless it were a generic pluggable interface that could be used by multiple schema registry type things... but I haven't really looked into that space lately to know if that's even feasible to do or not...
