### ISSUE TITLE
callbacks for KafkaProducer?

### ISSUE THREAD

**Issue by chenly23** [dpkp/kafka-python#1944]
Hi,
I know there is a way to add callbacks in `future` as the document says
```
# produce asynchronously with callbacks
producer.send('my-topic', b'raw_bytes').add_callback(on_send_success).add_errback(on_send_error)
```
but some callbacks are common, such as logging  the sent message only, but I need to add the common callback every time I send the message?
Is it possible to define the callbacks in `KafkaProducer`? 
```
producer = KafkaProducer(callbacks=[], errbacks=[])
producer.send('my-topic', b'raw_bytes')
```
Or can I configue some common callbacks in settings for Kafka?

**Comment by jeffwidman** [comment]
I don't recall a way to do this generically, so I suggest just wrapping the send call into a custom send function that you use that always appends your desired callbacks.
