### ISSUE TITLE
when run  docker-compose run --rm web upgrade  has errors

### ISSUE THREAD

**Issue by 18308996929** [dpkp/kafka-python#1946]
File "/usr/local/lib/python2.7/site-packages/sentry_kafka-1.1-py2.7.egg/sentry_kafka/models.py", line 9, in <module>
    from kafka import KafkaClient, SimpleProducer
ImportError: cannot import name SimpleProducer

why has these error？？

**Comment by jeffwidman** [comment]
You should check with the `sentry_kafka` project. Also, #1193 may be related if they are using `master` of `kafka-python`.
