### ISSUE TITLE
kafka producer async send doesn't send messages

### ISSUE THREAD

**Issue by roushan05** [dpkp/kafka-python#1954]
I am using kafka-python in a django project. Initialised the producer in settings.py file. Calling producer.send is not sending the messages.

Earlier my producer was initialised in a function everytime and I was using producer.send().get(timeout=10) to send messages and it worked fine. Now I have changed the initialisation to settings file  and removed `.get()` while calling `send` and it is not working.
Old working code below:

In `module_x.py`:
```
from kafka import KafkaProducer

def my_func():
   KAFKA_CONNECTION = KafkaProducer(bootstrap_servers=CONFIGS.KAFKA_URL)
   producer = KAFKA_CONNECTION
   producer.send(topic, key=key, value=json.dumps(data)).get(timeout=1)
```
Changed code below:
Now changed the initialisation to settings file to avoid initialisation everytime `my_func` is called.

In `settings.py`:
```
KAFKA_CONNECTION = KafkaProducer(bootstrap_servers=CONFIGS.KAFKA_URL)
```

In `module_x.py`:
```
from django.conf import settings

def my_func():
   producer = settings.KAFKA_CONNECTION
   producer.send(topic, key=key, value=json.dumps(data))
```
Note that I even tried with `.get(timeout=1)` on `send` but I was getting `Kafka.TiemoutError`

Tried using `linger_ms=5` in while initialising producer but that also doesn't help

**Comment by roushan05** [comment]
@dpkp Please reply as this is causing multiple delays in the response time. Intialising a new producer everytime has increased our response time very much.

**Comment by dpkp** [comment]
I'm not familiar w/ django settings, but it sounds like perhaps you are getting forked processes and your sender thread needs to be reinitialized in each process? This would explain a timeout on get()

If you want to rely on a global producer instance, I would recommend a lazy initialization that gets triggered on first "send":

i.e.
```
def get_producer():
    if producer is None:
        producer = KafkaProducer(bootstrap_servers=CONFIGS.KAFKA_URL)
    return producer
```
