### ISSUE TITLE
Need example describe_acls()

### ISSUE THREAD

**Issue by rootVIII** [dpkp/kafka-python#1960]
Can you give a simple example of describing ACLs? I’m looking at the [source code](https://github.com/dpkp/kafka-python/blob/master/kafka/admin/acl_resource.py) but I’m not sure how to pass a filter object to describe_acls(). Can you give an example of how to declare an ACLFilter object?

For instance how would I create a filter object to list by principal name? Or by resource (ie topic, group, or cluster)?

**Comment by dpkp** [comment]
Here's a quick example:
```
 filter = ACLFilter(
        principal='User:A',
        host='*',
        operation=ACLOperation.ANY,
        permission_type=ACLPermissionType.ANY,
        resource_pattern=ResourcePattern(
            resource_type=ResourceType.TOPIC,
            resource_name='some-topic',
            pattern_type=ACLResourcePatternType.LITERAL
        )
    )
```

Take a look at https://github.com/dpkp/kafka-python/blob/1.4.7/test/test_admin_integration.py#L81-L89 for more
