### ISSUE TITLE
Purpose of bootstrap_connected()

### ISSUE THREAD

**Issue by Tim1000V** [dpkp/kafka-python#1962]
Hi,
When reading the documentation I was assuming that bootstrap_connected(), would allow me to check if the client was disconnected from the kafka cluster. 
But in cluster.py _boostrap_broker returned by _generate_bootstrap_brokers, can't match any real broker_id (eg: [1,2,3] vs [bootstrap-1,bootstrap-2,bootstrap-3]) .

So what's the purpose of this function?

**Comment by dpkp** [comment]
This function was community submitted, and I can't speak to the submitters purposes. The PR is #1876 . I think it's a totally reasonable implementation for people that think this information is useful for them. But agree, this is not going to tell you whether "the client was disconnected from the kafka cluster"
