### ISSUE TITLE
hp-ux 11

### ISSUE THREAD

**Issue by lovrainy** [dpkp/kafka-python#1967]
how can i use it on hp-ux 11

**Comment by tvoinarovskyi** [comment]
I don't see why would it not work, as long as you get a normal installation of Python2.7+ installed. The library is pure Python, no C library dependancies, so you only need Python. If you have an issue please add additional logs, error message. Hope it helps.

**Comment by dpkp** [comment]
Docs are at https://kafka-python.readthedocs.io/en/master/
