### ISSUE TITLE
How to set at least once/exactly once at the clinet?

### ISSUE THREAD

**Issue by jossiekat** [dpkp/kafka-python#1968]
I want the client to consume the message only once.
which parameter in the client does it?
thanks
joseph

**Comment by dpkp** [comment]
Not supported. I'm skeptical that this will ever work well, and recommend that you focus on writing in an idempotent style. That said, there are transactional messaging features implemented by more recent kafka brokers that haven't been implemented in kafka-python yet. PRs welcome!
