### ISSUE TITLE
kafka.errors.IncompatibleBrokerVersion: IncompatibleBrokerVersion: Kafka broker does not support the 'DescribeConfigsRequest_v0' Kafka protocol.

### ISSUE THREAD

**Issue by ccmanito** [dpkp/kafka-python#1971]
kafka.errors.IncompatibleBrokerVersion: IncompatibleBrokerVersion: Kafka broker does not support the 'DescribeConfigsRequest_v0' Kafka protocol.

**Comment by dpkp** [comment]
Are you passing `api_version` to the admin client? If so, this should be fixed via #1953
