### ISSUE TITLE
Documentation bug: KafkaConsumer doc does not list all valid values for security_protocol

### ISSUE THREAD

**Issue by pranavmarla** [dpkp/kafka-python#1990]
The [KafkaConsumer documentation](https://kafka-python.readthedocs.io/en/master/apidoc/KafkaConsumer.html) says the following about the _security_protocol_ setting:
`security_protocol (str) – Protocol used to communicate with brokers. Valid values are: PLAINTEXT, SSL. Default: PLAINTEXT.`
This indicates that there are only 2 valid values for _security_protocol_: **PLAINTEXT** and **SSL**.

However, further down in the same document, when talking about the _sasl_mechanism_ setting, it says the following:
`sasl_mechanism (str) – Authentication mechanism when security_protocol is configured for SASL_PLAINTEXT or SASL_SSL. Valid values are: PLAIN, GSSAPI, OAUTHBEARER.`
This clearly implies that there are actually 2 **more** valid values for _security_protocol_, that are not mentioned above: **SASL_PLAINTEXT** and **SASL_SSL**.

This is confirmed by looking at the corresponding _security_protocol_ section of the [KafkaProducer documentation](https://kafka-python.readthedocs.io/en/master/apidoc/KafkaProducer.html), which correctly lists all 4 valid values:
`security_protocol (str) – Protocol used to communicate with brokers. Valid values are: PLAINTEXT, SSL, SASL_PLAINTEXT, SASL_SSL. Default: PLAINTEXT.`

**Comment by jeffwidman** [comment]
@pranavmarla want to submit a PR fixing this? Both `KafkaConsumer` and `KafkaProducer` inherit their security settings from `KafkaClient` (as long as the params are correctly plumbed through) so all three should list:

    Valid values are: PLAINTEXT, SSL, SASL_PLAINTEXT, SASL_SSL. Default: PLAINTEXT.

**Comment by pranavmarla** [comment]
@jeffwidman Sorry, completely missed this -- thank you for fixing this!
