### ISSUE TITLE
Help: Howto read the config options for a topic

### ISSUE THREAD

**Issue by acs** [dpkp/kafka-python#1992]
I have created a new topic with:

```
    topic_list = [NewTopic(topic, num_partitions=3, replication_factor=1,
                           topic_configs={'retention.ms': '168'})]
    admin_client.create_topics(new_topics=topic_list, validate_only=False)
```
Is it possible to get back the **retention.ms** config using the kafka-python API?

**Comment by acs** [comment]
Ok, I have found a way to do it.

```
admin_client = KafkaAdminClient(bootstrap_servers=[KAFKA_URL])
configs = admin_client.describe_configs(config_resources=[ConfigResource(ConfigResourceType.TOPIC, KAFKA_TOPIC)])
config_list = configs.resources[0][4]
```
Inside the **config_list** (tuple list) there is an entry with the retention_ts for the topic.

It is a bit tricky and probably, it is a better way to parse the configs object to avoid the magical **configs.resources[0][4]** to get the config entries for the topic, but it works.

Closing the ticket.

**Comment by jeffwidman** [comment]
We also welcome PR's improving the Admin Client, especially it's translation from the raw struct back to more pythonic data structures.

**Comment by acs** [comment]
Ok @jeffwidman . I take note and if I continue using kafka and python in real use cases I will try to help on it.
