### ISSUE TITLE
KafkaAdminClient.*_topics() is broken

### ISSUE THREAD

**Issue by StefPtrs** [dpkp/kafka-python#2001]
This fix (on master) solves the issue:
https://github.com/dpkp/kafka-python/commit/7195f0369c7dbe25aea2c3fed78d2b4f772d775b

Is there a new release planned that includes this fix?

**Comment by jeffwidman** [comment]
It should be only `describe_topics()` that's broken. The others didn't call the controller so they should still work.

As far as a release, that's up to @dpkp
