### ISSUE TITLE
CertificateError: hostname 'xx.xxx.xxx.xxx' doesn't match 'messagehub.dco.mycompany'

### ISSUE THREAD

**Issue by AnamikaN** [dpkp/kafka-python#2013]
I am trying to test kafka-consumer and i am getting error. It looks like, i need to configure ssl for it. Below is my connection block.

client_id=consumer_api
security_protocol=SASL_SSL
sasl_mechanism=PLAIN

consumer = KafkaConsumer(bootstrap_servers=bootstrap_servers,
                                     client_id=client_id,
                                     security_protocol=security_protocol,
                                     sasl_mechanism=sasl_mechanism,
                                     sasl_plain_username=self.username,
                                     sasl_plain_password=self.password,
                                     auto_offset_reset=self.offset,
                                     group_id=configuration['consumer_group_id'],
                                     ssl_cafile=configuration['ca_file'])

configuration = {
    'config_file': '/config.ini',
    'consumer_group_id': 'jenkins_svckafkaops',
    'ca_file': '/kafka.ca-cert'
}

how to fix this issue?

**Comment by jeffwidman** [comment]
Afraid I am not very familiar with SASL/SSL configs, and that's a bit out of scope of what we do... it actually looks like a certificate problem, or using the wrong certificate, not a `kafka-python` problem.
