### ISSUE TITLE
[Contribution]Example : Integration of Kafka with Gunicorn & Gevent

### ISSUE THREAD

**Issue by mohammedvaghjipurwala** [dpkp/kafka-python#2014]
Example to demonstrate the integration of Gunicorn with Kafka streaming and its worker as gevent.

I have not found any relevant documentation for these technologies.

I had integration issues like the consumer getting hanged, Kafka connectivity issues, etc. I finally resolved this issue and I would like to contribute this solution with an example to this repository.

**Comment by jeffwidman** [comment]
Hmm... honestly, a fair bit of that sounds out of scope for this repo / docs, and might be better as a blog post. There's a different level of expectations about docs correctness of "this must be correct" vs "oh this is a blog post that shows me the general idea, and I may need to tweak a few things".

That way you can touch on a bunch of stuff relevant to all those technologies, vs if we add to the docs here it will likely go out of date, be not quite correct for some else's use case, etc. 

And to be clear, I think it'd be a great idea for you to write this! Would probably be very helpful to many people.

**Comment by mohammedvaghjipurwala** [comment]
Thanks Jeff for the suggestion... I'll surely think of making a blog for this use case

**Comment by mohammedvaghjipurwala** [comment]
@jeffwidman , Here is the link to my blog 

https://medium.com/@mohammed.vaghy/implementing-kafka-with-gunicorn-gevent-workers-87e679926ddc
