### ISSUE TITLE
API to create a topic with a particular number of partitions

### ISSUE THREAD

**Issue by mjwillson** [dpkp/kafka-python#202]
Is it possible to use this client library to create a topic with a particular number of partitions, like the `kafka-create-topic.sh` script which ships with kafka allows? I couldn't spot any API for this (or even to create a topic at all!)

It can be useful to do this programmatically, e.g. when setting up system/integration tests.

**Comment by himaprasoonpt** [comment]
Is this possible now? Is there a way to create a topic with n partitions using the API?
