### ISSUE TITLE
Pull the information several times, the first time is empty, after several times can get the information

### ISSUE THREAD

**Issue by ghleilei** [dpkp/kafka-python#2034]
hi，@dpkp
Run the consumer code, pull the information several times, get it null the first time, and get it several timeshis is the consumer code. Why?
This is the consumer code

def consumer():
    consumer = KafkaConsumer(kafka_topic,
                             bootstrap_servers=server ,
                             auto_offset_reset='earliest',
                             enable_auto_commit=False, 
                             group_id='kafka-test-1',
                             consumer_timeout_ms=10000,           
                             value_deserializer = bytes.decode
                             )
    for _ in range(3):
        datass = consumer.poll(timeout_ms=5,max_records=10) 
        print(datass)
        consumer.commit()

**Comment by jeffwidman** [comment]
The first poll() sets the consumer's assignment, then a subsequent poll() fetches the data. Since you're explicitly committing, and then still repeatedly seeing the data, are you sure the consumer isn't getting evicted from the consumer group?

**Comment by ghleilei** [comment]
> 第一个poll（）设置使用者的分配，然后一个后续的poll（）获取数据。由于您是明确提交的，然后仍在反复查看数据，因此您确定不会将消费者从消费者组中逐出吗？

@jeffwidman 
This is my first time using kafka-python,I'm not sure.
So what do I do

**Comment by jeffwidman** [comment]
I think you should read up on how consumer groups work in Kafka... the official Kafka docs are a good place to start.

**Comment by ghleilei** [comment]
> 我认为您应该阅读消费者团体在Kafka中的工作方式，尤其是消费者团体分区分配/重新平衡。Kafka官方文档是一个不错的起点。如果您现在不花时间来理解它们，则会在以后遇到更多问题。

Ok i will read it seriously
