### ISSUE TITLE
KafkaTimeoutError:

### ISSUE THREAD

**Issue by skskcco2o17** [dpkp/kafka-python#2050]
My code:

```
def kafka_producer():
     producer = KafkaProducer(bootstrap_servers='{0}:{1}'.format(HOST, PORT),
                         api_version=(0, 10, 1)
                         )
   try:
       future = producer.send('test', b'hello kafka')
       producer.flush()
       record_metadata = future.get(timeout=10)
       print(record_metadata)
except KafkaError as e:
       print(e)    
```

 
 
My Kafka Broker (v 2.4.0) is running in OpenShift container. My Python producer code is similar to the above and that is causing the below issue.

```
KafkaTimeoutError: Batch for TopicPartition(topic='test', partition=0) containing 1 record(s) expired: 31 seconds have passed since batch creation plus linger time
   File "C:\Users\XXXXXXX\Anaconda3\lib\site-packages\kafka\producer\future.py", line 65, in get
    raise self.exception # pylint: disable-msg=raising-bad-type
```

My kafka-python version is 2.0.1

I am fighting on the issue for last two days. I am frustrated. Please assist how do you resolve it / why does it occur?

I have tested using the Kafka sh script to send the topic it's working. So where is the problem in python?

**Comment by skskcco2o17** [comment]
kafka-python team (dpkp) please help, it's production delivery issue.

**Comment by tvoinarovskyi** [comment]
@skskcco2o17 Hi, sadly did not see anything similar before. Could you verify that you run the `**.sh` script from the same container/machine you were running the python script? It may be that you have an incorrectly configured broker settings, did you properly set ADVERTIZE_LISTENERS on broker side? (It's the configuration that tells clients the host/port of each machine to connect to)

Could you also try:
* Removing api_version hint, let the client autodetect version
* Do something simpler, like `producer. partitions_for('test')`. Does it timeout too?
* You are on Windows it seems, could you elaborate on your setup, do you try to access from local machine, or is your infrastructure hosted on Windows?

**Comment by tvoinarovskyi** [comment]
If nothing of above helps it would help if you could provide DEBUG logs for kafka-python client. You can enable them by running something similar to this:
```python
log_level = logging.DEBUG
logging.basicConfig(level=log_level)
log = logging.getLogger('kafka')
log.setLevel(log_level)
```

**Comment by skskcco2o17** [comment]
Hi tvoinarovskyi, thanks for  assisting.  
After providing the log_level to DEBUG,  I see the problem is due to following error : 
```
WARNING:kafka.conn:DNS lookup failed for kafka-zookeeper-7-wfx9x:9092, exception was [Errno 11001] getaddrinfo failed. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
ERROR:kafka.conn:DNS lookup failed for kafka-zookeeper-7-wfx9x:9092 (AddressFamily.AF_UNSPEC)
```
where  kafka-zookeeper-7-wfx9x is the prod host name , already configured with ip in /etc/hosts file. To check whether pod host name is correct or not, I ping this  from Pod terminal. It's resolving the IP address  172.30.66.31. 

I am not sure why it's not resolvable.

Deployment scenario : 
 - My Kafka Zookeeper image is deployed in OpenShift container pod with host name 'kafka-zookeeper-7-wfx9x'. where Kafka broker is listening to port 9092 and the zookeeper is listening to 2181.
- My Kafka producer is running locally (localhost) with bootstrap_servers = localhost:9092
- I used openshift port_forwarding feature where port 9092 is forwarding from local host to Pod host , using 'oc' command.

Testing Scenarion:
When I run producer, producer resolve localhost:9092 and oc port is then forwarding the request to Pod host:port i.e.  kafka-zookeeper-7-wfx9x:9092   and here I am getting this error.

Please assist.  :-)

**Comment by tvoinarovskyi** [comment]
@skskcco2o17 As far as I understand you run a port forward command on your local machine to get access to Kafka Broker hosted in the container and connect to it using `bootstrap_servers="localhost:9092"`, correct?
What did you provide into /etc/hosts? From your setup, I would assume the correct way to access would be to:

* Provide `kafka-zookeeper-7-wfx9x 127.0.0.1` to `/etc/hosts`
* Connect using `kafka-zookeeper-7-wfx9x:9092` string in `bootstrap_servers`

**Comment by skskcco2o17** [comment]
Hi tvoinarovskyi ,     
Your understanding is absolutely correct. I run a openshift port forward command on my local windows machine to get access to Kafka Broker hosted in the OpenShift POD container and connect to it using bootstrap_servers="localhost:9092". 

I have provided entry in /etc/hosts of Pod container (where Kafka Broker is running), NOT in my local machine.  I open the pod container SSH terminal , go to /etc/hosts and do the changes , like  below:
`172.30.66.31 kafka-zookeeper-7-wfx9x`

'kafka-zookeeper-7-wfx9x' is the host name of the OpenShift Pod where the Kafka broker container is running. So change in local C:\Windows\System32\drivers\etc\hosts, as you suggested, should not work, since Pod container IP is not resolvable in local machine...

**Comment by tvoinarovskyi** [comment]
Glad it helped, a lot of people have problems with it. Kafka clients get a list of brokers on first connect from a random broker. That list shows hosts that Kafka broker think is correct, but in case of port forwarding is mostly incorrect (eg. even thou you connect using `localhost:9092` it will still ask Kafka what is its hostname and connect using that one).
