### ISSUE TITLE
How to specify TLS version

### ISSUE THREAD

**Issue by ErikBrewster** [dpkp/kafka-python#2053]
I have several devices trying to connect to my brokers. Most of them work, but some are getting rejected and I can see reset packets in wireshark that show it is communicating on TLS1.0 and getting rejected by our server because it only allows TLS1.2. We are deploying in containers, so the environment that the different devices run should be the same, except for the certs and stuff like UUIDs. I don't understand where to set the allowed TLS version in config.

If I edit the library and change (line 465, conn.py) from:
            self._ssl_context = ssl.SSLContext(ssl.PROTOCOL_SSLv23)  # pylint: disable=no-member
to
            self._ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)  # pylint: disable=no-member

It appears to connect ok. It seems like this is something that could be changed in config -- perhaps in ssl_context = ??? when initializing the producer. Any tips on how to specify TLS 1.2 only?

**Comment by ErikBrewster** [comment]
In lots of packet sniffing, it appears that Kafka-Python is using the TLS1.0 spec fine (TLS1 record layer, TLS1.2 handshake protocol verison, as is normal in TLS1.2). It appears we are doing something else to get blocked by an IT security appliance. I still think it would be great to be able to more granularly specify TLS version used in conn.py, but I'm closing this, as I don't think anything is "Broken" and I haven't thought out the feature request precisely enough to make a real change request.

**Comment by tvoinarovskyi** [comment]
@ErikBrewster Hi, sorry for not getting back to you. The library still supports Python2.7, making adapting changes to ssl a bit more complicated, as there are a lot of differences in API's. The library exposes the `ssl_context` parameter for this purpose, would that not satisfy your case?

Related docstring explains it as such:
```
ssl_context (ssl.SSLContext) – Pre-configured SSLContext for wrapping socket connections. If provided, all other ssl_* configurations will be ignored. Default: None.
```
