### ISSUE TITLE
Kafka consumer process the same message several time if scaled

### ISSUE THREAD

**Issue by Sabutobi** [dpkp/kafka-python#2065]
Hi, all.
My code:
Consumer settings:
```
from kafka import KafkaConsumer
from kafka.coordinator.assignors.roundrobin import RoundRobinPartitionAssignor

consumer = KafkaConsumer(
    bootstrap_servers=kafka_host + ":" + kafka_port,
    security_protocol='PLAINTEXT',
    group_id='messages',
    partition_assignment_strategy=[RoundRobinPartitionAssignor],
    auto_offset_reset='latest',
    session_timeout_ms=60000,
    enable_auto_commit=True,
    max_poll_records=100
)
```
Consumer execution:
```consumer.subscribe(config['topic_que']['topic'])
for msg in consumer:
        message = json.loads(msg.value.decode("utf-8"))
        if message['msg'] == config['some']['message']:
            # do something
            # nothing else there about kafka consumer
```
Not default settings in kafka broker:
```
group.max.session.timeout.ms = 70000
```

Problem:
Done the 
``` docker-compose up -d --build --scale my-service=3 ```
In another word, we have 3 Consumers that using the same group_id
From the first looks like all works fine messages are shared between several consumers:
```
my-service_1  | 10:07:13.902 INFO     __main__:33  --- Message from kafka - some my message
my-service_2  | 10:07:13.902 INFO     __main__:33  --- Message from kafka - some my message2
my-service_3  | 10:07:13.902 INFO     __main__:33  --- Message from kafka - some my message3
```
Approx. The number of messages is 100. Time of execution of logic that was activated by messages from 30 sec to 5-6 minutes.
After some time of execution I can see:
```
my-service_1  | 11:09:18.469 INFO     __main__:33  --- Message from kafka - some my message
my-service_2  | 11:45:39.202 INFO     __main__:33  --- Message from kafka - some my message2
my-service_3  | 10:37:13.902 INFO     __main__:33  --- Message from kafka - some my message3
```
That is the same message in the same scaled service. 
I've checked for duplicates in kafka-broker-topics - all are **unique**.
In other words looks like that messages haven't marked as processed. And that services can run infinite time and will process those messages again and again.
Note: if I add `consumer.commit()` in the end.
I'll receive error:
```
CommitFailedError: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured max_poll_interval_ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing the rebalance timeout with max_poll_interval_ms, or by reducing the maximum size of batches returned in poll() with max_poll_records.
```

Maybe I've set something wrong? Seeking for some fresh ideas. Thanks a lot for your attention to this issue.

**Comment by tvoinarovskyi** [comment]
> Note: if I add consumer.commit() in the end.

Please set commit after each message you process, as the processing time in your case is very long. Bump your `max_poll_interval_ms` setting to a larger value too, say 10 mins (5 by default).
If you get `CommitFailedError` you need to decide for yourself what to do with this message. It means that you were too slow to process the message (larger than `max_poll_interval_ms`) and this partition **may** have already passed to a different worker. Usually, you just log a message and continue processing with the assumption that the next worker will either reprocess the message or see that it's already processed and just commit right ahead (say by checking some SUCCESS status in the result DB).

Kafka is not designed to process messages for a really long time, 5mins is a lot. It will be fine if you go 1 message at a time, but it's only possible to get a limited level of concurrency in Kafka (up to the number of partitions).

**Comment by tvoinarovskyi** [comment]
There are several alternative ways to process long messages. 1 example is republishing messages that take too long to process to a separate `long-running` topic and committing the current one. This may be the case if you have a Web crawler and some sites are just slow to process and you want those separated for a different process to handle them, while all that are fast enough to respond up to few seconds will be processed from the main topic.
Another way is to split your processing into several steps and use separate compaction topic to save progress on long-running tasks, while using the incoming topic only as a starting point, for example:
* cluster-updates topic would contain all changes to be applied to the cluster. The processor writes a record to `update-state` with status `pending` and commits right away to process next message.
* update-state will be a compacting topic containing states for each long update request. A separate processor would read this topic from start to end to recreate the status of all update requests and if some would still be required would perform those updates and publish a clear marker to the compaction topic. See this as a `transaction log` for update requests.

**Comment by Sabutobi** [comment]
Hi, @tvoinarovskyi 
Thanks for helping me. I've resolved the issue with these settings
```
max_poll_interval_ms = 3600000
max_poll_records = 10
```

Just wondering `max_poll_interval` is period to handle `max_poll_records` or these two settings don't affect each one to another?

**Comment by tvoinarovskyi** [comment]
> Just wondering max_poll_interval is period to handle max_poll_records or these two settings don't affect each one to another?

That is correct, you are telling the driver, you will spend at most 3600000 ms to process 10 messages. I would recommend just doing `max_poll_records=1` and a lower `max_poll_interval_ms` thou, as `max_poll_interval_ms` also determines how much time the group will wait on rebalances, meaning if 1 of your services dies others would wait for 1hour for it to go back up...

**Comment by Sabutobi** [comment]
@tvoinarovskyi Thanks a lot for explanations. The issue is 100% resolved.

**Comment by him7jindal** [comment]
but you have auto_commit enabled right? then as soon as message is received by consumer, offset will be committed to broker. Then why broker is waiting for consumer to complete/commit before `max_poll_interval_ms`?
