### ISSUE TITLE
How to yeild CPU if consumer empty

### ISSUE THREAD

**Issue by evgeniyasti** [dpkp/kafka-python#2066]
Hello.

I consuming message with

    for message in consumer:
       ...

I need to yield the CPU though if there are no messages in the consumer:

    for message in consumer or 'default':
       if message == 'default':
           await asyncio.sleep(0)

Something along those lines. Basically I need to either consumer or do other stuff on another co-routine.

How do I achieve this?

Thanks

**Comment by evgeniyasti** [comment]
Ok. Thanks kindly for the response!

**Comment by evgeniyasti** [comment]
How do I mark it as resolved?

**Comment by tvoinarovskyi** [comment]
Hope it helps)
