### ISSUE TITLE
Support for encoding/decoding non-string messages

### ISSUE THREAD

**Issue by jakekdodd** [dpkp/kafka-python#210]
I've been trying to figure out how to send Avro-encoded messages with kafka-python. As best as I can tell, this isn't possible, since the `write_int_string ` method called by `_encode_message` checks to make sure that the message is of type String, and errors out if this is not the case.

I don't see any reason why the kafka-python Producer should require that the message be a string, since Kafka messages are just bytes. Why was this design decision made, and is this something that's easily changeable to support non-string messages?

Or, am I just missing something, and this is possible with the current release of kafka-python?

**Comment by malonej7** [comment]
Hi, late to the party here, but I've been looking all over the internet to find an example that can show me how to implement kafka-python using an avro encoding and I can't find anything amazingly.  Would you be able to point me to any code samples for this?  It would be greatly appreciated.  Thanks.

**Comment by jakekdodd** [comment]
Heh blast from the past, I'd forgotten that I worked on this issue.

I was able to dig up this script and, miraculously, it worked. Here's a gist that should get you started:

https://gist.github.com/jakekdodd/e7ee38fd945818d86eb4

**Comment by malonej7** [comment]
Nice thank you!  That's very helpful.  I appreciate it.

**Comment by dpkp** [comment]
KafkaProducer and KafkaConsumer classes support `value_serializer` and `value_deserializer`, respectively, which mean you can use any arbitrary function to convert messages to bytes and back.
