### ISSUE TITLE
committed() not able to retrieve the last committed offset

### ISSUE THREAD

**Issue by Anshita1Saxena** [dpkp/kafka-python#2115]
Problem Statement: Using the committed() to get the last committed offset from the Kafka Consumer, however, observed that it is not able to return the offset properly.

Environment:
kafka-python==2.0.1
kafka_2.11-0.10.2.1
TopicName: node-Replication-BAT
group_id: nodeReplicationBATConsumerGroup
Properties used:
```
    kafka_consumer = KafkaConsumer(
        bootstrap_servers=(kafka_servers),
        group_id=group_id,
        enable_auto_commit=False,
        auto_offset_reset='earliest',
        max_partition_fetch_bytes=9437184)
```

Code used to check the last committed offset:
```
        for partition in kafka_consumer.partitions_for_topic(topic_name):
            tp = TopicPartition(topic_name, partition)
            print(tp)
            kafka_consumer.assign([tp])
            committed = kafka_consumer.committed(tp)
            print(committed)
            if committed == None:
                committed = 0
            kafka_consumer.seek_to_end(tp)
            last_offset = kafka_consumer.position(tp)
            print(last_offset)
            if last_offset != None and committed != None:
                lag = last_offset - committed
                partition_lag[partition] = lag

            partition_info = 'group: ' + str(group_id) \
                             + ' topic: ' + str(topic_name) \
                             + ' partition: ' + str(partition) \
                             + ' lag: ' + str(lag)
            logging.info(partition_info)
```
From the logs, it is observed that same messages got consumed successfully on 24th Aug. Then, again on 31st Aug, it consumed because it found lag on the topic.
On 24th Aug:
```
Mon, 24 Aug 2020 13:03:23 - INFO - group: nodeReplicationBATConsumerGroup topic: node-Replication-BAT partition: 0 lag: 63
Mon, 24 Aug 2020 13:03:23 - INFO - group: nodeReplicationBATConsumerGroup topic: node-Replication-BAT partition: 1 lag: 62
Mon, 24 Aug 2020 13:03:23 - INFO - group: nodeReplicationBATConsumerGroup topic: node-Replication-BAT partition: 2 lag: 63
```

On 31st Aug:
```
Mon, 31 Aug 2020 14:00:02 - INFO - group: nodeReplicationBATConsumerGroup topic: node-Replication-BAT partition: 0 lag: 63
Mon, 31 Aug 2020 14:00:02 - INFO - group: nodeReplicationBATConsumerGroup topic: node-Replication-BAT partition: 1 lag: 62
Mon, 31 Aug 2020 14:00:02 - INFO - group: nodeReplicationBATConsumerGroup topic: node-Replication-BAT partition: 2 lag: 63

```
In between the above two timings:
```
Mon, 24 Aug 2020 15:00:02 - INFO - group: nodeReplicationBATConsumerGroup topic: node-Replication-BAT partition: 0 lag: 0
Mon, 24 Aug 2020 15:00:02 - INFO - group: nodeReplicationBATConsumerGroup topic: node-Replication-BAT partition: 1 lag: 0
Mon, 24 Aug 2020 15:00:02 - INFO - group: nodeReplicationBATConsumerGroup topic: node-Replication-BAT partition: 2 lag: 0
```
This happened for the same messages, there was no message published to the topic after 24th Aug even then it consumed same messages twice. Sometimes, it is getting the correct committed offset number and sometimes it is not able to retrieve the correct number. Can you please suggest why does it happen? Is there any problem in this approach or `committed()` ?

**Comment by Anshita1Saxena** [comment]
I had verified from the commandline that the number didn't change also:
```
./kafka-run-class.sh kafka.tools.GetOffsetShell --broker-list kafka03:9092 --topic node-Replication-BAT | awk -F ":" '{sum += $3} END {print sum}'
188
```

**Comment by Anshita1Saxena** [comment]
any suggestions?

**Comment by Anshita1Saxena** [comment]
Hi All,

Yesterday again, same issue found where we had seen that same messages repeated but those messages were already reposted and found that committed function not able to capture the stats.
Here is the evidence:
At 07 Sep 2020 09:00, committed function is showing the messages properly.
```
Mon, 07 Sep 2020 09:00:02 - INFO - ==== Processing Started ====
Mon, 07 Sep 2020 09:00:02 - INFO - Committed: 45 for partition: 0
Mon, 07 Sep 2020 09:00:02 - INFO - Committed: 45 for partition: 0
Mon, 07 Sep 2020 09:00:02 - INFO - End offset: 45 for partition: 0
Mon, 07 Sep 2020 09:00:02 - INFO - group: nodeReplicationBATConsumerGroup topic: node-Replication-BAT partition: 0 lag: 0
Mon, 07 Sep 2020 09:00:02 - INFO - Committed: 48 for partition: 1
Mon, 07 Sep 2020 09:00:02 - INFO - Committed: 48 for partition: 1
Mon, 07 Sep 2020 09:00:02 - INFO - End offset: 48 for partition: 1
Mon, 07 Sep 2020 09:00:02 - INFO - group: nodeReplicationBATConsumerGroup topic: node-Replication-BAT partition: 1 lag: 0
Mon, 07 Sep 2020 09:00:02 - INFO - Committed: 50 for partition: 2
Mon, 07 Sep 2020 09:00:02 - INFO - Committed: 50 for partition: 2
Mon, 07 Sep 2020 09:00:02 - INFO - End offset: 50 for partition: 2
Mon, 07 Sep 2020 09:00:03 - INFO - ==== Processing Ended ====
```
At 07 Sep 2020 10:00, committed function is showing None (no prior commit), how is this possible?
```
Mon, 07 Sep 2020 10:00:01 - INFO - ==== Processing Started ====
Mon, 07 Sep 2020 10:00:02 - INFO - Committed: None for partition: 0
Mon, 07 Sep 2020 10:00:02 - INFO - Executing Committed None!
Mon, 07 Sep 2020 10:00:02 - INFO - Committed: 0 for partition: 0
Mon, 07 Sep 2020 10:00:02 - INFO - End offset: 45 for partition: 0
Mon, 07 Sep 2020 10:00:02 - INFO - Committed: None for partition: 1
Mon, 07 Sep 2020 10:00:02 - INFO - Executing Committed None!
Mon, 07 Sep 2020 10:00:02 - INFO - Committed: 0 for partition: 1
Mon, 07 Sep 2020 10:00:02 - INFO - End offset: 48 for partition: 1
Mon, 07 Sep 2020 10:00:02 - INFO - Committed: None for partition: 2
Mon, 07 Sep 2020 10:00:02 - INFO - Executing Committed None!
Mon, 07 Sep 2020 10:00:02 - INFO - Committed: 0 for partition: 2
Mon, 07 Sep 2020 10:00:02 - INFO - End offset: 50 for partition: 2
Tue, 08 Sep 2020 01:00:02 - INFO - ==== Processing Ended ====
```
Could you please let us know in this case, what should we use for checking the offset commit partition wise?
Appreciate you earliest assistance on this.

Thanks and Regards,
Anshita Saxena

**Comment by swenzel** [comment]
Hey, can you check the broker setting `offsets.retention.minutes`? In Kafka versions prior to 2.0.0 this was set to 1440 which amounts to one day. If your consumer does not re commit it's offsets within that time frame, they're lost and it will restart from the beginning.

**Comment by Anshita1Saxena** [comment]
Hi @swenzel , 

I checked in the configuration file and there the retention period is mentioned:
`/opt/kafka_2.11-0.10.2.1/kafka_2.11-0.10.2.1/config/server.properties`
`offsets.retention.minutes=10080`
It is observed that this happens in the interval of 7 days.
 
Can we able to set this configuration at the code level so that it will not take these platform level properties?

Thanks and Regards,
Anshita Saxena

**Comment by swenzel** [comment]
IIRC it's a global, non-dynamic broker setting and cannot be changed from the client side. The only thing you can do is make sure that your group keeps committing its offsets at a certain interval.

**Comment by Anshita1Saxena** [comment]
Hi @swenzel ,

Thanks for the suggestion. Currently, I am doing the manual commit. Whenever messages are coming to this topic then only it is doing the manual commit for those messages. I set here the `enable_auto_commit=False` so that it should pick up the message where it left.

Can you please suggest the direction to keep committing the offset at a certain interval in this case ?

Thanks and Regards,
Anshita Saxena

**Comment by swenzel** [comment]
How to do this properly depends on your implementation. I don't know what additional information you need. You know what the problem is and what your program needs to do in order to solve it. The concrete implementation should be your task, not mine :slightly_smiling_face:  
I suggest you try it for yourself first, and if you really cannot figure it out, ask on [stackoverflow.com](https://www.stackoverflow.com).  
It's evident that the issue is not with kafka-python so I'd kindly ask you to close this issue :slightly_smiling_face:

**Comment by Anshita1Saxena** [comment]
Hi Swenzel,

Thanks for your directions and reply. Appreciate your inputs.

Since the messages are not able to come at the topic in between the duration fixed at `offsets.retention.minutes` configuration hence resetting will be happened and lost the last committed offset , therefore I will try to figure out the other way of implementing this so that loosing of offset will not be happened.

Thanks and Regards,
Anshita Saxena
