### ISSUE TITLE
Kafka + OAuth + Azure EventHub - unexpected issues

### ISSUE THREAD

**Issue by MichalKosowski** [dpkp/kafka-python#2120]
Hello all!

In my team, we are using the Kafka interface to communicate with Azure EventHub. We switched to your library as it has support to OAuth Token authorization (in contrast to Confluent Kafka implementation).

I have done a quick prototype of a producer that is using you your Kafka Producer and SASL_SSL security protocol and it is working fine. Then I tried to use the OAuth configuration as described in the PR for this feature. And whatever I am trying to do, we get timeout error:

`kafka.errors.KafkaTimeoutError: KafkaTimeoutError: Failed to update metadata after 60.0 secs.`

In debug, we do not even reach the code responsible for generating token so the problem must be elsewhere, but no idea where... Can you help with debugging here?

configuration for OAuth:
```python
producer = KafkaProducer(
    bootstrap_servers='{namespace}.servicebus.windows.net:9093',
    client_id="{some_guid_value}",
    security_protocol='SASL_PLAINTEXT',
    sasl_oauth_token_provider=TokenProvider(),
    sasl_mechanism='OAUTHBEARER',
    api_version=(2, 0, 1),
)
```

and TokenProvider code is below. Independently I tested and it is working and receives token from Azure:
```python
class TokenProvider(AbstractTokenProvider):
    def token(self):
        # config = json.load(open(sys.argv[1]))
        config = json.load(open("parameters.json"))

        # Create a preferably long-lived app instance which maintains a token cache.
        app = msal.ConfidentialClientApplication(
            config["client_id"], authority=config["authority"],
            client_credential={"thumbprint": config["thumbprint"], "private_key": open(
                config['private_key_file']).read()},
            # token_cache=...  # Default cache is in memory only.
            # You can learn how to use SerializableTokenCache from
            # https://msal-python.rtfd.io/en/latest/#msal.SerializableTokenCache
        )

        result = None
        result = app.acquire_token_silent(config["scope"], account=None)

        if not result:
            logging.info(
                "No suitable token exists in cache. Let's get a new one from AAD.")
            result = app.acquire_token_for_client(scopes=config["scope"])

        if "access_token" in result:
            print("authentication: success")
            return result['access_token']
        else:
            print(result.get("error"))
            print(result.get("error_description"))
            print(result.get("correlation_id"))
            raise Exception("Authentication failed!")
```

Similarly, working configuration for SASL_SSL:
```python
producer = KafkaProducer(
    bootstrap_servers='{namespace}.servicebus.windows.net:9093',
    security_protocol='SASL_SSL',
    sasl_mechanism='PLAIN',
    sasl_plain_username='username',
    sasl_plain_password='password',
    api_version=(2, 0, 1),
)
```

Thank a lot for any help :)

**Comment by jeffwidman** [comment]
No idea, unfortunately this is something you'll need to debug further... Can you run it under `pdb` and step through it? 

One thing to check is how eventhub responds when we probe for the broker api version... you can bypass the probing by manually pinning the version.

**Comment by swenzel** [comment]
I can see that you're using the same ports for `SASL_SSL` and `SASL_PLAINTEXT`. Is it because `{namespace}` differs and you have different instances behind it? Because usually one port can only serve one security protocol. So either your port or your protocol might be wrong in case of OAuth...

**Comment by MichalKosowski** [comment]
> 
> 
> I can see that you're using the same ports for `SASL_SSL` and `SASL_PLAINTEXT`. Is it because `{namespace}` differs and you have different instances behind it? Because usually one port can only serve one security protocol. So either your port or your protocol might be wrong in case of OAuth...

I removed the port and the same error. There is only the above port specified in the documentation. Anyway, we switched to use a dedicated Python client and AMQP protocol to communicate with the cloud. So no further investigation on this problem from my side.

**Comment by ThanosKarousos** [comment]
Has anybody figured the root cause of this? we are having the exact same issue
I can confirm that the token generated is correct (in our case), but passing it in `sasl_oauth_token_provider` some how is not enough for the producer to be authenticated
