### ISSUE TITLE
Hooks support in kafka-python

### ISSUE THREAD

**Issue by Rohit-dot-KumarAM** [dpkp/kafka-python#2137]
Like Django and Celery comes with hooks(called signals there), using which some pre and post tasks can be triggered.
Is there something similar kind of concept is present in kafka-python, if yes then where to find that.

**Comment by jeffwidman** [comment]
Yes, the message futures support callbacks, search for "callback" https://kafka-python.readthedocs.io/en/master/apidoc/KafkaConsumer.html and and as it's not super well-documented it's probably worth inspecting the relevant source code as well.
