### ISSUE TITLE
Missing/additional API calls in admin client

### ISSUE THREAD

**Issue by johnseekins** [dpkp/kafka-python#2140]
It isn't clear from the documentation/code whether this is possible, but:

1. Can we _delete_ topic/broker configs with the admin client? This would be analogous to `kafka-configs.sh --delete`

2. Can we set the replication factor on an existing topic? This is clearly possible with _new_ topics, but I don't see a way to change it for existing topics.

**Comment by jeffwidman** [comment]
Did you try https://kafka-python.readthedocs.io/en/master/apidoc/KafkaAdminClient.html#kafka.KafkaAdminClient.alter_configs ?

You may want to look at the unit tests for the relevant code to see examples of how to use it...

**Comment by johnseekins** [comment]
I don't see any examples in the `test/` folder around deleting configuration options for a topic or broker. And I don't see any examples changing replica counts for a topic. So while I'm sure it does work, I have no idea how to test it.
