### ISSUE TITLE
KafkaConsumer is unable to consume messages

### ISSUE THREAD

**Issue by vaastav** [dpkp/kafka-python#2142]
I was following the tutorial on the docs/readme and the KafkaConsumer does not consume any messages!
I tried consuming the messages from the ConsoleConsumer shipped with the Kafka installation and that was able to consume messages from the given topic.
I ensured that I gave the correct bootstrap_server address to the consumer as well.
Any ideas as to what might be going on?

I am using Python 3.8.3

**Comment by vaastav** [comment]
Explicitly seeking to the starting position for the partition and then polling for records seem to have worked. However, the iterator-based consumption does not work.

**Comment by vaastav** [comment]
On further experimentation, I found that the Consumer consumes messages that were sent AFTER the consumer had subscribed for messages. Shouldn't the consumer consume prior messages as well?

**Comment by aswinjoseroy** [comment]
You might want to double-check the consumer group's status (that your python consumer belongs to). If it is set to default and your shell-based (or any other) consumer has been consuming using the same group, then set it to a new group or reset the group. `group_id` is the parameter you are looking for. Also, set `auto_offset_reset='earliest'` . All the best.

**Comment by jeffwidman** [comment]
Thanks @aswinjoseroy for chiming in, great answer!

**Comment by aswinjoseroy** [comment]
@jeffwidman happy to help! @vaastav hope you figured it out.
