### ISSUE TITLE
Missed Messages

### ISSUE THREAD

**Issue by 2020testuser** [dpkp/kafka-python#2146]
Hi,
Could anyone help me please?
I want to read the messages that are missed by consumer when the consumer was down? I have enable_auto_commit set to False.
Any sample or details would be very helpful for me.

Thanks in advance!

**Comment by jeffwidman** [comment]
When the consumer comes back up, it will read the messages from where it left off, so you don't need to do anything. If those messages are no longer in Kafka, then there's nothing this library can do... I suggest reading up on how kafka consumers work as they are async from when messages are produced.
