### ISSUE TITLE
SSL Connection Failing in Python 3.9

### ISSUE THREAD

**Issue by 2020testuser** [dpkp/kafka-python#2148]
Hi,
Could anyone please help me?
I'm using the latest kafka-python with Python 3.9. I'm fetching the ssl information from the evnvironment using os.environ().
What is the stable kafka-python and python version to use ssl. Appreciate if anyone can provide details. Thanks in advance!

I'm getting the below error. 
`  ssl_cafile=os.environ['KAFKA_TLS_CA_CERT']
    ssl_certfile=os.environ['KAFKA_TLS_CERT']
    ssl_keyfile=os.environ['KAFKA_TLS_KEY']

  consumer=KafkaConsumer(                      
                        bootstrap_servers=bootstrap_server,   
                        group_id=group_id,     
                        security_protocol="SSL",
                        ssl_check_hostname=True,
                        ssl_cafile=ssl_cafile,
                        ssl_certfile=ssl_certfile,
                        ssl_keyfile=ssl_keyfile,
                        auto_offset_reset='earliest', 
                        enable_auto_commit=False)

Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.9/site-packages/werkzeug/serving.py", line 314, in execute
    for data in application_iter:
  File "/usr/local/lib/python3.9/site-packages/werkzeug/wsgi.py", line 506, in __next__
    return self._next()
  File "/usr/local/lib/python3.9/site-packages/werkzeug/wrappers/base_response.py", line 45, in _iter_encoded
    for item in iterable:
TypeError: 'FileNotFoundError' object is not iterable
Exception while creating consumer - [Errno 2] No such file or directory
`

**Comment by jeffwidman** [comment]
This looks like a `werkzeug` issue based on the traceback... the creating consumer part is probably related to something in there...  maybe a missing config file?
