### ISSUE TITLE
DNS lookup fails on remote Kafka 

### ISSUE THREAD

**Issue by alisoho** [dpkp/kafka-python#2156]
Hi,

I am trying to publish Json messages to a remote Kafka with:

```
p = {"message": "json"}
producer = KafkaProducer(bootstrap_servers={ip:port}, value_serializer=lambda v: json.dumps(v).encode('utf-8')) 
producer.send({topic}, p)
```

but I am getting this:

`ERROR:kafka.conn:DNS lookup failed for client:9092 (AddressFamily.AF_UNSPEC)
WARNING:kafka.conn:DNS lookup failed for client:9092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
`

I can resolve this by adding client with Kafka server IP in "hosts", but how can I fix this in general without touching hosts?

**Comment by jeffwidman** [comment]
It's either a networking issue within your environment, or it's possibly misconfigured advertised listeners... this may help: https://www.confluent.io/blog/kafka-listeners-explained/
