### ISSUE TITLE
The "offset" argument in the consumer "commit" method is completely ignored

### ISSUE THREAD

**Issue by pauelm** [dpkp/kafka-python#2164]
When making a call to the consumer "commit" method and specify a valid name for offset parameter, the following error is thrown:

'Requires group_id' 

This error occurs on line 524 in group.py.

This error is thrown regardless if the group ID is specified or not, even though the group_id was explicity specified at the time for the consumer object when KafkaConsumer method is successfully called / created.

It appears that the offset argument is completely ignored.

kafka-python:  2.0.2
Python:  3.9.0

**Comment by dpkp** [comment]
The `offsets` parameter to KafkaConsumer.commit must be a dictionary with keys of type TopicPartition and values of type OffsetAndMetadata. This parameter is not required, however, and defaults to committing the last consumed message offsets. I believe it is exceptionally rare for anyone to use the offsets parameter directly, but it is included as an advanced feature (primarily to support metadata, which is not for the faint-of-heart).

I was not able to reproduce the 'Requires group_id' error you mentioned:

```
from test.fixtures import ZookeeperFixture, KafkaFixture
zk = ZookeeperFixture.instance()
k = KafkaFixture.instance(0, zk)

from kafka import KafkaConsumer
consumer = KafkaConsumer(bootstrap_servers='{}:{}'.format(k.host, k.port), group_id='foobar')
consumer.commit()
# no exception raised
```
