### ISSUE TITLE
Neither "auto_commit_enable" / "enable_auto_commit" function properly, and documentation should be updated to avoid confusion.

### ISSUE THREAD

**Issue by pauelm** [dpkp/kafka-python#2165]
When a consumer object is created, neither the "auto_commit_enable" or "enable_auto_commit" parameters function properly.  Also, these parameters are redundant, and once the defect is resolved, one should replace the other.

auto_commit_enable
enable_auto_commit

References:
https://codesuche.com/python-examples/kafka.KafkaConsumer/
https://kafka-python.readthedocs.io/en/master/_modules/kafka/consumer/group.html

Kafka-Python:  2.0.2
Python:  3.9.0

**Comment by dpkp** [comment]
There is no `auto_commit_enable` parameter. It looks like you are reading some 3rd party code samples that are incorrect (or at least out of date). We have no control over what is posted on the internet! Please refer to the online documentation for correct API usage:

https://kafka-python.readthedocs.io/en/master/apidoc/KafkaConsumer.html
