### ISSUE TITLE
When wiil you do the next Relaese on pipy?

### ISSUE THREAD

**Issue by mberkman-psh** [dpkp/kafka-python#2184]
I am seeing in pipy that the last released version doesnt support kafka v2.6
But master code here on github does.

I need 2.6 support for my python project, want to know when do you plan to have the next release for that

**Comment by dpkp** [comment]
Are there specific features you need? If not, the kafka protocol is backwards compatible and kafka-python should be able to connect + work with 2.6 brokers without much fuss. The master branch added support for a few new apis and protocol updates in 2.6, but unless you need them specifically you shouldn't need to wait for a new release.
