### ISSUE TITLE
KafkaProducer never sent message Please help stuck from a week nothing works

### ISSUE THREAD

**Issue by iam-jay** [dpkp/kafka-python#2227]
producer = KafkaProducer(bootstrap_servers=[<server>], value_serializer=lambda v: json.dumps(v).encode('utf-8'))
producer.send("<topic>", data2).add_callback(on_send_success).add_errback(on_send_error)
producer.flush()

File "produce.py", line 9, in <module>
    producer = KafkaProducer(bootstrap_servers=['<servers>'], value_serializer=lambda v: json.dumps(v).encode('utf-8'))
  File "/Users/jay.prakash/UpGrad/csa/lib/python3.6/site-packages/kafka/producer/kafka.py", line 382, in __init__
    **self.config)
  File "/Users/jay.prakash/UpGrad/csa/lib/python3.6/site-packages/kafka/client_async.py", line 242, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/Users/jay.prakash/UpGrad/csa/lib/python3.6/site-packages/kafka/client_async.py", line 925, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable

**Comment by ryuzak** [comment]
I used to have this problem when i just had one instance of kafka running. There is some problems when it is receiving a lot of data, your kafka broker tends to block itself which causes the unavailability of the broker. I read in a lot of blogs that the recommendations are at least 3 kafka brokers so you have a fallback to avoid this kind of problems. Now i have a minimun of 5 instances of kafka running over docker and the problem dissapeared.

i hope this helps you.

**Comment by Raniem-Ar** [comment]
@ryuzak thanks for you answer, can you please refer to some documentation where it is recommended to use at least 3 Kafka brokers. Thanks a bunch!

**Comment by iam-jay** [comment]
I am using 3 brokers. Basically, greater than one and odd brokers recommended for the elect a  leader.
