### ISSUE TITLE
Why does producer asks for describing every topic in cluster?

### ISSUE THREAD

**Issue by Pyrrha** [dpkp/kafka-python#2244]
Hello,

I received a lot of logs, where I see that kafka-python try to describe every topic of the cluster, with Denied result. I don't know where this list come from, and why the package use it and ask for a describe.

Do you know where I can disable the "auto-discovery" feature of the package? It's on kafka-python==1.4.6.
The documentation doesn't seem to indicate something about it.

Thanks!

**Comment by lquastana** [comment]
Hi , 

We have the same issue ... @Pyrrha , have you found a solution for this problem ? 

Thank you

**Comment by lquastana** [comment]
We find a solution , if you set bootstrap_topics_filter parameter with the topics needed, the producer only do the describe on the specified topics. For the consumer its a little bit tricky because the argument is not accepted by the constructor :(

**Comment by Pyrrha** [comment]
Hello @lquastana, this subject wasn't a priority so we didn't dig a lot since my post. Moreover, I went in vacation...
Thanks for your advice, I'll add this modification when back at the office, and look after a solution for the consumer part.

**Comment by dinegri** [comment]
It happening in our cluster as well. We have almost 2000 topics, because of that we noticed a latency increase in kafka request handler because it is writing in the log4j files authorizer 1999 denied describe (we changed for ERROR)…We’ll try to use bootstrap_topics_filter

**Comment by Pyrrha** [comment]
As far as I remember, it solved our issues to use the filter.
