### ISSUE TITLE
Any plan to support producer config enable.idempotence?

### ISSUE THREAD

**Issue by dongwook-chan** [dpkp/kafka-python#2266]
I've been using kafka-python for quite a while.
I need utilize kafka's **exactly-once semantics** from now on.
But it seems that **kafka-python doesn't support enable.idempotence** config.
The only feasible option is to switch to confluent-kafka.
However, I think kafka-python is by far the best python API out there and this makes me hesitate to switch.

So, I wonder is there any **plan to support enable.idempotence** in the future?

**Comment by MateusMarcuzzo** [comment]
> I've been using kafka-python for quite a while. I need utilize kafka's **exactly-once semantics** from now on. But it seems that **kafka-python doesn't support enable.idempotence** config. The only feasible option is to switch to confluent-kafka. However, I think kafka-python is by far the best python API out there and this makes me hesitate to switch.
> 
> So, I wonder is there any **plan to support enable.idempotence** in the future?

There's an old issue regarding the same need: 

https://github.com/dpkp/kafka-python/issues/1396

I wish we could have this property, too

**Comment by dongwook-chan** [comment]
@MateusMarcuzzo 
Thank you for sharing the information.
I appreciate your kindness.
