### ISSUE TITLE
ImportWarning on Python 3.10

### ISSUE THREAD

**Issue by pcarn** [dpkp/kafka-python#2282]
When using Python 3.10, kafka-python 2.0.2, in `python -Wd`:

```
>>> from kafka import KafkaConsumer
<frozen importlib._bootstrap>:914: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:671: ImportWarning: _SixMetaPathImporter.exec_module() not found; falling back to load_module()
```

Needs find_spec and exec_module here https://github.com/dpkp/kafka-python/blob/f19e4238fb47ae2619f18731f0e0e9a3762cfa11/kafka/vendor/six.py#L170

**Comment by francipvb** [comment]
Hello,

Any solution to this?
