### ISSUE TITLE
is master branch stable?

### ISSUE THREAD

**Issue by Domoryonok** [dpkp/kafka-python#2297]
Hello, from [this issue](https://github.com/dpkp/kafka-python/issues/2290) I see that the project is not actively maintained anymore, so my question is master branch contain a stable codebase, I need some functionality that is only in master, but idk if there are any known issues in this code?

**Comment by jeffwidman** [comment]
Known issues are listed on the issue tracker. If you encounter something that doesn't have a known issue, please file a new bug so that future developers can see what the current issues are.
