### ISSUE TITLE
Kafka version 3.x support

### ISSUE THREAD

**Issue by awsmasudur** [dpkp/kafka-python#2343]
As per the doc (https://kafka-python.readthedocs.io/en/master/compatibility.html), kafka-python is not compatible with Kafka version 3.x. Could you please add support for Kafka version 3.x?

**Comment by marcosschroh** [comment]
Hi,

Do we know the status of this? Did you manage to do some testing with kafka 3.x.x?

**Comment by bpuri7** [comment]
Bumping up the previous comment, 

> Do we know the status of this? Did you manage to do some testing with kafka 3.x.x?
