### ISSUE TITLE
Release plan for kafka-python

### ISSUE THREAD

**Issue by sahil3390** [dpkp/kafka-python#2353]
As per understanding its last release was released in 2020, after that 
there is no release. We are planning to use v2.0.2, if we face any 
issue in this version will it fixed in any upcoming release or what 
should be the workaround.

Can you please share the release plan for kafka-python?

Regards,
Sahil

**Comment by jack-mcivor** [comment]
FYI there is some discussion of the maintenance of the project here https://github.com/dpkp/kafka-python/issues/2290

**Comment by wbarnha** [comment]
Kafka-python will be coming back to life very shortly, please follow the discussion in https://github.com/dpkp/kafka-python/issues/2290!
