### ISSUE TITLE
Internally handle Heartbeat poll expiration

### ISSUE THREAD

**Issue by Diego-Hernandez-Moodys** [dpkp/kafka-python#2360]
I'd like to catch a Heartbeat poll expiration and trigger a shutdown when it happens. What triggers the heartbeat poll warning?
```
    logger.info("Calling consumer")
    try:
        for message in instance_consumer:
            if message is None:
                logger.debug("Empty message")
                continue
            if message.value is None:
                continue
            if not message.headers:
                logger.warning(f"Empty header: {message.timestamp}, {message.partition}, {message.offset}")

            instance_queue.put(message_decoded)

            if event_shutdown.is_set():
                logger.warning("Stopping GET messages")
                break
    except kafka.errors.??? as error: # <------
        logger.warning(error)
        event_shutdown.set()        
```

**Comment by mro-rhansen2** [comment]
Is this the message that you're referring to?

https://github.com/dpkp/kafka-python/blob/0864817de97549ad71e7bc2432c53108c5806cf1/kafka/coordinator/base.py#L992

If so,then there's not any sort of event triggered when a heartbeat expiration occurs. It just goes right into the normal coordinator shutdown routine. Your only hope of doing exactly as you're looking to do would be to globally monkeypatch the base coordinator's `maybe_leave_group()` method and wire up some post operations that way.

The client does seem to emit events but I don't recall what they support off the top of my head as I am not a contributor here. I'm actually trying to figure out a separate issue. I just happened to spend a lot of time in that area of the code in doing so and figured that I could answer your question. Check out the events that they do currently offer. There might be something there that you can work with. 

On a side note - why do you feel the need to close the consumer manually on heartbeat timeout?

**Comment by Diego-Hernandez-Moodys** [comment]
Aah, no wonder. I couldn't find that snippet.

I wasn't aware the poll_timeout_expired() caused the consumer to "maybe_leave_group". Although I closed the consumer manually in order to fail fast since I suspected it didn't raise any error.
