### ISSUE TITLE
Increase message size > 1mo

### ISSUE THREAD

**Issue by Zat-Code** [dpkp/kafka-python#2372]
Hello, 

I would like to increase the size of messages > 1mo in order to send more data on a rare event. 

I saw that I had to do several things: 

- Broker side: 
  
  add the following parameters to the server.properties file of my kafka server: 
  
  message.max.bytes=15728640
  replica.fetch.max.bytes=15728640
  
  15728640 being 15 * 1024 * 1024

- Producer code side : 

  Without max_request_size=15728640 parameter
  I had the following error: 
  
![image](https://github.com/dpkp/kafka-python/assets/33628286/28f98f0e-908e-4893-bab6-c1a04b6a3b31)

with the parameter, I get the following error: 

![image](https://github.com/dpkp/kafka-python/assets/33628286/25c66e72-43b3-4c4b-96f4-9a087af041c0)

![image](https://github.com/dpkp/kafka-python/assets/33628286/6e6abbef-ab52-4666-9f18-7a18a7f4e8f1)

- Consumer side :

On the consumer side, I have defined the following max_partition_fetch_bytes parameter

![image](https://github.com/dpkp/kafka-python/assets/33628286/b48d10ab-d7b6-4a5c-af7f-e1b335d8645a)

Did I miss something? 

I followed several topics on the internet that talked about this and apparently it doesn't pose a problem up to ~20mo.

**Comment by wbarnha** [comment]
I recommend reviewing https://stackoverflow.com/a/59328711/9852671, max message size is usually 1 MB but other people have been able to increase message size following suggestions in https://stackoverflow.com/a/68319460/9852671.
