### ISSUE TITLE
Support SSL for v0.9.0

### ISSUE THREAD

**Issue by joestein** [dpkp/kafka-python#253]
Kafka is adding SSL support => https://issues.apache.org/jira/browse/KAFKA-1477 and would be great to have this available in python libraries.

**Comment by davidrabinowitz** [comment]
+1

**Comment by dpkp** [comment]
I adapted Ormond's PR (474) and pushed to this branch: https://github.com/dpkp/kafka-python/tree/ssl_support . It needs some testing and hopefully validation from a few more eyeballs...
