### ISSUE TITLE
adding new partitions to a topic is ignored by producer

### ISSUE THREAD

**Issue by hzshlomi** [dpkp/kafka-python#265]
I just left a keyed producer sending to the topic on one tty and had the topic added more partitions on the other tty and saw that the partitioner never saw the new partitions and hence was producing only to the old partitions leaving the newly added ones empty

**Comment by dpkp** [comment]
same issue as #264 -- none of the producer code handles metadata refreshes.  keyed producer needs to reset the `partitioners` dict.

**Comment by dpkp** [comment]
The new KafkaProducer in master refreshes metadata on a configurable timeout (`metadata_max_age_ms`). There are no plans to update SimpleProducer / KeyedProducer .
