### ISSUE TITLE
Does kafka-python support broker rebalancing?

### ISSUE THREAD

**Issue by ddieterly** [dpkp/kafka-python#269]
I understand that kafka-python does not do consumer rebalancing (consumer failover) when consumers come and go. That has been made clear by other discussion threads. How does kafka-python handle broker rebalancing? Does it handle broker rebalancing?

From https://cwiki.apache.org/confluence/display/KAFKA/Consumer+Client+Re-Design we see that the high-level Java Consumers do the following:

1) Auto/Hidden Offset Management
2) Auto(Simple) Partition Assignment
3) Broker Failover => Auto Rebalance
4) Consumer Failover => Auto Rebalance

We know that kafka-python does not do #4, the consumer failover. Which of the others does kafka-python handle? Or conversely, which of the others does kakfa-python not handle? It appears to be handling #1 but none of the others. Can we get confirmation on that?

Thanks.

**Comment by jyotidhiman0610** [comment]
What's the ideal solution for broker rebalancing?
