### ISSUE TITLE
No handlers could be found for logger "kafka"

### ISSUE THREAD

**Issue by Dinoshauer** [dpkp/kafka-python#278]
When a handler is not set up by the application that uses kafka-python this message is emitted:
``No handlers could be found for logger "kafka"``

I've read in the docs that you can use a "NullHandler" or something else that emits nothing, so that a handler is found to get around this issue: https://docs.python.org/3.1/library/logging.html#configuring-logging-for-a-library - Would that be something of interest? I might be able to do a PR in the near future if there is a consensus for it

**Comment by dpkp** [comment]
I think that would be a nice improvement -- PR welcome!
