### ISSUE TITLE
how to improve SimpleConsumer throughput?

### ISSUE THREAD

**Issue by scootli** [dpkp/kafka-python#284]
My problem is:
One thread consumes one specific partition. All consumes  have same group. But I find the throughput of single consumer is about 20MB/sec. I have six partitions in the topic. The message size in the kafka queue is about 1.5KB. When the message size is 700KB, i find the the throughput of single consumer is about 180MB/sec in same the configs of the consumer and the kafka. But I cann't change the message size. Can I  improve kafka consumer throughput by the configs of the kafka or the configs of consumer? 

our configs of the consumer   is as follow:
onsumer = SimpleConsumer(kafkaclient, "yunjiasu", “topic”,
                                          auto_commit=True,partitions=[0],
                                          fetch_size_bytes=8192,buffer_size=1048576,max_buffer_size=2097152)

message = consumer.get_message(True,60)

our configs of the kafka are as follow(the kafka cluster has six machines):
broker.id=5
port=9092
host.name=10.205.35.11
num.network.threads=5
num.io.threads=8
socket.send.buffer.bytes=5048576
socket.receive.buffer.bytes=5048576
socket.request.max.bytes=104857600
log.dirs=/home/work/kafka/kafka-logs,/home/disk0/kafka-logs,/home/disk1/kafka-logs,/home/disk2/kafka-logs,/home/disk3/kafka-logs,/home/disk4/kafka-logs
num.partitions=5

log.retention.hours=24

message.max.bytes = 5000000

replica.fetch.max.bytes = 5048576

default.replication.factor = 2

log.segment.bytes=536870912
log.retention.check.interval.ms=60000
log.cleaner.enable=false
zookeeper.connect=10.206.215.54:2181,10.206.215.55:2181,10.206.215.57:2181
zookeeper.connection.timeout.ms=1000000

Thanks！

**Comment by scootli** [comment]
My message size is 1.5KB, so I cann't change the message size. how to improve kafka consumer throughput by other way?

**Comment by dpkp** [comment]
Development has shifted to KafkaConsumer which allows for multiple consumer instances to distribute partition assignments.
