### ISSUE TITLE
Remove support for ProduceRequest acks>1 for 0.8.3

### ISSUE THREAD

**Issue by dpkp** [dpkp/kafka-python#294]
server 0.8.3 is expected to raise an exception on ProduceRequests with ack>1 .  See KAFKA-1697

kafka-python should update interface, code, and docs to reflect the new approach to produce request "acks".

**Comment by wizzat** [comment]
Should we just go forward with "-1, 0, 1" as the only allowable values?

**Comment by dpkp** [comment]
yes, i think that is what the server supports going forward

**Comment by dpkp** [comment]
KafkaProducer takes `acks` as 0, 1, or all. No plans to put parameter validation at the protocol level or to update SimpleProducer.
