### ISSUE TITLE
When only one partition have data, simple consumer will hang

### ISSUE THREAD

**Issue by 0scarLi** [dpkp/kafka-python#327]
Hi,
I've recently encounter this problem that simple consumer will hang, if only one of the partitions have data. I have a topic that have 4 partitions, due to a bug on my end only one of the 4 partitions have data and rest 3 have 0 entries. I found that in this case, simple consumer will hang (does not receive any data) and it seems like it's waiting for rest of the partitions to get data. And eventually it will time out.

My consumer looks like this:
consumer = SimpleConsumer(kafka_client, "my-group", source_topic, iter_timeout=60*30)

Is this intended behaviour of is this something that might need to addressed? For my case, the 'Basic' consumer works just fine.

Thanks a lot

**Comment by dpkp** [comment]
do you mind trying the new `KafkaConsumer` interface?

**Comment by dpkp** [comment]
This behavior will happen if your partitions are distributed across multiple brokers. The current consumer implementation does not process broker requests in parallel, so a single blocking fetch request will block the entire consumer, even if other brokers would have responded immediately.

Fixing this involves either spawning a different thread per broker or using an async event loop. I dont have a timeline for either of those currently, so for now we will have to leave this open.

**Comment by dpkp** [comment]
I believe this is fixed as of PR #473
