### ISSUE TITLE
KafkaConsumer always get some commited data after restart

### ISSUE THREAD

**Issue by halolk** [dpkp/kafka-python#343]
Hi all,

I'm using SimpleProducer and KafkaConsumer to process some web logs. A strange thing is that although the Consumer has read all the messages and Producer is not running any more, if I terminate the processes using KafkaConsumer and rerun them, they will still read some old messages again. Since my script enabled auto_commit (and even explicitly called commit() for every message later), and the Consumer called set_topic_partitions(), I expected the Consumer will noitce the offset and get nothing. But no matter how many times I restart the processes, they will always read a random number of commited old messages (not all commited messages).

Can you point out any idea about this problem? Thanks a lot!

**Comment by dpkp** [comment]
Are you using compressed messages?  The last release has a bug that can cause compressed messages to be processed more than once.

**Comment by halolk** [comment]
Hi,

Thanks dpkp! I saw that issue, but looks like my codes didn't use compression. Here are the codes:

    broker_list = ['192.168.1.187:9092', '192.168.1.1:9092',
                   '192.168.1.156:9092']
    consumer = kafka.KafkaConsumer('mytopic', group_id='mygroup',
                             metadata_broker_list=broker_list,
                             auto_commit_enable=True,
                             auto_commit_interval_ms=30 * 1000)
    consumer.set_topic_partitions({'mytopic': part_list})

    for msg in consumer:
        /* codes to process message */
        consumer.task_done(msg)

(part_list is a list of partition numbers for this consumer to process)

**Comment by dpkp** [comment]
ok, I think what is happening here is that the consumer is committing on the 30sec timed interval you've configured (`auto_commit_interval_ms=30 * 1000`), but when you quit the script any messages since the last 30sec interval will not be saved.  What we should do here is do a final commit on `__del__` when doing auto_commit.

**Comment by dpkp** [comment]
removing from 0.9.4 -- you can explicitly call kafka.commit() before exiting your script to make sure all commits are stored.

**Comment by dpkp** [comment]
Updated KafkaConsumer to expose the official java api. Use KafkaConsumer.close() to commit any pending offsets that have not yet auto-committed. Also note that the default auto-commit-interval has been reduced to 5 seconds.
