### ISSUE TITLE
MultiProcessConsumer with multiple topics

### ISSUE THREAD

**Issue by kornicameister** [dpkp/kafka-python#348]
Is there a plan to support MultiProcessConsumer with multiple topics ? As far as I know it seems to be not implemented at this point.

For following code:
```python
self.consumer = MultiProcessConsumer(
                client=kafka_client,
                group=None,
                topic=['a','b'],
                num_procs=2,
                partitions_per_proc=1
            )
```
the error is thrown at ***kafka/client.py** line 123 (method *_send_broker_unaware_request*).

Could You tell me if such functionality is planned or feasible by means of creating own MultiProcessTopicConsumer or something ?

Best regards,
kornicameister

**Comment by dpkp** [comment]
There is no support for that currently -- you will have to manage your consumer processes directly.  The new KafkaConsumer class makes multi-topic consumers really easy, but it doesn't support multiprocess yet.

**Comment by kornicameister** [comment]
Thanks for quick answer. So basically what You are saying is that I could implement multiple topics functionality via the KafkaConsumer, is that so ?

Also just one last question, not directly associated with current one. Is there a way to inject some sort of message normalization into the the code which actually retrieves messages. I would like minimize a job required to loop over 100k messages for instance before processing them further ?

Could it be done with the help of a serializer class of some sort ? Like for instance, let's take JSON processing and dozens of possible classes to handle this task ?

**Comment by dpkp** [comment]
The new KafkaConsumer w/ group coordination should make distributing consumption of multiple topics across multiple consumer processes relatively easy.
