### ISSUE TITLE
Support for gevent, process and threaded drivers

### ISSUE THREAD

**Issue by mahendra** [dpkp/kafka-python#37]
@mumrah I took the branch based on #35 and #36 - and added support for something called drivers.

Basically, if you look at the code base, we use <tt>Queue()</tt>, <tt>Event()</tt>, <tt>sleep()</tt>, <tt>socket</tt> and <tt>multiprocessing.Process()</tt> to run the show - workers, multiple-consumers and co-ordination.

Now, <tt>Queue</tt>, <tt>Event</tt>, <tt>Pool</tt>, <tt>sleep</tt>, <tt>socket</tt> etc. are provided by <tt>multiprocessing</tt>, <tt>threading</tt> and <tt>gevent</tt>. So, the code can be used as-is (almost) for running it as different process, threads or gevent co-routines.

When <tt>SimpleConsumer</tt> or <tt>MultiConsumer</tt> is initialized, we can specify driver = thread / process / gevent and
* in <tt>SimpleConsumer</tt> - commit thread will run as a thread/process/gevent-coroutine
* In <tt>MultiConsumer</tt>, the various fetches (among which the partitions are distributed) will be run under different threads, processes or gevent co-routines.

The changes are very negligible. The only complexity is in managing the duplicate connections. When a consumer is initialized, an appropriate driver (<tt>KafkaDriver</tt>) instance is created, which contains the modules that must be used.

Most involved work was in test cases :-)

You can see the diffs here (on top of #35 and #36). 
https://github.com/mahendra/kafka-python/compare/mpcommit...gevent

Will send a pull request after they are merged. Later will provide driver support for <tt>Producer</tt>

**Comment by little-arhat** [comment]
What is the state of this issue? Haven't found any notion of "drivers" or "driver_types" in the current HEAD.

**Comment by dpkp** [comment]
There is no work on this afaik.

**Comment by dpkp** [comment]
There are no plans to use pluggable driver support. The current client code now has a very simple async io loop. I expect that if we were to implement a full async io stack, we would probably use asyncio.
