### ISSUE TITLE
Unknown configuration key(s): ['bootstrap_servers'] 

### ISSUE THREAD

**Issue by tarikd** [dpkp/kafka-python#370]
I'm having an issue with kafka-python when trying to implement a kafka consumer. I have a kafka broker running flawlessly and a topic full of logs but when i do this (like in the doc examples) : 

     consumer = KafkaConsumer("clusters_centers", group_id="spark-streaming-consumer", bootstrap_servers=["localhost:9092"]) 

I get this error message : 

     kafka.common.KafkaConfigurationError: Unknown configuration key(s): ['bootstrap_servers'] 

I'm using exactly the same code snippet as in the doc and my kafka is running on port 9092.

**Comment by dpkp** [comment]
Hi tarikd - unfortunately the docs are currently for master. For 0.9.3 release, use 'metadata_broker_list' as the configuration key instead. That key is deprecated in favor of bootstrap_servers in the upcoming 0.9.4 release.

**Comment by Shaunwei** [comment]
Hi dpkp - When will we have 0.9.3 release, I found the current docs has a lot mismatch.

**Comment by tarikd** [comment]
Hi guys, I managed to work with kafka-python partially using the multiprocess consumer, but a simple code like this one : 

    from kafka import SimpleProducer, KafkaClient, KafkaConsumer

    # To send messages synchronously
    kafka = KafkaClient("localhost:9092")
    producer = SimpleProducer(kafka)

    # Note that the application is responsible for encoding messages to type str
    producer.send_messages("my-topic", "some message")
    producer.send_messages("my-topic", "this method", "is variadic")

    # To consume messages
    consumer = KafkaConsumer("my-topic", group_id="my_group", metadata_broker_list=["localhost:9092"], client_id="my_client")
    for message in consumer:
        print("%s:%d:%d: key=%s value=%s" % (message.topic, message.partition,
                                         message.offset, message.key,
                                         message.value))

    kafka.close()

I get this error : 

    No handlers could be found for logger "kafka.consumer.kafka"

**Comment by dpkp** [comment]
see #278 re: logger
