### ISSUE TITLE
Support Consumer-Coordination / Rebalancing

### ISSUE THREAD

**Issue by mahendra** [dpkp/kafka-python#38]
Implemented simple Zookeeper support. Using Kazoo.

This was built on top of the gevent patch (#37).
* For Producer, it provides support retries in case there is an error during send
* For SimpleConsumer, it provides support for re-balancing of partitions among other kafka-python clients. (We can look at full support for Java/Scala clients once the new design is finalized). This will allow us to use kafka as a backend for systems like celery.

You can have a look at the code here:
https://github.com/mahendra/kafka-python/compare/gevent...zookeeper

Not tested yet. Will keep updating the code as I progress with the tests.

**Comment by dpkp** [comment]
Kafka 0.9.0.0 Group Coordination support has been added to KafkaConsumer in the 0.9 git branch. I'm planning to merge to master soon and will cut a new release after a bit more testing.

**Comment by dpkp** [comment]
group coordination merged to master.
