### ISSUE TITLE
SimpleConsumer gzip message return error

### ISSUE THREAD

**Issue by haosdent** [dpkp/kafka-python#381]
I use
```
consumer = SimpleConsumer(self._kafka, self._consumer_group, self._topic, partitions=self._partitions)
```

And my producer write gzip compression message to kafka. But consumer side I use python-kafka, it always return this error:

```
WARNING:kafka:Fetch size too small, increase to 8192 (2x) and retry
WARNING:kafka:Fetch size too small, increase to 16384 (2x) and retry
```

If I don't use gzip, it works well. Anything I wrong here?

**Comment by dpkp** [comment]
Will try to reproduce - what client are you using to produce messages?

**Comment by haosdent** [comment]
Thank you for your reply, I use [rdkafka](https://github.com/edenhill/librdkafka) to produce message.

**Comment by haosdent** [comment]
When I use kafka-console-consumer.sh to consume the gzip message, it could works normal.

**Comment by dpkp** [comment]
Please reopen if this is still an issue
