### ISSUE TITLE
MultiProcessConsumer code not working

### ISSUE THREAD

**Issue by jpblair** [dpkp/kafka-python#385]
I'm trying to use the MultiProcessConsumer as shown in the "Usage" section of the docs, but I'm not able to connect to the Kafka server.  I'm getting this error:

Could not send request [1] to server localhost:9092, trying next server
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\kafka\client.py", line 116, in _send_broker_unaware_request
    payloads=payloads)
  File "C:\Python\lib\site-packages\kafka\protocol.py", line 377, in encode_metadata_request
    message.append(struct.pack('>h%ds' % len(topic), len(topic), topic))

Yet I do have a Kafka server running on my localhost, which I am able to access using the command line consumer:

kafka-console-consumer --zookeeper localhost:2181 --topic my-replicated

**Comment by dpkp** [comment]
kafka-python does not use zookeeper, can you verify that you are able to connect using
```
kafka-simple-consumer-shell.sh --broker-list localhost:9092 --topic my-replicated
```

**Comment by jpblair** [comment]
Yes, I am.  For what it's worth, I am able to use the single process KafkaConsumer without any problems.

**Comment by dpkp** [comment]
can you paste the code you are using to initialize the working KafkaConsumer and the failing MultiProcessConsumer?

**Comment by jpblair** [comment]
`from kafka import KafkaClient, MultiProcessConsumer

kafka = KafkaClient('localhost:9092')

# This will split the number of partitions among two processes
consumer = MultiProcessConsumer(kafka, 'test_consumer', 'my-replicated', num_procs=2)

for message in consumer.get_messages(count=5, block=True, timeout=4):
    print(message)`

**Comment by zhjchen** [comment]
How many partitions do you have for this topic ?

**Comment by dpkp** [comment]
MultiProcessConsumer is now deprecated.
