### ISSUE TITLE
Add gevent support for Producer

### ISSUE THREAD

**Issue by mahendra** [dpkp/kafka-python#39]
This will be done as soon as #37 and #33 are merged. Should be few lines of code.

You can see the diffs here (on top of #37). 
https://github.com/mahendra/kafka-python/compare/gevent...gevent-producer

**Comment by dpkp** [comment]
There are no plans to use pluggable driver support. The current client code now has a very simple async io loop. I expect that if we were to implement a full async io stack, we would probably use asyncio.
