### ISSUE TITLE
Null payload for Kafka log compaction deletion feature

### ISSUE THREAD

**Issue by vshlapakov** [dpkp/kafka-python#408]
According to [the official doc](https://cwiki.apache.org/confluence/display/KAFKA/Log+Compaction) Kafka log compaction could be used to delete messages from the log:
```Compaction also allows from deletes. A message with a key and a null payload will be treated as a delete from the log. This delete marker will cause any prior message with that key to be removed (as would any new message with that key), but delete markers are special in they will themselves be cleaned out of the log after a period of time.```

But now there's a [limitation](https://github.com/mumrah/kafka-python/blob/master/kafka/producer/base.py#L358) in the code that doesn't allow to pass null payloads, so the deletion feature doesn't work at all. Was it done by purpose for some reasons or I can prepare a short PR to fix it?

**Comment by vshlapakov** [comment]
Tested; Kafka deletion feature works with this patch, take a look please!

**Comment by dpkp** [comment]
PR welcome. Can you also take a look at https://github.com/mumrah/kafka-python/issues/124 while you're addressing None values?
