### ISSUE TITLE
Improve HTML documentation for readthedocs

### ISSUE THREAD

**Issue by dpkp** [dpkp/kafka-python#411]
http://kafka-python.readthedocs.org/en/latest/ is currently a little hard to digest. I think the first page should probably be or include the usage docs. The api reference also needs to be organized a bit. I think it would be useful to document by top-level class (KafkaClient, SimpleProducer, SimpleConsumer, etc), than by package / module. Within those docs we should probably also be a bit more selective about what is included and what the ordering is.

**Comment by dpkp** [comment]
also note that several modules are included multiple times, both as submodules (kafka.consumer.simple.SimpleConsumer) and as imported modules (kafka.SimpleConsumer).

**Comment by peichengcheng001** [comment]
In my opition, it is better to prodive more details about the APIs. For example, as for the kafka.client.KafkaClient class, I need to know what does close() do and when to use it. Also, as for the ensure_topic_exists(), at beginning, I thought it is used to check whether one topic exists. But finally, I found that it is used to create a new topic if not exists. Am I right? It is confusing when I use them.

**Comment by dpkp** [comment]
Updated docs organization in master. Open separate issues for specific documentation issues.
