### ISSUE TITLE
Handle temporary errors on getting offsets for consumer pending request

### ISSUE THREAD

**Issue by vshlapakov** [dpkp/kafka-python#417]
There are several very common [Kafka errors](https://github.com/mumrah/kafka-python/blob/4b064340e8796cb85307e014853ddb0435809f2f/kafka/client.py#L252) related with cluster changes. Currently these errors are followed by resetting metadata operation but then they are reraised as we're not sure if it's temporary or not.

But afaik **NotLeaderForPartitionError** is temporary, and in the case of getting offsets for calculating pending messages count - the offset request should be retried after getting fresh metadata. Is it so or it's a responsibility of user application and not kafka-python library to handle such errors when get pending count?

**Comment by dpkp** [comment]
That makes sense to me.  Want to submit a PR?

**Comment by vshlapakov** [comment]
Great! Yes, I'll prepare it then.

**Comment by dpkp** [comment]
closing per 0.9.0.0 KafkaConsumer refactor
