### ISSUE TITLE
Wrong KafkaUnavailableError

### ISSUE THREAD

**Issue by spicavigo** [dpkp/kafka-python#419]
client = KafkaClient(host)
    topic = u'topic'
    group = 'my-group'
    consumer = SimpleConsumer(client, group, topic)

    error: argument for 's' must be a string

This shouldn't be a problem but the fact is that `_send_broker_unaware_request` fails to report the exact error. I fished out the above error by inserting a raise in the except block of that function. Otherwise it would report this error:

    KafkaUnavailableError("All servers failed to process request")

The problem, of course, is that struct.pack is expecting a byte string and fails if we provide it a unicode string.

My suggestion is to perform a check before hand. Plus, a more robust exception handling than the catch all phrase. At the very least, differentiate between network error and local errors.

**Comment by dpkp** [comment]
Thanks for the bug report. I agree -- the existing protocol stack makes debugging difficult, and bytes/string handling is particularly gnarly. I've got a rewrite in the works that I hope will improve. But I'll leave this issue open until then.

**Comment by dpkp** [comment]
Closing b/c protocol stack has been rewritten. There are of course likely to be bugs, but they'll be different bugs so I'm going to close this issue.
