### ISSUE TITLE
Offset fetch request does not support Kafka-committed offsets

### ISSUE THREAD

**Issue by toddpalino** [dpkp/kafka-python#421]
The offset fetch request as implemented only supports offsets stored in Zookeeper. I've added support internally for fetching Kafka-committed offsets by adding the basic support needed for the consumer coordinator and adding a separate client method for fetching offsets from Kafka. The separate method is needed because fetching offsets from Kafka vs. from Zookeeper uses different versions of OffsetFetchRequest, even though the wire format is the same.

I've created PR #420 to add this functionality. We should be able to build the rest of the support for the consumer coordinator, including committing offsets to Kafka storage, from there.

**Comment by wushujames** [comment]
I'm interested in this functionality as well.

**Comment by zorkian** [comment]
+1. It'd be great to get PR #420 reviewed and merged if possible.

**Comment by dpkp** [comment]
merged
