### ISSUE TITLE
Exception when passing key in hashed.py

### ISSUE THREAD

**Issue by siniG** [dpkp/kafka-python#423]
Hi,
I receive the following error when trying to send a message using HashedPartitioner with Murmur2 function "TypeError: string argument without an encoding".

This happens on line #53 at the beginning of murmur2 method as bytearray is expecting encoding type which is not given.

# Convert key to a bytearray
    if not isinstance(key, bytearray):
        data = bytearray(str(key))

**Comment by mutability** [comment]
Together with #428 this makes Murmur2Partitioner unusable in python 3: you can't pass a bytearray, but you can't pass a non-bytearray either.

**Comment by dpkp** [comment]
fixed in PR #439
