### ISSUE TITLE
add new public method get_partitions_count to class KafkaConsumer

### ISSUE THREAD

**Issue by sunmoonone** [dpkp/kafka-python#430]
A method get_partitions_count would be helpful when I use multiple message handlers to process messages from one consumer.

I use produce(topic1,key1,msg) to make sure all messages with key1 go to the same partition, and want to dispatch messages from consumer(topic1,group1) to multiple message handlers, one handler process one partition in order to preserve the message insertion order.

### Pyseudocode
```python
consumer=KafkaConsumer(topic1, bootrap, group1)
count = consumer.get_partitions_count()
handlers=[Handler() for i in range(count)]

def dispatch(msg):
    handlers [msg.partition].handle(msg)
```

**Comment by dpkp** [comment]
The new KafkaConsumer interface exposes `assignment()` which will return the set of assigned TopicPartitions.

http://kafka-python.readthedocs.org/en/latest/apidoc/KafkaConsumer.html#kafka.KafkaConsumer.assignment
