### ISSUE TITLE
Feature: Delete topics

### ISSUE THREAD

**Issue by mcandre** [dpkp/kafka-python#433]
Could we expose topic deletion through the kafka-python library? I would appreciate the ability to delete topics as a setup method in my integration tests, similar to how a PostgreSQL integration test would delete all records.

**Comment by rquinlivan** [comment]
Unfortunately this is a limitation of Kafka currently. Deleting topics is non-trivial. It is generally better to let data age out of a topic when it is not longer needed instead of trying to manually prune the data as one would a database.

**Comment by dpkp** [comment]
My understanding is that there is no way for a client to delete topics via the server API. Happy to revisit if that changes.

**Comment by llamahunter** [comment]
https://kafka.apache.org/protocol#The_Messages_DeleteTopics

**Comment by jeffwidman** [comment]
We already have support for this at the protocol level: https://github.com/dpkp/kafka-python/pull/944

Adding the `AdminClient` interface is tracked in #935
