### ISSUE TITLE
If one topic does not exist, it will be created after produce() function called several times

### ISSUE THREAD

**Issue by peichengcheng001** [dpkp/kafka-python#442]
I am trying to produce one message "0---testing---" to topic "test9", which did not exist at beginning. It threw out Exception. So I made my program to produce again and again. It threw out Exception again and again. Finally, it was created. Following are some printout (See the Exception and the client info after "---Info of Kafka Client and Kafka Producer---"). Also, notice the highlight part in the attached picture.

![kafka-topic-issue](https://cloud.githubusercontent.com/assets/13469530/9010516/52385c76-3775-11e5-8f41-0b1581b046a1.png)

----------- 0 --------------
Exception while trying to produce msg: TopicMetadata(topic='test9', error=5, partitions=[])
Message: 0---testing---
Exception while trying to produce msg: TopicMetadata(topic='test9', error=5, partitions=[])
Message: 0---testing---
Exception while trying to produce msg: TopicMetadata(topic='test9', error=5, partitions=[])
Message: 0---testing---
Exception while trying to produce msg: TopicMetadata(topic='test9', error=5, partitions=[])
Message: 0---testing---
Exception while trying to produce msg: TopicMetadata(topic='test9', error=5, partitions=[])
Message: 0---testing---
Exception while trying to produce msg: TopicMetadata(topic='test9', error=5, partitions=[])
Message: 0---testing---
Exception while trying to produce msg: TopicMetadata(topic='test9', error=5, partitions=[])
Message: 0---testing---
Exception while trying to produce msg: TopicMetadata(topic='test9', error=5, partitions=[])
Message: 0---testing---
Exception while trying to produce msg: TopicMetadata(topic='test9', error=5, partitions=[])
Message: 0---testing---
Exception while trying to produce msg: TopicMetadata(topic='test9', error=5, partitions=[])
Message: 0---testing---
Exception while trying to produce msg: TopicMetadata(topic='test9', error=5, partitions=[])
Message: 0---testing---
---Info of Kafka Client and Kafka Producer---
*Kafka Client*
client_id: kafka-python
correlation_id: 14
hosts: [('localhost', 9092)]
brokers: {0: BrokerMetadata(nodeId=0, host='cyclops-9803', port=9092)}
timeout: 120
conns: {('localhost', 9092): <KafkaConnection host=localhost port=9092>, (u'cyclops-9803', 9092): <KafkaConnection host=cyclops-9803 port=9092>}
topics_to_brokers: {TopicAndPartition(topic='test1', partition=0): BrokerMetadata(nodeId=0, host='cyclops-9803', port=9092), TopicAndPartition(topic='test6', partition=0): BrokerMetadata(nodeId=0, host='cyclops-9803', port=9092), TopicAndPartition(topic='test2', partition=0): BrokerMetadata(nodeId=0, host='cyclops-9803', port=9092), TopicAndPartition(topic='test9', partition=0): BrokerMetadata(nodeId=0, host='cyclops-9803', port=9092), TopicAndPartition(topic='test7', partition=0): BrokerMetadata(nodeId=0, host='cyclops-9803', port=9092), TopicAndPartition(topic='test3', partition=0): BrokerMetadata(nodeId=0, host='cyclops-9803', port=9092), TopicAndPartition(topic='test4', partition=0): BrokerMetadata(nodeId=0, host='cyclops-9803', port=9092), TopicAndPartition(topic='test', partition=0): BrokerMetadata(nodeId=0, host='cyclops-9803', port=9092), TopicAndPartition(topic='test5', partition=0): BrokerMetadata(nodeId=0, host='cyclops-9803', port=9092)}

**Comment by dpkp** [comment]
The standard way to create a topic is to enable topic auto creation in your server properties (consult server documentation on this), then submit a MetadataRequest for the new topic name. The server will then begin initializing the new topic, electing a leader, and starting replication as configured. This process does take a short amount of time, so it is quite normal to see a small lag between when the server first "learns" of the new topic name and when it will accept produce and fetch requests.
