### ISSUE TITLE
async producer threads

### ISSUE THREAD

**Issue by imazor** [dpkp/kafka-python#449]
Hi,

I would like to understand little bit more the implementation of the async producer in kafka-python.

 I was reading in this link:
https://engineering.gnip.com/kafka-async-producer/
regarding the async producer concept, and according to the link the async producer creates a separate thread which manage the message sending to the kafka broker.
Also according to the link, in order to scale the async producer, one can use multiple kafka brokers, and in such case the async producer will create separate thread for each kafka broker.

Using kafka-python, I have noticed that indeed separate thread is created when using the async producer, however even when providing to the kafka client a list of kafka brokers (2 in my case), still only 1 thread is created.

***
kafka = KafkaClient('broker1:9092', 'broker2:9092')
producer = SimpleProducer(kafka, batch_send_every_n=50, batch_send_every_t=60, async=True)
***

Do I miss something or the kafka-python implementation different from the described in the link
(or perhaps I didnt understand the content of the link correctly ) ?

Thanks

**Comment by dpkp** [comment]
The link appears to describe a different client (perhaps the java client?). The current async design in kafka-python is to use a single-thread to handle IO across all brokers. 0.9.4 and earlier used sync io operations to process connections in sequence. A patch to be included in 0.9.5 changes this to a simple async io loop, which should improve throughput in some cases.

**Comment by dpkp** [comment]
The new KafkaProducer class (merged to master but as of today not released to pypi) is structured the same as the java client.

Pls reopen if this does not answer your question

**Comment by jeffwidman** [comment]
> The new KafkaProducer class (merged to master but as of today not released to pypi) is structured the same as the java client.

Does this mean it opens one background IO thread per broker in the cluster? Or one per broker that it needs to produce to (ignoring brokers that its not producing to)?
