### ISSUE TITLE
from-beginning equivalent when using the client

### ISSUE THREAD

**Issue by drorata** [dpkp/kafka-python#461]
The command line tool `kafka-console-consumer.sh` has the option `--from-beginning`. What is the client's equivalent?

**Comment by matthewfranglen** [comment]
You can create a `KafkaConsumer` with the `auto_offset_reset='smallest'` keyword argument:

```python
from kafka import KafkaConsumer

consumer = KafkaConsumer('test', bootstrap_servers=['localhost:9092'], auto_offset_reset='smallest')

consumer.offsets()
{'commit': {('test', 0): None},
 'fetch': {('test', 0): 0},
 'highwater': {('test', 0): None},
 'task_done': {('test', 0): None}}
```

**Comment by dpkp** [comment]
yes -- `auto_offset_reset='smallest'`

**Comment by dbolser** [comment]
This doesn't work for me. i.e. setting `auto_offset_reset='smallest',` doesn't give me the queue from the beginning. As a work around for testing I'm just changing the group_id.

**Comment by matthewfranglen** [comment]
`smallest` is deprecated, you should use `earliest`. See the docs on the KafkaConsumer or the [relevant fallback code](https://github.com/dpkp/kafka-python/blob/6b66e11529301b1958db7a5f34ca247490751fef/kafka/consumer/group.py#L318-L323):

         auto_offset_reset (str): A policy for resetting offsets on
            OffsetOutOfRange errors: 'earliest' will move to the oldest
            available message, 'latest' will move to the most recent. Any
            other value will raise the exception. Default: 'latest'.

**Comment by jmess4** [comment]
auto_offset_reset only kicks in if the consumer does not have a valid offset for a given partition. As far as I can tell the Kafka-python client does not natively have this functionality. You need to either change your consumer group or manually set the offsets for each TopicPartition.
