### ISSUE TITLE
[Question] How does the default kafka-python configuration differ from vanilla Java kafka configuration?

### ISSUE THREAD

**Issue by mcandre** [dpkp/kafka-python#462]
kafka-python makes Kafka so easy to use, that when I switched from a Python project to a Java project, I suddenly became aware of just how much configuration I need to get basic producers/consumers to work! The same simple producer/consumer structure that works in my Python projects, creates weird kafka errors (`Request of length 1937006964 is not valid, it is larger than the maximum size of 104857600 bytes. (kafka.network.Processor)` and `FailedToSendMessageException: Failed to send messages after 3 tries`) with Java producers/consumers.

Does kafka-python assume any particular client or server kafka configuration, that must be manually applied in a vanilla Java Kafka project?

**Comment by dpkp** [comment]
We've currently got 2 different consumers, SimpleConsumer and KafkaConsumer. SimpleConsumer has relatively few configuration options and they aren't correlated directly with the java client. KafkaConsumer is a more recent rewrite of the consumer class that attempts to mirror the java client configuration options.
