### ISSUE TITLE
MultiProcessorConsumer KafkaConnection object has no attribute host

### ISSUE THREAD

**Issue by wrivers** [dpkp/kafka-python#465]
version = kafka-python 0.9.4
OS; Windows 

When I try to create a multiprocess consumer, in the _mp_consume  function I am getting the above mentioned error. This is happening when the function is trying to call client.reinit() for whatever reason it appears as if the connections are not instantiated ? the host and port is missing from the object

**Comment by dpkp** [comment]
Both KafkaConnection and MultiProcessConsumer are deprecated now. If you are still using kafka-python, I suggest migrating to the newer KafkaConsumer interface
