### ISSUE TITLE
Implementation of Murmur2 hash has errors.

### ISSUE THREAD

**Issue by rthille** [dpkp/kafka-python#469]
See my comments on the commit: https://github.com/mumrah/kafka-python/commit/4e339a746d84650f75fb401e3bd9cfe6e3a65e00

The function will fail if passed a bytearray, and incorrectly calculates the hash if the length of the key % 4 is 2 or 3.

**Comment by dpkp** [comment]
Please take a look at PR #439 (merged). Does that address all of your concerns? If so, please close issue. If not, perhaps can you provide a few test cases?

**Comment by rthille** [comment]
The changes in the PR look good to me.
