### ISSUE TITLE
import Murmur2Partitioner and RoundRobinPartitioner

### ISSUE THREAD

**Issue by alexbarta** [dpkp/kafka-python#471]
Hi 

I'm not able to import Murmur2Partitioner and RoundRobinPartitioner from kafka as showed here http://kafka-python.readthedocs.org/en/latest/usage.html . I have easily fixed by myself adding those classes to __init__.py kafka file.

I'm the only one experiencing this?

Thanks

Alex Barta

**Comment by dpkp** [comment]
Good catch -- fixed in master
