### ISSUE TITLE
When consumer group will be implemented and released?

### ISSUE THREAD

**Issue by chengchengpei** [dpkp/kafka-python#472]
I found that even group_id is specified, it did not work at all. All the consumers with the same group_id can receive the same messages.

**Comment by edenhill** [comment]
@chengchengpei Pykafka has a balanced consumer: 
http://pykafka.readthedocs.org/en/latest/api/balancedconsumer.html

**Comment by gth828r** [comment]
I have heard that the plan for this project was to wait for the new consumer API to be implemented in order to support this (as opposed to using a client connection to Zookeeper).  Does anyone know if there is a timeline to add support for the new consumer API?

**Comment by fabeschan** [comment]
Well kafka 0.9 was released last week so we can work on that now, right? :-P

**Comment by dpkp** [comment]
0.9 client support is in progress. I expect to release a small bug-fix update first -- to include the merged PRs that haven't been released to pypi yet. Then we'll follow with a version bump and 0.9 support.

Work is happening on 0.9 branch

**Comment by dpkp** [comment]
See issue #38 for more info
