### ISSUE TITLE
Socket issue with distributed Kafka partitions (timeout on one server?)

### ISSUE THREAD

**Issue by zoltan-fedor** [dpkp/kafka-python#476]
Environment:
- a topic with multiple partitions split between two Kafka servers (each topic is replicated, but the leadership is split between the two servers)
- using kafka-python to read from this topic and write into a file
- auto-commit offset is set to false, so after writing the file the file is read back to verify and only then the offset is committed
- high socket timeout set: socket_timeout_ms=60*60*1000

Issue:
When the file is big and it takes long (more than just 2-3 mins, for example about 30 mins) to read back the file to verify, when after verification the kafka offset is committed I receive the below error and only offsets of partitions hosted on one server has the new offset, while the other server has the old offsets.

Error received when committing after that 30 mins delay: 
```
ERROR:kafka.conn:Unable to receive data from Kafka
Traceback (most recent call last):
  File "/data/app/venv1/src/kafka-python/kafka/conn.py", line 103, in _read_bytes
    raise socket.error("Not enough data to read message -- did server kill socket?")
OSError: Not enough data to read message -- did server kill socket?
WARNING:kafka.client:ConnectionError attempting to receive a response to request 323 from server BrokerMetadata(nodeId=1, host=b'myserver2.com', port=9092): Kafka @ myserver2.com:9092 went away
```

And these are the new offsets (partitions of myserver1 got updated while myserver 2 aren't):
```
{   0: 373000849,
    1: 377241595,
    2: 373000849,
    3: 377241605,
    4: 373000849,
    5: 377241665,
    6: 373000849,
    7: 377241655,
    8: 373000849,
    9: 377241655,
    10: 373000849,
    11: 377241645,
    12: 373000849,
    13: 377241585,
    14: 373000849,
    15: 377241595}
```

Kafka connection has been opened as:
```
        kafka_consumer = KafkaConsumer(
            'mytopic'
            group_id='kafka_group_id',
            bootstrap_servers=['myserver1:9092', 'myserver2:9092'],
            consumer_timeout_ms=2000, 
            auto_commit_enable=False,
            socket_timeout_ms=60*60*1000
        )
```

It seems that on server times out while the other doesn't.
I have tried this multiple times and each time the same server (myserver2) was the one showing the issue, the other wasn't.
Is it possible that the socket_timeout_ms is only applied against one of the servers?

**Comment by dpkp** [comment]
What do the kafka server logs say? This error usually signals a server crash, perhaps caused by a malformed request. If that is the case, the server logs should include a stacktrace with more detail.

**Comment by dpkp** [comment]
KafkaConsumer has changed substantially since this was filed. But please reopen with more details if problem persists!
