### ISSUE TITLE
Question about producing in bulk

### ISSUE THREAD

**Issue by DataEngg** [dpkp/kafka-python#479]
Unable to send bulk messages to kafka server using kafka-python code. My requirement is to send messages in batch to kafka server but unable to send.

I need a help how should I able to send a bulk messages to kafka server using kafka-python. I read the documentation but it does have much of the information and example how to send the bulk messages.

Can anyone help me out from this?

I tried with create_message_set and created a set of messages but when i send the created set of message using producer.send_message(topic,message), i got an error raise TypeError("all produce message payloads must be type bytes"). Please help me out  

I am using Python 2.7 and  Kafka 0.8.2.1

**Comment by dpkp** [comment]
There are some examples here: http://kafka-python.readthedocs.org/en/latest/usage.html

You dont need to worry about create_message_set; `producer.send_message(topic,message)` accepts multiple messages:
```
topic = 'mytopic'
message1 = 'foo'
message2 = 'bar'

producer.send_message(topic, message1, message2)
```
You can include as many messages in this api call as you want.

**Comment by DataEngg** [comment]
Thanks dpkp

Suppose i have to send 20,000 messages at a time to kafka server, according to you would i need to declare 20,000 variables for sending a message to kaka server. 

I don't want to do like this. I need to have a set of messages in one place, after collecting a messages i just send a set of messages at one hit to kafka server.

**Comment by dpkp** [comment]
in your example you would just do:
```
producer.send_messages(topic, *message)
```
and it will send all messages together.

But kafka is a distributed, partitioned log system. So your group of 20,000 messages will very likely get split across all available partitions -- you wont actually be sending all messages together in a single batch.

Is there a reason you want direct control over the batching system? Typically users let the kafka client handle batching in the background.

**Comment by santosh-d3vpl3x** [comment]
@DataEngg: You could use lambdas along with the method suggested by dpkp.

@dpkp: Sometimes, status of tasks sending data to Kafka depends on whether data was sent to Kafka successfully or not. In such cases, async producer is too abstract to deal with. So burden of batching is transferred to developer. However, I don't really know what DataEngg is trying to achieve.

**Comment by StuartAxelOwen** [comment]
Possibly unrelated, but is there a similar `producer.send_messages` for bulk producing of keyed messages?  Something like `producer.send_messages(topic, *keyed_messages)`, where `keyed_messages` is a tuple[str, str]?

**Comment by dpkp** [comment]
@StuartAxelOwen the KeyedProducer interface currently only accepts a single key per call to send_messages. The signature is `send_messages(topic, key, *msg)`

**Comment by dpkp** [comment]
You might also try the new KafkaProducer interface, which -- like the java client -- will batch messages in the background according to various configuration parameters.

Please re-open if you'd like more help on this.
