### ISSUE TITLE
ImportError: cannot import name SimpleProducer

### ISSUE THREAD

**Issue by vlall** [dpkp/kafka-python#482]
Simple mistake, Closed

**Comment by 18308996929** [comment]
I has the same error， but I  donot know why

**Comment by niranj555** [comment]
Can you tell us what the error? Im stuck on this issue too

**Comment by jeffwidman** [comment]
As of Kafka-python 2.0, the SimpleClients are gone, see https://github.com/dpkp/kafka-python/commit/ed8c9cb2d2ad0d9eb2b37a0bdc3cf01ca253b2b9#diff-8b1c3fd0d4a6765c16dfd18509182f9dR3-R7.

Please open new tickets rather than commenting on tickets that are from 2015, it's unlikely we'll see them.
