### ISSUE TITLE
Enhancements: Some tips for performance

### ISSUE THREAD

**Issue by jackyfkc** [dpkp/kafka-python#492]
Some suggestions for improving performance

* Using **memoryview** when parsing response to avoid unnecessary copy, like **decode_fetch_response()** in **protocol.py**

* Recommend to use **concurrent.futures** instead of **_send_upstream**, so we can use multiple threads or processes if needed

**Comment by dpkp** [comment]
Thanks -- great suggestions. There is a fairly large refactor in the `0.9` git branch, including a re-written protocol stack that avoids unnecessary copying (using BytesIO buffers). Feel free to take a look and let me know if you have additional thoughts on that work. I expect to merge to master in the next few days.

Next up will be re-writing the async producer to align more closely with the java client KafkaProducer. I dont expect to use concurrent.futures b/c the kafka protocol is optimized for batch production over a small number of connections, not multiple concurrent producer threads each managing separate connections.
