### ISSUE TITLE
Help: Async Producer not working as expected

### ISSUE THREAD

**Issue by tsheasha** [dpkp/kafka-python#493]
I was trying to run the Producer in kafka.producer.base with async=True , however I noticed by debugging that the consumer thread iterated here https://github.com/dpkp/kafka-python/blob/v0.9.4/kafka/producer/base.py#L110 forever since it sees the queue with no items. However when I tried to print the qsize and items here: https://github.com/dpkp/kafka-python/blob/v0.9.4/kafka/producer/base.py#L377. I could see items and size > 0.

**Comment by dpkp** [comment]
Hi tsheasha: can you provide a code snippet that isn't working for you?

**Comment by tsheasha** [comment]
Hey dpkp sure, I have omitted some specific business logic

```python

from kafka import HashedPartitioner
from kafka.producer.base import Producer


class MyProducer(Producer, object):

    def __init__(self, *args, **kwargs):

        super(MyProducer, self).__init__(
            client,
            async=True,
            req_acks=acks, ack_timeout=ack_timeout,
            batch_send_every_n=batch, codec=codec,
            async_retry_limit=retries, async_retry_backoff_ms=stagger,
            async_stop_timeout=close_timeout,
        )

        self.partitions = self.client.get_partition_ids_for_topic(self.topic)
        if len(self.partitions) == 0:
            raise Exception("No partitions for the specified topic")

        #…. some partitioning logic

    def _next_partition(self, key):
        #….. next partition logic … 

    def send_messages(self, topic, key, *msg):
        topic = str(self.topic)

        partition = self._next_partition(key)

	 #…. more partitioning logic ….

        return self._send_messages(
            topic,
            partition,
            *msg
        )
```

When I call send messages and print some debug on https://github.com/dpkp/kafka-python/blob/v0.9.4/kafka/producer/base.py#L377 I see that the queue is being filled and the items are being placed. However I never seem to be able to get them from that queue at:  https://github.com/dpkp/kafka-python/blob/v0.9.4/kafka/producer/base.py#L110 since that queue is empty when i tried to check for elements in it.

**Comment by jackyfkc** [comment]
@tsheasha how did you start the python script? In my experience, some applications (like uWSGI) does not support Kafka async producer (via spawn a background thread) naturally if multiple processes are used.

**Comment by tsheasha** [comment]
@jackyfkc I just ran the script from shell using python not through uwsgi just a simole script invoked from shell

**Comment by dpkp** [comment]
I can't see an obvious problem here. I've run the async producer in the background of production uwsgi deployments w/ multiple processes -- I'm not aware of any problems doing that. Can you share any more detail? Are the messages definitely not being delivered? What do the debug logs say?

**Comment by tsheasha** [comment]
@dpkp unfortunately all I can see is that I can not read the message from the consumer. It seems they are not being delivered. When I turn async mode to False though, I receive the messages just perfectly. Can you help me find out somewhere to place a debug statement right before the real send is actually done, so I can see that printed out the results of the send to the console.

**Comment by dpkp** [comment]
Can you enable DEBUG logging for `kafka.producer` and post a snippet of
logs? Also, what is your configured batch_send_every_n (default is 20)?
Note that the default batch timer is 20seconds, so you should expect a
delay before messages are actually produced.

**Comment by tsheasha** [comment]
@dpkp Sure, I will turn that on and send over a snippet. As for batch_send_every_n I left that untouched however I am using batch_send_every_t and set that to 5 and I am waiting for longer than 5 seconds.

**Comment by tsheasha** [comment]
@dpkp These are all the log being produced multiply that by 15 minutes:
DEBUG:kafka.producer:Batching size: 128, timeout: 5
DEBUG:kafka.producer:Batching size: 128, timeout: 5
DEBUG:kafka.producer:Batching size: 128, timeout: 5
DEBUG:kafka.producer:Batching size: 128, timeout: 5
DEBUG:kafka.producer:Batching size: 128, timeout: 5
DEBUG:kafka.producer:Batching size: 128, timeout: 5
DEBUG:kafka.producer:Batching size: 128, timeout: 5
DEBUG:kafka.producer:Batching size: 128, timeout: 5

**Comment by dpkp** [comment]
which version of kafka-python are you using? v0.9.4 (guessing via the links above)? Have you tried with the latest release (0.9.5)? Also, what version of python? This feels like a `queue` variable name conflict, but it's hard to say because I can't reproduce locally.

**Comment by tsheasha** [comment]
I am using Python 2.7.6 and tried to use 0.9.5 same issue holds.

**Comment by dpkp** [comment]
can you add the queue id to your debug output to verify that the put and get operations are using the same object? [`id(queue)`]

**Comment by tsheasha** [comment]
```bash
DEBUG:kafka.producer:PUT: 50413512
DEBUG:kafka.producer:Batching size: 128, timeout: 5
DEBUG:kafka.producer:GET: 50413512
```

```diff
        while count > 0 and timeout >= 0:                               while count > 0 and timeout >= 0:
            try:                                                            try:
                log.debug("GET: {0}".format(id(queue)))       <
                topic_partition, msg, key = queue.get(timeout                   topic_partition, msg, key = queue.get(timeout
            except Empty:                                                   except Empty:
                break                                                           break
```

```diff
                try:                                                            try:
                    item = (TopicAndPartition(topic, partitio                       item = (TopicAndPartition(topic, partitio
                    log.debug("PUT: {0}".format(id(self.queue <
                    if self.async_queue_put_timeout == 0:                           if self.async_queue_put_timeout == 0:
                        self.queue.put_nowait(item)                                     self.queue.put_nowait(item)
                    else:                                                           else:
                        self.queue.put(item, True, self.async                           self.queue.put(item, True, self.async
```

**Comment by tsheasha** [comment]
I have tried also printing `msg` with the put and it is printed properly. I avoided displaying that in the output for sensitivity of the data

**Comment by dpkp** [comment]
ok, so the queues are the same. And you are seeing that the put operation succeeds, but the get operation always raises Empty ? That is extremely strange behavior.

**Comment by tsheasha** [comment]
exactly I tried printing the qsize() as well after the PUT although it is not always accurate as you can see however:
```bash
DEBUG:kafka.producer:PUT: 38612792 214
DEBUG:kafka.producer:PUT: 38612792 215
DEBUG:kafka.producer:PUT: 38612792 216
DEBUG:kafka.producer:PUT: 38612792 217
DEBUG:kafka.producer:GET: EMPTY RAISED 38612792 0
```

**Comment by dpkp** [comment]
hrmm. and to clarify -- are you also logging a debug statement after the get operation, but before the except -- to show successful gets?

**Comment by tsheasha** [comment]
Yes, however I have seen no successful gets so far

**Comment by dpkp** [comment]
have you tried running the kafka-python test suite locally (without modification)? does it pass? what OS are you running?

**Comment by tsheasha** [comment]
Tests fail, because dependency python-snappy could not be resolved since I need libpython-dev2.7 and since I am using Lucid that is not very trivial. It might actually be the fact that I am using lucid. I will try my code on a trusty box and get back to you with feedback tomorrow.

**Comment by dpkp** [comment]
Were you able to resolve this?
