### ISSUE TITLE
High CPU load when using Group Coordination

### ISSUE THREAD

**Issue by CVTJNII** [dpkp/kafka-python#494]
Using kafka.KafkaConsumer in multiple processes with the same group ID I'm noticing high CPU load when idle.  I'm running the kafka-python 0.9 branch (commit 31c3d59ee3507a65533a3db58dd0fa59d9925b11) against Kafka 0.9.0.0.  Group coordination is working as expected, with each message being processed by one consumer in the group, however (n-1)/n consumers in the group are running at 100% CPU.  With n=1 CPU load is low as expected, however with n>1 I see n-1 processes running 100% CPU as if they were busy-spinning.

I'm seeing this with the following, stripped-down consumer worker function:

```python
def consumer_worker(kafka_uri, topic, group_id, heartbeat, stats_array):
    consumer = kafka.KafkaConsumer(topic, group_id=group_id, bootstrap_servers=[kafka_uri])
    for message in consumer:
        print "consumer_worker iterating"
```

The print shows that the for isn't busy-spinning.  I have not performed any further profiling at this point.

**Comment by CVTJNII** [comment]
More details:

This is seen when the consumer count exceeds the partition count.  I was testing about with a single partition test topic, which is where the 1 in (n-1) appears to be coming from.  If I have more partitions than consumers things behave as expected.

I haven't proven that the worker with no subscriptions is the one spinning the CPU yet, but after enabling logging I do notice that workers without partitions throw this error:

Task <kafka.coordinator.consumer.AutoCommitTask object at 0x7f787c0a8390> failed: future failed without an exception

**Comment by dpkp** [comment]
Thabks

**Comment by dpkp** [comment]
Thanks Tom - I'll investigate. Seems likely that there is a bug in handling idle consumers.

**Comment by CVTJNII** [comment]
Here is the cProfiler output of the 'for message in consumer' block:
[profiler.txt](https://github.com/dpkp/kafka-python/files/79331/profiler.txt)

**Comment by CVTJNII** [comment]
It looks like the busy looping is coming from [KafkaClient._poll() in client_async.py](https://github.com/dpkp/kafka-python/blob/0.9/kafka/client_async.py#L314-L332).  When the client has assigned partitions self._conns has a connection with in flight requests populated, however with no partitions in_flight_requests is empty.  This causes _poll [to return [] as the sockets list is empty](https://github.com/dpkp/kafka-python/blob/0.9/kafka/client_async.py#L320-L321) which allows [the consumer loop](https://github.com/dpkp/kafka-python/blob/0.9/kafka/consumer/group.py#L610) to spin as it isn't delayed by [the socket select](https://github.com/dpkp/kafka-python/blob/0.9/kafka/client_async.py#L323)

**Comment by dpkp** [comment]
landed PR 496 to master, which fixes this issue in my testing. please reopen if it does not appear fixed in your tests.

**Comment by songxin1990** [comment]
good job.
