### ISSUE TITLE
KafkaConsumer.poll return TopicPartition object

### ISSUE THREAD

**Issue by clyquan** [dpkp/kafka-python#508]
Hi guys, I use this client in our project and get some interesting response.
When I use codes below, it return normal record objects.
for msg in consumer:
    print(msg)

However, when I use:
messages = comsumer.poll()
for msg in messages:
     print(msg)

It return TopicPartition objects, these are unexpected. can you give me some details?

**Comment by dpkp** [comment]
The poll interface returns a dict of {TopicPartition: [records]} , not a simple message stream. It's identical to the official java client interface. See the docstring / help for more info!
