### ISSUE TITLE
ImportError: cannot import name SimpleClient

### ISSUE THREAD

**Issue by prafulbagai** [dpkp/kafka-python#514]
As per the docs, we need to import `from kafka import SimpleProducer, SimpleClient` for producing the messages.

However, instead of `SimpleClient`, it should be `KafkaClient`. Kindly update the docs.

**Comment by dpkp** [comment]
Class has been renamed to SimpleClient in master. Docs reflect the name change. Legacy import will work, but is deprecated and will be removed in a future release.
