### ISSUE TITLE
why create_message_set() in _send_upstream() use the key of last gathered messages as message set key

### ISSUE THREAD

**Issue by jackyfkc** [dpkp/kafka-python#517]
In _send_upstream() [base.py](https://github.com/dpkp/kafka-python/blob/master/kafka/producer/base.py#L135) (master branch), 

        # Send collected requests upstream
        for topic_partition, msg in msgset.items():
            messages = create_message_set(msg, codec, key, codec_compresslevel)

Note that the **key** parameter passed to create_message_set() is used in the above [**while** loop](https://github.com/dpkp/kafka-python/blob/master/kafka/producer/base.py#L119)

        while count > 0 and timeout >= 0:
            try:
                topic_partition, msg, key = queue.get(timeout=timeout)
            except Empty:
                break

Does it make sense?

**Comment by dpkp** [comment]
Yes, it is a little odd. But if you look closer, you'll find that `msg` is actually a tuple of `(msg, key)`, so each message in the message_set will get associated with its key correctly. The outer `key` is actually only used as the key of a compressed messageset "message", but as I understand it the kafka servers ignore that key.

In any event, we've shifted resources to the KafkaProducer implementation, so there are no plans to clean up _send_upstream or any of the legacy producer code.
