### ISSUE TITLE
Docs (or code) are out of date

### ISSUE THREAD

**Issue by Pehat** [dpkp/kafka-python#519]
Hello, 
I want to create a consumer that tracks events from multiple queues named by single pattern. [Here](http://kafka-python.readthedocs.org/en/latest/apidoc/KafkaConsumer.html) I found `subscribe()` method, so I use it.

I'm trying to run the following code:

```
from kafka import KafkaConsumer
consumer = KafkaConsumer(
            bootstrap_servers=[kafka_address],
            group_id=None
        )
consumer.subscribe(pattern=KAFKA_PATTERN_TOPIC)
```
and get the following error:

```AttributeError: 'KafkaConsumer' object has no attribute 'subscribe'```

Kafka-python version is 0.9.5. What can be the problem?

**Comment by dpkp** [comment]
That feature is currently unreleased. Version-specific documentation is available at kafka-python.readthedocs.org. Github docs refer to master branch. If you want to try it out, you can install from github instead of pypi.

Expect new release this week.
