### ISSUE TITLE
Multiprocess consumer bottleneck 

### ISSUE THREAD

**Issue by roycamp** [dpkp/kafka-python#52]
It appears that the multiprocessor consumer puts all events back into a single queue.  However, to process these events using multiprocessing, no queue is needed and there should be a way to define the code that is executed in each process upon event arrival.

**Comment by dpkp** [comment]
Multiprocess consumer is deprecated in favor of the new KafkaConsumer w/ group coordination. Closing as wontfix.

**Comment by pedrolarben** [comment]
Hello, I'm interested in KafkaConsumer w/ group coordination but I cannot find the documentation about it.
Where can I find information about KafkaConsumer w/ group coordination?
