### ISSUE TITLE
ImportError: cannot import name KafkaProducer

### ISSUE THREAD

**Issue by pablitoAM** [dpkp/kafka-python#521]
I'm getting the following error:

    from kafka import KafkaProducer
ImportError: cannot import name KafkaProducer

Looks like is not imported in .../kafka/`__init__.py`

```from kafka.producer import SimpleProducer, KeyedProducer```
```from kafka.partitioner import RoundRobinPartitioner, HashedPartitioner, Murmur2Partitioner```
```from kafka.consumer import SimpleConsumer, MultiProcessConsumer, KafkaConsumer```

**Comment by dpkp** [comment]
You'll need to install from github master - KafkaProducer has not been released to pypi yet.

**Comment by mrb-github** [comment]
My problem was I have installed flask. If I run the environment to setup the flask and then run the code, it fails: I intentionally stubbed out rest of the code, until i resolve this

my code:
(venv) ubuntu@ip-172-31-21-208:~/flaskproj$ more kafka_producer.py 
from kafka import KafkaProducer
from kafka.errors import KafkaError
import sys
sys.stdout.write(' Hello world') ; sys.stdout.flush()
(venv) ubuntu@ip-172-31-21-208:~/flaskproj$ 

my flask booting bash file
#!/bin/bash
. venv/bin/activate
export FLASK_ENV=development
export FLASK_APP=hello.py

If run without booting my flash setup, the code works fine.
