### ISSUE TITLE
Cannot import KafkaProducer

### ISSUE THREAD

**Issue by mz1991** [dpkp/kafka-python#525]
When installing the library with pip/pip3 can not import

`_from kafka import KafkaProducer_
`

`kafka.py `is missing from `/usr/local/lib/python3.4/dist-packages/producer/`

Cloning the repository and running the `setup.py` solves the problem.

**Comment by dpkp** [comment]
That is correct. The master branch is under development and has not been released to pypi yet. Expect release this weekend or next week.
