### ISSUE TITLE
Support SASL/Kerberos 

### ISSUE THREAD

**Issue by jorisdevrede** [dpkp/kafka-python#533]
Kafka v0.9.0.0 also has SASL/Kerberos support added to the new API (https://issues.apache.org/jira/browse/KAFKA-1686), which makes it possible to expand standard kerberos based security to Kafka. Could SASL (security.protocol = "SASL_PLAINTEXT" or "SASL_SSL") be added to kafka-python?

**Comment by ah-** [comment]
+1

**Comment by dpkp** [comment]
PRs welcome! I do not have an easykerberos setup to test with. Any tips or gists to get one configured for testing would be fantastic.

**Comment by mvervuurt** [comment]
This is really a critical feature to have ;)

**Comment by pearlstam** [comment]
This would really make my life a lot easier :)

**Comment by jorisdevrede** [comment]
https://gist.github.com/jorisdevrede/a7933a99251452bb1867

Hi dpkp, I have put together a gist that describes how you can configure Kafka 0.9.0.0 and its accompanying Zookeeper with Kerberos. This is only a test configuration without any proper service accounts or permissions, but it should be enough for developing SASL support into kafka-python.

Please let me know if you have any questions.

**Comment by jorisdevrede** [comment]
And here is a [SASL implementation](https://github.com/thobbs/pure-sasl) that relies on [PyKerberos](https://pypi.python.org/pypi/kerberos), which you can use as a reference.

**Comment by ah-** [comment]
Has anyone looked into this? How much is required to get it running?

**Comment by dpkp** [comment]
I have not investigated deeply, but I expect it would not be terribly difficult for someone that understands the kerberos components and setup. I do not have access to a kerberos-authenticated kafka cluster and have not spent time trying to figure out how to build one myself. Until that happens I doubt I'll spend time on this feature. PRs absolutely welcome.

**Comment by gwittel** [comment]
I'd also note that there are multiple SASL backends; of which Kerberos and plain auth are builtin.  However, its pluggable in Kafka (just not well documented) so in theory one can add their own auth provider (like OAuth) as well.

**Comment by DataEngg** [comment]
@dpkp , Is it possible to setup Plain authentication to brokers via SASL mechanism?

**Comment by dpkp** [comment]
Anything is possible with a PR!

**Comment by larsjsol** [comment]
@DataEngg: I've made PR #779 that adds plain sasl authentication

**Comment by dpkp** [comment]
#779 merged to master. It provides SASL PLAIN auth mechanism.

**Comment by skysilence** [comment]
@dpkp but it seemed to be failed? Can you provide some test examples?

**Comment by dpkp** [comment]
I don't have a SASL setup to verify right now, but the configuration docs should be up to date AFAIK. See http://kafka-python.readthedocs.io/en/master/apidoc/KafkaProducer.html and sasl_* options

**Comment by dpkp** [comment]
SASL Plain should be working as of 1.3.3 .

**Comment by Harald-Berghoff** [comment]
if i get it right, SASL is working but not with Kerberos?  We are running Kafka with Kerberos authentication enabled, and it seems not to be possible to get kafka-python running with it.

I am happy to support here, but my knowledge of this module is almost non-existent.

**Comment by dpkp** [comment]
Correct. kafka-python supports kafka's SASLHandshake api request / response, but there is only support for the PLAIN auth mechanism. If the handshake response requires kerberos or some other mechanism, kafka-python raises an error.
The relevant code is here: https://github.com/dpkp/kafka-python/blob/1.3.3/kafka/conn.py#L415-L466

It shouldn't be terribly difficult to add kerberos support. It would just take knowledge of the kerberos protocol requirements and a working installation for testing. Unfortunately, I have neither. But I would welcome a PR implementing this!

**Comment by Harald-Berghoff** [comment]
I am on it.

I came across an unhandled exception, when the broker returns an error on the handshake. As soon as the response is processed, the object _sasl_auth_future seems to be again 'None'. I am not completely sure why this is happening, i guess that it is an effect of the callback, and the object might be a different instance? 

The error response is what i think should happen in my case, i just think it should not end with an simple unhandled exception.

`
Traceback (most recent call last):
  File "/home/harald/.eclipse/org.eclipse.platform_793567567_linux_gtk_x86_64/plugins/org.python.pydev_5.8.0.201706061859/pysrc/pydevd.py", line 1557, in <module>
    main()
  File "/home/harald/.eclipse/org.eclipse.platform_793567567_linux_gtk_x86_64/plugins/org.python.pydev_5.8.0.201706061859/pysrc/pydevd.py", line 1551, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/harald/.eclipse/org.eclipse.platform_793567567_linux_gtk_x86_64/plugins/org.python.pydev_5.8.0.201706061859/pysrc/pydevd.py", line 982, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/harald/workspace_python/kafka_python/kafka_main.py", line 25, in <module>
    sasl_plain_password='no',
  File "/home/harald/git/kafka-python/kafka/consumer/group.py", line 325, in __init__
    self._client = KafkaClient(metrics=self._metrics, **self.config)
  File "/home/harald/git/kafka-python/kafka/client_async.py", line 215, in __init__
    self._bootstrap(collect_hosts(self.config['bootstrap_servers']))
  File "/home/harald/git/kafka-python/kafka/client_async.py", line 248, in _bootstrap
    bootstrap.connect()
  File "/home/harald/git/kafka-python/kafka/conn.py", line 350, in connect
    if self._try_authenticate():
  File "/home/harald/git/kafka-python/kafka/conn.py", line 427, in _try_authenticate
    if self._sasl_auth_future.failed():
AttributeError: 'NoneType' object has no attribute 'failed'
`

[kafka_sasl.txt](https://github.com/dpkp/kafka-python/files/1150247/kafka_sasl.txt)

**Comment by Harald-Berghoff** [comment]
my current version seems to handle the GSSAPI handshake for SASL fine now (the gssapi establishes successful a security context), but i am not able to test completely, as my Kafka installation doesn't support the bootstrapping, port 9092 isn't open on the host running Kafka. Maybe someone has a tip, how i can bypass the bootstrapping by providing the metadata (ie. previously retrieved via zookeeper)?

Still i already opened a PR (https://github.com/dpkp/kafka-python/pull/1152), so you can check the code for some feedback. Please bear with me, this is my first change for python and even direct socket code.

**Comment by natedogs911** [comment]
@Harald-Berghoff is there any documentation on how this is intended to be used? I may have an environment setup soon with kerberos and would like to test this addition.

**Comment by Harald-Berghoff** [comment]
there is no docu yet, but it can be explained quite fast:
- you need the gssapi module for python installed
- you need a fully configured Kerberos client (workstation)
- you need to have a valid Kerberos ticket when starting the kafka-client

When creating i.e. the consumer, you need to provide the parameters:
security-protocol = SASL_PLAINTEXT
sasl_mechanism = GSSAPI
if your broker runs with a different principal name than 'kafka', you need to also pass the correct name in 
sasl_kerberos_service_name

The client will then aquire the kerberos ticket from your standard ticket store and exchange authentication tokens with the broker until either the security context is established or a failure occurs. If the context is established, the communication continues normally.

Using a keytab is not yet implemented, and using SSL via Kerberos key isn't implemented as well.

**Comment by jeffwidman** [comment]
@Harald-Berghoff Can this be closed now that https://github.com/dpkp/kafka-python/pull/1152 is merged?

**Comment by Harald-Berghoff** [comment]
sorry for the delay. for me this issue can be closed, but i am not the original reporter. The open points can be implemented independent of this issue:
- enable use of keytab
- enable SASL_SSL with Kerberos
But first i will get this module running in our environment without bootstrapping,

**Comment by chan71** [comment]
@Harald-Berghoff has the use of keytab being implemented? I believe this feature will enable passing a keytab to KafkaProducer and KafkaConsumer so that kerberos ticket creation is handled automatically so that pre-existing ticket is not required. Please clarify.
