### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by ebourgeois** [dpkp/kafka-python#534]
Can you please cut a new release? The KafkaProducer that is documented at http://kafka-python.readthedocs.org/en/master/apidoc/KafkaProducer.html is only in master and I would really like to take advantage of it, as 0.9.5 is behind by 288 commits.

**Comment by dpkp** [comment]
I think it's pretty close now. There are still one or two open issues that may need investigation.

**Comment by Poogles** [comment]
Do you mind labelling up what needs a look?  We've just moved to using this in production now so can probably set aside some time to help.

**Comment by davidbirdsong** [comment]
+1, I just lost an hour trying to reconcile readthedocs against 0.9.4 and then 0.9.5 and then just finally reading the code to realize how far out master was in front of any tagged version.

**Comment by dpkp** [comment]
1.0.0 released to pypi
