### ISSUE TITLE
Help: kafka-python consumer not receiving messages

### ISSUE THREAD

**Issue by maverickz** [dpkp/kafka-python#535]
I am having trouble with KafaConsumer to make it read from the beginning, or from any other explicit offset.  

Running the command line tools for the consumer for the same topic , I do see messages with the `--from-beginning` option and it hangs otherwise

`$ ./kafka-console-consumer.sh --zookeeper {localhost:port} --topic {topic_name} --from-beginning`

If I run it through python, it hangs, which I suspect to be caused by incorrect consumer configs

```
consumer = KafkaConsumer(topic_name,
                         bootstrap_servers=['localhost:9092'],
                         group_id=None,
                         auto_commit_enable=False,
                         auto_offset_reset='smallest')

print "Consuming messages from the given topic"
for message in consumer:
    print "Message", message
    if message is not None:
        print message.offset, message.value

print "Quit"
```

Output:
----------
Consuming messages from the given topic
<hangs after that> 

Not sure if the consumer configs are wrong or I am running against incompatible brokers.

**Comment by dpkp** [comment]
Can you try setting group_id=None ?

**Comment by maverickz** [comment]
Ya group_id was set to None and it didn't affect the behavior. 

This happens if any consumer is sending fetch requests to at least one broker that is a leader for the partitions being queried but has no messages retained in its log.
#https://issues.apache.org/jira/browse/KAFKA-3159

The consumer works fine if all the partitions have at least one message.

**Comment by maverickz** [comment]
Also `_decode_message` does not throw an exception for unsupported compression types and keeps retrying infinitely. Would be helpful if it logs an error message at the least.

**Comment by dpkp** [comment]
Are you using master or a previous release?

**Comment by maverickz** [comment]
I was using `0.9.5` and figured out the issue was with `_decode_message` with additional logging.

**Comment by dpkp** [comment]
Ok, sounds like this is resolved. Please reopen if not!

**Comment by hosseinmousavi** [comment]
set auto_offset_reset='earliest' solved mine
consumer = KafkaConsumer('test', auto_offset_reset ='earliest')

**Comment by asmhack** [comment]
With `auto_commit_enable=False` option you need to commit manually I believe. Something like `consumer.commit()`.
Also @hosseinmousavi, your code has `auto_commit_enable=True` by default, this is the reason why it works and not because of `auto_offset_reset='earliest'`. Fix me if I'm wrong.

**Comment by dws-bijaya** [comment]
I m facing same issues. Can anyone help me .

**Comment by B9527** [comment]
consumer = KafkaConsumer(
    'test02',
    group_id='test-consumer-group1',  # Changing group_id can start from scratch.
    bootstrap_servers=['{kafka_host}:{kafka_port}'.format(kafka_host=KAFKA_HOST, kafka_port=KAFKA_PORT)],
    auto_offset_reset='earliest'  # earliest == --from-beginning
)

but first change file :config/server.properties 
<code>  advertised.listeners=PLAINTEXT://192.168.xx.xx:9092</code>

**Comment by mariomtzjr** [comment]
I have a similar issue, when I want to get a message for my consumer, my output is this:
```
test_1       | 2019-07-10 16:18:27,246: kafka.conn - DEBUG: <BrokerConnection node_id=1 host=172.30.0.3:9092 <connected> [IPv4 ('172.30.0.3', 9092)]> Request 364: FetchRequest_v2(replica_id=-1, max_wait_time=500, min_bytes=1, topics=[(topic='dbhistory.beta-api.profile', partitions=[(partition=0, offset=0, max_bytes=1048576)])])
test_1       | 2019-07-10 16:18:27,752: kafka.protocol.parser - DEBUG: Received correlation id: 364
test_1       | 2019-07-10 16:18:27,752: kafka.protocol.parser - DEBUG: Processing response FetchResponse_v2
test_1       | 2019-07-10 16:18:27,754: kafka.conn - DEBUG: <BrokerConnection node_id=1 host=172.30.0.3:9092 <connected> [IPv4 ('172.30.0.3', 9092)]> Response 364 (506.2146186828613 ms): FetchResponse_v2(throttle_time_ms=0, topics=[(topics='dbhistory.beta-api.profile', partitions=[(partition=0, error_code=0, highwater_offset=0, message_set=b'')])])
test_1       | 2019-07-10 16:18:27,756: kafka.consumer.fetcher - DEBUG: Adding fetch request for partition TopicPartition(topic='dbhistory.beta-api.profile', partition=0) at offset 0
test_1       | 2019-07-10 16:18:27,758: kafka.consumer.fetcher - DEBUG: Sending FetchRequest to node 1
```
**`message_set=b''`**
