### ISSUE TITLE
Messages encoded in formats unsupported by the consumer results in infinite retry to decode the message

### ISSUE THREAD

**Issue by maverickz** [dpkp/kafka-python#541]
`_decode_message` does not throw an exception for unsupported compression types and keeps retrying infinitely. Would be helpful if it logs an error message at the least

**Comment by dpkp** [comment]
_decode_message is the old protocol stack. It has been removed from master. I do not believe this issue affects the new protocol parsing code. Please retry with master and reopen if you discover similar issues.
