### ISSUE TITLE
can kafka.common.Future support concurrent.futures.Future?

### ISSUE THREAD

**Issue by aisch** [dpkp/kafka-python#542]
maybe use http://pythonhosted.org/futures for 2.x or just add a few methods so its interface is ~ the same.

**Comment by dpkp** [comment]
How would you propose managing the async kafka client event loop?

**Comment by aisch** [comment]
couldn't that stay as it is? what i mean is: can we make the kafka `Future` interface ~ `concurrent.futures.Future`.

it doesn't matter for internal use but for futures handed out to clients (eg `KafkaPrducer.send()`) it might be nicer if the future they got looked like a *standard* future (esp if they have code for dealing w/ async results already that is written to `concurrent.futures.Future`).

just didn't want to submit a patch if there was some reason not to do that.

**Comment by dpkp** [comment]
Happy to review a PR. The main goal has been to align w the java interface
for consistency. But pythonic touches are great too. I've mostly worked
with twisted deferreds, which may explain some of the choices I made on the
first cut here.

**Comment by dpkp** [comment]
No plans to work on this currently, but happy to review a PR to demonstrate the value of this proposal.
