### ISSUE TITLE
SimpleClient documentation needs update

### ISSUE THREAD

**Issue by shichao-an** [dpkp/kafka-python#543]
The [SimpleClient usage](https://github.com/dpkp/kafka-python/blob/d56d2faddabd36ecbec73954bd4a8f17ed501e84/docs/simple.rst#simpleclient) is broken: `ProduceRequest` is not in `kafka.common` anymore, and the `ProduceRequest` from `kafka.protocol.produce` cannot be used like this.

**Comment by dpkp** [comment]
Updated docs in master @ `c6b9f84`
