### ISSUE TITLE
Data Loss caused by StopIteration in message deserializer

### ISSUE THREAD

**Issue by schmidtc** [dpkp/kafka-python#545]
A bug in the fastavro package for python raises "StopIteration" when deserializing truncated messages. kafka-python sees the StopIteration and aborts the loop when consuming a batch of messages. This results in the loss of data with no warning or exceptions being thrown.

While the root cause is a bug in an unrelated package, kafka-python should raise an exception when the deserializer class behaves unexpectedly. This was tested against version '0.9.5', and a quick glance at master suggest it has not been resolved.

See also: https://github.com/tebeka/fastavro/issues/46

**Comment by dpkp** [comment]
Great point. This needs to be handled better.

**Comment by dpkp** [comment]
Fix pushed to master @ `7c779b3`
