### ISSUE TITLE
MultiProcessorConsumer always throw "AttributeError: 'AutoProxy[Queue]'"

### ISSUE THREAD

**Issue by shenzhun** [dpkp/kafka-python#546]
kafka-python version: 0.9.5
python version: 2.6.9
OS: AWS linux

When I try to create a multiprocess consumer, I got the error above.
The full error log in this gist [https://gist.github.com/shenzhun/9a1d1673e12740d4ee66](url)

**Comment by dpkp** [comment]
This has been fixed in master. Also note that the MultiProcessConsumer is deprecated. You should consider using the newer KafkaConsumer with 0.9.0.0 brokers.

**Comment by shenzhun** [comment]
I install the lastest master and it works. Thanks.
