### ISSUE TITLE
Support connections_max_idle_ms

### ISSUE THREAD

**Issue by dpkp** [dpkp/kafka-python#548]
KafkaClient should disconnect sockets that have not been active for the configured max idle duration.

**Comment by deejay1** [comment]
We have a problem now, where `KafkaProducer` keeps open hundreds of connections for the Kafka cluster and seems to fall into an infinite loops after a while using up the CPU.
We're trying to get some more debug information, right now strace says:

```
futex(0x1304560, FUTEX_WAKE_PRIVATE, 1) = 1
accept(8, 0x7ffd84aee080, [16])         = -1 EAGAIN (Resource tempor
arily unavailable)
futex(0x1304560, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
``` on the hung gunicorn workers...
