### ISSUE TITLE
WARNING:kafka.client:_poll called with a non-zero timeout and sleep=False

### ISSUE THREAD

**Issue by nickvasilyev** [dpkp/kafka-python#559]
Hello, 

I am running into an issue with the client and was hoping you can help. I am just starting out with Kafka, so it may be something stupid. 

I have two kafka brokers; I ran this to create my topic:
$ bin/kafka-topics.sh --create --zookeeper localhost:7081/kafka --replication-factor 2 --partitions 1 --topic testing1
Created topic "testing1".

I have sample producer and sample consumer code. 

producer.py

    #!/usr/bin/env python3
    from kafka import KafkaProducer
    import time

    topic = 'testing1'
    p = KafkaProducer(bootstrap_servers=['192.168.1.211:9092'])

    start = 0
    while True:
        time.sleep(2)
        p.send(topic, bytes(str(start),'utf-8'))
        print(start)
        start+=1

This looks fine, it is generating messages and I can confirm via kafka console consumer. 

Here is the first consumer. 

    #!/usr/bin/env python3
    from kafka import KafkaConsumer
    import logging
    logging.basicConfig(level='INFO')
    c = KafkaConsumer('testing1', bootstrap_servers=['192.168.1.211:9092'], group_id='1')
    for msg in c:
        print(msg)

When I run the consumer, it connects to kafka and then I see the following message non stop, no items from kafka queue. 

    WARNING:kafka.client:_poll called with a non-zero timeout and sleep=False -- but there was nothing to do. This can cause high CPU usage during idle.

Any ideas what is going? I have similar code running elsewhere and it is working fine, same cluster, but different topid. 

I also occasionally get the following when I run the consumer or producer, however, if I run it again, it works fine. 

Traceback (most recent call last):
  File "consumer1.py", line 6, in <module>
    c = KafkaConsumer('testing1', bootstrap_servers=['192.168.1.211:9092'], group_id='1')
  File "/usr/local/lib/python3.4/dist-packages/kafka/consumer/group.py", line 182, in __init__
    self.config['api_version'] = self._client.check_version()
  File "/usr/local/lib/python3.4/dist-packages/kafka/client_async.py", line 629, in check_version
    connect(node_id)
  File "/usr/local/lib/python3.4/dist-packages/kafka/client_async.py", line 590, in connect
    while not self.ready(node_id):
  File "/usr/local/lib/python3.4/dist-packages/kafka/client_async.py", line 190, in ready
    self._initiate_connect(node_id)
  File "/usr/local/lib/python3.4/dist-packages/kafka/client_async.py", line 158, in _initiate_connect
    return self._finish_connect(node_id)
  File "/usr/local/lib/python3.4/dist-packages/kafka/client_async.py", line 162, in _finish_connect
    state = self._conns[node_id].connect()
  File "/usr/local/lib/python3.4/dist-packages/kafka/conn.py", line 91, in connect
    if not ret or ret is errno.EISCONN:
UnboundLocalError: local variable 'ret' referenced before assignment

Thanks in advance

**Comment by dpkp** [comment]
Did you get this resolved?

**Comment by nickvasilyev** [comment]
Yes, thanks. Kafka was not configured correctly and it was getting intermittent errors depending on the broker the script connected to.
