### ISSUE TITLE
Help: messages not delivering from producer

### ISSUE THREAD

**Issue by rakesh91** [dpkp/kafka-python#563]
Hi,
I just started working with kafka, as part of it, I have created a single node kafka using quickstart tutorial.
But, I am not able to send messages from producer to consumer using python code.

producer.py

from kafka import KafkaProducer
producer = KafkaProducer(bootstrap_servers=['localhost:9092'])
print producer.send('foobar', b'some_message_bytes')

consumer.py

from kafka import KafkaConsumer
consumer = KafkaConsumer('foobar')
for msg in consumer:
        print (msg)

kafka-python==1.0.1
python : 2.6.6
kafka: 0.9.0.1

What is the issue? Please help.
Thank you

**Comment by dpkp** [comment]
A couple thoughts: when debugging it can be useful to use the console-consumer that comes packaged with kafka. This can help identify whether your problem is on producer side or consumer side. Another good place to look when debugging is kafka server logs.

My rough guess from your code is that you may be killing your producer before messages are actually delivered (`send` operates asynchronously). You might try doing this in the producer to block until your message is delivered:

```
print producer.send('foobar', b'some_message_bytes').get(timeout=30)
```

**Comment by rakesh91** [comment]
@dpkp Thank you, for the suggestion. Will try it out.

**Comment by rakesh91** [comment]
print producer.send('foobar', 'some_message_bytes').get(timeout=30)
  File "/usr/lib/python2.6/site-packages/kafka/producer/future.py", line 46, in get
    "Timeout after waiting for %s secs." % timeout)
kafka.common.KafkaTimeoutError: Timeout after waiting for 30 secs.

**Comment by dpkp** [comment]
Does the foobar topic exist in your cluster? If not, have you enabled auto topic creation? You should take a look at your server logs. You can also enable python logging to get a view into what is happening internally:

import logging
logging.basicConfig(level=logging.INFO)

**Comment by rakesh91** [comment]
Thank you. Its working now.

**Comment by dpkp** [comment]
Fantastic!

**Comment by sunmoonone** [comment]
@rakesh91  what is the reason for the KafkaTimeoutError, I encounters the same problem.

**Comment by rakesh91** [comment]
@sunmoonone I restarted kafka and messages got delivered, din't check with timeout later.

**Comment by raushendra** [comment]
My issue got fixed, failing because of producer killed before message delivered.

**Comment by rajish** [comment]
For me it was:
```kafka.errors.MessageSizeTooLargeError: [Error 10] MessageSizeTooLargeError: The message is 3453798 bytes when serialized which is larger than the maximum request size you have configured with the max_request_size configuration```
The exception was only visible after using the `get(timeout=30)` trick. No other info in logs from the library (loglevel INFO).
