### ISSUE TITLE
Help: KafkaConsumer fetch message one by one [1.0.1]

### ISSUE THREAD

**Issue by sunmoonone** [dpkp/kafka-python#565]
poll and iterator style of KafkaConsumer all fetch messages in batches
I found no api or config options for fetching only one message from kafka at a time 

Will this feature be supported or it is impossible to implement it because there may be some restrictions in the protocol of kafka client?

> kafka-python version 1.0.1

**Comment by sunmoonone** [comment]
There are cases that messages must be handled one after the other. There is no ways to do this using KafkaConsumer.

I think it is not safe to use consumer.commit to commit to an offset smaller than consumed offset when a task has been done, because after any rebalance caused by other consumers re-processing will happen.

**Comment by dpkp** [comment]
Have you tried iterating?

for msg in consumer:
    foo(msg)

**Comment by sunmoonone** [comment]
OK, poll in an infinite while loop is the same with iterating. I will use iterating, thanks @dpkp 

One more question: will the local store be cleared after any rebalance?

**Comment by dpkp** [comment]
Yes, the iterator handles reassignment of partitions due to rebalance.
