### ISSUE TITLE
Help: Problems connecting to broker

### ISSUE THREAD

**Issue by HuangSuoyuan** [dpkp/kafka-python#568]
kafka setting like this:

delete.topic.enable: true
auto.create.topics.enable: false

when trying to create a topic by using client.KafkaClient.add_topic(mytopic), nothing happend

**Comment by dpkp** [comment]
Can you provide more details on what code you are running exactly and what error you are seeing when? A stacktrace would be helpful.

Specifically, `add_topic` returns a future, so I would not expect anything to happen directly. But getting a NodeNotReadyError may mean that your client is not able to connect to your cluster.

**Comment by alexr967** [comment]
I have similar issue - NodeNotReadyError:

> Traceback (most recent call last):
>   File "pp.py", line 13, in <module>
>     producer = KafkaProducer(bootstrap_servers=['advertized_host_name:9092'])
>   File "/usr/lib/python2.6/site-packages/kafka/producer/kafka.py", line 246, in __init__
>     self.config['api_version'] = client.check_version()
>   File "/usr/lib/python2.6/site-packages/kafka/client_async.py", line 629, in check_version
>     connect(node_id)
>   File "/usr/lib/python2.6/site-packages/kafka/client_async.py", line 592, in connect
>     raise Errors.NodeNotReadyError(node_id)
> kafka.common.NodeNotReadyError: 0
> 

The error is very consistent. At the same time, kafka-console-producer and kafka-console-consumer work very well.

I was not able to find any pointers on the web. Any sugestions?

**Comment by dpkp** [comment]
The error occurs during auto version checks. You might try passing
api_version=0.9 (or 0.8.x) . this will suppress this error. But the error
suggests that you have connection problems generally, so I would expect
other errors to happen. Are you able to telnet to your bootstrap server
host/port?

**Comment by alexr967** [comment]
Dana, thank you for the quick response. I have no connection issues as I am logging to the broker host and ssh to the producer's host from the broker host.
I think you nailed it exactly:

>>> print kafka.__version__
1.0.0


Should I downgrade the kafka-python to 0.9 release?

**Comment by dpkp** [comment]
this appears to be a broker configuration error or networking error. you can try a different release, but I doubt that is the problem. I'd suggest looking at your advertised.host.name and advertised.port settings. see https://cwiki.apache.org/confluence/display/KAFKA/FAQ#FAQ-Whycan'tmyconsumers/producersconnecttothebrokers?

**Comment by alexr967** [comment]
Dana, thank you for the note. As you are pointing out, a host could have multiple dns aliases. Any of them would work for ssh or ping test. However kafka connection should use the alias that matches advertised.host.name in server.properties file of the broker.

I was using a different alias in bootstrap_servers parameter. Hence an error. Once I changed the call to use advertised.hostname, the problem was solved. Thank you for the help

**Comment by l15k4** [comment]
I have this issue with kafka `0.9.0.1` ...

**Comment by zackdever** [comment]
just to check `client.KafkaClient.add_topic(mytopic)` only works if `auto.create.topics.enable` is `true` correct?

**Comment by pouriatabari** [comment]
Dears
please be inform that, if you used the hostname in the config of broker (for example : `listeners=PLAINTEXT://kafka-01:9091`), you should use the same hostname in the command( for example:  ./bin/kafka-topics.sh --describe --topic test-01 --bootstrap-server `kafka-01:9091` )
