### ISSUE TITLE
Help: How to use kafkaProducer in multiprocessing

### ISSUE THREAD

**Issue by yuwei162** [dpkp/kafka-python#570]
**When i use threading, It works good**, eg:
`class MyThreadProducer(threading.Thread):
    def __init__(self, producer):
        super(MyThreadProducer, self).__init__()
        self.producer = KafkaProducer(bootstrap_servers=['localhost:9092'])
    def run(self):
        process_name = self.name
        while True:
            self.producer.send('my-topic', 'thread')
            time.sleep(5)`
**But when I change threading with multiprocessing, something is wrong, the message can not be sent to kafka**
`class MyThreadProducer(multiprocessing.Process):
    def __init__(self, producer):
        multiprocessing.Process.__init__(self)
        self.producer = KafkaProducer(bootstrap_servers=['localhost:9092'])
    def run(self):
        process_name = self.name
        while True:
            self.producer.send('my-topic', 'process')
            time.sleep(5)`

we are using kafka-python==1.0.1 and Kafka 0.9.0.0

**Comment by dpkp** [comment]
your multiprocessing use seems a bit strange to me. Try instantiating a new producer in the 'run' method, not `__init__` when using multiple processes. You should not expect to share a KafkaProducer instance across processes; instead you will need to create a new instance for each process.

**Comment by yuwei162** [comment]
@dpkp Thanks very much！I get it！

**Comment by hustshawn** [comment]
That's pretty tricky when I tried to just pass the producer handler to my worker function with multiprocessing. eg. worker_func(producer, *args, **kwargs)   The message cannot be sent to the queue. 
Should it be a bug in this `kafka-python` module? Can such behaviour be supported in future?

**Comment by dpkp** [comment]
No, you cannot share a producer object across processes.
