### ISSUE TITLE
producer  Broken pipe

### ISSUE THREAD

**Issue by abc100m** [dpkp/kafka-python#574]
I'm testing issue #571 . 

1, use a producer send out 100 messages, all successed
2,  go outdoor to do some happy things. (it take about  more then 30 minutes ) 
3,  use the producer which created by 1 to  send 100 messages.  without retry, 1 message failed and 99 messages successed.

here is the error:
```python
[2016-03-02 15:20:17,829] [ERROR] [kafka-python-producer-1-network-thread] Error sending ProduceRequest(required_acks=1, timeout=30000, topics=[(topic='test_receive1', partitions=[(0, <_io.BytesIO object at 0xfa7d70>)])]) to <BrokerConnection host=192.168.10.70 port=9092>
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/kafka/conn.py", line 186, in send
    sent_bytes = self._sock.send(message)
error: [Errno 32] Broken pipe
```

then I close my test script, it shows:

```
[2016-03-02 15:24:34,725] [INFO] [Dummy-14] Kafka producer closed
[2016-03-02 15:24:34,725] [INFO] [Dummy-14] Kafka producer closed
```

so, is this a bug? if so, how to fix this.
and  why there is two producer closed?

thanks

**Comment by dpkp** [comment]
You should check your server logs. That is a network error.

Also, you should not need to wait 30mins to send 100 messages? Something is
broken in your setup.

**Comment by abc100m** [comment]
Hi, 

please excuse my poor English, let me explain it again.

my application is a server daemon, it create a producer when startup.  

first time, App got a request so it send out 100 messages for response.  now there is no request incoming so the  <b>producer is in idle state; </b>

then, after about 30 minutes  our App got a request, so it  <b>reuse the producer </b>to send another 100 messages.  note:  this time, 1 failed and 99 succeeded

I can use "retry feature" of producer to resend the 1  failed message, but the order of messages are changed.

I think it's better if producer can take care of this situation:
<b> when socket is closed by remote server, kafka producer will send the failed message again. this will  ensure send the 1 failed message first,  because sometimes the order is important.
</b>

**Comment by dpkp** [comment]
if you want to maintain order on failures, you should either:

(1) send synchronously, blocking on future.get(): producer.send('foo',
'bar').get() and retry manually on errors

or

(2) configure your client to use max_in_flight_requests_per_connection=1
and retries=some large number

This is general kafka usage, not specific to kafka-python.
