### ISSUE TITLE
Is there any way to create/add new partitions to a specific topic ?

### ISSUE THREAD

**Issue by EverLoSa** [dpkp/kafka-python#575]

**Comment by dpkp** [comment]
No. You must use server-side admin tools for this. There are currently no client apis available to accomplish partition creation from Kafka clients.

**Comment by NewOne121** [comment]
Actually there is a way. At least in latest version/

For example:
`from kafka.admin import NewPartitions

part=NewPartitions(6)
m={'mynewtopic': part}
admin_client.create_partitions(m)`

**Comment by jeffwidman** [comment]
Yep, the `KafkaAdminClient` was added in `kafka-python 2.0` and supports new APIs that were added to newer Kafka brokers.
