### ISSUE TITLE
Error processing append operation on partition

### ISSUE THREAD

**Issue by shrivinayak** [dpkp/kafka-python#576]
Kafka version :  2.10-0.9.0.1
java version : 1.8.0_51

Kafka cluster contains 3 brokers, with 2 partitions each.
Trying to push messages into the cluster using python-kafka client 
Message rate : 1000/sec

Sample log is [here](http://pastebin.com/Ljyy9aZQ)
Python client code is [here](http://pastebin.com/L5W154AY)  

What could be the reason behind this?
Thank you.

**Comment by dpkp** [comment]
My hunch is it is related to gzip compression. If you disable compression or use a different codec, do you still see the same error?

**Comment by shrivinayak** [comment]
No problems when i ran it without the compression. Thanks for pointing it out!

**Comment by shrivinayak** [comment]
Due to some reasons I am allowed to use only gzip compression.( no snappy, no lz4)  
without compression bandwidth usage is pretty high.
Is there any way i can fix this issue?

**Comment by shrivinayak** [comment]
Any updates on this? 
Why is the gzip compression failing?

**Comment by dpkp** [comment]
I am able to reproduce and will investigate.
