### ISSUE TITLE
Help for compression and other serializer type

### ISSUE THREAD

**Issue by rakesh91** [dpkp/kafka-python#580]
Hi,
I am trying send logs via kafka to elastic stack, so I used the below code for producer creation
producer = KafkaProducer(bootstrap_servers='example.kafka.abc.com:9092',
                             max_block_ms=10000,
                                compression_type='gzip',
                             value_serializer=str.encode)
When I bombard around million messages continuously, I get below error.

kafka.message.InvalidMessageException: Message found with corrupt size (-1204238570) in deep iterator

So thought compression might be problem and removed, things went fine. Why is this problem? When I run load continuously I get this error? 
So I thought of using snappy compression, installed snappy and changed the compression_type to snappy. This time message dint get deliver to kafka.
Please Help.

**Comment by dpkp** [comment]
This sounds similar to issue #576 - is the error found in the kafka server logs or the kafka-python logs?

**Comment by dpkp** [comment]
I believe this is fixed in master -- please reopen if the problem happens again!
