### ISSUE TITLE
Help: KafkaConsumer position and assign

### ISSUE THREAD

**Issue by HariSekhon** [dpkp/kafka-python#584]
Hi,

I've been through all the docs on ReadTheDocs and am trying to do a very specific thing with the higher level consumer which is to produce + consume from a specific topic from a specific offset (by necessity using a specific partition).

The problem I have occurs when I'm trying to do:
```
self.consumer = KafkaConsumer(...)
self.consumer.assign([TopicPartition('myTopic', 0)])
self.start_offset = self.consumer.position(0)
```
I originally also tried:
```
self.consumer = KafkaConsumer('myTopic')
self.consumer.assign([0])
self.start_offset = self.consumer.position(0)
```
before attempting to retrieve the current offset. Either way I get the same exception:
```
...
    self.start_offset = self.consumer.position(self.partition)
  File "/Library/Python/2.7/site-packages/kafka/consumer/group.py", line 477, in position
    assert self._subscription.is_assigned(partition), 'Partition is not assigned'
AssertionError: Partition is not assigned
```

Partition 0 already exists as it's returned by ```self.consumer.partitions_for_topic('myTopic')```

I understand what I'm doing may be a bit lower level because I'm attempting to control the offset from which I start to consume (this is actually in order to run a very specific functional test).

Can you advise on what's I'm doing wrong here as I've been looking at the docs and the manual assignment of the partition is necessary for later specifying the ```seek``` offset but I seem unable to assign the partition to either the consumer or producer.

Thanks

Hari

**Comment by dpkp** [comment]
I think this is what you want:
```
partition = TopicPartition('myTopic', 0)
self.consumer = KafkaConsumer(...)
self.consumer.assign([partition])
self.start_offset = self.consumer.position(partition)
```

But note that there is a bug in `consumer.position` that was fixed in PR #578 . That fix is available in master, and will be in the 1.0.2 pypi release that should go out later this evening.

**Comment by dpkp** [comment]
1.0.2 has been released. Please reopen if that didn't resolve.

**Comment by HariSekhon** [comment]
Thanks, that did solve it, am using the 1.1.1 version of lib now, good job!

One thing I noticed was that I'm able to get more info out of the Perl library for Kafka when querying partitions for a topic - including Replicas, ISR and Leader for each partition.

Any chance to add those details to the consumer or are they already exposed somewhere else? The Perl library returned a dictionary with those fields, whereas I'm using ```consumer.partitions_for_topic(topic)``` which returns a set of partition ids

**Comment by dpkp** [comment]
Great! The partitions_for_topic api currently mirrors the new Java
consumer. I'm not sure how they handle exposing the additional broker
metadata, but I think we could either add a method, add an optional kwarg
to that method.
