### ISSUE TITLE
problems connecting to broker (Kafka 0.9.0)

### ISSUE THREAD

**Issue by asnir** [dpkp/kafka-python#600]
I am probably missing something, but are you sure that it supports the latest Kafka version?

```
from kafka import KafkaConsumer

consumer = KafkaConsumer('my_topic', bootstrap_servers='server1:port1',
                         group_id='group1', auto_offset_reset='earliest')
for msg in consumer:
    print (msg)
```

>   File "****\Python27\lib\site-packages\kafka\client_async.py", line 594, in check_version
>     raise Errors.NoBrokersAvailable()
> kafka.common.NoBrokersAvailable

**Comment by dpkp** [comment]
Currently broken on windows -- see issue #520
