### ISSUE TITLE
Unrecognized configs default_offset_commit_callback

### ISSUE THREAD

**Issue by ecksun** [dpkp/kafka-python#604]
I get an error when I try to give `default_offset_commit_callback` to `KafkaConsumer`:

```
Traceback (most recent call last):
  File "./bucket_kafka_consumer.py", line 47, in <module>
    default_offset_commit_callback=commited
  File "./venv/lib/python3.5/site-packages/kafka/consumer/group.py", line 174, in __init__
    assert not configs, 'Unrecognized configs: %s' % configs
AssertionError: Unrecognized configs: {'default_offset_commit_callback': <function commited at 0x7f69ef656950>}
```

`default_offset_commit_callback` is not listed in `DEFAULT_CONFIG` in `KafkaConsumer` in `group.py`. However it is mentioned in the documentation and in `ConsumerCoordinator` so I assume its just missing form the `DEFAULT_CONFIG`

**Comment by dpkp** [comment]
Pushed fix to master in f83e271
