### ISSUE TITLE
Help: how to check if async messages delivered

### ISSUE THREAD

**Issue by Skivmag** [dpkp/kafka-python#605]
I have the same issue as #563
But I want to check if async messages delivered
If I use blocking send - everything works perfectly:
```
for model in models:
    producer.send('transactions', model).get()
```
But if I remove .get() method - script finishes successfully, but I got nothing in console-consumer
How can I check delivering of asynch messages?

**Comment by dpkp** [comment]
Remember to call producer.flush() before exiting your script.

If you want to check future results but not block on each send, consider building a list of futures during your send loop and before exit iterate over that list calling get() on each.

**Comment by Skivmag** [comment]
>>Remember to call producer.flush() before exiting your script.

Thank you!
Works like a magic
Propose to add producer.flush() in examples in docs
I think it would be very helpfull

**Comment by dpkp** [comment]
Yes, we should update the docs on this. Another improvement might be to increase the internal timeout on exit (currently it is 0), which would give the producer a little extra time to finish async message processing before getting shutdown. Even better might be to make the timeout on close configurable.

**Comment by dpkp** [comment]
docs updated in 4f8d9fa
