### ISSUE TITLE
Installation of Kafka-Python

### ISSUE THREAD

**Issue by ashishvw** [dpkp/kafka-python#608]
Hello,

I'm planning to use Kafka Python as I know Python.
I have installed the Kafka-Python client.
But I don't know how to use it.

Do I need to install KAFKA and ZooKeeper before that ?

How to start using Kafka-Python?

**Comment by jackyfkc** [comment]
kafka-python is only a client, obviously, you need a server. And you should ask question on [stackoverflow](https://stackoverflow.com/).

**Comment by ashishvw** [comment]
Thanks a lot Jacky for your quick reply.
I'm new to Github also.
Sorry ..In future I will ask question on Stackoverflow.
