### ISSUE TITLE
KafkaProducer fails when many sockets are opened

### ISSUE THREAD

**Issue by deejay1** [dpkp/kafka-python#613]
When using KafkaProducer in an environment with over 1024 open sockets we get the following issue:

```python
File "/srv/.../lib/python2.7/site-packages/kafka/producer/kafka.py", line 248, in __init__
self.config['api_version'] = client.check_version()
File "/srv/.../lib/python2.7/site-packages/kafka/client_async.py", line 639, in check_version
self.poll(future=f)
File "/srv/.../lib/python2.7/site-packages/kafka/client_async.py", line 367, in poll
responses.extend(self._poll(timeout, sleep=sleep))
File "/srv/.../lib/python2.7/site-packages/kafka/client_async.py", line 402, in _poll
ready, _, _ = select.select(fds, [], [], timeout)
ValueError: filedescriptor out of range in select()
```

AFAIK this is because the select() call is limited to FD_SETSIZE being 1024 on Linux.

**Comment by dpkp** [comment]
thanks for bug report! we'll need to get more sophisticated here. one semi-related improvement is to add support for closing idle sockets (Issue #548). the real fix here may be to check for select alternatives (epoll / poll / etc).

**Comment by pnuckowski** [comment]
+1

**Comment by deejay1** [comment]
Maybe one possibility would be using `selectors` (https://pypi.python.org/pypi/selectors34) or libev?

**Comment by dpkp** [comment]
I had considered selectors originally - it would be great here, but I really do not want to add external dependencies. How would you feel about making this optional? Use selectors if available, otherwise stick w select and document the fd limit?

**Comment by deejay1** [comment]
Sure we can live with an optional dependency. other solution would be to write a custom class which would handle all the Python built in pollers (epoll, kqueue, etc), but it smells with NIH syndrome much and so far I haven't been able to find a thin wrapper around them.

**Comment by pnuckowski** [comment]
Also in console output we have following message:
```
Exception AttributeError: "'KafkaClient' object has no attribute '_wake_r'" in <bound method KafkaClient.__del__ of <kafka.client_async.KafkaClient object at 0x7f5fae215b10>> ignored
```

**Comment by dpkp** [comment]
@pnuckowski: that's unrelated. It happens during gc and as noted it is simply 'ignored'. Please file a separate issue if you think it is worth fixing.

**Comment by deejay1** [comment]
Hmm, after some thought as for the closing of idle sockets won't help in the case of this client, as the total number of sockets opened by the process is above 1024 (ZMQ sockets for workers, etc)

**Comment by michaelr524** [comment]
we are facing the same issue..
has anyone found a temporary workaround until this gets fixed?

**Comment by dpkp** [comment]
I put up PR #640 to migrate to the selectors module and remove the explicit use of `select`. Please let me know if you have comments or have a moment to test whether this fixes your issue.
