### ISSUE TITLE
Consumer Group Coordinator change not detected during heartbeats

### ISSUE THREAD

**Issue by choranus** [dpkp/kafka-python#614]
Hi,
I've made 3 brokers which are
localhost:9092, localhost:9093, localhost:9094
and I have made a topic with a console:
$KAFKA_HOME/bin/kafka-topics.sh --create --zookeeper localhost:2181 --topic replica1 --replication-factor 3 --partition 3

The codes work fine when all servers are up, but when I force a 9092 server down, the consumer class start to not work while it works on console.
When I check the status with kafka-topics.sh --describe --zookeeper localhost:2181 --topic replica1, it shows that the leader has been changed and that the ISR has only 2 servers.

As I understand the Kafka, it automatically chnages the leader when the original server is down, and the consumer starts to read the message from the changed leader, which is why we are using replication-factor. Consumer consumes messages from the leader broker, and when the leader broker has unexpectedly disconnected, another broker becomes the leader, and consumer starts to consume messages from the different leader.
That's what I'm understanding about kafka replication.

I wanted to check which servers are in connection, so I tried to use kafka.conn.collect_hosts('localhost') and I expected it to show localhost:9093, localhost:9094 when I force localhost:9092 down, but it ONLY showed 'localhost:9092'.

What I have tried to fix the problem is giving only two bootstrap_servers when declaring consumer.

**ex)
bootstrap_servers = [ ]
for servers in ['localhost:9092', 'localhost:9093', 'localhost:9094']:
     try:
         KafkaConsumer(bootstrap_servers = [servers])
         bootstrap_servers.append(servers)
     except:
         logging.warning("Brokers not available")
consumer = KafkaConsumer(bootstrap_servers = bootstrap_servers, {other configs such as auto_offset_rest = 'earliest'})
consumer.subscribe('replica1')

for message in consumer:
      print message.value**

Even though replica1 has more than 70,000 messages in the lag, consumer doesn't show any messages...

Am I missing any important points?
Can anyone explain how my understanding is wrong?
Is there any way to fix this problem?

**Comment by dpkp** [comment]
Try passing all of your known brokers as a list to bootstrap_servers:

```
consumer = KafkaConsumer(bootstrap_servers=['localhost:9092', 'localhost:9093', 'localhost:9094'])
consumer.subscribe(['replica1'])

for msg in consumer:
  print msg
```

**Comment by choranus** [comment]
I have tried to passing all of my known brokers to bootstrap_servers, but it doesn't show any messages.
As I said above, I have tried to check whether the leader has not been changed yet, but leader has already been changed, and the code also shows the list of topics.

**Comment by choranus** [comment]
Additionally, attaching the log I'm watching.

2016-03-30 17:33:43,186 INFO: Group coordinator for infra is BrokerMetadata(nodeId=0, host=u'localhost', port=9092)
2016-03-30 17:33:43,186 INFO: Group coordinator for infra is BrokerMetadata(nodeId=0, host=u'localhost', port=9092)
2016-03-30 17:33:43,187 ERROR: Connect attempt to <BrokerConnection host=localhost port=9092> returned error 111. Disconnecting.
2016-03-30 17:33:43,187 WARNING: Node 0 connect failed -- refreshing metadata
2016-03-30 17:33:43,187 INFO: Marking the coordinator dead (node 0): None.
2016-03-30 17:33:43,188 WARNING: Coordinator unknown during heartbeat -- will retry
2016-03-30 17:33:43,188 WARNING: Heartbeat failed; retrying


Then keep showing that

2016-03-30 17:33:43,506 WARNING: Coordinator unknown during heartbeat -- will retry
2016-03-30 17:33:43,506 WARNING: Heartbeat failed; retrying
2016-03-30 17:33:43,516 WARNING: Coordinator unknown during heartbeat -- will retry
2016-03-30 17:33:43,516 WARNING: Heartbeat failed; retrying
2016-03-30 17:33:43,517 WARNING: Coordinator unknown during heartbeat -- will retry
2016-03-30 17:33:43,517 WARNING: Heartbeat failed; retrying
2016-03-30 17:33:43,543 WARNING: Coordinator unknown during heartbeat -- will retry
2016-03-30 17:33:43,543 WARNING: Heartbeat failed; retrying
2016-03-30 17:33:43,546 WARNING: Coordinator unknown during heartbeat -- will retry
2016-03-30 17:33:43,546 WARNING: Heartbeat failed; retrying
2016-03-30 17:33:43,548 WARNING: Coordinator unknown during heartbeat -- will retry
2016-03-30 17:33:43,548 WARNING: Heartbeat failed; retrying
....

**Comment by dpkp** [comment]
Thanks for the logs -- it looks like there may be a bug in heartbeat processing when the coordinator changes. The problem here is not that the partitions are not replicated, but that the consumer group coordinator failover is not detected properly. Will investigate further.

**Comment by choranus** [comment]
Thank you for the help.

So you mean it's not my codes error?
Can I do anything to fix the error?
Can you recommend some functions to at least try to fix the problem?

**Comment by choranus** [comment]
Just for you information,
ERROR:kafka.conn:Connect attempt to <BrokerConnection host=localhost port=9092> returned error 111. Disconnecting.
ERROR:kafka.client:Unable to bootstrap from [('localhost', 9092)]
ERROR:kafka.client:No nodes found in metadata -- retrying bootstrap
ERROR:kafka.conn:Connect attempt to <BrokerConnection host=localhost port=9092> returned error 111. Disconnecting.
ERROR:kafka.client:Unable to bootstrap from [('localhost', 9092)]
Traceback (most recent call last):
  File "../../producer/6_postFinal.py", line 60, in <module>
    producer=KafkaProducer(retries=5)
  File "/root/wjcho/pypy/site-packages/kafka/producer/kafka.py", line 248, in __init__
    self.config['api_version'] = client.check_version()
  File "/root/wjcho/pypy/site-packages/kafka/client_async.py", line 594, in check_version
    raise Errors.NoBrokersAvailable()
NoBrokersAvailable
INFO:kafka.producer.kafka:Closing the Kafka producer with 0 secs timeout.
INFO:kafka.producer.kafka:Proceeding to force close the producer since pending requests could not be completed within timeout 0.

This is what I get for the really simple producer when I force server 9092 down.
In the code, I'm trying to connect to only 9093, but it still tries to connect to 9092, I think.

#!/bin/env python2.7

'''
This is a code that select datas from the postgresql
and make them as a dict type data.
Then put them in the producer.
'''

from psycopg2cffi import compat
compat.register()
import psycopg2cffi
import time
import json
import logging
from kafka import KafkaProducer


conn_string=(#config for the postgresql data)
conn=psycopg2cffi.connect(conn_string)
producer = KafkaProducer(bootstrap_servers=['localhost:9093'], value_serializer=lambda m: json.dumps(m, ).encode('ascii'), client_id='infra', retries=5)

logging.basicConfig(level=logging.INFO)

curs = conn.cursor()

curs.execute(#select datas from posgresql)

columns= (#columns to make it dict type data)

result = []



for row in curs.fetchall():
        result.append(dict(zip(columns, row)))

for item in result:
        producer.send('replica11', item)
        producer.send('replica12', item)


conn.commit()

producer=KafkaProducer(retries=5)


This is my code

**Comment by choranus** [comment]
I've solved the problem.
It was not the problem of kafka-python.
I tried to re-install kafka, and it was working after the re-installation.
I saw the difference in the __consumer_offset topic which automatically made after the consumption.
Before I re-installed, __consumer_offset topic was not replicated, which means that it shows only one replication-factor.
When I re-installed and consumed again, __consumer_offset has 3 replication-factor, and when I kill one kafka server, it automatically changed the leader, and it was working.

Still thank you for your help.

**Comment by dpkp** [comment]
Good news! Thanks for the update

**Comment by cs94njw** [comment]
You can also update the replication factor manually for "__consumer_offset" topic by using
`~/kafka/bin/kafka-reassign-partitions.sh --execute --zookeeper <ip>:<port> --reassignment-json-file ./offsetReplication.json`

Inside that .json file, for each partition you have, specify the node IDs you which to replicate to.
[offsetReplication.txt](https://github.com/dpkp/kafka-python/files/793856/offsetReplication.txt)
