### ISSUE TITLE
Synchronous producer, mistaken timeout

### ISSUE THREAD

**Issue by unclethan** [dpkp/kafka-python#618]
Following the 'sync' example at http://kafka-python.readthedocs.org/en/1.0.1/usage.html, using a timeout of 30 seconds:

    future = producer.send(topic, message) 
    try:
      record_metadata = future.get(timeout=30)
    except KafkaError as e:
      print "Got kafkaerror {0}".format(e)

the issue is that the messages are sent to kafka just fine, but errors are **immediately** returned stating:

    Got kafka error Timeout after waiting for 30 secs.

Putting a producer.flush() before the try alleviates the issue, but the example implied it was unnecessary.

**Comment by dpkp** [comment]
This would be a bug, but I'm not able to reproduce on the latest release. You should not need to call producer.flush() to avoid a timeout. Please reopen if this happens again.

**Comment by Qin-Long** [comment]
Hi,guys. I meet the same issue like this .How to deal with this issue for sync send?

**Comment by jeffwidman** [comment]
@Qin-Long this is an old ticket, if you are hitting problems please open a new ticket and include details like the version of kafka-python, broker version, sample code, etc
