### ISSUE TITLE
Check API raises Error

### ISSUE THREAD

**Issue by patitoaxel** [dpkp/kafka-python#627]
Hello, 

Maybe only happened in my implementation, however, it's a bug.

I have a VM setup under VirtualBox with Host-only network setup.

The VM holds both Kafka and Zookeeper.

When trying to do the most basic connection:

`consumer = KafkaConsumer("/messages", bootstrap_servers="192.168.56.101:9092")`

Raised

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../kafka/consumer/group.py", line 187, in __init__
    self.config['api_version'] = self._client.check_version()
  File ".../kafka/client_async.py", line 639, in check_version
    connect(node_id)
  File ".../kafka/client_async.py", line 602, in connect
    raise Errors.NodeNotReadyError(node_id)
kafka.common.NodeNotReadyError: 0
```

However, if I define the api_version:

`consumer = KafkaConsumer("something", bootstrap_servers="192.168.56.101:9092", api_version="0.9")`

Works fine!

**Comment by dpkp** [comment]
The error suggests that the consumer is unable to connect to the cluster.
Are you able to consume messages after setting api_version? What version of
Python are you using? kafka-python version? What OS? Can you post debug
logs of the error?

**Comment by patitoaxel** [comment]
You are right, the error came from the connection to the cluster. 

Thank you!
