### ISSUE TITLE
Help: Discrepancy between kafka.consumer.fetcher and KafkaConsumer

### ISSUE THREAD

**Issue by Poogles** [dpkp/kafka-python#631]
We seem to be losing messages in flight between kafka.consumer.fetcher._handle_fetch_response and the KafkaConsumer API.

```Apr 06 08:43:38 host bash[20676]: DEBUG:kafka.conn:<BrokerConnection host=kafka-1 port=9092> Response 115022: FetchResponse(topics=[(topics='click', partitions=[(partition=8, error_code=0, highwater_offset=82313, message_set=[(offset=82312, message_size=433, message=(crc=-261609733, magic=0, attributes=2, key=None, value=b'\x82SNAPPY\x00\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x01\x8f\xbe\x03\x00\x00\x01\x01\x90\x01A\x88\x00\x00\x01\xb2\x1dv\xc4\t\x00\x00\xff\xff\xff\xff\x00\x00\x01\xa4{MESSAGE}'))])])])
Apr 06 08:43:38 host bash[20676]: DEBUG:kafka.consumer.fetcher:Adding fetched record for partition TopicPartition(topic='click', partition=8) with offset 82312 to buffered record list
Apr 06 08:43:38 host bash[20676]: DEBUG:kafka.consumer.fetcher:Adding fetch request for partition TopicPartition(topic='click', partition=8) at offset 82312```

These messages are not then produced from the high level API.  A stripped down example of the code we're using.

```
self.consumer = KafkaConsumer(bootstrap_servers=self.kafka_hosts,
                              group_id=self.group_id,
                              auto_offset_reset='earliest',
                              heartbeat_interval_ms=1000)

### Lots of code missing.###

with open(file_path, 'a') as fp:

    for msg in self.consumer:

        # Transform (this decodes some json and pops some fields).
        fp.write(transform(msg.value))
        line_total += 1

        # Check if we're hitting our target.
        # We implement a batch pull timeout due to low activity at times.
        if line_total == self.line_target or self._max_fetch_time():

            # Force consumer commit.
            self.consumer.commit()

            break
```

I've had a look through the library and the message path seems quite simple, the only point I can see where we may be losing messages is https://github.com/dpkp/kafka-python/blob/master/kafka/consumer/fetcher.py#L422.  We're not however calling seek() manually anywhere?  I think it would be good to change this to log something when continue is called as currently that could be a bit of a black hole.

Any pointers on where to go from here would be good.  We're seeing around a 5% discrepancy on ~25k messages a day which is quite considerable.

**Comment by dpkp** [comment]
Are you running v1.0.2? master? Can you verify that all messages are getting produced correctly (console-consumer.sh)?

There was a snappy bug at one point that caused deserializing to raise a StopIteration that interfered with the Kafka iterator. I believe we fixed that, but this feels similar.

**Comment by Poogles** [comment]
1.0.2.  We've found the discrepancy by doing a sorted diff on the output of kafka-python vs the console consumer.

**Comment by dpkp** [comment]
Deserialization bug was in issue #545

**Comment by dpkp** [comment]
545 was wrt to avro. It is possible there is a similar issue w decompression. What version of snappy / python-snappy are you using?

**Comment by Poogles** [comment]
```dpkg -s libsnappy-dev | grep Version
Version: 1.1.3-2```

And

```Name: python-snappy
Version: 0.5```

**Comment by dpkp** [comment]
I haven't been able to reproduce. If you are able to test w/ master maybe the #634 changes might help diagnose whether you are seeing skipped messages or StopIteration exceptions.

**Comment by Poogles** [comment]
Patched what we currently have running with master; if this doesn't dig up anything I'll add in a load more logging and come back with what I find.

**Comment by Poogles** [comment]
I can't see anything in the kafka-python code that can be causing this, it must be something my side.  Closing, if I find anything further down the line I'll re-open.

Thanks for the help!
