### ISSUE TITLE
Possible typo in example JSON-serializing KafkaProducer

### ISSUE THREAD

**Issue by falquaddoomi** [dpkp/kafka-python#635]
I was trying out your library today and noticed that the following example from the README uses ```json.loads``` as the serializer (instead of ```json.dumps``` as I'd expect).

```
>>> # Serialize json messages
>>> import json
>>> producer = KafkaProducer(value_serializer=json.loads)
>>> producer.send('fizzbuzz', {'foo': 'bar'})
```
While trying it out, I noticed that using ```json.loads``` as in the original example results in nothing appearing on my active consumers, but replacing it with ```json.dumps``` causes the consumers to display the messages.

(Disclaimer: I'm extremely new to Kafka, so this may be a misunderstanding on my part of how it's supposed to delimit messages. I'm using both KafkaConsumer from your library with a json.loads deserializer and the test Kafka console consumer from the Kafka quickstart documentation.)

**Comment by dpkp** [comment]
Thanks for the bug report! Looks like we fixed on http://kafka-python.readthedocs.org/ but forgot to fix the README. Will update.

**Comment by dpkp** [comment]
pushed README fix. (also ref PR #573 )
