### ISSUE TITLE
possible deadlock on network interruption

### ISSUE THREAD

**Issue by kputland** [dpkp/kafka-python#638]
I'm pushing to kafka with producer.send(data) inside a loop in a generator being used by another process. Something like the following

```
def g(rawdata):
    producer = KafkaProducer(...)
    for something in rawdata:
        data = process(something)
        producer.send(data)
        # yield data to other process
        yield data
```

When the communication thread crashed with the errors included below, then the program hung and did not continue processing records.

Is there a way to test the state of the producer before calling send if that is where the deadlock is? T

2016-04-07 05:56:21,121 - kafka.conn - ERROR - <BrokerConnection host=kafka-data-01.dev.s.xxxxx.net port=9092>: Error receiving 4-byte payload header - closing socket
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/kafka/conn.py", line 248, in recv
    self._rbuffer.write(self._sock.recv(4 - self._rbuffer.tell()))
error: [Errno 104] Connection reset by peer
2016-04-07 05:56:21,976 - kafka.conn - ERROR - <BrokerConnection host=kafka-data-02.dev.s.xxxxx.net port=9092>: Error receiving 4-byte payload header - closing socket
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/kafka/conn.py", line 248, in recv
    self._rbuffer.write(self._sock.recv(4 - self._rbuffer.tell()))
error: [Errno 104] Connection reset by peer
2016-04-07 05:56:22,353 - kafka.conn - ERROR - <BrokerConnection host=kafka-data-03.dev.s.xxxxx.net port=9092>: Error receiving 4-byte payload header - closing socket
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/kafka/conn.py", line 248, in recv
    self._rbuffer.write(self._sock.recv(4 - self._rbuffer.tell()))
error: [Errno 104] Connection reset by peer

**Comment by dpkp** [comment]
Those errors don't look abnormal. It typically indicates network issues or your kafka broker has crashed while processing the request. Have you checked your broker logs?

I dont see anything indicating a "deadlock"

**Comment by kputland** [comment]
The program was stuck. There was not a way for me to attach pdb to find out where it was stuck.
The loop that yields was likely still doing producer.send() and at the end of the outer section it does a producer.flush(). How can I detect that the sockets are closed and that the producer needs to reconnect?

**Comment by kputland** [comment]
currently using 1.0.1

**Comment by dpkp** [comment]
Please upgrade to 1.0.2 -- there are known critical bugs in 1.0.1 that could crash the producer thread (take a look at the CHANGELOG for more details)

**Comment by kputland** [comment]
Upgraded to 1.0.2
Attached the logging.

Forcing a network connection issues causes the program to hang without notification to the main thread or to the producer process that the connection is closed. I'm checking producer._closed but that doesn't help. 

I created this scenario by disconnecting my network cable and then calling flush to force unsent data.

```python
producer_queue = Queue()
def producer_process():
    #kproducer = kafka.KafkaProducer(bootstrap_servers=OPTIONS.KAFKA_HOSTS, value_serializer=json_serializer.dumps)
    kproducer = kafka.KafkaProducer(bootstrap_servers=OPTIONS.KAFKA_HOSTS)
    logger.debug('\n{}\nproducer_process: kproducer._closed: {}\n{}'.format('='*80,kproducer._closed,'='*80))
    while not kproducer._closed:
        try:
            item = producer_queue.get(timeout=3)
            if item is None:
                logger.info('producer_process: None found in queue. No more items to process')
                break
            args, kwargs = item
            logger.debug('producer_process: send to topic: {}'.format(args[0]))
            kproducer.send(*args, **kwargs)
        except Empty:
            logger.info('producer_process: producer_queue: timeout - check kproducer._closed on next loop')
            pass
        except:
            raise
    kproducer.flush()
    kproducer.close()
```

[kafka-python-error.txt](https://github.com/dpkp/kafka-python/files/215917/kafka-python-error.txt)

**Comment by dpkp** [comment]
Have you tried inspecting the future returned by `kproducer.send(*args, **kwargs)` ? That is where producer errors get reported.

**Comment by kputland** [comment]
Documentation isn't clear on what to do with it. Nothing in API docs regarding RecordMetadata or FutureRecordMetadata. Following search doesn't yield useful results.

http://kafka-python.readthedocs.org/en/1.0.2/search.html?q=FutureRecordMetadata&check_keywords=yes&area=default

**Comment by kputland** [comment]
ok. I've sorted out the add_callback and add_errback
I think I can use this to signal the error to the loop condition.
Crude, but seems to work.

```python
producer_queue = Queue()
def producer_process():
    kproducer = kafka.KafkaProducer(bootstrap_servers=OPTIONS.KAFKA_HOSTS)
    logger.debug('\n{}\nproducer_process: kproducer._closed: {}\n{}'.format('='*80,kproducer._closed,'='*80))
    class KStatus:
        def __init__(self):
            self.connected = True
            self.error = None
        def callback(self, recordmeta):
            logger.info(recordmeta)
        def errback(self, error):
            self.connected = False
            self.error = error
    kstatus = KStatus()
    while kstatus.connected:
        try:
            item = producer_queue.get(timeout=3)
            if item is None:
                logger.info('producer_process: None found in queue. No more items to process')
                break
            args, kwargs = item
            logger.debug('producer_process: send to topic: {}'.format(args[0]))
            kproducer.send(*args, **kwargs).add_callback(kstatus.callback).add_errback(kstatus.errback)
        except Empty:
            logger.info('producer_process: producer_queue: timeout - check kproducer._closed on next loop')
            pass
        except:
            producer_queue.close()
    kproducer.flush()
    kproducer.close()
```

**Comment by kputland** [comment]
I still think that KafkaProducer should have some knowledge of the state of the communications channel so that calls to send raise an error instead of blocking on a full buffer that will never empty.

**Comment by dpkp** [comment]
Totally valid opinion. We are sticking closely to the Java client API,
which does block on send in those cases.
