### ISSUE TITLE
Client never chooses IPv6 after bootstrapping

### ISSUE THREAD

**Issue by Roguelazer** [dpkp/kafka-python#641]
If you provide IPv6 addresses when creating the client (e.g., `bootstrap_servers=["[::1]:9092"]`) and the server responds with a hostname (e.g., `localhost`), this library always actually uses IPv4. This is because the `get_ip_port_afi` function, when passed a hostname, always returns and address family of `AF_INET`.

Ideally, I think this code should be restructured to use `getaddrinfo` and a loop to detect whether the host is available over v4 or v6. It looks like there's no actual resolution in `kafka/conn.py`; we're relying on implicit resolution done by passing a hostname to `socket.connect_ex`; hopefully that uses getaddrinfo behind the scenes and follows RFC 3484.

**Comment by dpkp** [comment]
care to submit a PR that implements your proposal?

**Comment by Roguelazer** [comment]
I'm working on one now!

**Comment by dpkp** [comment]
awesome -- thanks for looking into this!
