### ISSUE TITLE
check version called without timeout

### ISSUE THREAD

**Issue by eastlondoner** [dpkp/kafka-python#643]
It's currently not possible to set the timeout on the check version call when a Producer is created.
If you do have a slow network or other issues affecting this then it's very frustrating that you cannot configure the timeout.

**Comment by dpkp** [comment]
The solution here is to pass in `api_version=#` when creating your KafkaConsumer or KafkaProducer. If we enabled configuring a timeout to check_version, it would still just raise an exception and crash and that isn't ideal (yes, the crash could be faster). The reason for the crash is that the client must have some value for api_version to operate.

**Comment by eastlondoner** [comment]
It's not true to say "If we enabled configuring a timeout to check_version, it would still raise an exception and crash"
I am getting an exception because it is timing out because I have an excessively slow network on the first call.

**Comment by eastlondoner** [comment]
https://github.com/dpkp/kafka-python/pull/644
