### ISSUE TITLE
Question: How do I commit a partition?

### ISSUE THREAD

**Issue by jgasyna** [dpkp/kafka-python#645]
Using kafka-python-1.0.2.

If I have a topic with 10 partitions, how do I go about committing a particular partition, while looping through the various partitions and messages.   I just cant seem find an example of this anywhere, in the docs or otherwise

From the docs, I want to use:   

```
consumer.commit(offset=offsets)
```

Specifically, how do I create the partition and OffsetAndMetadata dictionary required for offsets (dict, optional) – {TopicPartition: OffsetAndMetadata}.  

I was hoping the function call would just be something like:  

```
consumer.commit(partition, offset), 
```

but this does not seem to be the case.

Thanks in advance.

**Comment by jgasyna** [comment]
So it looks like this will pass the OffsetAndMetadata assertion check , but I am still not sure what goes in as the metadata value, the second parameter in the namedtuple.

The first parameter, 4,  is obviously the offset.

```
options = {}
options[partition] = OffsetAndMetadata(4, 0)
consumer.commit(options)
```

**Comment by jgasyna** [comment]
So it looks like I may have figured it out, funny how that happens when you write down your questions.  This seems to work:

```
            meta = consumer.partitions_for_topic(topic)
            options = {}
            options[partition] = OffsetAndMetadata(message.offset, meta)
            consumer.commit(options)

```

More testing is needed, but will update if anything changes.

**Comment by dpkp** [comment]
the metadata is really just an opaque string. You can also pass `None`. Nothing uses metadata internally, it is there as a way for you to store application-specific data if needed. But very few folks actually use that functionality, so beware if you go down that path.

**Comment by dpkp** [comment]
closing because OffsetAndMetadata is the way to do this.

**Comment by jeffwidman** [comment]
@gyoga99 this is an old issue, better to file a new ticket. Reading your description, there is also a decent chance that this is a misunderstanding of how kafka works, so you might want to also post this as a question on stackoverflow, as we generally try to reserve the issue tracker for bugs and feature requests.
