### ISSUE TITLE
HELP: Consumer re balance on new consumer subscription w/ local offset storage

### ISSUE THREAD

**Issue by nickvasilyev** [dpkp/kafka-python#646]
I have a topic with 10 partitions, I get a consumer by passing in group_id and client_id, then I subscribe to the topic. After I run poll() I can see all the partitions listed through assignment(). 

Then I start a brand new consumer in exactly the same way. I was expecting some of partitions assigned to the first consumer to go the second one so they are more equally spread out. However, what I am seeing is that both consumers have all partitions. If I start to pull items out, each consumer pulls out the same item (same partition, offset). 

What am I missing here?

**Comment by dpkp** [comment]
Assignment changes are typically triggered by heartbeat responses telling the consumer that a rebalance is in progress. All of this happens internally within consumer.poll() -- there is no background thread. That means that you need to run the consumers independently for them to coordinate. Have you tried using multiple python repls / multiple processes?

**Comment by nickvasilyev** [comment]
Yup, I am writing some unit tests and put a code.interact(local=locals()) to pause the execution half way through the test. 

I execute the test and it pauses, I check the assignment. Then in separate terminal I am running the test again.

**Comment by nickvasilyev** [comment]
Here is some sample code:

from kafka import KafkaConsumer
consumer = KafkaConsumer(group_id = 'consumer1',
                        client_id = 'consumer1-id',
                        bootstrap_servers='localhost:7021', **kwargs)
consumer.subscribe(topics=('dev1',))
consumer.poll()
print(consumer.assignment())
import code
code.interact(local=locals())

Running this in two different terminals gives me the same consumer.assignment() for each of the sessions. 

Thanks

**Comment by nickvasilyev** [comment]
Also, I don't really want to get all the data through poll. All I really want is to just ping kafka to get assignment and offsets for all partitions that are assigned to the consumer. Is there a better way to do this?

**Comment by dpkp** [comment]
The consumer object's state only changes during poll() calls. If you want coordinated state, you need to make sure that the consumers are running poll() simultaneously. This typically involves having processes looping over poll() or the iterator interface.

Re: responses, you can try the pause() interface to prevent consumers from fetching data for a list of partitions.

**Comment by nickvasilyev** [comment]
The trouble is that the list of partitions is not available after I make the consumer and subscribe. So I am not sure which partitions I should pause unless I manually assign them which is not something I want to keep track of. 

I am storing the offset for each partition locally. It gets logged when the consumer pulls enough data to pass to the next component and write to disk for backup. Until this happens the consumer wrapper keeps the data in memory, which will be lost if the consumer crashes.

When the consumer starts, I want it to read the latest offsets and assign them to the partitions if available, however I need to know what partitions it is subscribed to before it starts to pull messages. 

Additionally, if I bring online another consumer, they will re balance and change which partitions they are saving offsets for. I anticipated this to be rather straightforward since it seems like a pretty common use case. 

I was thinking that I can just disable autocommit in the consumer and send a commit to kafka manually, but I would really like a little more control of the process. Can you advise on the best way to proceed? 

Thanks in advance

**Comment by dpkp** [comment]
I'd suggest simply using the kafka offset storage systems. Why are you rolling your own? Most folks that roll their own offset storage also roll their own partition assignment.

**Comment by nickvasilyev** [comment]
Just to add extra complexity man, why else? :)

**Comment by dpkp** [comment]
ha! Ok, I haven't tried to use the setup you are considering. You might try sending a note to the kafka users email list. The kafka-python api is basically identical to the new java client apis, so maybe other folks in the larger community have tackled this already.
