### ISSUE TITLE
kafka-python for kafka streams & kafka 0.10

### ISSUE THREAD

**Issue by abuvaneswari** [dpkp/kafka-python#652]
Where can I find release plan for kafka-python? 

kafka-streams preview version is available now - can you comment if there are plans to support the same in kafka-python? 

kafka 0.10 will be out on Apr 22nd. what is the plan from kafka-python end to support the same?

**Comment by dpkp** [comment]
No plans to build a KStreams API into kafka-python. This would be a fun project, but should be developed separately from the client code, IMO.

0.10 server is still in development -- it will not be released 4/22 fwiw. There are several api improvements. The major one that I expect to support quickly is KIP-35. If KIP-4 lands, I would plan to support that as well. The remaining server improvements that I'm aware of relate to SASL, which would be blocked on getting baseline SASL support in kafka-python.

Hope this helps.

**Comment by abuvaneswari** [comment]
Data, thanks a lot for the quick response! 
when 0.10 Kafka server will be out, will the current APIs of kafka-python 1.0.2 be compatible with it?

**Comment by dpkp** [comment]
Yes. kafka brokers are intended to be backwards-compatible. For all kafka clients (not just kafka-python), you should be able to upgrade your brokers without breaking client operations.

**Comment by dpkp** [comment]
Apache kafka 0.10-rc6 has been approved and should be officially released in a few days. I expect to publish a new release with additional feature support this week.
