### ISSUE TITLE
TopicPartition does not validate partition type as integer

### ISSUE THREAD

**Issue by kashifusmani** [dpkp/kafka-python#653]
By mistake, I ended up creating TopicPartition('topic','0') instead of TopicPartition('topic',0).
Down the line, I did consumer.assign([topicPartition]) and consumer.seek(...), but never saw any warnings nor I could read messages until I debugged.

**Comment by notifytovishal** [comment]
I am not sure if it qualifies as a bug. If it does it is a problem in the core Kafka [https://github.com/apache/kafka/blob/6eacc0de303e4d29e083b89c1f53615c1dfa291e/clients/src/main/java/org/apache/kafka/common/TopicPartition.java](TopicPartition.java). When you passed in '0', it would have created a topic with partition 48 (ascii for '0') instead. I think a warning will be useful though.

**Comment by jeffwidman** [comment]
Closing as an ancient issue and this code has changed a bit since then. If anyone wants to spend the time to see if this can be replicated with `2.x` version than I'm happy to re-open and accept a patch.
