### ISSUE TITLE
KafkaProducer and auto.create.topics.enable

### ISSUE THREAD

**Issue by kirillkrainov** [dpkp/kafka-python#654]
auto.create.topics.enable = true in my kafka cluster, but when i try to produce message to topic, which does not exists yet, i getting following error: 
kafka.common.KafkaTimeoutError: ('Failed to update metadata after %s secs.', 60.0)

**Comment by dpkp** [comment]
Have you checked your broker logs? There isn't enough information here for me to reproduce. Topic auto-creation is used and tested fairly well in the kafka-python test suite, though there can always be bugs!
