### ISSUE TITLE
Connection exception handling incompatible with Python3.

### ISSUE THREAD

**Issue by dragonpaw** [dpkp/kafka-python#655]
In `kafka/conn.py` there is a line `if not ret or ret is errno.EISCONN`. This refers to the exception handler right above it that reads `except ... as ret`. In Python3 the variables created by exception handling are scoped to the exception handler. Once finished, the variable is destroyed. This leads to an `UnboundLocalError` when the connection fails, because there is no `ret` variable.

Sample of Py3 behavior:
```python
try:
    3/0
except ZeroDivisionError as e:
    pass
print(e)
```

**Comment by dpkp** [comment]
This has been fixed in master
