### ISSUE TITLE
client_async.__del__ can throw exception on failed construction.

### ISSUE THREAD

**Issue by dragonpaw** [dpkp/kafka-python#656]
In `client_async.py` there is a line `os.close(self._wake_r)`. Unfortunately as that property is only set at the end of `__init__` it is likely that property will not exist if there is an exception raised from within `__init__` during construction. This line needs to be guarded with a `if hasattr(self, '_wake_r')` or similiar to avoid creating a second exception that obscures the exception being raised by `__init__`

**Comment by dpkp** [comment]
Fixed in PR #649
