### ISSUE TITLE
Flow control: producer is sending messages when consumers are close to partition end

### ISSUE THREAD

**Issue by sibiryakov** [dpkp/kafka-python#658]
Hi guys,
I was developing Kafka-based message bus for our [Frontera](https://github.com/scrapinghub/frontera) web crawling framework. The idea was to use Kafka as a data bus to help scale and distribute web crawler components. To avoid generating heavy load and loosing messages because of log rotation in Kafka brokers we decided to introduce a flow control. Worker will produce new requests to crawl only when spiders are about to consume them, but doing it earlier before they face the log end. That implies periodical checking by worker the offsets of spiders (which are all members of the same group).

Here is the code doing that
https://github.com/scrapinghub/frontera/blob/master/frontera/contrib/messagebus/kafka/__init__.py

As I understand it requires significant refactoring to make it work in kafka-python 1.0.x versions with new async client. I would like to ask you to guide me how to implement it the most reliable way: using only public APIs, and resistant to kafka-python client future changes.

**Comment by sibiryakov** [comment]
@dpkp any thoughts on this, please? This is quite important feature for Frontera to perform efficiently with Kafka.

**Comment by dpkp** [comment]
Looks like you've managed to migrate to the new releases, so I'm going to close this out.
