### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by kennethreitz** [dpkp/kafka-python#659]
Very excited about the fact that SSL has been merged in, which is a requirement in my environment. 

Would it be possible to cut a release with this functionality (which has been merged into master)?

If not (understandable), when can we expect a release to be made?

Many thanks. You're doing great work!

**Comment by dpkp** [comment]
Aiming to cut 1.1.0 tomorrow or this weekend. There's a few outstanding
issues that need a little attention (IPv6, check version, and py3 PRs).
Soon!

**Comment by kennethreitz** [comment]
:sparkles: :cake: :sparkles:

**Comment by dpkp** [comment]
1.1.0 published to pypi. feedback welcome!
