### ISSUE TITLE
socket disconnect ignored when connection has no in-flight-requests

### ISSUE THREAD

**Issue by Roguelazer** [dpkp/kafka-python#661]
If I run my producers with a git rev that includes #640, I see super-high load after a few minutes. I haven't got a great repo case because it doesn't happen immediately or at low load; it only enters this state after a few minutes of production load.

I haven't tracked it down 100% yet, but `strace` shows that Kafka is spinning on `epoll_wait` at a fairly insane rate; basically just pages and pages of 

```
[pid  1633] 23:35:16.854435 epoll_wait(16, {{EPOLLIN, {u32=17, u64=14715574381581434897}}}, 7, 5000) = 1
[pid  1633] 23:35:16.854596 epoll_wait(16, {{EPOLLIN, {u32=17, u64=14715574381581434897}}}, 7, 5000) = 1
[pid  1633] 23:35:16.854755 epoll_wait(16, {{EPOLLIN, {u32=17, u64=14715574381581434897}}}, 7, 5000) = 1
[pid  1633] 23:35:16.854925 epoll_wait(16, {{EPOLLIN, {u32=17, u64=14715574381581434897}}}, 7, 5000) = 1
[pid  1633] 23:35:16.855088 epoll_wait(16, {{EPOLLIN, {u32=17, u64=14715574381581434897}}}, 7, 5000) = 1
[pid  1633] 23:35:16.855247 epoll_wait(16, {{EPOLLIN, {u32=17, u64=14715574381581434897}}}, 7, 5000) = 1
[pid  1633] 23:35:16.855406 epoll_wait(16, {{EPOLLIN, {u32=17, u64=14715574381581434897}}}, 7, 5000) = 1
[pid  1633] 23:35:16.855566 epoll_wait(16, {{EPOLLIN, {u32=17, u64=14715574381581434897}}}, 7, 5000) = 1
[pid  1633] 23:35:16.855728 epoll_wait(16, {{EPOLLIN, {u32=17, u64=14715574381581434897}}}, 7, 5000) = 1
[pid  1633] 23:35:16.855889 epoll_wait(16, {{EPOLLIN, {u32=17, u64=14715574381581434897}}}, 7, 5000) = 1
[pid  1633] 23:35:16.856063 epoll_wait(16, {{EPOLLIN, {u32=17, u64=14715574381581434897}}}, 7, 5000) = 1
[pid  1633] 23:35:16.856225 epoll_wait(16, {{EPOLLIN, {u32=17, u64=14715574381581434897}}}, 7, 5000) = 1
[pid  1633] 23:35:16.856385 epoll_wait(16, {{EPOLLIN, {u32=17, u64=14715574381581434897}}}, 7, 5000) = 1
[pid  1633] 23:35:16.856546 epoll_wait(16, {{EPOLLIN, {u32=17, u64=14715574381581434897}}}, 7, 5000) = 1
[pid  1633] 23:35:16.856707 epoll_wait(16, {{EPOLLIN, {u32=17, u64=14715574381581434897}}}, 7, 5000) = 1
[pid  1633] 23:35:16.856867 epoll_wait(16, {{EPOLLIN, {u32=17, u64=14715574381581434897}}}, 7, 5000) = 1
[pid  1633] 23:35:16.857036 epoll_wait(16, {{EPOLLIN, {u32=17, u64=14715574381581434897}}}, 7, 5000) = 1
[pid  1633] 23:35:16.857196 epoll_wait(16, {{EPOLLIN, {u32=17, u64=14715574381581434897}}}, 7, 5000) = 1
[pid  1633] 23:35:16.857356 epoll_wait(16, {{EPOLLIN, {u32=17, u64=14715574381581434897}}}, 7, 5000) = 1
[pid  1633] 23:35:16.857517 epoll_wait(16, {{EPOLLIN, {u32=17, u64=14715574381581434897}}}, 7, 5000) = 1
[pid  1633] 23:35:16.857677 epoll_wait(16, {{EPOLLIN, {u32=17, u64=14715574381581434897}}}, 7, 5000) = 1
```

This makes me think something is wrong with the selectors use...

**Comment by Roguelazer** [comment]
FWIW, this is with Kafka 0.9.0.1, in case it's something Kafka-version-specific.

Still haven't repro'd in dev with simulated production load, but it definitely happens in prod within 10 minutes or so. Might be because I only have one broker in dev...

**Comment by Roguelazer** [comment]
I've figured this out.

When a socket is closed on the remote side, `epoll` / `kqueue` get a READ event and then can do a 0-byte read to detect the closed socket. That can occur at any time (when the broker restarts or a load balancer terminates a connection). However, if there are no in-flight requests when this happens, `python-kafka` will never actually do a read on the socket to clear the epoll flag, so the code spins at 100% CPU with epoll returning 1 socket ready for reading.

To reproduce:

 - start a broker
 - start a KafkaProducer pointed to the broker
 - send a message to ensure that it connects, make sure it flushes out, then let it go through one 5s poll loop
 - kill the broker forcibly to terminate the TCP connection
 - voila, your KafkaProducer will spin at 100% CPU

**Comment by Roguelazer** [comment]
It might be worth cutting a 1.1.1 that includes this branch since it causes pretty bad borkage if you have firewalls or anything else that shut down idle TCP sessions...

**Comment by dpkp** [comment]
ha - my bad. I cut the release last night but forgot to upload to pypi!
