### ISSUE TITLE
Help: KafkaConsumer is not on the consumer-groups list

### ISSUE THREAD

**Issue by ayiis** [dpkp/kafka-python#662]
The sample [usage](http://kafka-python.readthedocs.org/en/1.0.2/usage.html#kafkaconsumer)

```python
from kafka import KafkaConsumer

consumer = KafkaConsumer(
    'test.ay.log',
    group_id = 'my-group-1',
    bootstrap_servers='192.168.70.221:19092'    # kafka cluster
)

for message in consumer:
    print message
```

It works good, message print as expected.

But somehow, i can't find the group (my-group-1) by the `groups-list` command on kafka cluster

```bash
bin/kafka-consumer-groups.sh --zookeeper 192.168.70.224:12181 --list
```

This command works for other consumers which is created by kafka-commandline or java even the [SimpleConsumer](http://kafka-python.readthedocs.org/en/1.0.2/simple.html) which is DEPRECATED, but doesn't work in this case.

Don't know why, am I mistaking something?

**Comment by dpkp** [comment]
My guess is that the script you are using to check groups is using an old
zookeeper-backed method. Try passing `api_version='0.8.1'` to KafkaConsumer
?

**Comment by dpkp** [comment]
Try `bin/kafka-consumer-groups.sh --new-consumer --list`

**Comment by ayiis** [comment]
It worked.

It reminds me that there is a [new consumer](http://kafka.apache.org/documentation.html#newconsumerconfigs) in kafka-0.9.0 I'm using.

When I passing `api_version=auto` by default, `check_version()` set `api_version` to 0.9, so I should use

```bash
bin/kafka-consumer-groups.sh --new-consumer --list
```

instead of

```bash
bin/kafka-consumer-groups.sh --list
```

By the way,  passing `api_version='0.8.x'` to KafkaConsumer doesn't work in this case, but never mind.

Thanks to you.
