### ISSUE TITLE
short-lived consumers can lead to uneven partition lag

### ISSUE THREAD

**Issue by zoltan-fedor** [dpkp/kafka-python#675]
I don't know why, but since I have upgraded to Kafka 0.9 and Kafka Python 1.1, my consumers become very highly unbalanced - to a point that consumption stops because one partition gets to 0 lag (runs out of messages), while others are still many millions of records behind.

See example below, where for a consumer running via kafka-python has partition 0 consumed fully (lag of 0 messages), while the consumption of other partitions are still far behind, but when try to consume more messages it doesn't return more messages.
The consumer started out with having the same offset on all partitions and after about consume 50 million messages, it became this unbalanced.

Is there any way to prevent this from happening? Any way to keep consumption balanced?

TOPIC A:
Partition |	        LogSize |		Consumer Offset |	Lag	Consumer
0			664138528	664138528		0
1			664119357	658899463		5219894	
2			664130323	656712249		7418074	
3			664126444	658191694		5934750	
4			664141710	656719190		7422520	
5			664124260	659035990		5088270	
6			664136092	656715270		7420822	
7			664138272	658300970		5837302	
8			664140116	656719047		7421069	
9			664129907	658761003		5368904	
10			664137420	656716581		7420839	
11			664125558	657185017		6940541	
12			664134645	656709180		7425465	
13			664141461	658481872		5659589	
14			664140271	656716946		7423325	
15			664130235	654488318		9641917	

The Kafka-python settings used by the consumer were the following:
```
  max_partition_fetch_bytes=10*1048576,
  receive_buffer_bytes=5*32768,
  enable_auto_commit=True,
  consumer_timeout_ms=45000,
  fetch_max_wait_ms=45*1000,
  auto_offset_reset='earliest',
  request_timeout_ms=60*60*1000
```

**Comment by dpkp** [comment]
Can you provide code to duplicate and/or log output?

**Comment by zoltan-fedor** [comment]
Sure, here comes the code (it is a lot longer, with more logging and stuff, so I had to remove those to make it shorter and leave the Kafka part in.

```
        kafka_consumer = KafkaConsumer(
            settings['topic'],
            group_id='kabinet_apphits_v2',
            bootstrap_servers=settings['kafka_servers'],
            max_partition_fetch_bytes=10*1048576,
            receive_buffer_bytes=5*32768,
            enable_auto_commit=True,
            consumer_timeout_ms=45000,
            fetch_max_wait_ms=45*1000,
            auto_offset_reset=settings['kafka_topic_auto_offset_reset'],
            request_timeout_ms=60*60*1000
        )
	num = 0
        try:
            for message in kafka_consumer:
                decoded_message = serializer.decode_message_w_schema_mapping(message.value)
    
                # write this message to hdfs
                writer.write(decoded_message)
    
                num += 1
                # if there is max export limit set, then exit when that has been achieved
                if num > settings['kafka_records_to_export']:
                    break
    
                # log at every milestone reached
                if num % 100000 == 0:
                    logger.info("Reached {0} rows (offset: {1} ...".format(num, message.offset))
    
            # when the for loop exited normally, because it ran out of messages or reached the maximum number of
            # messages allowed to export
            logger.info("""Consumed the last message, it seems there is no more in the topic or reached the
                        maximum allowed for export.
                        We wrote out {0} messages in total, so now we will check the file written.""".format(num))
            if 'message' in vars():
                logger.info("Last consumed message's partition={0} and offset={1}".format(message.partition, message.offset))

        except ConsumerTimeout:
            logger.info("""Timeout, it seems there are no more messages to consume (or reached export limit). We
                        have consumed and written {0} messages in total, so now we will check the file written.""".format(num))
            if 'message' in vars():
                logger.info("Last consumed message's partition={0} and offset={1}".format(message.partition, message.offset))

        except:  # capture all other exceptions - in which case we need to delete the partially written file from
            logger.info("UNKNOWN EXCEPTION - We got as far as message # {0}".format(num))
            if 'message' in vars():
                logger.info("Last consumed message's partition={0} and offset={1}".format(message.partition, message.offset))
                logger.info("Last consumed message's value={0}".format(message.value))
    
            try:
                # reset the offset back to what it was when we started
                reset_offset()
            except:
                # error with commiting the new offset!!!
                logger.error("""There was an error resetting the offsets back to what it was - so the file
                    was NOT deleted from HDFS {0}, but exiting here!!! {1}
                    """.format(settings['hdfs_target_file'], sys.exc_info()))
                sys.exit()

```

While running, it occasionally throws the next error - I am not sure whether this is related or not:

```
WARNING:kafka.coordinator:Heartbeat: local member_id was not recognized; this consumer needs to re-join
WARNING:kafka.coordinator:Heartbeat failed (UnknownMemberIdError - 25 - Returned from group requests (offset commits/fetches, heartbeats, etc) when the memberId is not in the current generation.); retrying
WARNING:kafka.coordinator.consumer:Auto offset commit failed for group kabinet_apphits_v2: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured session.timeout.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing the session timeout or by reducing the maximum size of batches returned in poll() with max.poll.records.
ERROR:kafka.coordinator.consumer:Offset commit failed: This is likely to cause duplicate message delivery
Traceback (most recent call last):
  File "/data/apps/kabinet-dev/kabinet/venv1/lib64/python3.5/site-packages/kafka/coordinator/consumer.py", line 382, in _maybe_auto_commit_offsets_sync
    self.commit_offsets_sync(self._subscription.all_consumed_offsets())
  File "/data/apps/kabinet-dev/kabinet/venv1/lib64/python3.5/site-packages/kafka/coordinator/consumer.py", line 369, in commit_offsets_sync
    raise future.exception # pylint: disable-msg=raising-bad-type
kafka.errors.CommitFailedError: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured session.timeout.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing the session timeout or by reducing the maximum size of batches returned in poll() with max.poll.records.
```

Also now I have seen other topics becoming unbalanced too (using the same code to consume) - see below example, which got this unbalanced after going through about 180 millions messages (it started out with balanced consumer offsets):

```
Partition |	LogSize |	Consumer Offset |	Lag
0	1024023690	1024013980	9710	
1	1024014825	1024014825	0	
2	1024023553	1024023553	0	
3	1024003337	1024003337	0	
4	1024035196	1013602923	10432273	
5	1024013348	1024013348	0	
6	1024023456	1024023456	0	
7	1024024469	1024024469	0	
8	1024030368	1021432451	2597917	
9	1024033217	1024033217	0	
10	1024030352	1024030352	0	
11	1024016847	1024016847	0	
12	1024021614	1024021614	0	
13	1024031666	1024031666	0	
14	1024030064	1024030064	0	
15	1024039107	1024037443	1664
```

**Comment by zoltan-fedor** [comment]
Probably the problem is with when we consume only a set amount of messages instead of all outstanding (the full lag), because the code just exit the `for` loop when it reached the given number of messages (10 million) we wanted to consume and probably this happens in an unbalanced way - leaving the consumer offsets unbalanced each time and overtime it adds up to become a huge difference in partition consumer offsets.

Once the consumer catches up and at every run it can consume all messages from the topic without hitting this maximum limit, then this issue of unbalanced consumer offsets across partitions doesn't show up anymore.

This makes me ask the question - how are we supposed to use kafka-python to read a set number of messages (not all outstanding) out of a partitioned topic on a way, that after reading the messages we leave the consumer offsets across the partitions balanced?

**Comment by dpkp** [comment]
The standard way to tune consumption rates is with the `max_partition_fetch_bytes` configuration. Also consider that most kafka consumer patterns involve long-running processes; this allows the consumer to round-robin consumption across partitions internally. You lose this internal buffer if you stop your consumer and restart using stored offsets.

**Comment by swapnilz08** [comment]
Does it mean that I catch the CommitError exception and do nothing and the consumer will align with the rebalance while my code continues consuming?

**Comment by l-easwar-akiyama** [comment]
I have also been facing this issue. My topic has 24 partitions and there are 12 consumers for it. Each consumer unevenly consumes from the topics assigned to it. Eventually leading to a sceanrio where once partition finishes and consumer consumes from the other alone ...

Now total messages consumed depends on "max_partition_fetch_bytes" * ( num of partitions ) ... So if one my partitions finishes early, wouldn't that redce the throughput of my consumer by 50 % ?

**Comment by zoltan-fedor** [comment]
@swapnilz08 , that is exactly what I am doing ("catch the CommitError exception and do nothing"), but no rebalance in the long term, just ever increasing unbalance.
Now I have 10s of millions records long lags in some partitions while other partitions are up-to-date.

This was not the case before the upgrade. I will have to consider something else, because this completely unacceptable. Basically there is no way to consume a set of messages (instead of all) from Kafka using kafka-python without causing hugely unbalanced partitions overtime, which never recover.

@dpkp , I don't think a simple round-robin is a good idea, as no guarantees that overtime that will balance out the partition offsets.
There would be a need to balance out partition offsets, the randomness of a round-robin consumption will not solve that - leading to unbalanced partition offsets overtime with no way to recover from it.

**Comment by dpkp** [comment]
#732 should improve. Let me know what you think.

**Comment by zoltan-fedor** [comment]
Thanks, this looks good, with randomized partition reading the chances on unbalancing should decrease.

Luckily since I switched to non-compressed topics (earlier was using Snappy) and had all the consumers caught up and so consuming all outstanding messages at each run, none of the consumers fall behind with unbalanced consumer offsets anymore.

But in either case I will give the randomized partition selection a try, but it will be hard to prove how much it helps, since - as you correctly wrote - this "helps" the problem, but not necessarily eliminates it completely.

Thanks again
