### ISSUE TITLE
Metrics implementation speed concern

### ISSUE THREAD

**Issue by Drizzt1991** [dpkp/kafka-python#676]
Hi, took a look at the layout for metrics. Looks interesting, little too Java-style, but can't be helped.
Problem is, that the current sensor implementation looks quite heavy for Python. You know, numbers, it's bad at it.
Question: _What I wan't to clarify is the role of metrics. Are they purely optional or will also be used for internal tasks?_
By the look of it, it's not really optional, sensors are called, doing some work. If metrics are needed to serve an internal cause (like a must for quota fixes or something) we should benchmark it and optimize. If it's just for users to install their own, maybe we should do something like:
```Python
if metrics_installed:
    self._sensors.records_fetch_lag.record(highwater - last_offset)
```
to minimize the impact. I didn't benchmark it yet, but in Python classes will always add overhead and metrics will only increase with time.

**Comment by dpkp** [comment]
Certainly a fair point, and something we considered before merging. Our internal profiling suggests that this metrics implementation is not a bottleneck, but we'll continue to evaluate as more metrics are added. If it ever gets to a point where metrics tracking becomes or could become a bottleneck, we'll consider options to disable.

But so by all means, help us profile! Join us in the oldest open issue #16 !

Re java, kafka-python has adopted a Java-style simply to avoid falling behind the official java client. once the upstream client is stabilized and kafka-python basically has feature-parity, I think we can consider larger refactors / pythonic improvements based on profiling concerns and/or python style.

**Comment by Drizzt1991** [comment]
Ok, I kinda profiled something. The scripts were super simple:
```Python
from __future__ import print_function
from kafka import KafkaConsumer
import time

# To consume latest messages and auto-commit offsets
consumer = KafkaConsumer('my-topic',
                         group_id="some-x",
                         bootstrap_servers=['127.0.0.1:9092'])

CONSUME_COUNT = 100


def main():
    global counts
    start = time.time()

    count = 0
    while True:
        data = consumer.poll(0.1)
        print(len(data))
        if data:
            for p_data in data.values():
                count += len(p_data)
        if count >= CONSUME_COUNT:
            break

    end = time.time()
    print("Processing %s of %s messages took %.5fs" %
          (count, CONSUME_COUNT, end-start))

main()

consumer.close()
```
Currently it's about 1%, as only 21 calls actually will be produced. As the whole machinery operates on batches it may as well be not so intensive (actually called much less then amount of messages).
I will try to do some more after the implementation is finished (producer is of interest in particular).

**Comment by dpkp** [comment]
Closing in favor of #16
