### ISSUE TITLE
Change the `await` call name

### ISSUE THREAD

**Issue by Drizzt1991** [dpkp/kafka-python#677]
As of Python3.7 `await` will be a keyword. To avoid future incompatibility the deprecation process should be started sooner =) https://github.com/dpkp/kafka-python/blob/1.1.1/kafka/producer/future.py#L26

Reference: https://www.python.org/dev/peps/pep-0492/#deprecation-plans

**Comment by dpkp** [comment]
This is a good point. PR welcome!
