### ISSUE TITLE
Group Consuming from topics which don't exist at initialization time 

### ISSUE THREAD

**Issue by Ormod** [dpkp/kafka-python#681]
In  my test setup I'm seeing issues when a KafkaConsumer of mine tries to consume messages from a topic which does not exist. (yet) The server has topic autocreation turned on.

May 09 10:28:44 c20 fooservice[41]: kafka.coordinator.consumer  Thread-3        INFO      Setting newly assigned partitions set() for group <foogroup>

Later on the topic gets created but the consumer doesn't seem to react to this at all. 
This is on Kafka 0.9 an I'm using the very latest kafka-python code from git.

Should I be doing something myself or should the group consumer get notified somehow that a new partition for the topic has been created somehow?

**Comment by dpkp** [comment]
If you are setting the topic name explicitly, the consumer should get the updated metadata very quickly. The kafka-python test-suite covers this extensively. If you are seeing something strange, can you write up a test case? Otherwise I am unable to reproduce.
