### ISSUE TITLE
SimpleConsumer always starts at offset 0 even if auto_offset_reset set to 'latest'

### ISSUE THREAD

**Issue by llamahunter** [dpkp/kafka-python#688]
The SimpleConsumer is based on the base Consumer.  In that code, on lines 81 and 120, if the initial offset of the consumer cannot be determined, it sets it to 0, rather than having a hook that can be run to call the SimpleConsumer.reset_partition_offset() method to use the passed in policy.

**Comment by llamahunter** [comment]
Note that this requires an uncompacted/truncated topic that still has a vaild offset 0.

**Comment by dpkp** [comment]
Have you tried KafkaConsumer ?

**Comment by llamahunter** [comment]
Will give that a try.  This is fixed there?

**Comment by dpkp** [comment]
it is!

**Comment by llamahunter** [comment]
Ok.. so, no plans to fix the legacy code, I'm guessing.  Closing this.

**Comment by dpkp** [comment]
I'll merge PRs to fix issues, but I'm not actively working on it :)
