### ISSUE TITLE
Creating multiple KafkaProducer instances results in 'Too many open files' error

### ISSUE THREAD

**Issue by reshmagodse** [dpkp/kafka-python#689]
We have a spark-streaming job that pushes the processed result to a kafka topic. For every batch, a new KafkaProducer is created and closed after pushing the data. When the job is started, we can see a gradual increase in the open file handles. And it eventually results in 'Too many open files' error. Stack trace is as follows:

```
  File "/usr/lib/python2.7/site-packages/kafka_python-1.1.1-py2.7.egg/kafka/producer/kafka.py", line 270, in __init__
  File "/usr/lib/python2.7/site-packages/kafka_python-1.1.1-py2.7.egg/kafka/client_async.py", line 673, in check_version
  File "/usr/lib/python2.7/site-packages/kafka_python-1.1.1-py2.7.egg/kafka/client_async.py", line 247, in _maybe_connect
  File "/usr/lib/python2.7/site-packages/kafka_python-1.1.1-py2.7.egg/kafka/conn.py", line 119, in connect
error: [Errno 24] Too many open files
```

To isolate the problem, I have written the following code:

```
from kafka import KafkaProducer
while True:
    msg = '123'
    print 'Pushing value: ' + msg
    producer = KafkaProducer(bootstrap_servers=["localhost:9092"], batch_size=0)
    producer.send("ss_test1", key='_', value=msg)
    producer.flush()  # To send all the accumulated records
    producer.close(0) # Now that we don't have any records in batch, this should be quick
```

I am using following command to check open file handles:

```
cat /proc/sys/fs/file-nr
```
If you run this program and monitor the open file handles via the command mentioned earlier, the count of open file handles increases monotonically until the system runs out of open file handles. The same behavior is also observed if I put in a sleep of x seconds for every pass in the loop.

**Comment by dpkp** [comment]
Thanks for the test case. I am able to reproduce. It looks like there are 2 leaks that need to be fixed:

(1) bootstrap connection (not getting closed properly when metadata response is successful)
(2) client "wake" sockets

I'll throw together a patch.

**Comment by dpkp** [comment]
Take a look at PR #696 -- I believe it fixes the leaks you are seeing.

**Comment by reshmagodse** [comment]
Thank you for the fix. I will try it.
