### ISSUE TITLE
KafkaConsumer.poll()  never receives first message on a topic

### ISSUE THREAD

**Issue by cwelton** [dpkp/kafka-python#691]
When the consumer is initialized without a group id it can never receive the first message written to a topic.

```
from __future__ import absolute_import, division, print_function
from kafka import KafkaConsumer, KafkaProducer
import time

timeout = 100
topic = 'test.10'

consumer = KafkaConsumer(topic, group_id=None, bootstrap_servers='localhost:9093')
producer = KafkaProducer(bootstrap_servers='localhost:9093')

def poll():
    partitions = consumer.poll(timeout)
    if len(partitions) > 0:
        for p in partitions:
            for response in partitions[p]:
                print(response)
    else:
        print("poll() - no results found")            

def produce():
    result = producer.send(topic, 'hello')
    md = result.get()
    print("send() - %s" % str(md))
    
poll()  # set high water mark
produce()
poll()  # get the value
poll()  # try again, just for the heck of it
produce()
poll()  # second produce result is found

---------------
bash$ python /tmp/consumer.py 
poll() - no results found
send() - RecordMetadata(topic=test.10, partition=0, offset=0)
poll() - no results found
poll() - no results found
send() - RecordMetadata(topic=test.10, partition=0, offset=1)
ConsumerRecord(topic=u'test.10', partition=0, offset=1, key=None, value='hello')

bash$ python /tmp/consumer.py 
poll() - no results found
send() - RecordMetadata(topic=test.10, partition=0, offset=2)
ConsumerRecord(topic=u'test.10', partition=0, offset=2, key=None, value='hello')
poll() - no results found
send() - RecordMetadata(topic=test.10, partition=0, offset=3)
ConsumerRecord(topic=u'test.10', partition=0, offset=3, key=None, value='hello')
```

First run, when before the topic was created the consumer does not receive the first message, but receives messages thereafter.

Second run the first poll() sets the high water mark and subsequent records are found.

Setting the topic to a new topic causes the above results to be repeatable.

**Comment by dpkp** [comment]
Set `auto_offset_rest='earliest'` in your consumer if you want to guarantee
you consume from the first available message.

**Comment by cwelton** [comment]
That's not actually what I want.  I want to start reading messages from 'now'.  

The context here is running a unit test, if the topic already exists I'm only interested in the new messages generated by the test so: get the high water mark, write a message, read the message, assert truth.

But I should be able to run the test multiple times, so if each run always starts from earliest then the test would not produce the correct, or consistent, results.

**Comment by cwelton** [comment]
A bit more detail here: 

It seems that the first poll() ends up resulting in:

```python
consumer.py:585:     log.debug("Node %s not ready -- failing offset fetch request"
```

Where it then loops a couple times before returning an empty offset dictionary `{}`.  refresh_committed_offsets_if_needed() then sets self._subscription.needs_fetch_committed_offsets = False without setting committed offsets on any partitions.  At which point the first poll() request returns without having set any high water marks.

This is distinct from when the topic already exits and the first call to poll() does successfully set the high water marks.

Solutions that seem to work include:
1. Increasing the timeout on the first poll() request.
2. polling multiple times before producing the first message.

But neither of those seems deterministic, instead relying on timing.

The solution that I found that seems to work is:
```
def consumerReady():
    partitions = None
    while partitions == None or len(partitions) == 0:
        partitions = consumer.partitions_for_topic(topic)
        consumer.poll(timeout)
```
and then replacing my first call to poll() with consumerReady()

Prior to deploying with that I'll add a retry count to prevent it from going into an infinite loop if it cannot connect to kafka.

Overall, it would be nice if there was a cleaner way of asking the consumer "are you ready yet?".

**Comment by dpkp** [comment]
If you want to read a specific message, why not seek to it ?

You may have a notion of "now" that isn't entirely clear within the context of a distributed system. I'd recommend treating offsets as logical clock values. Do not rely on implicit synchronization with physical clocks. Your producer will give you the topic, partition, and offset of the message produced. If you are simply attempting to test that the message was in fact produced, you can create a consumer, assign the topic/partition to that consumer, seek to the offset, and check the next message.
