### ISSUE TITLE
ConsumerRecord.offset is the offset in replication-offset-checkpoint?

### ISSUE THREAD

**Issue by sejust** [dpkp/kafka-python#692]
hi:
   I pushed a message using https://github.com/doujiang24/lua-resty-kafka kafka-lua-client, and 
consume in kafka-python.

  when producer send, return a offset is partition(8) offset(281), and consumer in python got the same message ConsumerRecord is ConsumerRecord(topic=u'transcoding', partition=8, offset=280, key='transcoding_front', value='balabala').
 In the kafka server logs I got replication-offset-checkpoint is "transcoding 8 281".

what happened? The offset of the message stored in kafka is 280 or 281?

**Comment by dpkp** [comment]
The message is 280. The checkpoint denotes the next message to fetch. The
producer is off by one.
