### ISSUE TITLE
gevent+kafka-python selector issue

### ISSUE THREAD

**Issue by dribler** [dpkp/kafka-python#702]
Hi, 

Actually i can't reproduce this issue currently, but probably this is potential problem. (Related to 1.1.1)

At some moment our app almost filled up disk (it was really quick) with logs like:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/kafka/producer/sender.py", line 55, in run
    self.run_once()
  File "/usr/local/lib/python2.7/dist-packages/kafka/producer/sender.py", line 145, in run_once
    self._client.poll(poll_timeout_ms, sleep=True)
  File "/usr/local/lib/python2.7/dist-packages/kafka/client_async.py", line 430, in poll
    responses.extend(self._poll(timeout, sleep=sleep))
  File "/usr/local/lib/python2.7/dist-packages/kafka/client_async.py", line 445, in _poll
    for key, events in self._selector.select(timeout):
  File "/usr/local/lib/python2.7/dist-packages/kafka/selectors34.py", line 340, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
TypeError: select() takes at most 4 arguments (5 given)
","filename":"sender.py","lineno":57,"msg":"Uncaught error in kafka producer I/O thread
```

I had no time to look deeper - just did emergency downgrade to 1.0.2.

Now i'm trying to reproduce it, but can't. Can you please look into this? As potential fix would be wrap `select.select` by `staticmethod()`....but i'm not sure (why it works now?). Does it related to how gevent do patch `select`?

Something like:
```
in selectors34.py:
...
    if sys.platform == 'win32':
        def _select(self, r, w, _, timeout=None):
            r, w, x = select.select(r, w, w, timeout)
            return r, w + x, []
    else:
        _select = staticmethod(select.select)
...
```

Thanks!

**Comment by dpkp** [comment]
Interesting. selectors34 is a vendored library. You might check whether there are similar issues reported there: https://pypi.python.org/pypi/selectors34

**Comment by dpkp** [comment]
Also fwiw, I have not tested kafka-python with gevent and don't expect it to work without changes.

**Comment by dribler** [comment]
Got it. We will keep it in mind.

This is obviously gevent issue. Getting same with simple code:

```python
from gevent.monkey import patch_all
patch_all()

import select
class DummySelector(object):
    select = select.select

s = DummySelector()
s.select(a, b, c, d)

>> TypeError: select() takes at most 4 arguments (5 given)
```
But works if don't do patch.

Looks like this is not an issue any more (at least looks like not an issue). Noticed that on recent gevent `DefaultSelector` is `PollSelector` (not buggy `SelectSelector`) that's why it works fine now.

Thanks.

**Comment by dpkp** [comment]
Glad you were able to resolve!

**Comment by cookingkode** [comment]
hi @dribler  - What gevent version are you using? I'm using 1.1.1 ( the latest) and still getting the error..

**Comment by dribler** [comment]
hi @cookingkode i'm using same gevent version. As i correctly understand this issue, gevent cannot work with backported `SelectSelector`. Depending on your environment `selectors34.DefaultSelector` will be `SelectSelector`, `PollSelector`....etc don't remember some other selectors. I'm running on Linux and default selector is PollSelector on (1.1.1). But on previous gevent version it was `SelectSelector` which doesn't work. Are you running code on Linux?
