### ISSUE TITLE
Timestamp support

### ISSUE THREAD

**Issue by vortec** [dpkp/kafka-python#703]
Kafka 0.10 comes with timestamp support per message:

https://issues.apache.org/jira/browse/KAFKA-2511

Is it possible to get this value via kafka-python yet?

**Comment by Poogles** [comment]
I believe this was added in https://github.com/dpkp/kafka-python/commit/795cb9b29fa05d4425f807f54dfa639c125fc0dd

**Comment by dpkp** [comment]
Yes, it is available in latest release (1.2.0)
