### ISSUE TITLE
Kafka Consumer cluster that can read dynamic topics

### ISSUE THREAD

**Issue by DataEngg** [dpkp/kafka-python#704]
I need to have a Kafka consumer cluster, which reads data from dynamically added Kafka topics in Kafka Cluster.

I did not get any information from kafka-python documentation.

Please help me out in this. My use case is Kafka consumer listen all messages from created topic as well as from dynamic topics

**Comment by dpkp** [comment]
You can provide a regex to KafkaConsumer.subscribe () to accomplish this.

**Comment by DataEngg** [comment]
I have done the same but still it does not able to receive message from dynamic topic


consumer.subscribe(pattern='[A-Za-z1-9]+') 

Topic can be any combination of uppercase letters or lowercase letters or numbers

**Comment by dpkp** [comment]
The setting for metadata_max_age_ms should configure how long it takes
before new topic data is refreshed by the consumer. How long are you
waiting?

**Comment by DataEngg** [comment]
I have not set this value must be it taking a default. Should i specify the configuration parameter in KafkaConsumer object

**Comment by iammehrabalam** [comment]
@DataEngg i have tested it works

**Comment by uddhavarote** [comment]
@DataEngg were you able to get it done? I am trying same thing but unfortunately it does not work for me. Is there any broker/ consumer configuration change ?
@iammehrabalam  How did you make it work?

**Comment by dpkp** [comment]
```
consumer = KafkaConsumer(...)
consumer.subscribe(pattern='foo.*')
for msg in consumer:
    print(msg.topic, msg.partition, msg.offset)
```

**Comment by uddhavarote** [comment]
@dpkp I tried this ten times now. 
```python
 consumer = KafkaConsumer() #default host:9092
 consumer.subscribe(pattern='temp.*')
 print consumer.subscription()
```
The final statement returns empty set. What am I missing?
Also why using subscribe() on same KafkaConsumer object twice, as follows, does not work
```python
consumer = subscribe(topics=[...])
for msg in consumer:
   print msg.topic, msg.offset
# .. prints the message topics and offsets
consumer.subscribe(topics=[...]) # new set of topics
for msg in consumer:
   print msg.topic, msg.offset # -> this does not do anything
```

Thanks, 
Uddhav

**Comment by dpkp** [comment]
`consumer.subscribe()` is lazy. You must call `consumer.poll()` or use the iterator to initiate a network update.
