### ISSUE TITLE
Support KafkaConsumer auto-commit with 0.8 brokers

### ISSUE THREAD

**Issue by huangnauh** [dpkp/kafka-python#706]
kafka 0.8.2    kafka-python 1.1.1

when enable auto_commit, an AutoCommitTask instance will be created
but when Enable the AutoCommitTask instance?
in the code , only find the function _on_join_complete will enable  the AutoCommitTask instance

```
def _on_join_complete(self, generation, member_id, protocol,
                          member_assignment_bytes):
        ...
        # restart the autocommit task if needed
        if self._auto_commit_task:
            self._auto_commit_task.enable()
```

but api_version < 0.9, the function _on_join_complete never be called

**Comment by sibiryakov** [comment]
+1
For Simple* interfaces auto commits do work for kafka 0.8.2.

**Comment by dpkp** [comment]
Yes, this is a missing feature! Thanks for reminding me.
