### ISSUE TITLE
KafkaConsumer not reading messages from queue... only reading from last published

### ISSUE THREAD

**Issue by shiladityasen** [dpkp/kafka-python#708]
I am doing these experiments in an IPython environment on OSX El Capitan.

These are the messages that have already been published in the topic 'test' by a command-line publisher:  

```
This is a message
This is another message
New message
Completely new message
Again, new message
new new
This one will get delivered
What?
```
 This is how I am setting up my consumer:

```
from kafka import KafkaConsumer  
consumer = KafkaConsumer('test', bootstrap_servers='localhost:9092',  auto_offset_reset='earliest')  
for msg in consumer:  
    print msg
```  

However, this is only giving as output:  
`ConsumerRecord(topic=u'test', partition=0, offset=7, timestamp=1464290063509, timestamp_type=0, key=None, value='What?')`  
Even if I have set `auto_offset_reset='earliest'`... Shouldn't it just read from the start and give me all messages published to this topic?  
How do I get all messages from beginning?

**Comment by shiladityasen** [comment]
I apologize... There was some issue with the server I had started for kafka.  
I deleted the kafka log files from `/tmp/kafka-logs` and it works like a charm now.  
Thanks!

**Comment by shiladityasen** [comment]
Ok I understood where I was going wrong... I was not setting the `group_id` which defaults to ‘kafka-python-default-group’.  
As a result every consumer instance was being created for the same group and once the messages were consumed, they weren't repeated.  
But still, shouldn't explicitly setting `auto_offset_reset='earliest'` always set the offset of that consumer instance to the beginning of the queue?

**Comment by dpkp** [comment]
`auto_offset_reset` sets the policy when there is no stored offset for the group, or when the stored offset has expired / is beyond the broker retention period. it's useful to configure where new groups start and where lagging groups rejoin.

You are correct, to get a simple queue consumer with no "memory" of what has already been consumed, set group_id=None and auto_offset_reset='earliest'
