### ISSUE TITLE
connection failed and node not ready

### ISSUE THREAD

**Issue by shachr** [dpkp/kafka-python#711]
I'm sending logs through Kafka, using kafka-python 1.2.0 and kafka 0.9, i'm seeing the following debug/warning messages:
DEBUG [kafka.producer.sender:105] Node 557 not ready; delaying produce of accumulated batch
WARNING [kafka.client:231] Node 557 connection failed -- refreshing metadata

eventually its delaying messages and they are expired, some of the messages are being sent.
why would a connection disconnect few times a minute?
https://github.com/dpkp/kafka-python/blob/77cb35078a7408ebb0eab4bfc2220cc11c10d3b2/kafka/client_async.py#L223

It seems that sometimes connection of a nodeid doesn't exists, and it tries to open a new connection and at least few times a second fails,

https://github.com/dpkp/kafka-python/blob/77cb35078a7408ebb0eab4bfc2220cc11c10d3b2/kafka/client_async.py#L371

thanks,

**Comment by JohnTheodore** [comment]
@shachr did you find a solution for this?

**Comment by dpkp** [comment]
Can you check the kafka server logs for that node? That may help determine why the connection is dropping.

Also, please upgrade to 1.2.1 -- it shouldn't impact producer code, but there was a gnarly regression in the consumer code in 1.2.0.

**Comment by ikatson** [comment]
We've seen a similar issue, here's what happens:

the client successfully connects to the bootstrap servers, but the first node in the "brokers" metadata response is faulty. kafka-python does not seem to handle this use-case, as it crashes, when the first broker is not working.

It seems to happend because "least_loaded_node" always returns 0 in the beginning, which is the faulty broker in our case.

Here's a traceback (stripped out sensitive and unnecessary information from it)

```py
In [18]: KafkaProducer(bootstrap_servers=['some-bootstrap-server:9092'])
DEBUG:kafka.producer.kafka:Starting the Kafka producer
...
DEBUG:kafka.client:Node bootstrap connected
DEBUG:kafka.conn:<BrokerConnection host=some-bootstrap-server/some-ip port=9092> Response 1: MetadataResponse_v0(brokers=[(node_id=0, host=u'node-0', port=9092), <a bunch of other nodes, that work>], <a bunch of other stuff>)
DEBUG:kafka.cluster:Updated cluster metadata to Cluster(brokers: 6, topics: 14, groups: 0)
DEBUG:kafka.client:No connected nodes found. Trying disconnected nodes.
DEBUG:kafka.client:No luck. Trying all broker metadata
DEBUG:kafka.client:Initiating connection to node 0 at node-0:9092
DEBUG:kafka.conn:<BrokerConnection host=node-0 port=9092>: creating new socket
INFO:kafka.producer.kafka:Kafka producer closed
---------------------------------------------------------------------------
NodeNotReadyError                         Traceback (most recent call last)
<ipython-input-18-1210b6929715> in <module>()

/usr/local/lib/python2.7/site-packages/kafka/producer/kafka.pyc in __init__(self, **configs)
    274         # Check Broker Version if not set explicitly
    275         if self.config['api_version'] == 'auto':
--> 276             self.config['api_version'] = client.check_version()
    277         assert self.config['api_version'] in ('0.10', '0.9', '0.8.2', '0.8.1', '0.8.0')
    278

/usr/local/lib/python2.7/site-packages/kafka/client_async.pyc in check_version(self, node_id, timeout, strict)
    679         self._maybe_connect(node_id)
    680         conn = self._conns[node_id]
--> 681         version = conn.check_version()
    682         self._refresh_on_disconnects = True
    683         return version

/usr/local/lib/python2.7/site-packages/kafka/conn.pyc in check_version(self, timeout, strict)
    588
    589         for version, request in test_cases:
--> 590             connect()
    591             f = self.send(request)
    592             # HACK: sleeping to wait for socket to send bytes

/usr/local/lib/python2.7/site-packages/kafka/conn.pyc in connect()
    585                     return
    586                 time.sleep(0.05)
--> 587             raise Errors.NodeNotReadyError()
    588
    589         for version, request in test_cases:

NodeNotReadyError:
```

**Comment by JohnTheodore** [comment]
@dpkp should we file a separate issue for what @ikatson is describing? We can reproduce the issue. We have 4 good kafka brokers, and 1 bad one (the first one). kafka-python crashes because it can't connect to the first one.

Though another kafka client (in go), https://github.com/Shopify/sarama can talk to the kafka VIP and successfully connects to other brokers and routes around the bad one. (It actually connect to all of them regardless).

It seems like kafka-python relies on the first broker being good, or it crashes. The client should be more resilient.

**Comment by ikatson** [comment]
FYI we use Sarama too and it works fine with that setup

**Comment by JohnTheodore** [comment]
btw, I'm using the latest version (1.2.1)

**Comment by dpkp** [comment]
The error is in the auto-version checking, so a workaround is to pass `api_version='0.9'` (or whichever version you are using). In the meantime, please do file a separate issue on NodeNotReadyError from check_version.

**Comment by dpkp** [comment]
I'm not sure if it is related, but while investigating these issues I did notice that `KafkaClient.least_loaded_node()` -- which is the method that picks which node to connect to when a metadata refresh is required -- could potentially always return the same failed node. Could that explain your issue above (not the check_version, though it is related).

**Comment by dpkp** [comment]
Moved version check error details to #725 . The issue reported above does not appear related to it.

@shachr were you able to find any information from your broker logs?

**Comment by dpkp** [comment]
kafka-python 1.2.2 included several fixes to connection / node handling. Please re-open if this issue persists. I will assume from the lack of further updates that it is no longer a problem for folks who have upgraded to the latest kafka-python release.

**Comment by chiwah-keen** [comment]
same error.

**Comment by dpkp** [comment]
@chiwah-keen with kafka-python 1.2.2 ?

**Comment by chiwah-keen** [comment]
1.3.2.dev
