### ISSUE TITLE
Consumer Offset not commited when using assign() to consume select partitions only

### ISSUE THREAD

**Issue by zoltan-fedor** [dpkp/kafka-python#714]
When consuming from select partitions only, the offset is not being committed, but stays unchanged.

```
        kafka_consumer = KafkaConsumer(
            group_id=settings['kafka_group_id'],
            bootstrap_servers=settings['kafka_servers']
        )
        
        kafka_consumer.assign([
                TopicPartition(settings['topic'],2),
                TopicPartition(settings['topic'],4),
             ])
```

Checking the consumer offset of partition 2 and 4 shows now change, even after consuming 25M records.

**Comment by dpkp** [comment]
I believe this is a dup of #626

**Comment by zoltan-fedor** [comment]
Thanks, that helps, so at least I can work around it by using autocommit False
