### ISSUE TITLE
Performance degrades for synchronous producer in 1.2.0 vs 0.9.4

### ISSUE THREAD

**Issue by ottomata** [dpkp/kafka-python#717]
Hi!

Wikimedia been using (mumrah's) kafka-python 0.9.4 for our [EventLogging](https://github.com/wikimedia/eventlogging) codebase.  We use pykafka for consuming, mainly because it had a BalancedConsumer before kafka-python ever did.  We recently upgraded our brokers to 0.9.  We've also been having an issue with pykafka where consumer processes can die during broker restarts.  All of this is making us consider switching to kafka-python.

However, one of our use cases is synchronous production.  We have an HTTP Kafka produce service that uses kafka-python 0.9.4.  We only want to return a 200 response to clients if we are 100% sure that Kafka has persisted the message.  In 0.9.4, this could be accomplished by setting `async=False` and `req_acks=-1`.

kafka-python 1.2.0 provides both the deprecated `SimpleProducer` and the new `KafkaProducer` interfaces.  With both producers, we see a significant performance regression when doing 'synchronous' production.  With 0.9.4 we could synchronously produce in 1-10ms.  1.2.0 takes at about an order of magnitude longer.

#### SimpleProducer
For `SimpleProducer`, the regression seems to be mostly caused by some significant changes to `SimpleClient` since 0.9.4. [Previously](https://github.com/dpkp/kafka-python/blob/v0.9.4/kafka/client.py#L175), `_send_broker_aware_request` would iterate through each payload produce request and receive a response.  In the current version, it sends each payload produce request asynchronously, and then iterates while waiting for all futures to resolve. I used line_profiler to profile the `_send_broker_aware_request` in 0.9.4 and 1.2.0.  Over 1000 individual produce requests, in 0.9.4, `conn.recv()` was called 1000 times.  However, in 1.2.0, `conn.recv()` was called 575283 times.  I'm aware that `conn` is a different type of connection in each version (`BrokerConnection` `KafkaConnection`) and that `conn.recv()` is doing different things.  I might be way off here, but it seems the constant looping over a non blocking is causing a big performance hit.  Performance is about an order of magnitude worse in 1.2.0.

My line_profiler results are here: https://gist.github.com/ottomata/741ccf084f220249102d6c97abda963d

#### KafkaProducer
Ok, buuut, I should use the new `KafkaProducer`, right?  I should!  I would much prefer to do this, as we would like to eventually take advantage of some newer Kafka features.  But I need a way to do 'synchronous' production.

I've tried by setting `batch_size=0`, and doing `response.get()` to wait for my produce request future to resolve.  This has a huge performance hit, also of about an order of magnitude.  I've tried to dive into the `KafkaProducer` code a bit here, but got a little lost.  In doing so I noticed a some places where futures seemed to be waited for just by looping continuously.  If produce throughput is high enough, the constant iteration and checking for future resolution wouldn't be noticed, but in our 'synchronous' use case, we want to produce 1 message at a time.  I don't yet have a full grasp on this code, so I'm probably just missing something simple.

Is there a way to quickly produce a single message at a time?

**Comment by dpkp** [comment]
Howdy! Thanks for peeking into the guts of kafka-python.

The new KafkaProducer design follows the official java client, which was optimized for async throughput. The best KafkaProducer settings for single-message sync producing is `batch_size=0` and `future.get()` But as you have noticed, the performance is still noticeably worse than the old SimpleProducer design which was designed for simple sync message sends.

That said, I don't think the performance should be horrible. Testing on my laptop (so no network latency):
```
In [7]: %timeit producer.send('foobar', b'msg1').get()
1000 loops, best of 3: 1.14 ms per loop
```

Are you persisting your producer object between requests, or are you having to create a new producer instance each time?

**Comment by ottomata** [comment]
Hm, interesting.  a ~1ms send time would be great!  I am seeing more like around 40ms.  For a second I thought it might have been because I am using using a json value_serializer, but I get about the same performance with straight up bytes.

https://gist.github.com/ottomata/ef90712fa10bca906d582cf91b129de8

```
Time KafkaProducer synchronous send bytes
1000 sends took total 40461.1122608 ms, average 40.4611122608 ms each send
```
I see this in both my local dev environment, and also with our production brokers.

**Comment by dpkp** [comment]
Can you try again w/ latest kafka-python? I've made a few performance improvements.

Also, it would help if you could post debug logs (w/ timestamps) for a single synchronous send that is taking 40ms.

**Comment by dpkp** [comment]
Can you try w/ latest kafka-python -- I've made some performance improvements.

Also, can you post debug logs w/ timestamps for a sync send that takes 40ms ?

**Comment by ottomata** [comment]
Ok, sure!

This is with kafka-python 1.2.5 and Kafka 0.9.0.1.

```
import time
import sys
from kafka import KafkaProducer

import logging
logging.basicConfig(
    stream=sys.stderr,
    level=logging.DEBUG,
    format='%(asctime)s [%(process)s] (%(threadName)-10s) %(message)s')


def time_send(msg, producer):
    start = time.time()
    producer.send('test', msg).get()
    taken = (time.time() - start) * 1000.0
    logging.info("::::::::: Sync send took %s ms" % (taken))

# Usage: python produce_sync_one.py localhost:9092
producer = KafkaProducer(bootstrap_servers=sys.argv[1], batch_size=0)

# sending twice, the first one takes ~90ms
time_send(b'msg1', producer)
time_send(b'msg1', producer)
```

```
2016-07-28 21:22:52,767 [7499] (MainThread) ::::::::: Sync send took 90.2390480042 ms
2016-07-28 21:22:52,813 [7499] (MainThread) ::::::::: Sync send took 45.6159114838 ms
```

Debug log output here:

https://gist.github.com/ottomata/180a5b2f27ab076b6197f16f1efea72a#file-kafka-python-sync-send-txt

**Comment by dpkp** [comment]
Thanks, debug logs are quite useful. It looks like the first send (90ms) is going to a new broker so there is initial connection overhead:
```
(kafka-python-producer-1-network-thread) Node 0 not ready; delaying produce of accumulated batch
```
In most cases I would expect you to have an existing producer w/ active connections, so I wont focus on that particular timing issue.

The second send (45ms) looks like it takes ~1-2ms from send() to bytes sent on the wire, then there is a 42 ms delay before we have a response payload. Finally, 1ms elapses between response and the timing log message.

What is the RTT from your test node to your broker? It looks like you may be using a localhost broker, but I can't tell for sure.

**Comment by ottomata** [comment]
I am using localhost.  This is just running in a local Trusty Ubuntu Server vagrant/virtualbox VM on my Mac.

Just network RTT?  Avg ping is 0.030 ms.

For contrast, here's a sync send with librdkafka (via confluent-kafka-python):

```
from confluent_kafka import Producer
import time

def time_send(msg, producer):
    start = time.time()
    producer.produce('test', msg)
    producer.flush()
    taken = (time.time() - start) * 1000.0
    print("::::::::: rdkafka Sync send took %s ms" % (taken))

p = Producer({
    'bootstrap.servers': 'localhost:9092',
    'queue.buffering.max.ms': 1,
    'socket.blocking.max.ms': 1,
    'log_level': 7,
    'debug': 'all'
})

msg = 'msg'.encode('utf-8')
time_send(msg, p)
time_send(msg, p)

```

The second send takes 2-10 ms.
```
...
%7|1469746238.394|TOPPAR|rdkafka#producer-1| mediawiki-vagrant.dev:9092/0: test [0] 1+0 msgs
%7|1469746238.394|PRODUCE|rdkafka#producer-1| mediawiki-vagrant.dev:9092/0: produce messageset with 1 messages (29 bytes)
%7|1469746238.394|TOPPAR|rdkafka#producer-1| mediawiki-vagrant.dev:9092/0: test [0] 0+0 msgs
%7|1469746238.394|SEND|rdkafka#producer-1| mediawiki-vagrant.dev:9092/0: Sent ProduceRequest (v1, 78 bytes @ 0, CorrId 3)
%7|1469746238.394|TOPPAR|rdkafka#producer-1| mediawiki-vagrant.dev:9092/0: test [0] 0+0 msgs
%7|1469746238.396|RECV|rdkafka#producer-1| mediawiki-vagrant.dev:9092/0: Received ProduceResponse (v1, 32 bytes, CorrId 3, rtt 1.09ms)
%7|1469746238.396|TOPPAR|rdkafka#producer-1| mediawiki-vagrant.dev:9092/0: test [0] 0+0 msgs
%7|1469746238.396|MSGSET|rdkafka#producer-1| mediawiki-vagrant.dev:9092/0: MessageSet with 1 message(s) delivered
::::::::: rdkafka Sync send took 3.34787368774 ms
```

**Comment by ottomata** [comment]
Maybe I'm reading that wrong, but it looks like there is about 2 ms between rdkafka sending the request and receiving the response, right?

**Comment by dpkp** [comment]
Can you check the type of `producer._sender._client._selector` to see what selector you are using? (`selector` is available as configuration option in master)

**Comment by dpkp** [comment]
Something is strange, because I see ~3ms latency when using a local broker (0.9.01 w/ kafka-python 1.2.5):
```
In [15]: time_send(b'msg1', producer)
DEBUG:kafka.producer.kafka:Sending (key=None value=msg1) to TopicPartition(topic='test', partition=0)
DEBUG:kafka.producer.record_accumulator:Allocating a new 38 byte message buffer for TopicPartition(topic='test', partition=0)
DEBUG:kafka.producer.kafka:Waking up the sender since TopicPartition(topic='test', partition=0) is either full or getting a new batch
DEBUG:kafka.producer.sender:Nodes with data ready to send: set([2])
DEBUG:kafka.producer.sender:Created 1 produce requests: {2: ProduceRequest_v1(required_acks=1, timeout=30000, topics=[(topic='test', partitions=[(partition=0, messages=['(offset=0, message=18)'])])])}
DEBUG:kafka.producer.sender:Sending Produce Request: ProduceRequest_v1(required_acks=1, timeout=30000, topics=[(topic='test', partitions=[(partition=0, messages=['(offset=0, message=18)'])])])
DEBUG:kafka.conn:<BrokerConnection host=::1/::1 port=55846> Request 4: ProduceRequest_v1(required_acks=1, timeout=30000, topics=[(topic='test', partitions=[(0, <_io.BytesIO object at 0x112be7f50>)])])
DEBUG:kafka.conn:<BrokerConnection host=::1/::1 port=55846> Response 4: ProduceResponse_v1(topics=[(topic=u'test', partitions=[(partition=0, error_code=0, offset=3)])], throttle_time_ms=0)
DEBUG:kafka.producer.sender:Parsing produce response: ProduceResponse_v1(topics=[(topic=u'test', partitions=[(partition=0, error_code=0, offset=3)])], throttle_time_ms=0)
DEBUG:kafka.producer.record_accumulator:Produced messages to topic-partition TopicPartition(topic='test', partition=0) with base offset 3 and error None.
INFO:root:::::::::: Sync send took 3.65018844604 ms
```

My default selector is `kafka.selectors34.KqueueSelector` . I wonder if you are using a different one?

**Comment by ottomata** [comment]
Hm!

```
In [5]: p._sender._client._selector
Out[5]: <kafka.selectors34.EpollSelector at 0x7fc388dbcf10>
```

**Comment by ottomata** [comment]
I did the same tests running on my Mac (sending to the same broker on my Ubuntu VM) using KqueueSelector, and get much better results.  I see an average of 9.098 ms for a sync produce request.

So, it looks like the switch to using epoll for async is causing a hit here.  I guess it makes sense.  I'm trying to make an async call work like a sync one.  I think this issue is unlikely to affect many people, since doing individual sync produce requests is a bad idea in general.  I need it for the time being though.  Not sure what to do atm. :/

**Comment by dpkp** [comment]
It could also be lower level networking unrelated to differences between
kqueue (BSD) and epoll (Linux). Will try to investigate further this
weekend.

**Comment by ottomata** [comment]
Hm, maybe, but as far as I can tell there aren’t big networking changes
between 0.9.4 and 1.2.x.  I see that you are creating sockets more low
level now, vs socket.create_connection() in 0.9.4, but the underlying
socket should be the same, no?

**Comment by dpkp** [comment]
I setup linux brokers (0.9.0.1) and looked into this a bit more.

It appears to be a TCP send delay. Nagle. Smart guy, Nagle, but sometimes I curse him.

With TCP_NODELAY set, I see the expected 3-5ms latency for your `time_send` method.

PR forthcoming

**Comment by ottomata** [comment]
This works! 💃  YES!  Thank you.

**Comment by ottomata** [comment]
Think we can get a tag for this?  If not I can deal, but it is nicer to build .deb packages based on official tags.

**Comment by dpkp** [comment]
I expect to release 1.3.0 in the next few days (once we get #779 merged).
