### ISSUE TITLE
negative value of index_of_schema in read_union

### ISSUE THREAD

**Issue by iiivnv** [dpkp/kafka-python#720]
Method read_union(self, writers_schema, readers_schema, decoder) raises Exception "IndexError: list index out of range" because int(decoder.read_long()) returns negative value (-51 in my case) and below on line 651, the code: 
   selected_writers_schema = writers_schema.schemas[index_of_schema]
of course raises such Exception.

Please let me know what additional data should I add into this ticket to help you investigate the issue.

**Comment by dpkp** [comment]
There is no read_union method in kafka-python. Have you got the right project?

**Comment by iiivnv** [comment]
ahh, you are right, this is avro/io.py
I just use it in Kafka consumer which is consuming and decoding Avro messages.

Sorry.
