### ISSUE TITLE
KafkaProducer hangs when publishing to new topic (and using uWSGI master process)

### ISSUE THREAD

**Issue by parkerfinch** [dpkp/kafka-python#721]
I'm trying to upgrade from `SimpleProducer` to the newer `KafkaProducer`, but I'm running into an issue where the producer hangs when it tries to publish to a topic that doesn't exist. This occurs only when the producer is run with uWSGI, **and** uWSGI is configured to use a master process.

The messages are successfully published if uWSGI is run without a master process or if the topic already exists.

This behavior manifests with both kafka 0.9.0.1 and 0.10.0.

It seems like this might be related to http://stackoverflow.com/questions/37693563/how-to-make-kafka-python-or-pykafka-work-as-an-async-producer-with-uwsgi-and-gev and https://github.com/dpkp/kafka-python/issues/709, but the fact that it only breaks for nonexistent topics makes me think it might be a separate issue.

**Comment by parkerfinch** [comment]
Actually, it looks like the messages aren't actually published if uWSGI is running with a master process. The producer doesn't hang, but the messages don't make it to kafka.

**Comment by dpkp** [comment]
Can you provide a code snippet to reproduce?

**Comment by parkerfinch** [comment]
Sure thing! The plot has thickened a little bit.
Here's an `app.py` that results in the hanging issue when run with `uwsgi --http :9090 --wsgi-file app.py --master`
```python
from kafka import KafkaProducer
PRODUCER = KafkaProducer(bootstrap_servers="kafka-host:9092")

def application(env, start_response):
    PRODUCER.send("new_topic", "some data")
    start_response("200 OK", [("Content-Type", "text/plain")])
    return ["Finished"]
```
Nothing appears in the kafka logs when this is run. After waiting a minute, I get the error `kafka.errors.KafkaTimeoutError: ('Failed to update metadata after %s secs.', 60.0)`.

When run without the `--master` flag the topic is created but the messages are not published. After the first request without the `--master` flag the kafka logs contain:
```
[2016-06-09 08:17:29,141] INFO Topic creation {"version":1,"partitions":{"0":[0]}} (kafka.admin.AdminUtils$)
[2016-06-09 08:17:29,143] INFO [KafkaApi-0] Auto creation of topic new_topic with 1 partitions and replication factor 1 is successful (kafka.server.KafkaApis)
[2016-06-09 08:17:29,151] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions [new_topic,0] (kafka.server.ReplicaFetcherManager)
[2016-06-09 08:17:29,153] INFO Completed load of log new_topic-0 with log end offset 0 (kafka.log.Log)
[2016-06-09 08:17:29,154] INFO Created log for partition [new_topic,0] in /storage/kafka-logs with properties {compression.type -> producer, message.format.version -> 0.10.0-IV1, file.delete.delay.ms -> 60000, max.message.bytes -> 1000012, message.timestamp.type -> CreateTime, min.insync.replicas -> 1, segment.jitter.ms -> 0, preallocate -> false, min.cleanable.dirty.ratio -> 0.5, index.interval.bytes -> 4096, unclean.leader.election.enable -> true, retention.bytes -> -1, delete.retention.ms -> 86400000, cleanup.policy -> delete, flush.ms -> 9223372036854775807, segment.ms -> 604800000, segment.bytes -> 1073741824, retention.ms -> 345600000, message.timestamp.difference.max.ms -> 9223372036854775807, segment.index.bytes -> 10485760, flush.messages -> 9223372036854775807}. (kafka.log.LogManager)
[2016-06-09 08:17:29,155] INFO Partition [new_topic,0] on broker 0: No checkpointed highwatermark is found for partition [new_topic,0] (kafka.cluster.Partition)
```

I'm guessing some of this behavior has to do with how uWSGI copies the memory from the master process into the worker processes. Here's another configuration I tried, recreating the producer in an attempt to avoid memory funkiness.
```python
from kafka import KafkaProducer

def application(env, start_response):
    producer = KafkaProducer(bootstrap_servers="kafka-host:9092")
    producer.send("newer_topic", "some data")
    start_response("200 OK", [("Content-Type", "text/plain")])
    return ["Finished"]
```

This successfully creates the topic but doesn't publish a message. Successive requests do produce messages, but only if they are run in "rapid" succession. (My tenuous theory is that a connection is being held, and if it times out then the next request will fail but re-establish the connection.) This behavior occurs with and without the uWSGI master process.

**Comment by dpkp** [comment]
Ah, thank you! Two issues:

You cannot share producer instances across processes, only threads. I expect that is why the master process pattern is failing.

Second, producer.send() is async but is not guaranteed to deliver if you close the producer abruptly. In your final example I suspect that your producer instances are so short-lived that they are being reaped before flushing all pending messages. To guarantee delivery (or exception) call producer.send().get(timeout) or producer.flush() . otherwise you'll need to figure out how to get a producer instance per-uwsgi-thread and have it shared across requests (you would still want to flush before thread shutdown to guarantee no messages are dropped)

**Comment by parkerfinch** [comment]
Aha, thanks! After looking more closely at uWSGI options I discovered the [lazy-apps](http://uwsgi-docs.readthedocs.io/en/latest/articles/TheArtOfGracefulReloading.html#preforking-vs-lazy-apps-vs-lazy) option, which causes each worker to load the entire app itself. This seems to have resolved my issue.

**Comment by FlyingFishBird** [comment]
uWsgi with 'master=false' option works fine for this scene.
But I solved this by create independent producer contexts in each process.
I write a 'mq' module

```python
# __init__.py

from mq.MsgQueue import MsgQueue
from flask import current_app


def _init(app):
    uri = app.config['MQ_URI']
    return MsgQueue(uri)


mq_context = _init(current_app)

```

```python
# MsgQueue.py

from kafka import KafkaProducer
from ujson import dumps


class MsgQueue(object):
    def __init__(self, uri):
        super(MsgQueue, self).__init__()
        self.producer = KafkaProducer(
            bootstrap_servers=uri, api_version=(0, 10, 2))

    def send(self, topic, data):
        self.producer.send(topic, dumps(data, ensure_ascii=False).encode())

```

And in app logic:
```python
from mq import mq_context  # ensure only  load 'mq_context' once in each process
mq_context.send(topic, data)
```
