### ISSUE TITLE
Feature Request: Ability to fetch Kafka Version

### ISSUE THREAD

**Issue by HariSekhon** [dpkp/kafka-python#723]
Feature Request to be able to determine and return the Kafka version of the broker(s) we are connected to.

I have been through the docs but couldn't see this feature. When testing things against various versions of a piece of software I use Docker and prefer to have tests to check that the running container is the version it's supposed to be (this checks on several potential issues such as a left over container or error in a Dockerfile not having the right version).

**Comment by dpkp** [comment]
Beware that the kafka brokers do not expose this information, so you can get my best guess but nothing official. See `consumer.config['api_version']` . This works for KafkaConsumer and KafkaProducer only.

**Comment by HariSekhon** [comment]
I thought that was the case as I didn't see anything in the main Kafka doc / JVM APIs.

I shall raise this as an upstream improvement, thanks.

**Comment by dpkp** [comment]
I've raised it upstream many times. Jay does not believe the broker version should be exposed directly. The compromise is KIP-35 which exposes individual API versions, which is a little different. But always happy to have more voices on our side.
