### ISSUE TITLE
misleading consumer_timeout_ms documentation

### ISSUE THREAD

**Issue by fillest** [dpkp/kafka-python#726]
Documentation for `consumer_timeout_ms` says "to throw a timeout exception" but actually looks like it throws `StopIteration`. Maybe it would better be something like "to throw a StopIteration exception ... after specified timeout"

**Comment by dpkp** [comment]
Agree -- PRs welcome! Get your name in lights!

**Comment by dpkp** [comment]
Fixed in master

**Comment by fillest** [comment]
Thank you. My English is bad anyway for a good enough formulation:)
