### ISSUE TITLE
Consumer offset migration from 0.9.5 KafkaConsumer to 1.x KafkaConsumer

### ISSUE THREAD

**Issue by ms7s** [dpkp/kafka-python#737]
When using `KafkaConsumer` from kafka-python 0.9.5, the consumer offsets are stored in ZooKeeper.
In kafka-python 1.x the offsets are stored in Kafka and it does not pick the offsets up from ZooKeeper, but starts at the end of the topic. This may cause messages to be skipped if the offsets are not migrated. I have tested this with broker version 0.9. 

According to Kafka [FAQ](https://cwiki.apache.org/confluence/display/KAFKA/FAQ#FAQ-HowdowemigratetocommittingoffsetstoKafka%28ratherthanZookeeper%29in0.8.2?) and [documentation](http://kafka.apache.org/documentation.html#offsetmigration) the migration is handled by setting `dual.commit.enabled=true` in the Java consumer temporarily to force the offset being copied from ZooKeeper to Kafka, then reconfiguring the consumers again to only commit to Kafka. As far as I can tell, kafka-python does not have such option.

What seems to work for us is a simple script that takes the offsets from ZooKeeper and commits them manually to Kafka using the new client, but this needs to be done with all consumers in the consumer group to be down at the same time.

Other options include adding dual commit support to python-kafka or creating new topics for new consumers (the latter requiring to reconfigure producers as well at the time of migration).

I miss a migration guide in the documentation so I'd like to contribute one. What are the recommended steps to upgrade consumers to use the new `KafkaConsumer` implementation?

**Comment by dpkp** [comment]
Thanks for looking into this!

Unfortunately there currently is no support for zookeeper offsets in KafkaConsumer, so the first step is to add that. I filed #753 with more specific information.

Once that is working, we should support a `dual_commit_enabled` option that functions the same as the java consumer.

Finally, we would also want documentation!

**Comment by dpkp** [comment]
Apologies - my recollection was wrong about zookeeper offset support. consumer.commit() does go to zookeeper storage when using <= 0.8.1 brokers. What does not work is autocommit. That is issue #706 (I will push a patch for that now).

So all of the dependent bits should be in place to add support for a `dual_commit_enabled` flag. Do you want to take a stab at that? The code here is very similar to the java client so it may be helpful to take a look at how it is implemented in java first and duplicate that in kafka-python.

**Comment by jeffwidman** [comment]
Is there currently no `dual_commit_enabled` flag in the consumer? 

We're looking at a 0.8.2 --> 0.10 migration and not sure the smoothest way to transition from ZK to Kafka storage for the offsets.

**Comment by ms7s** [comment]
(@dpkp sorry for not responding earlier, I forgot about this issue as I had a lot of other tasks to do)

@jeffwidman When we migrated our consumers from ZK offsets to Kafka we were able to do it with a short downtime (which might not work for you), so I didn't need that feature. We just stopped the entire consumer group, copied the offsets from ZooKeeper to Kafka and then started the new consumers that only used the Kafka offsets.

**Comment by dpkp** [comment]
There is no dual_commit_enabled feature currently. I would happily merge a PR for it though

**Comment by jeffwidman** [comment]
I was planning to put together a PR for this, but turns out we have multiple consumers internally (custom built, old kafka-python, pykafka, etc), and we're migrating all of them to using kafka offsets rather than ZK offsets. So a custom script is the better solution for us as well.

**Comment by jeffwidman** [comment]
I vote to close this issue as unlikely to be worth fixing at this point. 

It's most useful to folks who have complex systems and can't shut down their consumers. Those folks are likely to have a lot of edge cases where simply adding `dual.commit` won't solve what they need--for example we want to rename our consumer groups as part of our migration. And most simple implementations have either already migrated or can simply stop their consumers long enough to run a migration script.

Personally, I'd also rather see support for this only added in the `SimpleConsumer`, not in `KafkaConsumer` as it adds complexity for a rarely used feature.
