### ISSUE TITLE
AttributeError: "'KafkaProducer' object has no attribute '_cleanup'"

### ISSUE THREAD

**Issue by fillest** [dpkp/kafka-python#741]
I've just upgraded to 1.2.2 and I get `Exception AttributeError: "'KafkaProducer' object has no attribute '_cleanup'" in <bound method KafkaProducer.__del__ of <kafka.producer.kafka.KafkaProducer object at 0x7fa789764590>> ignored` message at script termination. Can be reproduced with just `p = kafka.KafkaProducer(); p.send('test', 'hello')` (kafka broker is not started).
Looks like it's related to 6271c02c6eebf52a6d368416db49bfa57b09ef04

**Comment by dpkp** [comment]
Thanks! You can safely ignore the error. But it would be nice to make sure `__del__` doesn't hit any AttributeErrors

**Comment by JonasGroeger** [comment]
I have the same error running from the current master (114bfa87).

```
Exception ignored in: <bound method KafkaProducer.__del__ of <kafka.producer.kafka.KafkaProducer object at 0x7f263f82bac8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/kafka/producer/kafka.py", line 330, in __del__
    self.close(timeout=0)
  File "/usr/local/lib/python3.4/dist-packages/kafka/producer/kafka.py", line 340, in close
    self._unregister_cleanup()
  File "/usr/local/lib/python3.4/dist-packages/kafka/producer/kafka.py", line 313, in _unregister_cleanup
    if getattr(self, '_cleanup'):
AttributeError: 'KafkaProducer' object has no attribute '_cleanup'
```

**Workaround**

Instead of doing this:
```
import kafka
p = kafka.KafkaProducer(…)
```

I'm currently by doing this:

```
import kafka

class Workaround741KafkaProducer(kafka.KafkaProducer):
    def __del__(self):

        # Remove when issue #741 is fixed
        # https://github.com/dpkp/kafka-python/issues/741
        def do_nothing(*args, **kwargs):
            pass
        self._cleanup = do_nothing

        self.close(timeout=0)

p = Workaround741KafkaProducer(…)
```

**Comment by dpkp** [comment]
I definitely would not recommend that as a workaround.

Note that the only issue here is log messages. The exception is handled by
python gc and there should be no noticeable effect other than annoying log
messages using current master.

**Comment by fillest** [comment]
Thanks
