### ISSUE TITLE
consumer.subscribe can register group information on brokers, but consumer.assign function not

### ISSUE THREAD

**Issue by hicqu** [dpkp/kafka-python#744]
I am working with kafka-python, and it's very good. But there is a case:
when I call consumer.subscribe(topic_name"), and consume some messages, I can get offsets information by kafka-consumer-group.sh --new-consumer --bootstrap-server localhost:9092 --list. It perfectly good.
But when I call consumer.assign(tp) to assign a partition to that consumer, I could not get offsets information by kafka-consumer-group.sh!
PS, I am using kafka 0.9.1.0 and kafka-python 1.1.1.
Maybe it's a bug? please help me. thank you !
code：
```
#!/usr/bin/env python2
# coding=utf8
import time
from kafka import KafkaProducer

p = KafkaProducer(
    bootstrap_servers="arch:9092,arch:9093,arch:9094",
    client_id="qupeng_pclient",
    acks=1, compression_type="gzip",
    retries=2, retry_backoff_ms=100
    )

msg_count = 0
while True:
    try:
        v = "I am a message: %s" % msg_count
        k = "I am a key: %s" % msg_count
        p.send("test", value=v, key=k)
        p.flush()
        print("send: %s\t%s" % (k, v))
        msg_count += 1
        time.sleep(1)
    except Exception as e:
        print(e)
        break
```

```
#!/usr/bin/env python2
# coding=utf8
import time
import logging
from kafka import KafkaConsumer
from kafka import TopicPartition

logging.basicConfig(level=logging.INFO)


c = KafkaConsumer(
    bootstrap_servers="arch:9092,arch:9093,arch:9094",
    group_id="qupeng_client",
    retry_backoff_ms=100,
    auto_offset_reset="earliest",
    enable_auto_commit=True,
    auto_commit_interval_ms=1000
    )

# when we subscribe the topic, we can get offsets with kafka-consumer-group.sh.
c.subscribe(topics=["qupeng"])

# but when we call assign to attach consumer with some partitions, we can not.
tps = [TopicPartition(topic="qupeng", partition=x) for x in range(3)]
c.assign(tps)

while True:
    data = c.poll(100)
    if not data:
        time.sleep(1)
        continue
    for tp, vlist in data.items():
        for v in vlist:
            print("%s.%s:%s, value: %s" % (tp.topic, tp.partition, v.offset, v.value))
```

**Comment by hicqu** [comment]
OK, I have checked the documention again. I found a note:
`Manual topic assignment through this method does not use the consumer’s group management functionality. As such, there will be no rebalance operation triggered when group membership or cluster and topic metadata change.`
So I got that. What I want is isolution consumers into different process, not threads. so I what one process consumers one partition, and another process consumers another partition, and  their offsets can be managed by kafka itself. So What's you suggestion?

**Comment by dpkp** [comment]
General comment: can you upgrade to the latest kafka-python release?

Specific comment: use `c.subscribe(topics=["qupeng"])` and if you want to distribute the load across 3 different processes, just run 3 different copies of the same script and the processes will automatically distribute the load.

**Comment by hicqu** [comment]
OK, thanks for your response. But when I use 3 processes subscribe one topic with 3 partitions, and let it auto distribute to them, maybe there is a case not expected:
in the beginning, just one process subscribes the topic, and when it calls poll,  data from 3 partitions will coming.  That's right. But now I start up the second process, and partition 1 is rebalance to that process. Maybe there is some data from partition 1 is still processed by process 1, and there is some data from partition 1 is processed by process 2. if process 1 is slower than process 2, and they both write results to MySQL after their process, maybe the order is wrong!
Will this case happend? Thank you!

**Comment by hicqu** [comment]
OK, I have figured out my questions. The answer is "ConsumerReblanceListener". The two callback functions of that class are running in the same thread with poll function, so that if a partition is assigned to another process, the old offset must already be committed by the original process.
Anyway, thanks a lot!

**Comment by dpkp** [comment]
Yes, though your intuition is correct. Distributed systems are hard to
manage. You should expect that there are failure scenarios in which
messages will be consumed multiple times. This is rare, but generally
cannot be prevented in light of possible network partitions.

I'd recommend that you write database statements that are idempotent so
that processing a message twice is OK.

**Comment by hicqu** [comment]
Yes, you are right, I should use  a external storage to store data and kafka offset both. So that I can recovery from failure without consume one message twice. Thanks a lot!
