### ISSUE TITLE
Support ListGroups / DescribeGroups APIs

### ISSUE THREAD

**Issue by hicqu** [dpkp/kafka-python#745]
the script kafka-consumer-group.sh encapsutes java class kafka.admin.ConsumerGroupCommand, which can get many information from kafka. So could you add those function into kafka-python? Thanks!

**Comment by dpkp** [comment]
`kafka.admin` commands require java so kafka-python cannot use them directly.

kafka-python can provide access to API calls, and there are APIs for listing and describing consumer groups. I'll change the issue request to reflect that distinction.
