### ISSUE TITLE
Help: multiple kafka.conn errors "unable to receive data from kafka" lead to a zombie pid

### ISSUE THREAD

**Issue by DefyGravity** [dpkp/kafka-python#748]
producing errors like below (one every 6 to 10 minutes) will eventually lead to a PID that is still alive, but unable / unwilling to consume more messages. This appears like the final comment on #486 . Let me know what more you need from me to reproduce the error.

> kafka.conn  ERROR Unable to receive data from Kafka
> Traceback (most recent call last):
>   File "_x/y/z.py_" in _read_bytes
>     raise socket.error("not enough data to read message -- did server kill socket?")
> error: Not enough data to read message -- did server kill socket?
> Kafkclient  WARNING ConnectionError attempting to receive a response to request 5 from server BrokerMetadata(node = _x_, host = _y_, port = _z_):Kafka @ _host.domain:port_ went away
> kafka.consumer ERROR FailedPayloadsError saving offsets:

**Comment by dpkp** [comment]
What version of kafka-python and what broker version? What do your broker
logs say?

**Comment by DefyGravity** [comment]
just a second, matching timestamps and whatnot

**Comment by DefyGravity** [comment]
more information, my specific consumer i run drops from 5 pids to 4 pids.  its fairly random, and catching it in the act is a bit hard. will post more if i can deduce it's my problem and not kafka-python.  I start one KafkaClient and a single MultiProcessConsumer for each topic I listen to.  i'm getting to 5 pids with one main pid, and 2 configured topics so far.  When i drop to 4 pids running, I know i've stopped consuming the one topic that is talking to a specific kafka node (logs in previous comment)

**Comment by DefyGravity** [comment]
ok, more information:  

> lsof -Pp 'pid' | grep -w TCP

servicename pid user 5u IPv4  numbers 0t0 TCP   servicename.server:port --> kafka broker A:port  (CLOSE_WAIT)
servicename pid user 6u IPv4  numbers 0t0 TCP   servicename.server:port --> kafka broker A:port  (CLOSE_WAIT)
servicename pid user 7u IPv4  numbers 0t0 TCP   servicename.server:port --> kafka broker A:port  (ESTABLISHED)
servicename pid user 11u IPv4  numbers 0t0 TCP   servicename.server:port --> kafka broker B:port  (CLOSE_WAIT)
servicename pid user 16u IPv4  numbers 0t0 TCP   servicename.server:port --> kafka broker B:port  (CLOSE_WAIT)

our network guy says those close_wait connections should not stick around, "but after 60 seconds they were still there"

**Comment by DefyGravity** [comment]
this is from a healthy cluster, that does not lose a topic:
4 close wait entries (one for each broker)
4 established entries (one for each broker)

cpu usage across the PIDs is less than nothing, with ram usage next to nothing.

on the problem cluster, one pid will be hogging a cpu core (tyvm nice +10) and @ 4x ram then normal.  The other topic for the problem cluster keep processing, but they were the 'first' topic Connection & multiprocessConsumer combo's started.  The problem cluster will have an issue with the last topic's Connection & multiprocessConsumer combination

**Comment by dpkp** [comment]
Please upgrade to latest version of kafka-python. The core has been completely re-written since 0.9.5.

**Comment by dpkp** [comment]
I dont know if there is an issue here, but 0.9.5 issues are definitely wontfix so I'm going to close. Please upgrade and reopen if this problem persists.
