### ISSUE TITLE
consumer_timeout_ms no longer raises ConsumerTimeout

### ISSUE THREAD

**Issue by trent** [dpkp/kafka-python#749]
I'm upgrading from 0.9.4 to 1.2.2 and I see a change in behavior when I set consumer_timeout_ms.  ConsumerTimeout exception used to be thrown when the timeout occurred, but I am now seeing a StopIteration instead.  Is this intended?  If so, the API documentation (http://kafka-python.readthedocs.io/en/1.2.2/apidoc/KafkaConsumer.html) still mentions a timeout exception getting thrown.  But I am also curious why the change from ConsumerTimeout to StopIteration?  ConsumerTimeout was a nice exception to handle when listening to a topic that is slowly getting populated but hasn't reached my expected end.

**Comment by dpkp** [comment]
Thanks for the bug report! Docs should be fixed.

The reason for StopIteration is that it is simply more pythonic. Consider:

```
for msg in consumer:
    process(msg)
else:
    print("Timeout: No new messages available.")
```

Apologize that I'm a sucker for the for/else construct

**Comment by dpkp** [comment]
Updated docs in master
