### ISSUE TITLE
Create consumers based on wild carded topics

### ISSUE THREAD

**Issue by motherhubbard** [dpkp/kafka-python#75]
Not sure if this is the best way of creating a question but here goes....

I searched the code but couldn't see anything obvious. I tried topic.* but it just looped waiting for it to be created.

The Java / Scala clients have a createMessageStreamsByFilter method which also listens to new topics matching the wildcard. It'd be nice if your API did this too ;-)

Cheers

**Comment by dpkp** [comment]
Supported in master as KafkaConsumer.subscribe(pattern='foo')
