### ISSUE TITLE
Help: KafkaTimeoutError question

### ISSUE THREAD

**Issue by dribler** [dpkp/kafka-python#773]
Hi, 

we got this exception during produce.send() `KafkaTimeoutError: Failed to allocate memory within the configured max blocking time`. Can u please explain what may cause it and how we could raising this in future? package version is 1.2.0

Thanks

**Comment by dpkp** [comment]
Are you able to reproduce? If so, please enable debug logging and post logs.

**Comment by dribler** [comment]
Sorry for delay with reply. I'm not able to reproduce this now. Looks like this is one-off, but not sure what exactly could cause it.  I think this is not actual for now, i will reopen if this appear again. Thanks!

**Comment by jeffwidman** [comment]
Sounds like this should be closed?

**Comment by nextkitt** [comment]
Maybe max_block_ms  is too small.

**Comment by dribler** [comment]
@dpkp @nextkitt i think it can be closed. Looks like one-off.

**Comment by dpkp** [comment]
consider increasing `max_block_ms` and/or `buffer_memory`
