### ISSUE TITLE
kafka.protocol.pickle is not fully python3 compatible

### ISSUE THREAD

**Issue by aristiden7o** [dpkp/kafka-python#774]
It still uses `im_func`, `im_self`, `im_class`, it should ude `__func__`, `__class__`, `__self__.__class__`
http://www.diveintopython3.net/porting-code-to-python-3-with-2to3.html#methodattrs

**Comment by dpkp** [comment]
Good catch! want to submit a PR? If not, I will try to fix it up at some point when i get a chance

**Comment by aristiden7o** [comment]
@jpaulodit took care of it https://github.com/dpkp/kafka-python/pull/777

**Comment by dpkp** [comment]
#777 merged
