### ISSUE TITLE
Issue Using KafkaProducer() in Class

### ISSUE THREAD

**Issue by Tom-Gorup** [dpkp/kafka-python#776]
So, I'm having a very odd issue. When I attempt to send a message to a topic called 'test' via a class, it fails. Its seems to fail pretty gracefully since I'm receiving no error message either in Kafka, ZooKeeper or via the command prompt.

```python
class WorkingInKafka(object):
    def send_to_queue(self):
        producer = KafkaProducer(bootstrap_servers='KAFKA_SERVER_IP:9092')
        producer.send('test', b'some_message_bytes')

if __name__ == "__main__":
    kafka_work = WorkingInKafka()
    kafka_work.send_to_queue()
```

Oddly enough, if I run the contents of the class right out of main, it works fine...
```python
if __name__ == "__main__":
   producer = KafkaProducer(bootstrap_servers='KAFKA_SERVER_IP:9092')
   producer.send('test', b'some_message_bytes')
```

**Comment by dpkp** [comment]
Hi -- a couple things to try. First, enable logging to see if there are any warnings or errors. Second, producer.send() is asynchronous and returns a future. If you want to check for errors, you can block with `future.get(timeout=1234)` and then check future.failed() etc. Third, if you just want to make sure pending messages are actually sent before you end execution, try `producer.flush()`

**Comment by Tom-Gorup** [comment]
Thanks! I saw producer.flush() but didn't realize that was need in this case. Appreciate the lightning fast assist!
