### ISSUE TITLE
Help: Getting a kafka.errors.NoBrokersAvailable

### ISSUE THREAD

**Issue by snehamj** [dpkp/kafka-python#781]
I get the error as soon as I execute the second line.

>> from kafka import KafkaProducer
>> producer =  KafkaProducer(bootstrap_servers=['127.0.0.1:9092'])

The error is as such:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/kafka/producer/kafka.py", line 281, in __init__
    self.config['api_version'] = client.check_version(timeout=(self.config['api_version_auto_timeout_ms']/1000))
  File "/usr/lib/python2.7/site-packages/kafka/client_async.py", line 701, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable

**Comment by dpkp** [comment]
do you have a broker listening on `127.0.0.1:9092` ? If you are on unix, you may be able to check with `netstat -lntp | grep 9092`

**Comment by snehamj** [comment]
Issue is fixed. I re-started kafka service and it works fine now. Thanks though!
