### ISSUE TITLE
Help: Infinite loop while disconnecting

### ISSUE THREAD

**Issue by barutm** [dpkp/kafka-python#782]
Hi,

I setup a basic instance with a dozen of consumers / producers talking to each other. After a couple of days with everything running fine I got my system stuck with the following logs (twice):

ERROR    Connect attempt to <BrokerConnection host=xxxx port=9092> returned error 64. Disconnecting.
WARNING  Node 0 connection failed -- refreshing metadata
ERROR    Connect attempt to <BrokerConnection host=xxxx port=9092> returned error 64. Disconnecting.
WARNING  Node 0 connection failed -- refreshing metadata
WARNING  Coordinator unknown during heartbeat -- will retry
WARNING  Heartbeat failed (GroupCoordinatorNotAvailableError - 15 - The broker returns this error code for group coordinator requests, offset commits, and most group management requests if the offsets topic has not yet been created, or if the group coordinator is not active.); retrying
WARNING  Coordinator unknown during heartbeat -- will retry
WARNING  Heartbeat failed (GroupCoordinatorNotAvailableError - 15 - The broker returns this error code for group coordinator requests, offset commits, and most group management requests if the offsets topic has not yet been created, or if the group coordinator is not active.); retrying
WARNING  Coordinator unknown during heartbeat -- will retry
WARNING  Heartbeat failed (GroupCoordinatorNotAvailableError - 15 - The broker returns this error code for group coordinator requests, offset commits, and most group management requests if the offsets topic has not yet been created, or if the group coordinator is not active.); retrying
WARNING  Coordinator unknown during heartbeat -- will retry
WARNING  Heartbeat failed (GroupCoordinatorNotAvailableError - 15 - The broker returns this error code for group coordinator requests, offset commits, and most group management requests if the offsets topic has not yet been created, or if the group coordinator is not active.); retrying
WARNING  Coordinator unknown during heartbeat -- will retry

etc

If I understand well, the initial error is an error 64 from a socket, then there is an issue on the _on_state_change triggering a metadata refresh attempt. Do you have any suggestions to get me out of this stuck situation? Even a way to stop retrying and raise out would enable me to automate a clean restart. 

I am using:
kafka server 2.11-0.10.0.0
zookeeper server 3.4.6
python 3.5.0
kafka-python 1.2.5

Thanks a lot!

**Comment by dpkp** [comment]
Have you checked your broker logs? This usually means your cluster is
unhealthy. Once the cluster recovers the consumers should also recover
automatically.

**Comment by barutm** [comment]
So, when the issue occurs, all my python jobs get stuck in the same way described above. I tried restarting a couple of them manually and they restart fine, which probably at least means that the broker is healthy (again) when I do the manual restart. The other python processes though keep being stuck in the same way so they are probably not able to recover from the unhealthy situation.

**Comment by dpkp** [comment]
error 64 is `ENONET` . Can you determine what is happening on your host or
your network to cause that?

**Comment by barutm** [comment]
The issue happened twice in 7 days, so it is probably my host getting down, making it hard to reproduce (I am prototyping on a local server). Is there a way I can investigate further?
Looking at the code on code.py, it looks like the difference between a successful recover (when I manually restart) and the stuck issue relies in the self._sock whether it is fully created (from state = DISONNECTED), or whether there is a series of attempts to get the connection through socket.connect_ex (from state = CONNECTING).

**Comment by barutm** [comment]
I was finally able to reproduce and get out of it.
The issue was based on the fact that the default broker host name was not set on localhost by default, for some reason (was set to xxx.attlocal.net). This was creating socket connection & reconnection issues, as well as the infinite stuck loop. 
I traced it back from the client.cluster.broker_metadata(node_id) broker host. 

A simple override of the host.name in my broker config to 0.0.0.0 fixed the issue.

Thanks for your help!
