### ISSUE TITLE
How to create a topic with all the partitions?

### ISSUE THREAD

**Issue by ja8zyjits** [dpkp/kafka-python#790]
Well I would like to do create a topic with multiple partitions

**presently**

i follow this [documentation](https://github.com/dpkp/kafka-python#kafkaproducer) to create a producer
but i would like to create it on multiple partitions

**required**

from [this](http://kafka.apache.org/documentation.html#quickstart)

`bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 3 --partitions 1 --topic my-replicated-topic`

here i can decide any number of partitions that i have to be assigned to this partition.

Is there any way to do that here?

Thank You

**Comment by dpkp** [comment]
No. There is currently no way to create topics via remote kafka API calls. This may change in 0.11 or maybe in an 0.10.* release. But for now, you must create topics on the broker directly or rely on auto-create w/ default settings.
