### ISSUE TITLE
node going down causing time out error

### ISSUE THREAD

**Issue by rminxha** [dpkp/kafka-python#800]
When I produce a message to send to a topic on a node that has gone down, I get a timeout following a failure to fetch metadata
 
`Traceback (most recent call last):`

`File "python/sauce/override_triggers.py", line 68, in send_to_kafka_once`

`File "/usr/local/lib/python2.7/site-packages/kafka_python-1.3.1.dev0-             py2.7.egg/kafka/producer/kafka.py", line 481, in send self._wait_on_metadata(topic, self.config['max_block_ms'] / 1000.0)`

`File "/usr/local/lib/python2.7/site-packages/kafka_python-1.3.1.dev0-  py2.7.egg/kafka/producer/kafka.py", line 598, in _wait_on_metadata`

`"Failed to update metadata after %s secs.", max_wait)`

KafkaTimeoutError: KafkaTimeoutError: ('Failed to update metadata after %s secs.', 60.0)

The  file "python/sauce/override_triggers.py" is where I create the producer as follows: 
producer = KafkaProducer(bootstrap_servers=host)

Here's what I'm running on:
kafka-python 1.3.1
python 2.7
kafka api 0.9.0.1

Any thoughts on what I might be doing wrong? What changes would I need to make to ensure the producer can handle node failures?

**Comment by dpkp** [comment]
This error is expected. KafkaProducer handles node failures internally. But you are not seeing a simple node failure. Your producer is unable to retrieve from any node in the cluster any information about the topic you to which you are trying to produce. There is very little that can be done in this case except wait until your cluster has righted itself. And in fact, this error is so bad that it warrants an exception.

The specific timeout can be tuned via `max_block_ms`.

The behavior is identical to the official java client, and I do not want to diverge from that.
