### ISSUE TITLE
Unable to run sync producer via greenlet

### ISSUE THREAD

**Issue by hemendra619** [dpkp/kafka-python#802]
I am trying to put data to Kafka from my Django rest API and got this when I flush/close or apply the below sync method 

```
# Block for 'synchronous' sends
try:
    record_metadata = future.get(timeout=10)
except KafkaError:
    # Decide what to do if produce request failed...
    log.exception()
    pass

```

Error 

```
  link(self)
error: cannot switch to a different thread
(<built-in method switch of greenlet.greenlet object at 0x4076d70>,
 <gevent.event.AsyncResult object at 0x4166550>) failed with error
```

This is working fine from the normal script and pushing message to Kafka. I have also tried to run this with bottle framework with no success.

Does this support to run inside a server thread ?

**Comment by dpkp** [comment]
Looks like you are using greenlet, not threads. kafka-python should work within a django stack using a standard thread- or process-based concurrency stack (uwsgi, for example). I haven't tested against greenlet, though I would love to see some tests written and would gladly accept any PRs to improve greenlet support.

**Comment by hemendra619** [comment]
Correct, Removed greenlet. Working fine with Django and uwsgi . Thanks for your reply.
