### ISSUE TITLE
KafkaConsumer does not work with gevent on python3

### ISSUE THREAD

**Issue by asgoel** [dpkp/kafka-python#806]
Running Ubuntu 14.04 LTS with gevent 1.1.1 on python 3.5.0 with kafka-python 1.3.2... Unable to connect a KafkaConsumer to my brokers. Here is a sample script:

```
from gevent import monkey
monkey.patch_all()

from kafka import KafkaConsumer
k = KafkaConsumer(bootstrap_servers=["remotehost1:9092", "remotehost2:9092"], group_id=None)
```

 and I receive the following error:

`ERROR:kafka.conn:Connect attempt to <BrokerConnection host=xxxxxxx port=9092> returned error [Errno 115] Operation now in progress. Disconnecting.`

Digging deeper it seems like it stems from the fact that the library manually controls the blocking state of the socket, which makes it incompatible with gevent (see here: https://github.com/gevent/gevent/issues/670). Stack trace from the socket error below:

```
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    group_id=None)
  File "/home/asgoel/Documents//venv/lib/python3.5/site-packages/kafka/consumer/group.py", line 284, in __init__
    self._client = KafkaClient(metrics=self._metrics, **self.config)
  File "/home/asgoel/Documents//venv/lib/python3.5/site-packages/kafka/client_async.py", line 197, in __init__
    self._bootstrap(collect_hosts(self.config['bootstrap_servers']))
  File "/home/asgoel/Documents//venv/lib/python3.5/site-packages/kafka/client_async.py", line 227, in _bootstrap
    bootstrap.connect()
  File "/home/asgoel/Documents//venv/lib/python3.5/site-packages/kafka/conn.py", line 266, in connect
    ret = self._sock.connect_ex((self.host, self.port))
  File "/home/asgoel/Documents//venv/lib/python3.5/site-packages/gevent/_socket3.py", line 291, in connect_ex
    return self.connect(address) or 0
  File "/home/asgoel/Documents//venv/lib/python3.5/site-packages/gevent/_socket3.py", line 265, in connect
    return _socket.socket.connect(self._sock, address)
BlockingIOError: [Errno 115] Operation now in progress
```

Are there any plans to support gevent in the near future? Or any ways you can think of to get around this? a lot of our existing code depends on gevent so would love to be able to integrate smoothly.

**Comment by dpkp** [comment]
I haven't used gevent extensively, but kafka-python does set blocking
options for sockets. Is the problem that we put sockets into non-blocking
mode before connecting or that we switch them to blocking for some
operations after connecting?

**Comment by asgoel** [comment]
I think the problem is putting the sockets into non-blocking mode before connecting. For example if I comment out this line: https://github.com/dpkp/kafka-python/blob/master/kafka/conn.py#L253 it seems to work ok.

**Comment by asgoel** [comment]
Hmm that's weird. It seems like the code already checks for
errno.EINPROGRESS (code 115) and ignores it. It's possible gevent sockets
return something else on error which is why it's still hitting that.

**Comment by dpkp** [comment]
Putting sockets into non-blocking mode is core to kafka-python. I don't
think we can change that if it a problem for gevent.

**Comment by asgoel** [comment]
Actually the issue is pretty simple to fix. The gevent socket returns an instance of `BlockingIOError` instead of a pure errno, so we just have to wrap if necessary. I will submit a PR (if that's ok with you) soon. tests should all still pass.

**Comment by dpkp** [comment]
Closing per #1867 discussion + reports that 1.4.7 works w/ gevent
