### ISSUE TITLE
High CPU consumption when using threading on kafka-python 1.3.1

### ISSUE THREAD

**Issue by samirsx** [dpkp/kafka-python#817]
When using threads (or multiprocessing), one sees high CPU consumption by the kafka-python 1.3.1 client using KafkaConsumer even when there are no messages. None of the fetch_max_wait_ms, request_timeout_ms, retry_backoff_ms, consumer_timeout_ms help.

Here is a simple code snippet to repro:
# !/usr/bin/python

from kafka import KafkaConsumer
import thread
import threading

KAFKA_BROKER = '192.168.10.11:9092'
TOPIC = "topic1"

def Thread1(threadName):
        print "THREAD1"
        consumer = KafkaConsumer(TOPIC, group_id='unique', bootstrap_servers=[KAFKA_BROKER])
        for message in consumer:
                print "GOT: "+str(message)

def Thread2(threadName):
        print "THREAD2"
        consumer = KafkaConsumer(TOPIC, group_id='unique1', bootstrap_servers=[KAFKA_BROKER])
        for message in consumer:
                print "GOT: "+str(message)

try:
        thread.start_new_thread( Thread1, ("Thread1",) )
        thread.start_new_thread( Thread2, ("Thread2",) )
except:
        print "Error: unable to start thread"
while 1:
        pass

**Comment by dpkp** [comment]
what is your kafka broker version ?

**Comment by dpkp** [comment]
is this the same issue? https://github.com/dpkp/kafka-python/issues/813

**Comment by samirsx** [comment]
Broker is 0.8.2.2

**Comment by samirsx** [comment]
#813 was fixed on Broker 0.9.0.1. I am able to reproduce this with Broker 0.10.0.0 too. 
Unique signature of the issue is that it happens when kafka-consumer is being run in a thread. Stop using threads and it doesn't surface.

**Comment by dominicfollett** [comment]
Samirsx, facing a similar issue on >= 0.10.0.0, have you  found any further insights as to why this si the case?

**Comment by jianbin-wei** [comment]
I can reproduce this on kafka 0.10.0.1.  kafka-python is 1.3.1

**Comment by jianbin-wei** [comment]
@samirsx , @dominicfollett the reason for high cpu is due to the busy loop in main thread.  Maybe a more realistic code snippet to reproduce it?

```
while 1:
    pass
```

**Comment by jeffwidman** [comment]
I'm closing, as it sounds like this is simply a bad test case that simply spins rather than kafka-python issue.
