### ISSUE TITLE
how to resolve "ERROR Fetch to node 1 failed: [Error 7] " without update kafka?

### ISSUE THREAD

**Issue by hicqu** [dpkp/kafka-python#818]
Full error log: RequestTimedOutError: Request timed out after 5000 ms.

I have set request_timeout_ms to 5000ms instead of 40000ms.

I am using kafka 0.9.0.1. And in server.log, I found:

ERROR Processor got uncaught exception. (kafka.network.Processor)
java.lang.ArrayIndexOutOfBoundsException

And I find that it's a bug of kafka 0.9.0.1 from： https://issues.apache.org/jira/browse/KAFKA-3547

Now my question is:
1. if consumer got a timeout, a new tcp connection will be established, or the consumer hung up forerver?
2. is it correct that I set request_timeout_ms low in order to avoid too long block until timeout? Because I can't update kafka to 0.10.0.1 quickly.

Please help me, thanks!

**Comment by dpkp** [comment]
please attach full debug logs. KAFKA-3547
<https://issues.apache.org/jira/browse/KAFKA-3547> should not affect
kafka-python's operation, although you may see ArrayIndexOutOfBoundsException
in broker logs during startup as kafka-python attempts to "guess" the
broker version. You can skip that step by passing `api_version=(0, 9)` if
you like. But I dont think that is related at all to whatever behavior you
are seeing.

I might suggest you look at session_timeout_ms and verify that there are no
lingering consumers in your consumer group that would cause a rebalance to
block for the session timeout while waiting on a consumer heartbeat from an
old consumer or a consumer that is blocked processing messages.

**Comment by hicqu** [comment]
I did not use group cooperation feature. Instead, I just assign some partitions to one consumer and I store offset in mysql, not commit that to kafka. Full log is attached here. 

In log file, I find kafka-python block here too long time:

Adding fetch request for partition TopicPartition(topic='myfm_api_songlist_no_uid', partition=4) at offset 2024447
Sending FetchRequest to node 1
<BrokerConnection host=10.116.27.40/10.116.27.40 port=9292> Request 4: FetchRequest_v1(replica_id=-1, max_wait_time=500, min_bytes=1, topics=[(topic='myfm_api_songlist_no_uid', partitions=[(partition=4, offset=2024447, max_bytes=1048576)])])

[kafka.zip](https://github.com/dpkp/kafka-python/files/438477/kafka.zip)

**Comment by dpkp** [comment]
If you look closely at the logs you should see that the failure is followed by a reconnect / retry. I would not expect a networking error like that to disrupt your consumer code. It may reduce throughput / increase latency.

The root cause seems like a networking issue, not a software issue, so I don't think that upgrading kafka will solve.

Do you have network monitoring? If not, you might consider putting more telemetry in place.

**Comment by hicqu** [comment]
OK, I will add a network monitor entry in zabbix and look how it works. Thanks a lot!

**Comment by dpkp** [comment]
Can you try reducing max_partition_fetch_bytes and see if that helps? I
have seen cases where the size of the fetch response itself caused
excessive processing time and triggered a timeout.
