### ISSUE TITLE
How to get offset for specific consumer-group?

### ISSUE THREAD

**Issue by chrislee87** [dpkp/kafka-python#819]
I use mirror-maker(which is an outsider and independent consumer/producer) to sync data between clusters, mirror-maker record offset in kafka, how to get offset for it? 
What I want is the offset for a specific group-topic-partition, not logsize for a topic-partition.

**Comment by dpkp** [comment]
There is a kafka API (OffsetFetchRequest), but kafka-python does not currently provide any admin client to make this type of check easy. I'd recommend using the kafka shell scripts for now.

**Comment by jeffwidman** [comment]
We now have an admin client that offers this functionality: https://kafka-python.readthedocs.io/en/master/apidoc/KafkaAdminClient.html#kafka.KafkaAdminClient.list_consumer_group_offsets
