### ISSUE TITLE
Kafka ES Docker-compose, kafka consumer failing

### ISSUE THREAD

**Issue by Lukeout** [dpkp/kafka-python#821]
I'm trying to run this batch script in a python container ... however I'm getting this error. I tried looking around the previous issues but I don't know what the problem is. 

[31mbatchRefresh |[0m Traceback (most recent call last):
[31mbatchRefresh |[0m   File "indexRefresh.py", line 8, in <module>
[31mbatchRefresh |[0m     consumer = KafkaConsumer('new-listings-topic', group_id='listing-indexer', bootstrap_servers=['kafka:9092'])
[31mbatchRefresh |[0m   File "/usr/local/python/lib/python3.5/site-packages/kafka/consumer/group.py", line 182, in __init__
[31mbatchRefresh |[0m     self.config['api_version'] = self._client.check_version()
[31mbatchRefresh |[0m   File "/usr/local/python/lib/python3.5/site-packages/kafka/client_async.py", line 629, in check_version
[31mbatchRefresh |[0m     connect(node_id)
[31mbatchRefresh |[0m   File "/usr/local/python/lib/python3.5/site-packages/kafka/client_async.py", line 592, in connect
[31mbatchRefresh |[0m     raise Errors.NodeNotReadyError(node_id)
[31mbatchRefresh |[0m kafka.common.NodeNotReadyError: None
[31mbatchRefresh exited with code 1

My batch script is this, 

from kafka import KafkaConsumer
import json
import time
from elasticsearch import Elasticsearch

time.sleep(10)

consumer = KafkaConsumer('new-listings-topic', group_id='listing-indexer', bootstrap_servers=['kafka:9092'])
es = Elasticsearch(['es'])

while True:
	for message in consumer:
		new_listing = json.loads((message.value).decode('utf-8'))
		es.index(index='listing_index', doc_type='listing', id=new_listing['_id'], body=new_listing)
		es.indices.refresh(index="listing_index")

**Comment by dpkp** [comment]
That is a connection error. Are you sure your environment can connect to `kafka:9092` ?

**Comment by Lukeout** [comment]
My docker-compose file is this. On a POST request from my web container, I hit the exp container which then is suppose to send a kafka message. This dosn't break. It's just that my batch container with python cannot stay running it errors out. I'm pretty sure I got the connections right here? 

mongo:
    image: mongo:latest
    ports:
        - "27017:27017"
    restart: always

models:
    image: node:latest
    container_name: models
    links:
        - mongo 
    ports:
        - "8001:8000"
    volumes:
        - ./models:/app
    working_dir: /app 
    command: "npm start"

exp:
    image: node:latest
    container_name: exp
    links:
        - models
        - es
    ports:
        - "8002:8000"
    volumes:
        - ./exp:/app
    working_dir: /app
    command: "npm start"

web:
    image: node:latest
    container_name: web
    links:
        - exp
    ports:
        - "8003:8000"
    volumes:
        - ./web:/app
    working_dir: /app
    command: "npm start"

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"   

batch:
   image: tp33/django
   container_name: batchRefresh
   links:
      - kafka:kafka
      - es:es
   volumes:
      - ./scripts:/app
   working_dir: /app   
   ports:
      - "8004:8000"
   command: "python indexRefresh.py"

**Comment by Lukeout** [comment]
Hmmm I think it's because my batch container was named batchRefresh

**Comment by dpkp** [comment]
Closing b/c this is a docker configuration issue, not a kafka-python bug.

**Comment by Lukeout** [comment]
Any advice on how to intergrate node and python here? My batch script should be pushing to my Elastic search but I think I'm not sending anything to kafka. 

Does this look right?

In node I have: 
var kafka = require('kafka-node'),
    Producer = kafka.Producer,
    KeyedMessage = kafka.KeyedMessage,
    client = new kafka.Client('kafka:9092'),
    producer = new Producer(client),
    km = new KeyedMessage('key', 'message');


payloads = [];
    var msg = { topic: 'new-listings-topic', messages: parsedBody, partition: 0 };
    payloads.push(msg);
    producer.on('ready', function () {
    producer.send(payloads, function (err, data) {
        console.log(data);
      });
   });

**Comment by dpkp** [comment]
Sorry, I have never used the node client.

**Comment by Lukeout** [comment]
Could you confirm that my python script is right though?

**Comment by Lukeout** [comment]
Eh actually, the error came back my python container with kafkaConsumer is crashing
