### ISSUE TITLE
Why doesn't KafkaProducer have an ssl_password option?

### ISSUE THREAD

**Issue by kierkegaard13** [dpkp/kafka-python#829]
I've used the KafkaConsumer with ssl with no issues, but for some reason, unlike the consumer, the KafkaProducer class doesn't have an ssl_password option, so every time I use it, I have to enter the pem password manually? Is there a way to fix this?

**Comment by dpkp** [comment]
ssl support was added in PR #750 . Looks like they only needed consumer support. PRs completely welcome to add it to the producer code as well!

**Comment by kierkegaard13** [comment]
Alrighty.. I will get on that :)
