### ISSUE TITLE
Help: NodeNotReadyError when sending offset request

### ISSUE THREAD

**Issue by bjorndv** [dpkp/kafka-python#832]
Hello,
I tried to send an offsetrequest via the async client but sometimes I get "NodeNotReadyError". Is there a way to perform some kind of synchronous request? I simply need to fetch the offsets for a given time, topic and partition. I used to use the OffsetRequest of the old kafka client for this.

**Comment by dpkp** [comment]
NodeNotReadyError will be raised if the socket connection to the requested broker is not fully setup. You should verify that `client.ready(node_id)` succeeds before attempting a direct send.
