### ISSUE TITLE
Add link to docs in repo description

### ISSUE THREAD

**Issue by jeffwidman** [dpkp/kafka-python#835]
Took me a bit to realize there was RTD site for `kafka-python`.

Can you add a link to http://kafka-python.readthedocs.io/ in the github repo description? 

For example, see the repo description for https://github.com/FactoryBoy/factory_boy

**Comment by dpkp** [comment]
Done!

**Comment by jeffwidman** [comment]
Thx. FYI that your link points to `.org`, when they actually now use `.io`
