### ISSUE TITLE
expecting StopIterator exception but did not happen

### ISSUE THREAD

**Issue by rolele** [dpkp/kafka-python#839]
I have noticed that KafkaConsumer is a subclass of six.Iterator so I am using the advance_iterator method to iterate over my topic:
https://pythonhosted.org/six/#six.advance_iterator

advance_iterator will raise a StopIteration exception if the iterator is exhausted but this never happen.
I think the KafkaConsumer prevent that to happen.

I see the benefit for the next method to block and wait for the next data to come though but advance_iterator in meant to raise the exception.

Another thing how can I run a particular method

```
def finish
    print("finish")
```

when a consumer has finish ready the topic (reaching the end of the topic)

**Comment by dpkp** [comment]
did you set `consumer_timeout_ms` ? If not, iteration will block forever.
