### ISSUE TITLE
Silent MessageSizeTooLargeError

### ISSUE THREAD

**Issue by lopuhin** [dpkp/kafka-python#841]
When trying to send a message that is larger than maximum allowed size (``max_request_size`` argument of the ``KafkaProducer``), the message is silently dropped, and only debug logs show that is was dropped:
```
DEBUG:kafka.producer.sender:Starting Kafka producer I/O thread.
DEBUG:kafka.producer.kafka:Kafka producer started
DEBUG:kafka.producer.kafka:Exception occurred during message send: [Error 10] MessageSizeTooLargeError: The message is 13561908 bytes when serialized which is larger than the maximum request size you have configured with the max_request_size configuration
DEBUG:kafka.producer.kafka:Flushing accumulated records in producer.
```
The code that sends the message is just
```
producer = KafkaProducer()
producer.send(topic, data)
producer.flush()
```
I would expect an exception to be thrown. I'm new to kafka so I'm not sure if my expectations are reasonable.

**Comment by lopuhin** [comment]
Right, I didn't notice it, thanks for making it clear! The exception does happen with `get()`.

**Comment by rajish** [comment]
Still I think the error should be reported at least at WARN level.

**Comment by sksethi25** [comment]
@rajish  I was facing same issue, i am thinking to use future.failed() method to check if it failed for this issue. I dnt think its going block the response till message is sent to kafka unlinke get method. 
@dpkp  you can clarify this, is it okay to use failed method for this?
