### ISSUE TITLE
Coordinator _send_group_coordinator_request crashes if least loaded node is disconnected

### ISSUE THREAD

**Issue by relyt0925** [dpkp/kafka-python#842]
Use case: 
We have multiple KafkaConsumer's running in independent processes all in the same group. This group consumes from a topic with a single partition. We run each process indefinitely (want to always have one consuming over time, and others to take over if one fails).  Each process has it's own declaration of the KafkaConsumer class (completely isolated). 

Sometimes, we will see the connection just randomly close and then be thrown an AttributeError: "NoneType" has no attribute 'setblocking' 

Outlined stack trace by linking it to where it is in actual code (NOTE LAST URL IS LINE WHERE EXCEPTION THROWN)

https://github.com/dpkp/kafka-python/blob/9ee77dfdbc4aeb5723ce7ebdae76f8b7141962af/kafka/consumer/group.py#L516

https://github.com/dpkp/kafka-python/blob/9ee77dfdbc4aeb5723ce7ebdae76f8b7141962af/kafka/consumer/group.py#L543

https://github.com/dpkp/kafka-python/blob/1937ce59b4706b44091bb536a9b810ae657c3225/kafka/coordinator/base.py#L212

https://github.com/dpkp/kafka-python/blob/1937ce59b4706b44091bb536a9b810ae657c3225/kafka/coordinator/base.py#L472

https://github.com/dpkp/kafka-python/blob/master/kafka/client_async.py#L454

https://github.com/dpkp/kafka-python/blob/master/kafka/conn.py#L527

After initial setup of the KafkaConsumer class (with default parameters) we just call poll with a timeout of 30 seconds (30000 ms)  in an infinite loop and iterate through each partition and all the messages in that partition that were returned and turn them into a list.

Are we missing something? Do we need to be calling a method to periodically refresh the connections with the broker/ other consumers in the group. Or is calling poll() enough to do so?

by poll I mean this method
https://github.com/dpkp/kafka-python/blob/master/kafka/consumer/group.py#L487

**Comment by relyt0925** [comment]
Kafka 1.3.1, Kafka 1.0

**Comment by dpkp** [comment]
Thanks -- that is a bug!

**Comment by dpkp** [comment]
Q: are you using SSL and/or authenticated sockets?

**Comment by dpkp** [comment]
also, what version of python are you on?

**Comment by relyt0925** [comment]
We are on python 2.7.11

We are using SSL and Authenticated sockets (SASL SSL)

**Comment by relyt0925** [comment]
Let me know if you need anything else! I'm able to help wherever I can

**Comment by dpkp** [comment]
This was fixed by #995
