### ISSUE TITLE
How to deal with RequestTimedOutError?

### ISSUE THREAD

**Issue by hicqu** [dpkp/kafka-python#844]
I am using kafka-python(version 1.3.1) for a while. But lately I found many logs like "RequestTimedOutError: Request timedout after 40000 ms, future-_call_backs-79". My question is,
Is this error critical? I means will it cause lose messages on consumer?
Please help me. It's very important for me. Thank everybody very much!

**Comment by dpkp** [comment]
There are lots of reasons you might see this error. Generally the client should retry, but not always. If, for example, it were a ProduceRequest from KafkaProducer and you had configured `retries` 0, you should expect that your future would resolve to an error.

If this error happens in a KafkaConsumer, one subtle configuration may be `max_partition_fetch_bytes` -- if you have a consumer that gets assigned a large number of high volume partitions, or is trying to catch up from the beginning of partitions, you can get timeouts on pending requests if you buffer too much data per partition. The default is 1MB. I will tune down to 10KB in many cases if I've got a consumer with more than a small number of partitions assigned.
