### ISSUE TITLE
Help: use sasl plain failed?

### ISSUE THREAD

**Issue by skysilence** [dpkp/kafka-python#846]
hi,everyone:
     I used the lastest version 1.3.1 for SASL auth,but I got errors.I maked a producer by this line:

```
  `KafkaProducer(bootstrap_servers='host:post', compression_type='snappy',security_protocol="PLAINTEXT",sasl_mechanism='PLAIN', sasl_plain_username='user', sasl_plain_password='pass')` 
```

By code above, I didn't get any exception from client,But I got exception at kafka server

> [2016-10-12 10:22:00,701] ERROR kafka-network-thread-1-PLAINTEXT-0 Processor got uncaught exception. (kafka.network.Processor.error Logging.scala:103)
>  java.lang.ArrayIndexOutOfBoundsException: 18
>     at org.apache.kafka.common.protocol.ApiKeys.forId(ApiKeys.java:68)
>     at org.apache.kafka.common.requests.AbstractRequest.getRequest(AbstractRequest.java:39)
>     at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:79)
>     at kafka.network.Processor$$anonfun$run$11.apply(SocketServer.scala:426)
>     at kafka.network.Processor$$anonfun$run$11.apply(SocketServer.scala:421)
>     at scala.collection.Iterator$class.foreach(Iterator.scala:727)
>     at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
>     at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
>     at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
>     at kafka.network.Processor.run(SocketServer.scala:421)
>     at java.lang.Thread.run(Thread.java:745)

Then i changed security_protocol to SASL_SSL and SASL_PLAINTEXT, I got the same message,
Did I  using it correctly? 

Thx a lot!

**Comment by skysilence** [comment]
It seemed to be the same question with [533](https://github.com/dpkp/kafka-python/issues/533),
did [779](https://github.com/dpkp/kafka-python/pull/779) fix it?

**Comment by dpkp** [comment]
You can safely ignore that broker error -- it is caused by the dynamic broker version check and is harmless. If you want to avoid the version check, set `api_version` explicitly when you create a KafkaProducer.

Are you seeing some other problem with SASL auth specifically?

**Comment by nicholasserra** [comment]
@skysilence would you happen to still have your config values on hand that got plaintext username/password auth working? Really struggling to get this implemented at the moment. Any insight is helpful, thanks!

**Comment by nicholasserra** [comment]
Nvm, got it working with:

server.properties

```
security.inter.broker.protocol=SASL_PLAINTEXT
sasl.mechanism.inter.broker.protocol=PLAIN
sasl.enabled.mechanisms=PLAIN
listeners=SASL_PLAINTEXT://server-ip:9092
```

And python command:

```
producer = KafkaProducer(bootstrap_servers='server-ip:9092', security_protocol="SASL_PLAINTEXT", sasl_mechanism='PLAIN', sasl_plain_username='username', sasl_plain_password='password')
```

For anyone googling

**Comment by nicholasserra** [comment]
So it seems I was incorrect in my comment above ^

With those settings I get a successful connection to the broker, but any messages I send via the producer end up with a timeout. So I have not yet been successful using the SASL_PLAINTEXT username/password auth with kafak & kafka-python. 

Really struggling to figure out what my disconnect is. If anyone has working settings for client and server that would be amazing.

**Comment by mmccuiston** [comment]
I am having the exact same problem, though I am using the included performance test producer.  

With a connected debugger in the client I can see that KafkaProducer is waiting at KafkaProducer:548 for something to happen.  Then a timeout exception occurs resulting in the log you're seeing.  Still not sure why this is happening either.

**Comment by nicholasserra** [comment]
I ended up using two listeners and only exposing one via AWS security groups. It doesn't feel quite right, but it's working without timeouts. Documented it here:

http://tech.nickserra.com/2017/02/09/apache-kafka-plaintext-authentication-and-kafka-python-configuration-reference/
