### ISSUE TITLE
My multiprocess program will block on the poll() for a long long time waiting for partition assignment rebalance

### ISSUE THREAD

**Issue by GeminiGuy** [dpkp/kafka-python#848]
Python  2.6.6
Kafka 0.10.0.1
kafka-python 1.3.1

I can repeat the problem sometimes（small probability） in the following conditions，Assuming consume the topic A which has 15 partitions：
1、If I hava started the program with 8 processes in the machine X，then I started the program with 7  processes in another machine Y，consuming kafka data normally in some minutes，all the processes will block on the poll()。
2、If I started the program with 8 processes only in the machine X，after consuming kafka data normally in some minutes, the processes may block on the poll() with low probability。
What I can do is using kill -9 PID， Could you please give me some suggestion？Thank you

My pseudocode is blow，the program entry is rundeal()：

`class datadispatchtemplate():

```
def __init__(self):
    self._break_flag = False
    self._property_dict = None
    self._consumer = None

def init_before_loop(self, property_dict):
    servers = property_dict['servers']
    group = property_dict['group']
    topic = property_dict['topic']
    self._consumer = KafkaConsumer(bootstrap_servers=servers, enable_auto_commit=True, group_id=group)
    self._consumer.subscribe(topics=[topic])

def init_after_loop(self, property_dict):
    self._consumer.close()

def parser_data(self, result_data_list):
    pass

def onsignal_term(self, a, b):
    print str(__file__) + "  " + str(os.getpid()) + " process recv signal"
    fastlog.info(str(__file__) + "  " + str(os.getpid()) + " process recv signal")
    self._break_flag = True

def rundeal(self, property_dict):
    self._property_dict = property_dict
    pid = os.getpid()
    fastlog.set_logid(property_dict['mod'] + "_" + str(pid))

    signal.signal(signal.SIGTERM, self.onsignal_term)
    self.init_before_loop(property_dict)

    get_null_count = 0
    while True:
        if self._break_flag:
            print "break while loop in " + property_dict['mod']
            fastlog.info("break while loop in " + property_dict['mod'])
            self.init_after_loop(property_dict)
            break
        try:
            # poll data
            fastlog.info("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
            records_dict = self._consumer.poll(100)
            fastlog.info("YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY")
            if not records_dict:
                get_null_count += 1
                if get_null_count >= 10:
                    get_null_count = 0
                    time.sleep(0.05)
                continue
            get_null_count = 0
            begin = time.time()

            result_data_list = []
            for key in records_dict:
                for consumer_record in records_dict[key]:
                    result_data_list.append(consumer_record.value
            self.parser_data(result_data_list)
            end = time.time()
            fastlog.info("consume data per poll cost time========>" + str((end - begin) * 1000) + " ms")
        except Exception as e:
            fastlog.error("parser data Exception: " + str(e) + " data: " + str())`
```

**Comment by dpkp** [comment]
My hunch is you are not closing your consumer group on kill -9. That would leave the group coordinator with a list of dead consumers and any attempt to rebalance the group with new consumers would block for the session_timeout_ms, at which point the group coordinator would expire the dead consumers from the group and allow the new members to join.

You can also try enabling debug logging to get a view for what exactly is happening internally.

**Comment by GeminiGuy** [comment]
All the consumer processes I mentioned above  are in the same consumer group，and there are no other consumer processes in condition  1 or 2。 I can ensure that there are no consumer process alive before I start the consumer processes in condition 1 or 2。And the consumer processes wil block all the time until I kill it with kill -9。I set session_timeout_ms to 60000。
I have another question is that how to close my multiprocess program gracefully？What I have done is sending signal SIGTERM through the parent process。The onsignal_term() function in my program above would set _break_flag to True，so next loop will exit。
[http://kafka.apache.org/0100/javadoc/index.html?org/apache/kafka/clients/](url) 
Class KafkaConsumer Multi-threaded Processing give the example which can use consumer.wakeup()
I also wrote a Java consumer framework。
