### ISSUE TITLE
Consumer blocks indefinitely when calling poll() with eventlet

### ISSUE THREAD

**Issue by relyt0925** [dpkp/kafka-python#851]
We have a long running consumer process that consumes messages from a single partition kafka topic. There are 3 consumer instances in the group. About 1-2 times every day (these run for days at a time) all 3 consumer instances will all block within 2 minutes of one another. They block when they all call into poll(). A monitoring process restarts them after 10 minutes (after detecting they are blocking), and then the group will begin consuming again and catching up on old messages.

We call into poll with a timeout of 30000 ms. I understand that poll() will block on a rebalance but it seems like this is not the sole cause of a 10 minute block.

Here are some of the logs from what I found.

The one below is logged when the consumer instance has been detected to be blocked for 10 minutes. 
![screen shot 2016-10-20 at 8 49 14 am](https://cloud.githubusercontent.com/assets/7716924/19563910/57f3d676-96a7-11e6-8036-1d9b02aeb99f.png)

Then after doing some more analysis, I saw that it was stopping after calling poll with the timeout of 30000 ms. I then ran a stack tracer in the consumer process to print out the stacks of all the threads in the process. Below is the trace of the thread that is actually consuming messages from kafka.
![screen shot 2016-10-20 at 8 36 56 am](https://cloud.githubusercontent.com/assets/7716924/19564222/60db7c0c-96a8-11e6-97df-d64e4b5f189c.png)

Doing some more digging I actually see the partition get revoked
![screen shot 2016-10-20 at 9 52 39 am](https://cloud.githubusercontent.com/assets/7716924/19565233/c42355f2-96ab-11e6-8366-98460ce02d29.png)

![screen shot 2016-10-20 at 9 59 47 am](https://cloud.githubusercontent.com/assets/7716924/19565505/adb187b6-96ac-11e6-9597-7947f75fee4e.png)

![screen shot 2016-10-20 at 10 06 09 am](https://cloud.githubusercontent.com/assets/7716924/19565575/e31f032e-96ac-11e6-9a1e-d6432c924857.png)

It seems like the partition is changed in two instances but the last log that is seen in instance 0 is just the poll (never sees a partition change). 

Any help/ advice is greatly appreciated. I described our workflow in this previous issue
https://github.com/dpkp/kafka-python/issues/842

**Comment by relyt0925** [comment]
We are thinking it might be related to https://github.com/eventlet/eventlet/issues/315

**Comment by relyt0925** [comment]
We are currently using eventlet==0.17.4

**Comment by dpkp** [comment]
I have not tested kafka-python with eventlet, but I don't know of any reason it should not work when monkey patched.

But that issue you linked seems like it could be a problem if you are using SSL connections to kafka.

**Comment by relyt0925** [comment]
Closing this now but will update with the findings of our investigation for future users

**Comment by relyt0925** [comment]
Eventlet turned out to be the issue in our case. Something with the event loop system was not playing nice with the library and would lead to a deadlock. Removed eventlet and the library has been working fine
