### ISSUE TITLE
I  have  some  trouble  about  using   KafkaConsumer

### ISSUE THREAD

**Issue by wavwind** [dpkp/kafka-python#854]
I use kafka-consume:

consumer = KafkaConsumer('my-topic',
group_id='my-group',
bootstrap_servers=['node1:9092', 'node2:9092', 'node3:9092'])

When I was receiving data, the node1 shut down. Then I can't receive any data.
What I want is : it should receive data from node2 or node3 automatic, How can I achieve it? Please help me.

**Comment by dpkp** [comment]
Failover should be automatic -- can you dig any deeper? There isn't enough information here to debug. Please reopen if you have more details.
