### ISSUE TITLE
Support CreateTopic / DeleteTopic APIs

### ISSUE THREAD

**Issue by dpkp** [dpkp/kafka-python#857]
New in 0.10.1.0 per KIP-4 / KAFKA-2945 / KAFKA-2946

**Comment by jeffwidman** [comment]
@dpkp Can you flesh out a little more of what of what you're envisioning for implementation?

**Comment by dpkp** [comment]
I think I'd use this ticket to track basic protocol support. Add class defs to `kafka.protocol.admin` . I think your other ticket, #935 , is a great idea for actually using them. The admin client would probably benefit from an easier I/O model, though, so I have been hoping to finish work on refactoring into a sans-IO protocol parser.

**Comment by jeffwidman** [comment]
Sounds great. Just pushed support for the basic protocol structs. 

> The admin client would probably benefit from an easier I/O model, though, so I have been hoping to finish work on refactoring into a sans-IO protocol parser.

Not sure I quite understand the I/O problem nor how to best solve it, so looking forward to seeing what you mean in code.

**Comment by Drizzt1991** [comment]
> The admin client would probably benefit from an easier I/O model, though, so I have been hoping to finish work on refactoring into a sans-IO protocol parser.

This sounds quite interesting, do you have any reference for that. Any way to help? I am (as the maintainer of `aiokafka`) quite interested in the topic. Maybe a separate issue at least?

**Comment by Drizzt1991** [comment]
> Not sure I quite understand the I/O problem nor how to best solve it, so looking forward to seeing what you mean in code.
Just as a reference https://sans-io.readthedocs.io/. Read as in `hyper-h2`, `hiredis`, where protocol parsing itself does not interact with IO.
