### ISSUE TITLE
consumer example call hangs on Ubuntu

### ISSUE THREAD

**Issue by ZmeiGorynych** [dpkp/kafka-python#863]
Just installed kafka and kafka-python on Ubuntu. 

The below code runs without problems, and I can see the messages being published via a shell client:
```
from kafka import KafkaProducer
producer = KafkaProducer(bootstrap_servers='localhost:9092')
for _ in range(100):
    producer.send('foobar', b'some_message_bytes')
from kafka import KafkaConsumer
consumer = KafkaConsumer('foobar',group_id=None)
#consumer.subscribe(topic=None, pattern="my-topic")
```
However, when I try to read them in Python, the below code just hangs (for several minutes at least):
```
for msg in consumer:
    print msg
```
Am I missing something obvious? Thanks a lot.

**Comment by dpkp** [comment]
Consumer reads from the tail by default. use `auto_offset_reset='earliest'` to read from the head.

**Comment by ZmeiGorynych** [comment]
Thanks, that worked!
