### ISSUE TITLE
KafkaProducer unable to send message to remote Kafka

### ISSUE THREAD

**Issue by gabrielhao** [dpkp/kafka-python#866]
The problem:
 1. start Kafka 0.10.1 on a remote machine with IP1; telnet test port 9092, 2181 are all open.
 2. on another machine, " producer= KafkaProducer(bootstrap_servers='IP1')"

>      
Error is:
Traceback (most recent call last):
File "<stdin>", line 1, in <module
File "/usr/local/lib/python2.7/dist-packages/kafka/producer/kafka.py", line 328, in __init__
    **self.config)
 File "/usr/local/lib/python2.7/dist-packages/kafka/client_async.py", line 202, in __init__
  self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/usr/local/lib/python2.7/dist-packages/kafka/client_async.py", line 791, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable

   
 3 Add api_version, producer=KafkaProducer(bootstrap_servers='IP1', api_version='0.10'). No error msg. But producer.send('topic,' 'message').get(60) will timeout.

While I tested this on the machine with Kafka running. producer=KafkaProducer(bootstrap_servers='localhost') and producer.send('topic,' 'message').get(60) are all ok. 

I think that api_version error also because the Kakfa-python cannot connect to remote host, couldn't get the api_version.

**Comment by dpkp** [comment]
This is a networking configuration error. Try enabling debugs to investigate your issue further.
