### ISSUE TITLE
KafkaConsumer groupid is not registered

### ISSUE THREAD

**Issue by suppandi** [dpkp/kafka-python#869]
A simple consumer program like

    consumer = KafkaConsumer('t1',bootstrap_servers='bootstrap-servers',
                                                     enable_auto_commit=True,
                                                     auto_commit_interval_ms=30 * 1000,
                                                     group_id='mygroup')

    for msg in consumer:
           print(msg.offset)
           process(msg.value)

is not saving the offset in kafka. If for some reason the program quits and is restarted, it is starting over from offset 0 rather then where it was when it was stopped.

**Comment by dpkp** [comment]
cannot duplicate. what version of kafka-python? what version of kafka?

**Comment by suppandi** [comment]
python-kafka 1.3.1
kafka 0.10.0.0

**Comment by suppandi** [comment]
https://www.apache.org/dyn/closer.cgi?path=/kafka/0.10.0.0/kafka_2.11-0.10.0.0.tgz to be precise

**Comment by dpkp** [comment]
Are you seeing any errors in the logs? You might try enabling DEBUG logging and see if anything strange pops out.
