### ISSUE TITLE
Consumers without group-cooperation lost messages after RequestTimeoutError

### ISSUE THREAD

**Issue by hicqu** [dpkp/kafka-python#882]
I am working with kafka-python-1.3.1 for a while. I didn't use group-cooperation feature but assign partitions to a consumers manually. Sometimes I get exceptions like "RequestTimeoutError" in logs, and "disconnect from some brokers" followed. 

I know that's maybe because my max_partition_fetch_bytes is too large. I thought that was ok, because my consumer could fetch messages again after a while.

But today after I check my logs more carefully, I found there are some messages losted after that Exception!
Anybody caught this problem before? I haven't figured out that's a bug or I use kafka-python in a wrong style.

Please help me. I could attach a business log here tomorrow to show my problem, but I don't have a verbose kafka-python log file.

Thanks a lot!

**Comment by dpkp** [comment]
I have not seen this before. Will need more information to proceed.
