### ISSUE TITLE
A problem with interpreting non-error "Fetch to node X failed: ConnectionError"

### ISSUE THREAD

**Issue by fillest** [dpkp/kafka-python#884]
I have a periodically launched script, which consumes at most N messages (using `consumer_timeout_ms`). The problem is, in the end there is nearly always this message: `ERROR:kafka.consumer.fetcher:Fetch to node 0 failed: ConnectionError: <BrokerConnection host=127.0.0.1/127.0.0.1 port=9092>`. Also I have other scripts for e.g. just printing consumed messages without commiting (`cat`-style). This message is quite cryptic and everybody working with consumer scripts get confused and send me this error from time to time and each time I have to reply with "nevermind, it is normal".
I tried to use `poll` directly but result is the same.

So if it is not a human-reaction-required error (my guess it's the case), this should be logged not as error or probably better not logged at all in such situations, or maybe there should be a way to temporary suppress this (but without missing the real error when it happens of course).

My env: kafka-python==1.3.1, kafka 0.10.1.0 (I observed this with older clients and brokers too), python 2.7.6

**Comment by dpkp** [comment]
agree, but it's a tricky one to prevent. I'm happy to merge a PR that addresses this.
