### ISSUE TITLE
Help: KafkaConsumer raises StopIteration

### ISSUE THREAD

**Issue by ZmeiGorynych** [dpkp/kafka-python#888]
When I call
```
consumer1 = KafkaConsumer(topic, auto_offset_reset='earliest', consumer_timeout_ms=100)
consumer1.next()
```
I always get a StopIteration exception.
A console client shows there's data in the topic, and when I run the above in an endless loop ignoring the exception, and publish some data onto the topic from elsewhere, the code above sees it. So it appears it just ignores the auto_offset_reset='earliest' kwarg - any idea why? Am I missing something obvious?

Python 2.7 on Ubuntu 16.04, kafka 0.9.2

Thanks a lot,
E.

**Comment by dpkp** [comment]
The StopIteration is caused by your consumer_timeout_ms. 100ms is probably too low to join the group, get partition assignments, fetch offsets, fetch messages, and return them.  Try increasing it to something like 1000 and see if that works.
