### ISSUE TITLE
Add additional values to API_VERSIONS for 0.10.x 

### ISSUE THREAD

**Issue by jeffwidman** [dpkp/kafka-python#892]
Currently [`API_VERSIONS`](https://github.com/dpkp/kafka-python/blob/master/kafka/client_async.py#L78)only has one value for 0.10 brokers. 

For safety, I'm trying to pin the Kafka broker API versions in our code. 
If there's a future 0.10.x release that breaks an API, there's no way I can demarcate that our code wasn't expecting anything newer than 0.10.0 API or 0.10.1 API version... 

Should we add values for those?

Also, It seems tedious to be adding values every time a new Kafka release happens. Is there something I'm missing? Like can I specify `(0, 10, 0)` in my code? And if an api changes, kafka-python will understand that that means 0.10.0.x?

**Comment by dpkp** [comment]
I believe this has been addressed now -- can we close?

**Comment by jeffwidman** [comment]
I guess in general my issue/question was whether the code allows putting in tuples that don't currently exist in `API_VERSIONS`?

For example, can I put in `(0, 10, 2)` or `(0, 11, 0)` and `kafka-python` will work fine by enabling all currently supported features. This would be a future-proofing in some ways, so that as support for new broker features get added to `kafka-python`, I will automatically get support for those as soon as I upgrade the library, even if I forget to bump the kwarg. 

Otherwise it's annoying to have to remember to set the API version to the minimum of brokers / kafka-python highest supported version.

**Comment by dpkp** [comment]
I'm still confused by what this issue is requesting.

**Comment by jeffwidman** [comment]
Perfect, thanks!
