### ISSUE TITLE
Help: Getting Attribute error: 'str' object has no attribute 'topic' on consumer.assign

### ISSUE THREAD

**Issue by arunsriniv** [dpkp/kafka-python#894]
I'm running Kafka 2.11-0.10.0.0 and kafka-python 1.31. When I try to assign a partition to consumer, am getting an attribute error. 

import time, json, zlib
from kafka import KafkaConsumer
from kafka import TopicPartition

hostTopic = "HOST_TOPIC"
myoffset = 75
kafka_data = []
mypartition = TopicPartition(hostTopic, 0)
print type(mypartition)
consumer = KafkaConsumer(...)
consumer.assign(mypartition)
consumer.seek(mypartition, myoffset)
for msg in consumer:
        mesg = zlib.decompress(msg.value, 24)
        print mesg
        kafka_data.append(mesg)
print kafka_data
print len(kafka_data)

Getting the below error, when I try to execute the above program

<class 'kafka.structs.TopicPartition'>
Traceback (most recent call last):
  File "kafka-consumer.py", line 11, in <module>
    consumer.assign(mypartition)
  File "/usr/lib/python2.7/site-packages/kafka/consumer/group.py", line 329, in assign
    self._client.set_topics([tp.topic for tp in partitions])
AttributeError: 'str' object has no attribute 'topic'

**Comment by dpkp** [comment]
`consumer.assign` expects a list of topic-partitions. Try this instead:
`consumer.assign([mypartition])`

**Comment by arunsriniv** [comment]
yeah I got it working. Thank you so much.
