### ISSUE TITLE
BrokerConnection API_VERSION has wrong default value in docstring

### ISSUE THREAD

**Issue by jeffwidman** [dpkp/kafka-python#902]
I'm confused about the API_VERSION default value.

[`conn.py`](https://github.com/dpkp/kafka-python/blob/master/kafka/conn.py#L77) says:
> 'api_version': (0, 8, 2), # default to most restrictive

But the [docstring](https://github.com/dpkp/kafka-python/blob/master/kafka/conn.py#L139) for that class says:

>  api_version (tuple): specify which kafka API version to use. Accepted
                values are: (0, 8, 0), (0, 8, 1), (0, 8, 2), (0, 9), (0, 10)
                If None, KafkaClient will attempt to infer the broker
                version by probing various APIs. *Default: None*

So the default isn't `None`, it's `(0, 8, 2)`. Which should be fixed, the docstring or the default value?

I'm *think* this class is only used by SimpleClient not by the newer KafkaClient async, since I see another set of values here:
https://github.com/dpkp/kafka-python/blob/master/kafka/client_async.py#L78 where both the code and the docstring state the default value is `None`.

Help?

**Comment by dpkp** [comment]
Sorry -- it is a bit confusing as is. I think I just copied the client docstring over and forgot to update. The default should not be None until we add an internal call to check_version in BrokerConnection. For now, we should just fix the docstring to just say `Default: (0, 8, 2)`
