### ISSUE TITLE
option to avoid requesting full metadata for all topics of the cluster?

### ISSUE THREAD

**Issue by dwo** [dpkp/kafka-python#906]
I'm using kafka-python against a Kafka (0.9) cluster with over 1000 topics and over 10,000 partitions. It seems like during bootstrap there are places in the code that explicitly request metadata for all the topics. On a cluster of this size, these requests can sometimes be pretty slow.

Here's the two places I spotted it:
* https://github.com/dpkp/kafka-python/blob/1.3.1/kafka/client_async.py#L216
* https://github.com/dpkp/kafka-python/blob/1.3.1/kafka/conn.py#L798

Would it be possible to offer an option to use a known topic at this stage of the process to reduce the bootstrap time and data transferred? I could even attempt a PR with a bit of guidance.

**Comment by dpkp** [comment]
I'm not totally opposed to this, but the kafka 0.10 protocol was updated to support no-topic metadata requests for exactly this reason. You might try simply upgrading your brokers to 0.10+ and kafka-python will start using MetadataRequest v1

**Comment by dwo** [comment]
One does not simply upgrade to Kafka 0.10... but that's a pretty compelling reason to add to our list. Thanks, I'll close this.

**Comment by dpkp** [comment]
Touche!

**Comment by dwo** [comment]
@dpkp one last question: do you know which Apache JIRA ticket covers the protocol update and "no-topic" requests?
