### ISSUE TITLE
KeyError: 'error_code' at kafka/protocol/struct.py __repr__

### ISSUE THREAD

**Issue by fillest** [dpkp/kafka-python#908]
kafka-python==1.3.1, kafka 0.10.1.0
I've set consumer's session_timeout_ms bigger than group.max.session.timeout.ms in the broker and used group coordination. Here is my consumer setup:
```python
SECOND = 1000
consumer = kafka.KafkaConsumer(
    topic,
    bootstrap_servers = bootstrap_servers,
    client_id = client_id,
    group_id = group_id,
    value_deserializer = value_deserializer,
    auto_offset_reset = 'earliest',
    enable_auto_commit = False,
    consumer_timeout_ms = 1000 * 1,
    api_version = (0, 10),
    session_timeout_ms = SECOND * 60 * 20,
    heartbeat_interval_ms = SECOND,
)
```
I use celery and I got the following exception:
```
[2016-12-12 07:50:36,281: ERROR/Worker-2] Attempt to join group some_name failed due to fatal error: [Error 26] InvalidSessionTimeoutError: JoinGroupResponse_v0(error_code=26, generation_id=0, group_protocol=u'', leader_id=u'', member_id=u'', members=[])
[2016-12-12 07:50:36,464: INFO/MainProcess] Task task_name[task_id] succeeded in 0.72630248405s: None
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/home/qwe/venv/local/lib/python2.7/site-packages/celery/utils/log.py", line 142, in format
    msg = logging.Formatter.format(self, record)
  File "/usr/lib/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
  File "/home/qwe/venv/local/lib/python2.7/site-packages/kafka/protocol/struct.py", line 46, in __repr__
    key_vals.append('%s=%s' % (name, field.repr(self.__dict__[name])))
KeyError: 'error_code'
```

**Comment by Drizzt1991** [comment]
Check your broker configuration. From [docs](https://kafka.apache.org/documentation/#newconsumerconfigs):
```
Note that the value must be in the allowable range as configured in the broker configuration by group.min.session.timeout.ms and group.max.session.timeout.ms
```
By default `group.max.session.timeout.ms=300000`, which is lower than your 20 min. Why do you even set the `session_timeout` so high, do you understand that this setting is directly affecting the rebalance time. In other words your cluster will rebalance in minimum (!) 20min in case of a failure, and as restart of consumers also triggers rebalance you will start consuming only 20min after restart.
Typically this setting is in 2-3 min for slow consumers, and the default is as low as 30s.

**Comment by fillest** [comment]
@Drizzt1991 1) I'm aware that the value is high, but currently this consumer logic code often blocks for very long time and it was much faster (I had a dedline) to just raise the timeout enough instead of rewriting the logic (which requires increasing the complexity).
2) The problem here is the resulting confusing exception which hides the cause,

**Comment by jianbin-wei** [comment]
@fillest , your celery task finished within 1 second **successfully** even with the exception.  Is it possible that your task does not handle exceptions properly?

I believe the exception is raised as it is detected at the beginning of the task.  It does not hide the issue but needs to be caught and handled.

**Comment by fillest** [comment]
@jianbin-wei "Task succeeded" message was likely regarding some other task (there are multiple celery workers running in parallel and their log messages are interleaved) - I forgot the details, unfortunately.
The exception is raised when the logging systems tries to format the message, as we can see from the call stack, and it results with KeyError in kafka/protocol/struct.py. And this message appears later then "InvalidSessionTimeoutError" message.
This should be easy to reproduce in a clean way (just set high enough `session_timeout_ms` and consume a message) either without or with celery - I can do it some (undefined) time later.
