### ISSUE TITLE
UnicodeDecodeError while producing binary data

### ISSUE THREAD

**Issue by duke-bartholomew** [dpkp/kafka-python#910]
When producing (large) binary messages, I get following error:
```UnicodeDecodeError: 'ascii' codec can't decode byte 0xd2 in position 45: ordinal not in range(128)```

I've traced this down, but the only reason I can think of is this line:
```https://github.com/dpkp/kafka-python/blob/master/kafka/producer/kafka.py#L502```

2 problems pop in mind: 
1) it will try to convert binary data to a String, which might not be possible (as in my case)
2) there is (in my opinion) no point in logging every message.
    These messages can, and will be, way to large to display (we're pushing megabytes per message)
    and will render the logging unusable because of the number of them while producing at high rates.

**Comment by jianbin-wei** [comment]
Can you have sample snippet to reproduce it? 

The logging is at debug level so normally messages are not logged.

**Comment by dpkp** [comment]
We should definitely improve that logging statement. But unless you have
debug logging enabled the format string will not be evaluated (log
formatting is lazy). Could there be a different source for your error? Or
did you have debug enabled at the time?

>

**Comment by jianbin-wei** [comment]
my simple test does not have issues.

**Comment by duke-bartholomew** [comment]
Thanks for the feedback.
It looks like I'm on the wrong track with this issue (as none of you had issues with producing binary data).
I'll need to do some further digging ...
I'll come back when I have an isolated reproducible scenario (or when I found the reason for this issue ;-) )

**Comment by lieut-data** [comment]
I encountered this issue when my `key` was a protobuf-encoded message in a `str`. My issue appears to have been resolved as part of https://github.com/dpkp/kafka-python/commit/8de40a20d909c90745b39df09b3aa9d2cc194b68 and will hopefully be in the next release.

**Comment by cloud-zhao** [comment]
import sys
if sys.version_info[0] == 2:
    reload(sys)
    sys.setdefaultencoding('utf-8')
