### ISSUE TITLE
KafkaConsumer always passes message key to deserializer, even if key is None

### ISSUE THREAD

**Issue by jeffwidman** [dpkp/kafka-python#913]
I specified `json.loads` as the `KafkaConsumer`'s `key_deserializer` callable, then produced a message without a key.

`json.loads` throws an exception about expecting a string. Looks like root cause is here: https://github.com/dpkp/kafka-python/blob/master/kafka/consumer/fetcher.py#L546

Fetcher is always using passing the key to the deserializer, even if the key is `None`.

Will submit a PR shortly.

**Comment by dpkp** [comment]
We generally wrap json.loads in a lambda to check for None. But I don't
think we can require that all deserializers map None -> None, however, so
we do not attempt to short circuit or special case internally.

**Comment by jeffwidman** [comment]
Thanks for the fast reply. 

> I don't think we can require that all deserializers map None -> None

That's up to you. While I agree that generally it's better to give the user flexibility, in this case I'd personally bypass it because sending null keys is very common, versus writing a custom deserializer to map a None to something else is very rare (for keys). More typically if I wanted null keys to be replaced with else, I'd add that at the app logic layer.

> We generally wrap json.loads in a lambda to check for None.

Good suggestion, hadn't thought of that. I'm guessing you mean `lambda k: json.loads(k) if k is not None else k` unless there's something special that I'm unaware of regarding how python's lambdas deal with None?

**Comment by jeffwidman** [comment]
Are you open to adding a note about this lambda tip to the tutorial doc, so that others don't have to debug it?

**Comment by dpkp** [comment]
Yes -- exactly. Although I agree that it is much more common to want None -> None, and much less common to want something else, I dont think we should make it impossible to do the latter. Options I think are ok: improve docs, provide a "stock" json deserializer, add a configuration to disable None skipping.

Also you might want to take a quick look at #912 where I'm changing the internals of serializer / deserializer handling slightly.
