### ISSUE TITLE
Don't log with ERROR severity if it's not an error condition

### ISSUE THREAD

**Issue by immerrr** [dpkp/kafka-python#916]
I don't think kafka-python should apply ERROR severity to log messages when reporting problems that would be retried. If a subsequent retry fixes the issue, it's not a problem anymore, which means the original isue should have been reported at "warning" severity, because there seems to be a consensus that warning describes an unusual event that may or may not lead to an error, but is not an error yet in itself: 

- https://docs.python.org/2/howto/logging.html#logging-basic-tutorial
- https://en.wikipedia.org/wiki/Syslog#Severity_level
- https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/Level.html#WARN

Ideally, an issue that will be retried would be reported as WARNING and as ERROR when retries are exhausted. Although there are borderline situations that might require extra attention, eg. example when consumer polls for messages and something happens, no retries are set up for the failed request, but it would be retried during the next poll.

**Comment by dpkp** [comment]
Sounds right - PRs welcome!
