### ISSUE TITLE
ETA for new release?

### ISSUE THREAD

**Issue by jeffwidman** [dpkp/kafka-python#918]
Is there an ETA on the next release... ? 

Be nice to have `max_poll_records` available on Pypi...

**Comment by dpkp** [comment]
Good call -- would like to do a release over the holidays when I have some spare time to make sure everything looks good.

**Comment by dpkp** [comment]
And thanks for all your help @jeffwidman w/ issue reports and PRs !

**Comment by dpkp** [comment]
released 1.3.2 -- thanks for all your help!

**Comment by jeffwidman** [comment]
Thanks!
