### ISSUE TITLE
Exceptions in value_serializer is swallowed by producer 

### ISSUE THREAD

**Issue by harelba** [dpkp/kafka-python#920]
When value_serializer throws an exception, producer.send() still succeeds, leading to the fake notion that the message has been sent successfully.

**Comment by dpkp** [comment]
`producer.send()` returns a future. Check `future.failed()` and `future.exception` for all error conditions.

**Comment by harelba** [comment]
True.. I missed it.. Thanks a lot!

**Comment by dpkp** [comment]
no problemo!
