### ISSUE TITLE
KafkaConsumer.poll stuck and not getting any data

### ISSUE THREAD

**Issue by gilbirenberg** [dpkp/kafka-python#921]
Hi

for some reason the when  i run this code: 
System.out.println("Before the pool");
ConsumerRecords<String, String> records = consumer.poll(1000);
System.out.println("after the poll");
it stuck, the poll never exit and i don't got the after print
Any suggestion's what can be the issue here?

**Comment by dpkp** [comment]
This looks like Java code - are you using the kafka-python client?

**Comment by gilbirenberg** [comment]
Hi
No , I am using java-code
Gil

Birenberg Gil

Sr Product Developer
TrueSight R&D

Office



972-4-6900498











[BMC Software|Bring IT to Life]<http://www.bmc.com/>

**Comment by dpkp** [comment]
This github project is for the python client.

**Comment by gilbirenberg** [comment]
OK and….

How can I address to the right place this question?
Gil

Birenberg Gil

Sr Product Developer
TrueSight R&D

Office



972-4-6900498











[BMC Software|Bring IT to Life]<http://www.bmc.com/>

**Comment by dpkp** [comment]
You might try the mailing list users@kafka.apache.org .
