### ISSUE TITLE
Spelling and Grammar

### ISSUE THREAD

**Issue by melissacrawford396** [dpkp/kafka-python#922]
I'm new to contributing to open source, so I went through and took a look at the comments/doc strings for:
- kafka/consumer/group.py
- A couple of cant --> can't

I was using this as a style example: http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

I'll create the PR shortly. Let me know if you need any changes! (or are interested in the PR lol)

**Comment by dpkp** [comment]
Always interested in PRs, thanks!

**Comment by eplanet** [comment]
Shouldn't this issue be closed since PR is merged?

**Comment by dpkp** [comment]
Yes, thanks for the reminder!
