### ISSUE TITLE
Consumer commit_async will fail several times per hour, [Error 7] RequestTimedOutError

### ISSUE THREAD

**Issue by GeminiGuy** [dpkp/kafka-python#928]
python 2.6
kafka-python 1.3.2
Kafka broker version : 0.10.0.1
Invoking the commit_async(callback=self.commit_callback) will always fail several times per hour which the response is "[Error 7] RequestTimedOutError". The tps of commit_async is no more than 5 per second. I have not modified the default value of request_timeout_ms. I do not know the reason.

**Comment by GeminiGuy** [comment]
But when using the tool to check my consumer group commited record,  I can find it! ........
bin/kafka-simple-consumer-shell.sh --topic __consumer_offsets --partition XX --broker-list XXXX:9092 --formatter "kafka.coordinator.GroupMetadataManager\$OffsetsMessageFormatter" | grep my_group | grep offset_num

**Comment by Drizzt1991** [comment]
Let me try to help with that. I assume you are using the `poll()` API to fetch requests. Note, that Kafka has somewhat hard behaviour here - basically it will only receive data from sockets in `poll()` call. In other words commit_async does send a `OffsetCommit` request to the broker, but will receive a reply only on the next `poll` call. Most likely your processing loop (time between `poll()` calls) takes more than 5s and so it raises a Timeout.

You can consider lowering the amount of data fetched from broker per `poll` call using `max_partition_fetch_bytes` or bound the number of rows using the latest `max_poll_records` setting. This will allow you to process data faster.
There is a more hard to implement approach, that involves the `pause` API, resulting in `poll` calls, that do not return data, but only send/recv socket data. If you are interested in that I can try to patch up a snippet.

**Comment by Drizzt1991** [comment]
By the way, did you change the `session_timeout_ms` setting to something higher?

**Comment by GeminiGuy** [comment]
I check my consumer log, the time between subsequent calls to poll() is no more than the default configured session.timeout.ms(30s). My processing loop will cost no more than 500ms.

**Comment by Drizzt1991** [comment]
The code there is pretty straightforward, I think your best bet is to enable logging (to `debug` if your load allows that) and post a few minutes of logs before/after the incident. I think you are hitting a rebalance once in an hour or so and that may be a reason for commit_async to fail. A rebalance will take at least `session_timeout_ms` time, so it's quite close.

**Comment by Drizzt1991** [comment]
Note, that while the error is mostly harmless, it will trigger another rebalance after `RequestTimedOutError`, as it assumes that coordinator is dead. It may lead to somewhat infinite rebalancing... So it's better to get rid of it even if just by raising the `request_timeout_ms` to something like 120s, so it has more room for a rebalance in between.

**Comment by GeminiGuy** [comment]
I call the commit() instead of commit_async, if my consumer group is hitting a rebalance, coommit cannot be completed since the group has already rebalanced and assigned the partitions to another member. And Exception and KafkaError have been excepted in my code, but the exception has never happended.  It makes me confused.

**Comment by dpkp** [comment]
Can you provide any code examples for this?

**Comment by dpkp** [comment]
Is this still an issue? Another idea is that you may have a pending / blocking JoinGroupRequest ahead of your commit request. JoinGroupRequest can block on the server for up to the group's session_timeout. If that happens, you may end up with requests queued up behind it that timeout. Commit requests in particular would be impacted because both have to be sent to the same broker (the group coordinator).

**Comment by GeminiGuy** [comment]
Yes, it is still an issue,no matter the python api or java api。The status of my consumer group is fine, there is no rebalance。So i guess is it possible that the commit_async() sends producer requests occur the read timeout ?

**Comment by dpkp** [comment]
Were you able to resolve this? I'd suggest upgrading to at least 1.3.5, if not further to the 1.4 branch
