### ISSUE TITLE
ImportError: cannot import name KafkaProducer

### ISSUE THREAD

**Issue by alvarodecastro74** [dpkp/kafka-python#930]
Installed it on a raspberry pi and I simply cant make it work, as even a file with a single "from kafka import KafkaConsumer" and nothing more will (as always!) yield a:
  File "test.py", line 1, in <module>
    from kafka import KafkaConsumer
  File "test.py", line 1, in <module>
ImportError: cannot import name KafkaProducer

As you can see, it says it cant import KafkaProducer, when I clearly said to import KafkaConsumer

**Comment by dpkp** [comment]
Does `import kafka` work? How did you install kafka-python? What version do
you have?

**Comment by alvarodecastro74** [comment]
From within python, "import kafka" leads to

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>
  File "/home/pi/recofacial/kafka.py", line 1, in <module>
ImportError: cannot import name SimpleProducer

 

The file /home/pi/recofacial/kafka.py does not exist

 

I installed it with pip install kafka-python and its 1.3.3.dev-py2.7
 



Sent: Tuesday, January 03, 2017 at 7:09 PM

**Comment by dpkp** [comment]
My guess is you have a file named kafka.py (or an old cached version as kafka.pyc). You might try using `from __future__ import absolute_import`

**Comment by alvarodecastro74** [comment]
Actually, I did see a kafka.pyc file among the installed folders. Either way, it seems it's just a matter of copying the entire kafka folder where my code is to make it work. Thank you for your kind support and hope I'm being useful. BTW, I also worked with online music so I know how hard it is ;)

**Comment by alvarodecastro74** [comment]
no, that did not work either

 

I run a site.getsitepackages() which showed that I have the following places for packages
/usr/local/lib/python2.7/dist-packages

/usr/lib/python2.7/dist-packages

 


I found kafka folders in both and I deleted them along with a kafka.pyc I found

 

I reinstalled and tried to run it with and without from future import and same results

 

It only works when I put those folders where my app is located


Sent: Wednesday, January 04, 2017 at 11:52 Pom futureM

**Comment by dpkp** [comment]
Yes, having a kafka.py or kafka.pyc in your app folder will cause problems. Glad you were able to fix!

**Comment by puneetjindal** [comment]
@dpkp I am trying to import kafka and getting this error 
```
Requirement already up-to-date: kafka-python in /usr/local/lib/python3.4/dist-packages
Cleaning up...
Traceback (most recent call last):
  File "/tmp/191e533e-bf47-4336-ac2f-9efa30d6ffbd/pyspark_job_v1.py", line 22, in <module>
    from kafka import SimpleProducer, KafkaClient
ImportError: No module named kafka
```

My machine is debian and

**Comment by xml34** [comment]
right: from kafka import KafkaClient
wrong: from kafka import kafkaClient
CHECK CAPITAL LETTER!!!

**Comment by BichengWang** [comment]
Met same issue:
```
    from kafka_rest.kafka_producer import KafkaProducer
E   ImportError: No module named kafka_producer
```
Any idea about it?
