### ISSUE TITLE
kafka.errors.RequestTimedOutError: [Error 7] RequestTimedOutError: Request timed out after 30000 ms

### ISSUE THREAD

**Issue by c-val** [dpkp/kafka-python#937]
Hi,

I parse large files and create JSON  arrays to be sent to Kafka using :
`producer.send('my_metric',json.dumps(resultJA).encode('utf-8')).get(timeout=60)`

At the above line, I get the following error after a while :
 File "/usr/local/lib/python3.4/dist-packages/kafka/producer/future.py", line 63, in get
    raise self.exception # pylint: disable-msg=raising-bad-type
kafka.errors.RequestTimedOutError: [Error 7] RequestTimedOutError: Request timed out after 30000 ms

Could you help me solve this?
Thank you for your work and your help!

**Comment by jianbin-wei** [comment]
How is your producer initialized?  Using default values?

**Comment by c-val** [comment]
My producer is now initialized this way :
`producer = KafkaProducer(bootstrap_servers=['***'], value_serializer=lambda v: json.dumps(v).encode('utf-8'))`

Now, I use `producer.flush()` and no longer have this pbm.

**Comment by c-val** [comment]
(Thank you)

**Comment by jeffwidman** [comment]
Looks like this can now be closed?
