### ISSUE TITLE
Consumer Hangs 10+ Minutes Before Consuming After Reboot

### ISSUE THREAD

**Issue by nursejason** [dpkp/kafka-python#941]
Referencing a small comment made in [Issue 822](https://github.com/dpkp/kafka-python/issues/822). 

> dpkp: (August 2016) Re your 'hanging' issue, you might try using a different group_id or setting it to None. Otherwise you are likely to get interference between test runs due to autocommit / recovery.

I've published 5,000 messages into a topic, `topic1` and am consuming from the earliest marked offset on "group1". I intend on consuming from this consumer and manually marking offsets.

When I run this, it beings consuming from the first offset as expected. However, if I kill the script and immediately restart it, the script hangs indefinitely. Restarting on a different groupid, again begins consumption as expected. 

```
        consumer = KafkaConsumer(
              "topic1",
              bootstrap_servers=servers,
              group_id="group1",
              auto_offset_reset="earliest",
              fetch_max_wait_ms=200,
              session_timeout_ms=300000
          )
        for message in consumer:
            print message.value
            consumer.commit()
```

I surmise the comment in the other issue is also referring to what's happening here. My consumers are long lived, however external API's may cause the service to stop and then attempt to restart not long after. This same issue is not present in my GoLang Kafka consumers. Is there a way that I can avoid this hanging issue?

**Edit**: My versions might help.
Kafka 0.9.2
Kafka-Python 1.3.2

**Edit 2** After letting the consumer sit for the duration of me writing this issue and then five minutes after, it eventually started consuming again (10-15 minutes?). Which makes me believe that this may be related to a Kafka timeout setting I'm missing.

**Comment by dpkp** [comment]
This is the group session timeout. If you dont call `consumer.close()` on exit, the group coordinator will not know whether the consumer has gracefully left or not. If not graceful exit, the group will wait for the duration of the session timeout before marking the consumer as "dead" and reallocating assigned partitions.

**Comment by nursejason** [comment]
Don't want to reopen this, but I have a consumer.close() in my code wrapped on both sides with logger output. I've handled sigterms in my code to allow for graceful exiting, which calls the consumer.close.

My log output shows the following:
```
2017-01-18T03:57:57.791250420Z Shutting down kafka consumer
2017-01-18T03:57:57.791255841Z Successfully shut down kafka consumer
```
I initially added a three second sleep after closing the consumer, which seemed to have some level of luck, but not 100% of the time. Is there any further explanation for what I'm seeing?
