### ISSUE TITLE
Delete unused branches in the git repo?

### ISSUE THREAD

**Issue by jeffwidman** [dpkp/kafka-python#942]
There's a lot of old/unused branches in the git repo. 

Mind deleting them? 

It just clutters things up when I'm trying to remember the names of the various branches I'm working on.

**Comment by dpkp** [comment]
Sorry -- forgot that github doesn't auto-delete branches on merge.

**Comment by jeffwidman** [comment]
Thanks. Much better. 

Looks like there's still a few branches that are either very old or completely merged such as `absolute_import` and `simple`, not sure if there's a reason you kept those.
