### ISSUE TITLE
CPU usage high after upgrading to 1.3.1

### ISSUE THREAD

**Issue by jianbin-wei** [dpkp/kafka-python#957]
We upgraded from 0.9.5 to 1.3.1.  Our producer code still uses SimpleClient interface before migrating to new KafkaClient.  We noticed that the cpu usage doubled after the upgrade.

After profiling, it turns out that `SimpleClient._send_broker_aware_request` calls BrokerConnection.recv` continuously without blocking.  We have the call ratio as 1:1500 on average.  It is similar for `SimpleClient._send_broker_unaware_request`.  The old KafkaConnection object uses blocking socket while the new one uses non-blocking one along with selector.  Thus the issue between the old SimpleClient and new non-blocking BrokerConnection.

**Comment by dpkp** [comment]
PR merged to master!
