### ISSUE TITLE
Getting error to send data to kafka cluster using SSL certificates

### ISSUE THREAD

**Issue by chillaxd** [dpkp/kafka-python#959]
Hi, i have enabled client authentication in my kafka cluster. I have created client keystore and truststore. After that I have extracted ca.pem, certificate.pem and key.pem from it to use in the producer. But when I try to send data to the cluster from the producer using kafka-python I am getting the following error:

[ERROR] 2017-01-27T08:19:09.167Z 45cf20f9-e469-11e6-aa95-b1058fcb78a0 Uncaught error in kafka producer I/O thread
Traceback (most recent call last):
File "/var/task/kafka/producer/sender.py", line 60, in run
self.run_once()
File "/var/task/kafka/producer/sender.py", line 147, in run_once
(self._client.send(node_id, request)
File "/var/task/kafka/client_async.py", line 454, in send
return self._conns[node_id].send(request, expect_response=expect_response)
File "/var/task/kafka/conn.py", line 516, in send
return self._send(request, expect_response=expect_response)
File "/var/task/kafka/conn.py", line 524, in _send
message = b''.join([header.encode(), request.encode()])
File "/var/task/kafka/protocol/struct.py", line 34, in _encode_self
[self.__dict__[name] for name in self.SCHEMA.names]
File "/var/task/kafka/protocol/types.py", line 124, in encode
for i, field in enumerate(self.fields)
File "/var/task/kafka/protocol/types.py", line 36, in encode
return _pack('>h', value)
File "/var/task/kafka/protocol/types.py", line 12, in _pack
raise ValueError(error)
ValueError: <class 'struct.error'>

My kafka-python version is: 1.3.1
My Kafka version is: 2.11-0.10.0.1
zookeeper version is: 3.4.6

Can you guys please tell me why it is getting such error, as it is working if I disable the SSL flag.

**Comment by chillaxd** [comment]
@dpkp Please check this.

**Comment by Drizzt1991** [comment]
@chillaxd Hey there, did you have any progress on this? It seems like a misconfiguration between producer and broker to me.

**Comment by chillaxd** [comment]
Hey yes I resolved that issue. Configuration was ok but I was doing wrong during certificate creation. Now the problem has been resolved. Should I close this now?

**Comment by Drizzt1991** [comment]
yea, probably
