### ISSUE TITLE
Help: Keep getting Fetch offset X is out of range. Resetting offset for topic-partition...

### ISSUE THREAD

**Issue by ilaif** [dpkp/kafka-python#972]
Hey,

Suddenly I started getting the following "info" messages every 10 minutes:
```
fetcher->_handle_fetch_response():750 - Fetch offset 17250 is out of range for topic-partition TopicPartition(topic=u'<TOPIC_NAME>', partition=0)
fetcher->_handle_fetch_response():753 - Resetting offset for topic-partition TopicPartition(topic=u'<TOPIC_NAME>', partition=0)
```
Also, the highwater seems to stay 0 (meaning that committing offsets fail?), Assignment dump:
```
[{'topic': u'<TOPIC_NAME>', 'highwater': 0, 'partition': 2, 'lag': 0, 'committed': 0}, {'topic': u'<TOPIC_NAME>', 'highwater': 0, 'partition': 0, 'lag': 0, 'committed': 0}, {'topic': u'<TOPIC_NAME>', 'highwater': 0, 'partition': 1, 'lag': 0, 'committed': 0}]
```

Notes:
1. I have 3 brokers.
2. Currently, only partition 0 should contain data, all the other partitions are empty.
3. I have 1 consumer fetching from the 3 brokers using HighLevelConsumer.
4. I have 2 other topics that are working fine without this behavior (on the same cluster).
5. I didn't deploy any new code or changed the infrastructure, it just started happening, all the usual metrics of kafka are healthy and there are no apparent errors.

Consequences: 
With auto_offset_reset set to 'earliest'/'latest' (doesn't matter since the offset stays 0), every 10 minutes, all of the messages in the topic (which are still retained - 7 days in my case for the retention period) are being re-fetched every 10 minutes!

Thoughts:
1. Maybe something is wrong with Zookeeper and it doesn't store offsets for this topic properly?
2. Maybe for some reason I'm not really committing? How can I check that?

Thanks,
Ilai.

**Comment by dpkp** [comment]
This suggests a bad kafka cluster / broker state. Take a look at https://issues.apache.org/jira/browse/KAFKA-2729 and see if you find those messages in your broker logs. I have seen the behavior you describe happen when one broker gets into a strange state and claims leadership without having an in-sync replica.
