### ISSUE TITLE
Use `selectors` rather than `select` for SimpleClient

### ISSUE THREAD

**Issue by jeffwidman** [dpkp/kafka-python#976]
Opening an issue just so we don't lose track of this... 

https://github.com/dpkp/kafka-python/pull/958#issuecomment-277318532

When switching to `selectors`, we should verify it plays nice with `gevent` code. 

We're hitting a bug internally when we migrated a service that uses `gevent` to the new `KafkaConsumer`. The traceback shows select.epoll was used, but then disappeared (probably related to gevent monkey-patching)... If I hardcode the selector used by `KafkaConsumer` to `PollSelector` the issue disappears. While that's a separate issue that I'm still debugging, in the meantime we need to verify that switching this patch to use `selectors` doesn't break `SimpleConsumer`.

**Comment by pulltab** [comment]
Bumping this issue as I just encountered it when leveraging KafkaProducer within greenlets.

**Comment by dpkp** [comment]
KafkaProducer is not affected by this one. Can you file a separate issue
with details?
