### ISSUE TITLE
Add an interface for sending structs automatically to the consumer group coordinator

### ISSUE THREAD

**Issue by jeffwidman** [dpkp/kafka-python#978]
Currently, there is no convenient way to send a low-level struct to the Kafka broker that's the coordinator for a particular consumer group. We have to manually send a `GroupCoordinatorRequest` to retrieve the broker ID that's currently the coordinator, then send structs to that broker. Slightly inconvenient, but not horrible. 

However, sometimes the group coordinator broker crashes, so this code needs to have the retry logic in place to catch the exception, identify the new GroupCoordinator, and switch to that. It gets painful pretty quickly because we have to keep track of which exceptions are retriable and which are fatal.

It'd be better if this logic was all encapsulated in a single interface somewhere where I can give the consumer group name and the struct. 

The function signature seems pretty simple:

    send_to_consumer_group_coordinator(consumer_group_name='my-consumer', request=structRequest)

However, I'm not sure where exactly this should go... KafkaClient, the new Admin client, or somewhere else? 

@dpkp if you can advise on the design, I'm happy to take a stab at initial implementation... I do think the first few releases of this should warn that it's a beta API subject to change.

**Comment by jeffwidman** [comment]
Just discovered `BaseCoordinator`, which would need to be extended ala `ConsumerCoordinator`, so I could use that.

But what should the public interface be? Should it be added to `KafkaClient`, sit on the upcoming `AdminClient`, or something else?

The ultimate problem I'm trying to solve is having a monitoring script that fetches all consumer groups, cycles through and gets all their offsets so we can calculate consumer lag. This seems more in the realm of `KafkaClient` as it's an informational gathering task, not an administrative task.

**Comment by jeffwidman** [comment]
@dpkp any design feedback here?

**Comment by dpkp** [comment]
I don't have any great ideas here, but I would like to keep KafkaClient fairly close to the java NetworkClient. So all else equal, I'd prefer to do this in an AdminClient or similar.

**Comment by jeffwidman** [comment]
I think https://github.com/dpkp/kafka-python/pull/1641 should suffice to make this doable. Just glue together the response of `_find_group_coordinator_id()` with `send_request_to_node()`, both within the `KafkaAdmin` class.

I also experimented a lot with trying to create something that includes sending structs, but it turns out the error checking is really difficult... and I don't see much value in a wrapper that glue's these together because it's two lines to do it manually...
