### ISSUE TITLE
Consumer gets "stuck" in multi-threaded scenario

### ISSUE THREAD

**Issue by kayakyakr** [dpkp/kafka-python#980]
I've got a consumer running in a multi thread environment. Each thread gets its own consumer and the set are coordinated through the kafka group. After running well for some time, yesterday 3 of the partitions got "stuck". In the kafka metrics interface, data out/sec jumped from ~150 KB/s to 5 MB/s. One partition came unstuck on its own early this morning while the other two came unstuck when I dropped the threading down to 1 thread. Data out/sec dropped down to the normal ~100 KB/s.

This is he first time this has happened in about 3 months of use, so I'm not sure what caused it to go crazy yesterday. I confirmed that it was never making it to the actual processing of the message, it was just reading from the topic non-stop at an incredible pace.

Has anyone seen this behavior? Any ideas about what it could be choking on?

**Comment by dpkp** [comment]
Interesting. One general suggestion is to use multiprocessing, not threading, to run multiple consumers. Each KafkaConsumer multiplexes IO over multiple broker connections, so you wont get much from multiple threads given the GIL restriction to a single CPU core. Multiprocessing (or any other strategy that gets you access to multiple cores) is a much better strategy for parallel processing in kafka-python.

With respect to your actual issue, it *feels* to me like you may have published a very large message that is larger than the maximum message size accepted by your consumers. What version of kafka-python are you using?

**Comment by kayakyakr** [comment]
It may be a too large message, but we've left the default max message size (10 MB, I think) which blocks out the most egregious messages.

I'm still not certain if dropping to 1 thread allowed it to unblock, or if it was just coincidence and it jumped forward in offset to skip past the choke-value.

And yeah, I'm gonna have to rewrite to use multi-process. Any suggestions for tools that would make multi-processing a bit easier to implement? I'm coming from ruby, not used to doing things the python way. Anything comparable to node's forever?

**Comment by dpkp** [comment]
What version of kafka-python are you using?

**Comment by kayakyakr** [comment]
1.3.2

**Comment by dpkp** [comment]
ok -- and what's your broker version?

**Comment by kayakyakr** [comment]
I believe we are on 0.10.1.1

**Comment by kayakyakr** [comment]
Got all of the missing values to pass through single-threaded, so I am going to guess it's a threading issue. Will keep it single thread, multi-process.

**Comment by kayakyakr** [comment]
@dpkp should using the multiprocessing library be sufficient for kafka-python to behave as if it's running entirely separate executables? I set it up to isolate on multi-process and that seems to be working, but it might have gotten "stuck" at some point in the last big batch run. It cleared up before I got Heroku to give us any insight.

**Comment by dpkp** [comment]
Yes -- multiprocessing will give you essentially separate executables. The problem with threading on python is that the GIL prevents multiple threads from running simultaneously.
