### ISSUE TITLE
SimpleConsumer: Deadlock on zombie sockets

### ISSUE THREAD

**Issue by duilio** [dpkp/kafka-python#984]
Waiting for an answer from the broker may halt the application.

The problem is actually here: https://github.com/dpkp/kafka-python/blob/8fde79dbb5a3793b1a9ebd10e032d5f3dd535645/kafka/client.py#L289

A blocking `select` is done for a socket connection without the keepalive flag. 

Basically a dead peer scenario can happen (http://www.tldp.org/HOWTO/html_single/TCP-Keepalive-HOWTO/#whyuse).

I would suggest to either:

* Add an option to enable/disable keepalive connections. (enabled by default)
* Enforce socket connection keepalive.

Another option would be to set a timeout to the `select` call.

**Comment by duilio** [comment]
Just to be clear, the following scenario has actually happened to me:

1. One of the kafka brokers crashed.
2. The fetch request was already been sent to the broker.
3. Consumer waited indefinitely for a reply exactly in that line. (using an older version of kafka-python, but the bug persists)

**Comment by dpkp** [comment]
Thanks for the bug report! The code you linked is for the deprecated
client. Have you seen this happen with KafkaConsumer or KafkaProducer?

**Comment by duilio** [comment]
The bug was spotted in version 0.9.5 on the consumer side, I've just looked for `select.select` in the new code, so I thought reporting it was useful.

 I've just noticed the async client, so I guess that's the new one.

**Comment by dpkp** [comment]
I'm happy to accept PRs to fixup issues with the SimpleConsumer, but I am not actively working on it. I suggest switching to KafkaConsumer which uses timeouts when polling non-blocking sockets.

**Comment by dpkp** [comment]
Closing -- SimpleConsumer has been removed from kafka-python
