### ISSUE TITLE
Once KafkaProducer reports "Failed to allocate memory within the configured" exceptions, it never recovers from the failures

### ISSUE THREAD

**Issue by threepea** [dpkp/kafka-python#985]
We have a situation there is a message burst in our business codes using Kafka 1.3.2. The message rate might reach 100K/s, each message size is less than 16Kb. The producer is shared between threads and configured as default parameters except 'compression_type='gzip', linger_ms=5, retries=3'.
We observe that during message burst, Kafka producer reports:
“KafkaTimeoutError: KafkaTimeoutError: Failed to allocate memory within the configured max blocking time”
And it never comes back.
Traceback listed below:
Traceback (most recent call last):
  File "/root/search/db_publisher.py", line 47, in publish
    self._publish(message)
  File "/root/search/db_publisher.py", line 41, in _publish
    self.producer.send(self.topic, msg)
  File "/usr/lib/python2.7/site-packages/kafka/producer/kafka.py", line 511, in send
    self.config['max_block_ms'])
  File "/usr/lib/python2.7/site-packages/kafka/producer/record_accumulator.py", line 243, in append
    buf = self._free.allocate(size, max_time_to_block_ms)
  File "/usr/lib/python2.7/site-packages/kafka/producer/buffer.py", line 201, in allocate
    "Failed to allocate memory within the configured"
KafkaTimeoutError: KafkaTimeoutError: Failed to allocate memory within the configured max blocking time

Then I check more and find another exception produced:
Traceback (most recent call last):  
File "/root/search/db_publisher.py", line 47, in publish    
self._publish(message)  
File "/root/search/db_publisher.py", line 41, in _publish    
self.producer.send(self.topic, msg)  
File "/usr/lib/python2.7/site-packages/kafka/producer/kafka.py", line 511, in send    self.config['max_block_ms']) 
File "/usr/lib/python2.7/site-packages/kafka/producer/record_accumulator.py", line 243, in append    
buf = self._free.allocate(size, max_time_to_block_ms) 
File "/usr/lib/python2.7/site-packages/kafka/producer/buffer.py", line 207, in allocate
assert removed is more_memory, 'Wrong condition'
AssertionError: Wrong condition

I check the source codes of above exceptions in code buffer.py (class SimpleBufferPool).
There is something wrong in the situation when producer fails to allocate memory from buffer pool within time limit:
                    if self._free:                                                                                                                                      
                        buf = self._free.popleft()                                                                                                                      
                    else:                                                                                                                                               
                        raise Errors.KafkaTimeoutError(                                                                                                                 
                            "Failed to allocate memory within the configured"                                                                                           
                            " max blocking time") 
Should we popleft the semaphore appended to the waiters before raising Errors.KafkaTimeoutError, so next allocation action no need to wait for "max_time_to_block_ms" milliseconds and thus its Condition assertion can pass? Due to each de-allocation notifies the wrong Condtion objects, each allocation action has to waste "max_time_to_block_ms" to wait the semaphore signal. As consequence, our program is slowing down rapidly and not acceptable for business.
The issue has been re-produced 3 times and I will provide debug information about memory allocation and de-allocation logging.
Anyway, thanks your guys  for this wonderful library.

**Comment by threepea** [comment]
I have to clarify about the statement "each allocation action has to waste "max_time_to_block_ms" to wait the semaphore signal" is not true actually. If Sender thread receives response from kafka server quickly, producer no need to wait on a semaphore since there is available memory block in pool. Eeven if producer is waiting on semaphore, it's still waken up quickly if more de-allocation actions happen.
Sorry about my mistake. But still a lot of "KafkaTimeoutError" and "Assertion" Exceptions seen.

**Comment by threepea** [comment]
Issue produced again. This time, I added some logging statements to monitor buffer consumption in buffer.py. I saw great heap about the consumption though it might be incorrect in multiple threads environment.
**5256:2017-02-19 06:47:26,993 0x7fc3cd7fa700 [INFO] buffer.py:178 - memory allocation: try to allocate memory from buffer pool, 1 unused
5263:2017-02-19 06:47:26,998 0x7fc3cd7fa700 [INFO] buffer.py:178 - memory allocation: try to allocate memory from buffer pool, 0 unused
5275:2017-02-19 06:47:27,004 0x7fc3ddcd1700 [INFO] buffer.py:235 - memory deallocation: return buf. 1 unused
5280:2017-02-19 06:47:27,010 0x7fc3ddcd1700 [INFO] buffer.py:235 - memory deallocation: return buf. 2 unused
5283:2017-02-19 06:47:27,010 0x7fc3ddcd1700 [INFO] buffer.py:235 - memory deallocation: return buf. 3 unused
5288:2017-02-19 06:47:27,012 0x7fc3ddcd1700 [INFO] buffer.py:235 - memory deallocation: return buf. 4 unused
5291:2017-02-19 06:47:27,012 0x7fc3ddcd1700 [INFO] buffer.py:235 - memory deallocation: return buf. 5 unused
5363:2017-02-19 06:47:27,882 0x7fc3ebb07740 [INFO] buffer.py:178 - memory allocation: try to allocate memory from buffer pool, 2048 unused
5369:2017-02-19 06:47:27,884 0x7fc3ebb07740 [INFO] buffer.py:178 - memory allocation: try to allocate memory from buffer pool, 2047 unused
5383:2017-02-19 06:47:27,893 0x7fc3de4d2700 [INFO] buffer.py:235 - memory deallocation: return buf. 2047 unused
5387:2017-02-19 06:47:27,894 0x7fc3de4d2700 [INFO] buffer.py:235 - memory deallocation: return buf. 2048 unused
5405:2017-02-19 06:47:28,423 0x7fc3dd4d0700 [INFO] buffer.py:178 - memory allocation: try to allocate memory from buffer pool, 4 unused**
A lot of AssertionError happened "assert removed is more_memory, 'Wrong condition'"
And a lot of KafkaTimeoutError Exception raised about “Failed to allocate memory within the configured max blocking time”
Attach LOG file
[log.query_dispatcher_new_15681.gz](https://github.com/dpkp/kafka-python/files/786886/log.query_dispatcher_new_15681.gz)

**Comment by Gowtham95india** [comment]
Any update on this?

**Comment by threepea** [comment]
Seems every is busy...
I am joking.
Anyway, I added this statement "self._waiters.popleft()" before raising Errors.KafkaTimeoutError in buffer.py.
Bad things still happened but my program could re-cover. That's good for me.
I hope some expert in this module can provide official fix which is wonderful thing for me.

**Comment by Gowtham95india** [comment]
Thanks...! I'll check out your suggestion.

**Comment by hicqu** [comment]
@threepea , could you tell me how do you configure these two entries:
`max_block_ms`: ??
`request_timeout_ms`: ??
I have a relative issue #994 .

Thank you.

**Comment by threepea** [comment]
left them as default. But I think there are different issues compared with #994 . I can accept the fact kafka reports "KafkaTimeoutError: Failed to allocate memory within the configured max blocking time" but I don't think it's good phenomenon that many Assertion "Wrong condition" ERROR seen after that.

**Comment by Gowtham95india** [comment]
@threepea  What does self._waiters.popleft() exactly will do ?

**Comment by threepea** [comment]
Remove the condition once kafka producer client fails to allocate memory from buffer pool, so next client being waiting will be notified correctly.

**Comment by Gowtham95india** [comment]
@threepea 
Thanks, anyway my issue because of async frameworks. It has it's own event loop and sanic has it's own loop. Which causing the problem?!
