### ISSUE TITLE
Handle offset out of range error manually

### ISSUE THREAD

**Issue by mgill25** [dpkp/kafka-python#988]
I am storing offsets at my consumer locally and manually incrementing them, only seeking the `position` when there is a non-existing offset in my storage. However, there can be a case when, because of the retention policy in kafka, older offsets get expired and my consumer hasn't caught up. In that case, the consumer will try to fetch older offsets. When that happens, kaka-python internally raises `Errors.OutOfRangeError` and handles it by resetting the offset.

The problem is that I need some sort of signal or trigger in my own code to detect when the above condition occurs so I can also update the offset stored in my own storage. As it stands, I just see lots of errors like the following:

`INFO     2017-02-15 10:15:52,543 -5s Thread-1    kafka.consumer.fetcher _handle_fetch_response          730 : Fetch offset 30 is out of range, resetting offset`.

While logging this info is fine, can I actually make this actionable somehow? Thanks! :)

**Comment by Drizzt1991** [comment]
As far as it's documented you can pass None for `auto_offset_reset` and it should just propagate the `NoOffsetForPartitionError` to you. I did not try this thou, as never had such a use case.
Something like this:
```python
consumer = Consumer(..., auto_offset_reset=None)
while True:
    try:
        res = consumer.poll(...)
    except NoOffsetForPartitionError as err:
        # handle it
```

**Comment by mgill25** [comment]
I tried this out. Does not propagate the exception to my end. It actually increases the frequency with which I get the offset reset error for some reason. Digging into the code a bit it seems like this happens because the reset offset code is only triggered when there is a default offset reset policy. Inside group.py:

```                elif error_type is Errors.OffsetOutOfRangeError:
                    fetch_offset = fetch_offsets[tp]
                    if self._subscriptions.has_default_offset_reset_policy():
                        self._subscriptions.need_offset_reset(tp)
                    else:
                        self._offset_out_of_range_partitions[tp] = fetch_offset
                    log.info("Fetch offset %s is out of range, resetting offset",
                             fetch_offset)```

**Comment by Drizzt1991** [comment]
Well I was a bit wrong, the error should be `OffsetOutOfRangeError`, but otherwise it works for me:
```python
from __future__ import print_function
from kafka import KafkaConsumer, TopicPartition
from kafka import KafkaProducer
from kafka.errors import KafkaError

producer = KafkaProducer(bootstrap_servers=['localhost:9092'])
future = producer.send('my-topic', b'raw_bytes')
future.get()

# To consume latest messages and auto-commit offsets
consumer = KafkaConsumer('my-topic',
                         group_id='my-group',
                         bootstrap_servers=['localhost:9092'],
                         auto_offset_reset="none")
consumer.poll(timeout_ms=0)  # Ensure group is rebalanced
consumer.seek(TopicPartition("my-topic", 0), 21312312331)
try:
    consumer.poll(timeout_ms=1000)
except KafkaError as err:
    print(err)
```
```
(.kafka-python-env) vagrant@my-dev:/workspace/kafka-python$ python test_reset.py 
[Error 1] OffsetOutOfRangeError: {TopicPartition(topic='my-topic', partition=0): 21312312331}
```

**Comment by Drizzt1991** [comment]
Could you provide your configuration and how you actually process messages? I can see `Thread-1` in log message, are you processing in different threads maybe?

**Comment by Drizzt1991** [comment]
What version of `kafka-python` are you using, by the way? The error message is changed in the last release.

**Comment by mgill25** [comment]
I tried your script, to some interesting results. 

First off, yes there are differences. I am using `kafka-python==1.3.1`. But here's the curious part.

I ran your script on an existing topic that I was using to test this on. When I tried to run the script using the same group name as my existing test, it exited silently. But when I changed the group name to something random, I got the exception.

```(mytest-virtualenv)root@services:/opt/mytest/scripts# python test_kafka_reset.py
Group is: psql
(mytest-virtualenv)root@services:/opt/mytest/scripts# python test_kafka_reset_new_group.py
Group is: hello
Traceback (most recent call last):
  File "test_kafka_reset_new_group.py", line 17, in <module>
    consumer.poll(timeout_ms=0)                                                 # Ensure group is rebalanced
  File "/opt/mytest-virtualenv/local/lib/python2.7/site-packages/kafka/consumer/group.py", line 514, in poll
    records = self._poll_once(remaining)
  File "/opt/mytest-virtualenv/local/lib/python2.7/site-packages/kafka/consumer/group.py", line 552, in _poll_once
    self._update_fetch_positions(self._subscription.missing_fetch_positions())
  File "/opt/mytest-virtualenv/local/lib/python2.7/site-packages/kafka/consumer/group.py", line 833, in _update_fetch_positions
    self._fetcher.update_fetch_positions(partitions)
  File "/opt/mytest-virtualenv/local/lib/python2.7/site-packages/kafka/consumer/fetcher.py", line 172, in update_fetch_positions
    self._reset_offset(tp)
  File "/opt/mytest-virtualenv/local/lib/python2.7/site-packages/kafka/consumer/fetcher.py", line 195, in _reset_offset
    raise NoOffsetForPartitionError(partition)
kafka.consumer.fetcher.NoOffsetForPartitionError: NoOffsetForPartitionError: TopicPartition(topic=u'sessions', partition=0)
```

As for the threads, the application used to be multithreaded but I've retrofitted it to only launch 1 thread (it doesn't run in the main thread). But there is no real multithreading going on.

**Comment by mgill25** [comment]
By the way, can you tell me why you do the first poll with `timeout_ms` set to 0? What does it mean for the group to be rebalanced?

**Comment by Drizzt1991** [comment]
> By the way, can you tell me why you do the first poll with timeout_ms set to 0? What does it mean for the group to be rebalanced?

A consumer group will split all processing partitions between consumers. For example when we have 2 consumers with group "my_sessions" and the subscribed topic has 10 partitions, each consumer will only fetch from 5 partitions. The process of *assignment* of those partitions I called a rebalance, but more precise would be "joining" the group. More info here: https://kafka.apache.org/documentation/#intro_consumers

> I ran your script on an existing topic that I was using to test this on. When I tried to run the script using the same group name as my existing test, it exited silently. But when I changed the group name to something random, I got the exception.

That is expected, I missed the `NoOffsetForPartitionError` part. You will get that error if it's a fresh topic and no offsets has been commited yet, so it does not know where to start. As for `OffsetOutOfRangeError` is raised if we know where to read, but that data is not present on our broker.
As for your topic, that exited silently I may only presume, that you actually have data on offset `21312312331`...

As far as I can tell it should work on your case, please recheck your code or provide some snippets, cause I have no idea why it does not work in you production case )

**Comment by mgill25** [comment]
The silently failing script I also tried on a much larger offset `2131231231231100000` with same result. Can't be that data is on that offset. I also retried by deleting and re-creating the topic to the same result.

The following script successfully reproduces my problem:

```from __future__ import print_function
from kafka import KafkaConsumer, TopicPartition
from kafka.errors import KafkaError
import logging
from redis import StrictRedis

logging.basicConfig(level=logging.INFO)
log = logging.getLogger(__name__)

def main():
    topic = "sessions"
    group = "psql"
    bootstrap_servers = ['localhost:9092']
    rc = StrictRedis()

    log.info('Topic is: {}'.format(topic))
    log.info("Group is: {}".format(group))

    # To consume latest messages and auto-commit offsets
    try:
        consumer = KafkaConsumer(group_id=group, bootstrap_servers=bootstrap_servers, auto_offset_reset="none")
        assigned_partition = 0
        tp = TopicPartition(topic, assigned_partition)
        consumer.assign([tp])

        # Make a unique offset key for storage
        offset_key = "offset_{topic}_{partition}_{group}".format(topic=topic,
                                                                partition=assigned_partition,
                                                                group=group)
        log.info("offset key: {}".format(offset_key))
        while True:
            # Get latest offset from redis, if not found, fetch from kafka
            next_offset = rc.get(offset_key)
            if not next_offset:
                log.info("offset wasn't found in redis, seek from kafka")
                next_offset = consumer.position(tp)
                log.info('got offset: {}'.format(next_offset))

            next_offset = int(next_offset)
            # next_offset = 21312312331

            # Seek to the position of the next offset
            consumer.seek(tp, next_offset)

            # Process messages
            k_msg = consumer.poll(timeout_ms=200)
            if k_msg:
                for msgs in list(k_msg.values()):
                    for msg in msgs:
                        log.info('got msg: {}'.format(msg))
                        # Process message and increment offset
                        log.info('setting offset key to {}'.format(msg.offset + 1))
                        rc.set(offset_key, msg.offset + 1)
    except KafkaError as e:
        log.info('Got kafka error %s: %s' % (str(e), type(e)))
    except Exception as e:
        log.info('Got exception %s: %s' % (str(e), type(e)))
    else:
        log.info('No exception raised!')

if __name__ == '__main__':
    main()
```

And in redis, `set offset_sessions_0_psql 1000000000` will reproduce exactly my case.

I get continuous `INFO:kafka.consumer.fetcher:Fetch offset 55 is out of range, resetting offset` errors.

**Comment by mgill25** [comment]
So in the above script, `consumer.position(tp)` is the source of truth for me, but I never get the exception that can indicate to me that I should now fetch the offset from kafka instead of relying on redis.

**Comment by Drizzt1991** [comment]
So here are my assumptions of what you want to achieve:
* Consume a topic and save position in kafka
* Also save position in Redis in case the consumer goes down the hard way, so we can restart from the same message.
* If the position in redis is obsolete (it was removed for example), we need to load the first available message in the topic.

Are those correct?

If so:
1) You don't need to call `seek` before every `poll()`. Just call it once during startup.
2) `consumer.position` is the next message to be read. It will be equal to next_offset after you call `consumer.seek(tp, next_offset)`. What you want is probably `consumer.commited(tp)`, it will load last saved offset in kafka.
3) You can reset it with something like:
```python
try:
   consumer.poll(...)
except OffsetOutOfRangeError:
   log.info("Offset out of range. Seeking to begining")
   consumer.seek_to_beginning(tp)
```

The following seem to work ok for me:
```python

from kafka import KafkaConsumer, TopicPartition
from kafka.errors import KafkaError
import logging
from redis import StrictRedis
from kafka.errors import OffsetOutOfRangeError

logging.basicConfig(level=logging.INFO)
log = logging.getLogger(__name__)


def main():
    topic = "sessions"
    group = "psql"
    bootstrap_servers = ['localhost:9092']
    rc = StrictRedis()

    log.info('Topic is: {}'.format(topic))
    log.info("Group is: {}".format(group))

    # To consume latest messages and auto-commit offsets
    try:
        consumer = KafkaConsumer(
            group_id=group, bootstrap_servers=bootstrap_servers,
            auto_offset_reset="none")
        assigned_partition = 0
        tp = TopicPartition(topic, assigned_partition)
        consumer.assign([tp])

        # Make a unique offset key for storage
        offset_key = "offset_{topic}_{partition}_{group}".format(
            topic=topic, partition=assigned_partition, group=group)
        log.info("offset key: {}".format(offset_key))

        # Get latest offset from redis, if not found, fetch from kafka
        next_offset = rc.get(offset_key)
        if not next_offset:
            log.info("offset wasn't found in redis, seek from kafka")
            next_offset = consumer.committed(tp) or 0
            log.info('got offset: {}'.format(next_offset))

        next_offset = int(next_offset)
        # next_offset = 21312312331

        # Seek to the initial position
        consumer.seek(tp, next_offset)

        while True:
            # Process messages
            try:
                k_msg = consumer.poll(timeout_ms=200)
            except OffsetOutOfRangeError:
                log.info("Offset out of range. Seeking to begining")
                consumer.seek_to_beginning(tp)
                # You can save `consumer.position(tp)` to redis after this,
                # but it will be saved after next message anyway
            else:
                if k_msg:
                    for msgs in list(k_msg.values()):
                        for msg in msgs:
                            log.info('got msg: {}'.format(msg))
                            # Process message and increment offset
                            log.info('setting offset key to {}'.format(msg.offset + 1))
                            rc.set(offset_key, msg.offset + 1)
    except KafkaError as e:
        log.info('Got kafka error %s: %s' % (str(e), type(e)))
    except Exception as e:
        log.info('Got exception %s: %s' % (str(e), type(e)))
    else:
        log.info('No exception raised!')
    finally:
        consumer.close()

if __name__ == '__main__':
    main()
```

output:
```
(.kafka-python-env) vagrant@my-dev:/workspace/kafka-python$ python test_reset.py 
INFO:__main__:Topic is: sessions
INFO:__main__:Group is: psql
INFO:kafka.conn:<BrokerConnection host=localhost/127.0.0.1 port=9092>: Closing connection. 
INFO:kafka.conn:Broker is not v(0, 10) -- it did not recognize ApiVersionRequest_v0
INFO:kafka.conn:Broker version identifed as 0.9
INFO:kafka.conn:Set configuration api_version=(0, 9) to skip auto check_version requests on startup
INFO:__main__:offset key: offset_sessions_0_psql
INFO:kafka.cluster:Group coordinator for psql is BrokerMetadata(nodeId=0, host='127.0.0.1', port=9092, rack=None)
INFO:kafka.coordinator:Discovered coordinator 0 for group psql
INFO:kafka.consumer.fetcher:Fetch offset 1000000000 is out of range for topic-partition TopicPartition(topic='sessions', partition=0)
INFO:__main__:Offset out of range. Seeking to begining
INFO:__main__:got msg: ConsumerRecord(topic='sessions', partition=0, offset=0, timestamp=None, timestamp_type=None, key=None, value=b'raw_bytes', checksum=1907705797, serialized_key_size=-1, serialized_value_size=9)
```

**Comment by mgill25** [comment]
Thanks, this worked with the latest version of the library! :)
