### ISSUE TITLE
Help: Can't poll new message after no message for a few seconds

### ISSUE THREAD

**Issue by JunfeiW** [dpkp/kafka-python#998]
After connect, poll could get messages for kafka server side. 
But when the publisher is stopped, and no new message is produced for a few seconds, 
poll would always return {}.

I tried with official client, kafka-console-consumer.sh. it works very well. so I do believe, the server side is ok.

**Comment by JunfeiW** [comment]
>>> kafka.version.__version__
'1.3.2'

**Comment by JunfeiW** [comment]
Please tell me how to debug problem. I tried another lib pykafka, which works fine, too

**Comment by dpkp** [comment]
Sorry, I'm not entirely sure what you are describing. Can you provide any more detail? A code snippet to reproduce the problem?

**Comment by JunfeiW** [comment]
`from kafka import KafkaConsumer, KafkaProducer
import selectors
import pdb

consumer = KafkaConsumer('7e5028a660c4414a99bb6cf63ccf7feb__test',
                          bootstrap_servers='kafka.gz.baidubce.com:9092',
                          security_protocol='SSL',
                          ssl_check_hostname=False,
                          ssl_cafile='key/ca.pem',
                          ssl_certfile='key/client.pem',
                          ssl_keyfile='key/client.key',
                          heartbeat_interval_ms=100,
                          selector=selectors.EpollSelector,
                          skip_double_compressed_messages=True)


# Read and print all messages from test topic
for msg in consumer:
    print(msg)

`

This is my client code, 

![image](https://cloud.githubusercontent.com/assets/5487724/23443783/06e1bb72-fe6c-11e6-9b90-41a41816c1b5.png)

There are three windows, from left to right, the first the one run the below code, the second is, sh bin/kafka-console-consumer.sh, and the third one is publisher. 

As you can see from picture, after a few seconds, I published four messages, the second windows received, and print four time, but the first windows, has nothing

**Comment by JunfeiW** [comment]
`from kafka import KafkaConsumer, KafkaProducer
import selectors
import pdb

consumer = KafkaConsumer('7e5028a660c4414a99bb6cf63ccf7feb__test',
bootstrap_servers='kafka.gz.baidubce.com:9092',
security_protocol='SSL',
ssl_check_hostname=False,
ssl_cafile='key/ca.pem',
ssl_certfile='key/client.pem',
ssl_keyfile='key/client.key',
heartbeat_interval_ms=100,
selector=selectors.EpollSelector,
skip_double_compressed_messages=True)

for msg in consumer:
print(msg)`

**Comment by JunfeiW** [comment]
When I rerun the program, the message can be polled again.
![image](https://cloud.githubusercontent.com/assets/5487724/23447547/ae3d2266-fe86-11e6-8116-80a0781e83d2.png)

**Comment by dpkp** [comment]
Have you tried looking at error or debug logs ?

**Comment by JunfeiW** [comment]
The problem is I didn't find any documents describes to debug.
And I can't access kafka server side for log info, because it is provided by third party.
Appreciated any help, thanks!

**Comment by dpkp** [comment]
using the python logging module. for example:
```
import logging
logging.basicConfig(level=logging.DEBUG)
```

**Comment by JunfeiW** [comment]
DEBUG:kafka.coordinator.consumer:OffsetCommit for group kafka-python-default-group failed: [Error 25] UnknownMemberIdError: kafka-python-default-group
WARNING:kafka.coordinator.consumer:Auto offset commit failed for group kafka-python-default-group: CommitFailedError: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured session.timeout.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing the session timeout or by reducing the maximum size of batches returned in poll() with max.poll.records.

**Comment by JunfeiW** [comment]
seems the same with https://github.com/dpkp/kafka-python/issues/569

**Comment by dpkp** [comment]
you might also try setting `group_id=None`, otherwise subsequent runs of your python script will have to deal with consumer group rebalancing / commits / etc -- the kafka-console-consumer.sh script does not use a consumer group by default.
